### ISSUE TITLE
\TODO breaks tables (Origin: bugzilla #779550)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6176] opened 2018-07-02 12:49 UTC
status NEW severity *normal* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-03-03 19:32:21 +0000, roberthannah89@gmail.com wrote:

    using \TODO inside a table causes subsequent rows to be booted from the
    table into a standard paragraph.

**Comment by albert-github** [comment] 2018-11-09 15:51
This report describes a problem like the problem described in #6028.

I think this is a duplicate of #6028.

**Closed** 2019-12-28 11:05 UTC
Labels: bug, duplicate
