### ISSUE TITLE
Building fails on Linux with gcc 5.4 (Doxygen cloned on 2021-03-17)

### ISSUE THREAD

**Issue by Stewori** [doxygen/doxygen#8436] opened 2021-03-17 15:36 UTC
**Describe the bug**
Compiling current Doxygen (9136e8c664bc4b0706a9cf419c76b2277b87f4a1) on my system (details below) fails. The latest release 1.9.1. still compiled fine on my system.
It goes fine until 80%, then crashes with the following four errors of two types:
```
/data/doxygen/src/memberlist.cpp: In member function ‘void MemberList::writeDocumentation(OutputList&, const char*, const Definition*, const char*, bool, bool) const’:
/data/doxygen/src/memberlist.cpp:706:78: error: no matching function for call to ‘std::unordered_map<std::__cxx11::basic_string<char>, MemberList::writeDocumentation(OutputList&, const char*, const Definition*, const char*, bool, bool) const::OverloadInfo>::insert(std::pair<QCString, MemberList::writeDocumentation(OutputList&, const char*, const Definition*, const char*, bool, bool) const::OverloadInfo>)’
       auto it = overloadInfo.insert(std::make_pair(md->name(),OverloadInfo())).first;
```

```
/usr/include/c++/5/bits/unordered_map.h:439:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/unordered_map.h:435:32: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
       template<typename _Pair, typename = typename
```

```
/data/doxygen/src/memberlist.cpp: In member function ‘void MemberList::writeDocumentationPage(OutputList&, const char*, const DefinitionMutable*) const’:
/data/doxygen/src/memberlist.cpp:779:78: error: no matching function for call to ‘std::unordered_map<std::__cxx11::basic_string<char>, MemberList::writeDocumentationPage(OutputList&, const char*, const DefinitionMutable*) const::OverloadInfo>::insert(std::pair<QCString, MemberList::writeDocumentationPage(OutputList&, const char*, const DefinitionMutable*) const::OverloadInfo>)’
       auto it = overloadInfo.insert(std::make_pair(md->name(),OverloadInfo())).first;
```

```
/usr/include/c++/5/bits/unordered_map.h:439:2: note:   template argument deduction/substitution failed:
/usr/include/c++/5/bits/unordered_map.h:435:32: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
       template<typename _Pair, typename = typename
```

The full logs are
[err_make.txt](https://github.com/doxygen/doxygen/files/6157415/err_make.txt)
[log_make.txt](https://github.com/doxygen/doxygen/files/6157417/log_make.txt)

And the configuration can be seen in the cmake output from ``cmake -G "Unix Makefiles" .. > log.txt``, usign cmake 3.5.
[log_cmake.txt](https://github.com/doxygen/doxygen/files/6157419/log_cmake.txt)

I suspect this is because of my somewhat outdated system, specifically due to still using gcc 5. However, it was not transparently documented that gcc 5 support was dropped; maybe this was done by accident? Otherwise it should be documented somewhere (I guess; sorry if I overlooked it!). Or maybe I am wrong and the cause is something "entirely" different...?

**Expected behavior**
I expect it to compile successfully or that the minimum gcc requirement is documented, e.g. in the installation instructions or that cmake would complain.

**To Reproduce**
Hard to tell without knowing the cause. I guess: Compile current doxygen using gcc 5.

**Version**
The latest release 1.9.1. still compiled fine on my system.
The issues are observed using a fresh clone from 2021-03-17. Commit id: 9136e8c664bc4b0706a9cf419c76b2277b87f4a1

`lsb_release -a`:
```
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	LinuxMint
Description:	Linux Mint 18 Sarah
Release:	18
Codename:	sarah
```

**Additional Context**
I can attempt to identify the commit that caused the issue, however that would be some work since it has been a while that I used advanced git magic. This might take me a while. Already posting this issue "as is" in the hope the cause might be more obvious or apparent for the Doxygen devs. Tell me if you regard it useful that I identify the commit.

I searched the tracker for duplicates back to the release date of 1.9.1 but found none.
I guess a thing worth trying would be building with clang, but it is not easily obvious how to do that, Maybe I can figure it out...  (hints welcome)
```
clang --version
clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

**Comment by albert-github** [comment] 2021-03-17 17:36
This change has been committed on January 22, s021 as part of a number of refactoring commits.
The commit before the set of refactoring commits is c6c2e1fe6e0806b0798395262e4b955e4493db86 
To test you can try:
- can to apply the patch on the 1.9.1. source
- try to apply the patch on the commit c6c2e1fe6e0806b0798395262e4b955e4493db86 

I think that its should be possible to apply the patch on the 1.9.1 version.

That said, the compiler version is quite old (according to https://gcc.gnu.org/releases.htmlfrom June 3, 2016) and also the cmake version (3.5) is quite old. I think it might be best to upgrade the gcc  version.
(on github actions I see the used gcc version is 7.5.0).

Regarding the message, I don't know a workaround maybe @doxygen has an idea.

**Comment by Stewori** [comment] 2021-03-17 21:44
Okay, I managed to update gcc to 9.3. It turned out easier than expected (using selected commands from [this ghist](https://gist.github.com/youmych/122e32cfa1c228c84684fec13b7d52e1)) Initially, I thought it would cause a bigger dependency odyssey and might even require a system update. Now I can confirm it works with gcc 9.3, while still using cmake 3.5.

So, just take this issue as an encouragement to list some minimal version requirements in the install guide.
I remember cmake >= 3.3 is mentioned there as a requirement. A similar hint for gcc could be added.
Maybe also some version guard for gcc could be placed in https://github.com/doxygen/doxygen/blob/master/CMakeLists.txt

Anyway, thanks for your hints!

**Comment by albert-github** [comment] 2021-03-18 08:58
Fortunately your problem was "easily" solved, I also was afraid of a cascade of requirements, great that there was a gist available with instructions (forked from https://gist.github.com/application2000/73fd6f4bf1be6600a2cf9f56315a2d91).

The minimal CMake version mentioned in the documentation is 3.3 and in the CMake "code" we did some special things for older CMake versions (alder than 3.6.2 and 3.11.0).
Regarding the minimal compiler version or regarding gcc I didn't find any indications but I vaguely remember that once I saw something like a modern compiler.
It is hard to find which minimum versions are required as not all compilers are present (most of the time the minimal version is governed a bit by the own systems and the CI / Github Actions system).

**Comment by Stewori** [comment] 2021-03-18 14:04
I would offer to checkout whether it works with gcc 6. Can we safely assume that it works with >=7? Then checking 6 would at least pin the required (major) gcc version.

**Comment by albert-github** [comment] 2021-03-18 14:37
I only know that with gcc version 7.5 doxygen does compile (used by github actions), I don't know about other 7.x versions or the different gcc 6.x versions.
The problem is of course that with forthcoming changes in the doxygen code the minimal version might not be correct anymore, so the minimum version might be a bit of a moving target for the master version. Even the default version used by github actions might change at the moment the system uses Ubuntu 18.04 LTE, but I've read that they want to change to switch to version 20.04 (looks like gcc versions remain the same).
At the moment we can say that doxygen compiles with gcc 7.5.0 but for the future ...

**Comment by Stewori** [comment] 2021-03-18 16:06
Sure, such a version info would need some update from time to time. But I would believe that it would last several years. Or just add a hint "The newest gcc version that is known to fail in compiling Doxygen is gcc 5.4." Then an update of this info would be optional as it stays true forever :)
Anyway, feel free to close this issue.

**Closed** 2021-08-18 20:25 UTC
Labels: install/build, Usage
