### ISSUE TITLE
dot file gets deleted too early if DOT_CLEANUP = YES (at least on windows)

### ISSUE THREAD

**Issue by cmorty** [doxygen/doxygen#6960] opened 2019-05-03 13:47 UTC
Version: 1.8.15 Windows
Output: SVG

I have a reproduceable environment where the `.dot` file is deleted before dot is run if `DOT_CLEANUP` is set to `yes`. This only happens on the second run if the target folder is not yet empty. Deleting all dot files manually works fine if  `DOT_CLEANUP`is set to `no`.

I traced this using procmon. As you can see at `15:41:07,7761734` the files is marked for deletion, before `dot` tries to open it and fails.

[doxy.log](https://github.com/doxygen/doxygen/files/3142131/doxy.log)

**Comment by albert-github** [comment] 2019-05-03 14:08
As described it looks like a race condition, but it is a bit strange to me that every time the file `C:\mypath\doc\html\de\d5c\a01708_a11d6d240c4d4eb4224e907766ceea3af_icgraph.dot` is used in the messages.

Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by cmorty** [comment] 2019-05-03 16:14
Ok, I spent some time digging into this. Seems like `DotClassGraph::writeGraph` gets called multiple times (5 in my case) for the same file.  For the last call the regenerate check matches and it deletes the `.dot` (`if (!regenerate) removeDotGraph(absDotName);`). 
Unfortunately I'm not too familiar with debugging QT using VS and QString is giving me a hard time.
Feel free to give me pointers, as I actually have a running build system. ;)

**Comment by albert-github** [comment] 2019-05-03 16:22
Is the code propriety code or open source code (so we can see if we can share it), it is hard to tell where to look without an example. The idea I currently have is that there is a class / namespace that is multiple times defined.

**Comment by cmorty** [comment] 2019-05-06 06:37
Unfortunately is proprietary and from a customer. But I'll try to invest some time to track this down.

**Comment by thomas-haller** [comment] 2019-05-09 12:04
I produced a code example for this bug(s).
[doxygen_test.zip](https://github.com/doxygen/doxygen/files/3161922/doxygen_test.zip)

Execute "doxygen doxygen/Doxyfile.Demo" twice. At the second run, it will fail (twice) to run dot because the .dot file got deleted and it will run dot twice on another .dot file. So there are two bugs.
This was reproduced here with trunc version in Windows 10 and with version 1.8.13 in Ubuntu.

My understanding of the bugs so far (names are related to the example):

The caller graph for AVehicle::crash is first needed in the compound AVehicle. As the md5 is the same as the file stored from the first run, the .dot file is deleted.
Then it is needed in the compound Bicycle. The md5 is a different one now! The reason is that the node numbers in the .dot file are different. The .dot file is created and it is marked for calling dot.
Then it is needed in the compound Car. The md5 is again a different one! It is marked again for calling dot.
In the phase of calling dot, dot is called twice for this file because it is marked twice. Only one run would be needed here. (first bug)

The caller graph for AVehicle::factory is first needed in the compound AVehicle. The md5 is different from the file of the last run, so it is marked for calling dot.
Then it is needed in the compound Bicycle. The md5 is again different (due to the node numbers), so it is marked again for calling dot.
Then it is needed in the compound Car. The md5 is the same as from the test in Bicycle so the .dot file is now deleted!
In the phase of calling dot, dot is called twice (again first bug), but the .dot file got deleted, so both runs fail (second bug)

**Comment by albert-github** [comment] 2019-05-09 12:15
With the given example I can reproduce the problem on Windows and Cygwin with the master version.
@thomas-haller thanks for the example.

**Comment by albert-github** [comment] 2019-05-18 08:30
Code (#6987) has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Closed** 2019-12-27 19:52 UTC
Labels: bug, solved in the mean time
