### ISSUE TITLE
Two minor issues with strange warnings

### ISSUE THREAD

**Issue by numericalfreedom** [doxygen/doxygen#7259] opened 2019-09-13 04:13 UTC
Two minor issues with strange warnings:

1) Multiple use of page label warning:
filetwo.dox:3: warning: multiple use of page label 'PAG_page_for_proc', (other occurrence: /home/users/tamas/tmp/doxygen/fileone.dox, line: 3)
filethree.dox:3: warning: multiple use of page label 'PAG_page_for_proc', (other occurrence: /home/users/tamas/tmp/doxygen/filetwo.dox, line: 3)

2) Found unknown command '\PROC warning:
filethree.dox:3: warning: Found unknown command '\PROC'
filethree.dox:3: warning: Found unknown command '\PROC'

ThanX for great product !

[MinorIssueWithWarnings.zip](https://github.com/doxygen/doxygen/files/3608361/MinorIssueWithWarnings.zip)

**Comment by albert-github** [comment] 2019-09-13 09:20
Regarding point 1.
in the files: `fileone.dox`, `filethree.dox` and `filetwo.dox` you have the construct `@page PAG_page_for_proc...` and as section labels are global you have 3 times the same label. So I think this problem is usage.

Regarding point 2. has to be investigated further.

**Comment by albert-github** [comment] 2019-09-13 15:53
Regarding point 2.
Due to the problem mentioned under point 1. the real messages are a bit hidden. When having separate pages we get the messages:
```
Generating docs for page PAG_page_for_proc1...
.../fileone.dox:3: warning: Found unknown command '\PROC'
.../fileone.dox:3: warning: Found unknown command '\PROC'
Generating docs for page PAG_page_for_proc2...
.../filetwo.dox:3: warning: Found unknown command '\PROC'
.../filetwo.dox:3: warning: Found unknown command '\PROC'
```

In the \@page` of the first and second page we see the command `\PROC` and this command is not defined. We don't get a message about the commands `@PROCONE` etc as this command is not parsed, see for this #6998 and #7153 

Conclusion:
- point 1 is usage
- point 2 is a duplicate of #6998 and #7135

**Closed** 2019-12-27 19:54 UTC
Labels: Usage, duplicate
