### ISSUE TITLE
Warning parameters of member <fn> not (all) documented for base class when using tag file (Origin: bugzilla #786795)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6244] opened 2018-07-02 13:05 UTC
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Example.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug786795_358389_Example.zip/download/download)_ (ID 358389)

On 2017-08-25 11:40:13 +0000, axelwaldheim@gmx.de wrote:

    Created attachment 358389
    Example code, doxyfiles and generated documentation
    
    The following warning is incorrectly issued when e.g. 
      - having 2 modules - module1 and module2
      - module2 depends on module1 by deriving from a class defined in module1 
      - the base class contains a fully documented (no warnings when generating
    documentation for module1) function that is not overridden in derived class
      - the function does not even have parameters
      - a tag file is used for module1 when generating the documentation for
    module2
    
    "module1.tag(1): warning: parameters of member Foo::blah are not (all)
    documented"
    
    This refers to a set up where the base class function is not intended to be
    overwritten but will just be used.
    
    A code sample along with the doxyfiles and the generated documentation is
    attached.
    
    Note that referencing the documention of module1 from module2 works (one can
    nvaigate from derived class documentation to base class documentation) which
    indicates that the tag file related configuration is valid.

**Comment by kingfisher63** [comment] 2019-12-29 10:34
I ran into this one today. As far as I can tell this only happens if WARN_NO_PARAMDOC is set to YES.

Since tag files do not contain parameter documentation for class members, my suggestion would be to ignore the value of WARN_NO_PARAMDOC (and assume NO) for class members from tag files.

**Comment by albert-github** [comment] 2020-01-02 15:44
@kingfisher63 

I tried to reproduce the problem with 1.8.17 but here I didn't see the message and with version 1.8.13 I do see the message.

- did you use version 1.8.17?
- did you see the problem with the example as provided in the original issue?
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by kingfisher63** [comment] 2020-01-05 17:42
This appears not to happen with 1.8.17, so I have now upgraded my system.

I searched open issues and found this one, but I didn't search closed issues. If I had done so, I would have found issue #6262 which was resolved in 1.8.14 !

Are this issue and #6262 duplicates? If so, this one can be closed too.

**Comment by albert-github** [comment] 2020-01-05 17:45
As far as I can see this one is a duplicate of #6262

**Closed** 2020-04-13 11:50 UTC
Labels: duplicate, solved in the mean time
