### ISSUE TITLE
Issue with "/// @}"

### ISSUE THREAD

**Issue by makelinux** [doxygen/doxygen#8815] opened 2021-10-05 03:46 UTC
Sometimes single-line instructions 
```
/// @}
/// \}
/**  @} */
```
don't close groups as expected.

Multi-line one
```
/**
@}
*/
```
works as expected.

Reproduced and worked around in https://github.com/makelinux/examples/commit/9f6e350d8b4438d4de7c7d607ada8a5db2a7b549

**Comment by albert-github** [comment] 2021-10-05 08:42
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by albert-github** [comment] 2021-12-25 09:39
Due to the (automatic) link with the pull request this issue was automatically closed as the code was integrated in master on github.
Reopening issue, please don't close the issue as this will be done at the moment of an official release.

**Comment by doxygen** [comment] 2021-12-31 11:10
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2021-12-31 11:10 UTC
Labels: bug
