### ISSUE TITLE
SIGSEGV presumably caused by C++ "using" declaration

### ISSUE THREAD

**Issue by gagern** [doxygen/doxygen#6597] opened 2018-11-04 23:58 UTC
Investigating https://bugs.gentoo.org/670230 I found that since 1.8.14 or more precisely (via git bisect) since 9468ede259153cf79eb8d61635389744e9a2ee7d doxygen will segfault when building the documentation for https://download.kde.org/stable/oxygen-gtk2/1.4.6/src/oxygen-gtk2-1.4.6.tar.bz2.

Investigating a bit via gdb I find https://github.com/doxygen/doxygen/blob/Release_1_8_14/src/defgen.cpp#L152 passing `defAl = nullptr` to `ArgumentListIterator`. The `MemberDef` argument `md` contains some strings indicating that `"connect"` is the symbol in question. Connecting this with the subject of the problematic commit mentioned above suggests that one of the declarations `using FollowMouseData::connect` in the oxygen-gtk2 code would be to blame here. But so far I haven't been able to produce a minimal reproducing example of this.

I don't care too much about the oxygen docs in particular, but I thought you might care about doxygen segfaulting for some input in a reproducible way.

**Comment by albert-github** [comment] 2018-11-05 11:13
A crash is never good especially when it is not clear what the cause is.
Workaround is in this case to disable the generation of the AutoGen documentation, but this means in a, probably unwanted, loss of functionality for the oxygen package

I've just pushed a proposed patch, pull request #6598

**Comment by albert-github** [comment] 2018-11-10 12:44
Code has been integrated in master on github.

**Comment by doxygen** [comment] 2018-12-27 21:47
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2018-12-27 21:47 UTC
Labels: C/C++, bug
