### ISSUE TITLE
The function is missing when using doxygen-1.9.4 in Windows

### ISSUE THREAD

**Issue by kunzeng-ch** [doxygen/doxygen#9486] opened 2022-08-01 11:33 UTC
Hi, sorry to bother you！When I apply doxygen-1.9.4 to generate call graph and caller graph, I get a problem that the functions defined in between `#if (condition)` and `#endif` are not in the graph. The conditions are all capital letters like `NGX_HAVE_EVENTFD`,`NGX_TEST_BUILD_EPOLL`. All functions defined outside of `#if (condition) ... #endif` are in the graph. This question has troubled me for a long time, and I look forward to your reply to help me solve my doubts.  My configuration follow this url: https://blog.csdn.net/fly542/article/details/7164633/

**Comment by albert-github** [comment] 2022-08-01 11:40
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by kunzeng-ch** [comment] 2022-08-01 13:38
Here are my source codes and configuration file. For example, some functions in codes\modules\ngx_epoll_module.c missed, such as epoll_create, epoll_ctl and io_destroy.


| |
13247194792
|
|
***@***.***
|
On 8/1/2022 ***@***.***> wrote：

Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by kunzeng-ch** [comment] 2022-08-01 13:40
I have send my source codes and configuration file to you by email. Looking forward to your reply, thank you！

**Comment by albert-github** [comment] 2022-08-01 13:45
I didn't receive the source code (and it isn't in the spam box either), for completeness it should anyway be added to the issue. At the bottom of a comment you see:

![image](https://user-images.githubusercontent.com/5223533/182161178-e37b53c9-e171-4d2c-8231-0b77fe7fe417.png)

Clicking on it gives you the possibility to attach a file to the comment.

**Comment by albert-github** [comment] 2022-08-01 13:58
I just created a small example:

**source code**

```
/// \file

/// the define
#define NGX_HAVE_EVENTFD_EXIST 1

#if (NGX_HAVE_EVENTFD_EXIST)
/// the conditional fie
void fie_cond_exist() {}
#endif

#if (NGX_HAVE_EVENTFD)
/// the conditional fie
void fie_cond() {}
#endif

/// the unconditional fie
void fie_uncond() {}

/// the fie
void fie()
{
  fie_uncond();
#if (NGX_HAVE_EVENTFD)
  fie_cond();
#endif
#if (NGX_HAVE_EVENTFD_EXIST)
  fie_cond_exist();
#endif
}
```
**Doxyfile** settings
```
QUIET = YES
HAVE_DOT = YES
CALL_GRAPH = YES
CALLER_GRAPH = YES
MACRO_EXPANSION = YES
ALWAYS_DETAILED_SEC = YES
```
and this gives (doxygen 1.9.4 (5d15657a55555e6181a7830a5c723af75e7577e2)):

![image](https://user-images.githubusercontent.com/5223533/182164028-9ddcab7e-b368-42c2-a0f1-3d2a479fdce7.png)

This looks all OK to me.


Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/9234447/example.tar.gz)

**Comment by kunzeng-ch** [comment] 2022-08-02 01:19
I am sorry for the failure to send packets yesterday due to network reasons. Here are the part of nginx source codes and my configuration file.[data.zip](https://github.com/doxygen/doxygen/files/9238306/data.zip)

**Comment by kunzeng-ch** [comment] 2022-08-02 07:21
> I just created a small example:
> 
> **source code**
> 
> ```
> /// \file
> 
> /// the define
> #define NGX_HAVE_EVENTFD_EXIST 1
> 
> #if (NGX_HAVE_EVENTFD_EXIST)
> /// the conditional fie
> void fie_cond_exist() {}
> #endif
> 
> #if (NGX_HAVE_EVENTFD)
> /// the conditional fie
> void fie_cond() {}
> #endif
> 
> /// the unconditional fie
> void fie_uncond() {}
> 
> /// the fie
> void fie()
> {
>   fie_uncond();
> #if (NGX_HAVE_EVENTFD)
>   fie_cond();
> #endif
> #if (NGX_HAVE_EVENTFD_EXIST)
>   fie_cond_exist();
> #endif
> }
> ```
> 
> **Doxyfile** settings
> 
> ```
> QUIET = YES
> HAVE_DOT = YES
> CALL_GRAPH = YES
> CALLER_GRAPH = YES
> MACRO_EXPANSION = YES
> ALWAYS_DETAILED_SEC = YES
> ```
> 
> and this gives (doxygen 1.9.4 ([5d15657](https://github.com/doxygen/doxygen/commit/5d15657a55555e6181a7830a5c723af75e7577e2))):
> 
> ![image](https://user-images.githubusercontent.com/5223533/182164028-9ddcab7e-b368-42c2-a0f1-3d2a479fdce7.png)
> 
> This looks all OK to me.
> 
> Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/9234447/example.tar.gz)

Thank you for your reply！I tried the configuration file you uploaded, but it still miss those functions such as epoll_create, epoll_ctl and io_destroy in codes\modules\ngx_epoll_module.c

**Comment by albert-github** [comment] 2022-08-02 08:37
In your `Doxyfile` I see:
```
INPUT                  = D:/nginx-release-1.21.6/src/event
```
though in the `data` directory of `data.zip` I see just the directories `./codes` and its subdirectory `./codes/modules` but I assume you meant to have in the input settings:
```
INPUT = codes
```
or its full path.

In your `Doxyfile` you have:
```
ENABLED_SECTIONS       = NGX_TEST_BUILD_EPOLL \
                         NGX_HAVE_EVENTFD \
                         NGX_HAVE_FILE_AIO \
                         NGX_HAVE_EPOLLRDHUP
```
these settings are for the doxygen commands like `\if` and `\cond` but **not**  for the preprocessor commands like `#if`. For the later one can use the setting `PREDEFINED` like:
```
PREDEFINED       = NGX_TEST_BUILD_EPOLL=1 \
                         NGX_HAVE_EVENTFD=1 \
                         NGX_HAVE_FILE_AIO=1 \
                         NGX_HAVE_EPOLLRDHUP=1
```

Now I do see the mentioned functions.

I think the problem is usage.

**Comment by kunzeng-ch** [comment] 2022-08-02 08:57
> In your `Doxyfile` I see:
> 
> ```
> INPUT                  = D:/nginx-release-1.21.6/src/event
> ```
> 
> though in the `data` directory of `data.zip` I see just the directories `./codes` and its subdirectory `./codes/modules` but I assume you meant to have in the input settings:
> 
> ```
> INPUT = codes
> ```
> 
> or its full path.
> 
> In your `Doxyfile` you have:
> 
> ```
> ENABLED_SECTIONS       = NGX_TEST_BUILD_EPOLL \
>                          NGX_HAVE_EVENTFD \
>                          NGX_HAVE_FILE_AIO \
>                          NGX_HAVE_EPOLLRDHUP
> ```
> 
> these settings are for the doxygen commands like `\if` and `\cond` but **not** for the preprocessor commands like `#if`. For the later one can use the setting `PREDEFINED` like:
> 
> ```
> PREDEFINED       = NGX_TEST_BUILD_EPOLL=1 \
>                          NGX_HAVE_EVENTFD=1 \
>                          NGX_HAVE_FILE_AIO=1 \
>                          NGX_HAVE_EPOLLRDHUP=1
> ```
> 
> Now I do see the mentioned functions.
> 
> I think the problem is usage.

I am sorry for wrong code path. The folder named event is equal to the folder named codes. I forgot to modify the code path in the configuration file. I have tried the method, I can see the functions missed before. But I get the problems: "D:/doxygen/doxygen/nginx/html/ngx__string_8h_acf81b027bc137c6e2a8b5dea23a7dd9e_icgraph.dot:1: error: Problems running dot: exit code=-1073741819, command='D:\graphviz\bin\dot.exe', arguments='"D:/doxygen/doxygen/nginx/html/ngx__string_8h_acf81b027bc137c6e2a8b5dea23a7dd9e_icgraph.dot" -Tgif -o "D:/doxygen/doxygen/nginx/html/ngx__string_8h_acf81b027bc137c6e2a8b5dea23a7dd9e_icgraph.gif"'

error: problems opening map file D:/doxygen/doxygen/nginx/html/ngx__string_8h_acf81b027bc137c6e2a8b5dea23a7dd9e_icgraph.map for inclusion in the docs!
If you installed Graphviz/dot after a previous failing run, 
try deleting the output directory and rerun doxygen.".
I have installed the Graphviz/dot, but i get the problem. Trying again, the same problem still exists.

**Comment by kunzeng-ch** [comment] 2022-08-02 09:01
This is my new configuration file.
[configuration.zip](https://github.com/doxygen/doxygen/files/9240669/configuration.zip)

**Comment by albert-github** [comment] 2022-08-02 09:31
I tried your configuration file with the source code and it ran without problems but I don't have a file `ngx_string.h` from which the error comes.
- which version of dot (`dot -V`) are you using?
- also good
   - to set `DOT_CLEANUP=NO` so the original dot files will still exist (so we can run some separate tests just on the file `ngx__string_8h_acf81b027bc137c6e2a8b5dea23a7dd9e_icgraph.dot`
   - run doxgen like `doxygen -d extcmd` so we know exactly which extrebnal commands have been executed (and especially those involving `ngx__string_8h_acf81b027bc137c6e2a8b5dea23a7dd9e_icgraph`
- I noticed that you use `DOT_FORMAT=gif`
  - is there as special reason for this? 
  - what happens when you use `DOT_FORMAT=png` or `DOT_DOMAT=svg` (in the later case maybe also set `INTERACTIVE_SVG=YES`)

**Comment by kunzeng-ch** [comment] 2022-08-02 12:13
> I tried your configuration file with the source code and it ran without problems but I don't have a file `ngx_string.h` from which the error comes.
> 
> * which version of dot (`dot -V`) are you using?
> * also good
>   
>   * to set `DOT_CLEANUP=NO` so the original dot files will still exist (so we can run some separate tests just on the file `ngx__string_8h_acf81b027bc137c6e2a8b5dea23a7dd9e_icgraph.dot`
>   * run doxgen like `doxygen -d extcmd` so we know exactly which extrebnal commands have been executed (and especially those involving `ngx__string_8h_acf81b027bc137c6e2a8b5dea23a7dd9e_icgraph`
> * I noticed that you use `DOT_FORMAT=gif`
>   
>   * is there as special reason for this?
>   * what happens when you use `DOT_FORMAT=png` or `DOT_DOMAT=svg` (in the later case maybe also set `INTERACTIVE_SVG=YES`)

OK! I tried it. But I have a question: If a function is used as an attribute of a Struct, and other functions call hidden functions through this Struct, can this be displayed in the graph?

For example:
static ngx_event_module_t  ngx_epoll_module_ctx = {
    &epoll_name,
    ngx_epoll_create_conf,               /* create configuration */
    ngx_epoll_init_conf,                 /* init configuration */

    {
        ngx_epoll_add_event,             /* add an event */
        ngx_epoll_del_event,             /* delete an event */
        ngx_epoll_add_event,             /* enable an event */
        ngx_epoll_del_event,             /* disable an event */
        ngx_epoll_add_connection,        /* add an connection */
        ngx_epoll_del_connection,        /* delete an connection */
#if (NGX_HAVE_EVENTFD)
        ngx_epoll_notify,                /* trigger a notify */
#else
        NULL,                            /* trigger a notify */
#endif
        ngx_epoll_process_events,        /* process the events */
        ngx_epoll_init,                  /* init the events */
        ngx_epoll_done,                  /* done the events */
    }
};
Ngx_epoll_create_conf,ngx_epoll_init_conf,ngx_epoll_del_event and so on are functinos. If a funtion call the ngx_epoll_init_conf by struct(maybe take an alias for take an alias for the function), will function -> take an alias for the function show in the call graph?

**Comment by albert-github** [comment] 2022-08-02 12:22
> OK! I tried it.

What are the results?

Doxygen is not very good in resolving functions through pointers (doxygen is not a compiler) so this might definitely be the problem you see.

**Comment by kunzeng-ch** [comment] 2022-08-02 12:24
> 

The results is normal, thank you very much!

**Comment by kunzeng-ch** [comment] 2022-08-02 12:29
Yes, I set png, the error disappeared.

**Comment by albert-github** [comment] 2022-08-02 12:33
In that case it is, from a doxygen point of view, important to know what caused the problem with the map when using the gif  setting. 
- So please provide the information as requested i.e. the dot version you are using and the `ngx__string_8h_acf81b027bc137c6e2a8b5dea23a7dd9e_icgraph.dot` file when you use gif.

**Comment by kunzeng-ch** [comment] 2022-08-02 12:37
dot - graphviz version 2.50.0 (20211204.2007). The gif file has been deleted.

**Comment by albert-github** [comment] 2022-08-02 12:42
It would be good to recreate the gif file and the accompanying dot file (setting `DOT_CLEANUP=NO`) so you can post this dot file and we can do some tests on it.

**Comment by kunzeng-ch** [comment] 2022-08-03 03:16
Hello! I tried to recreate the gif file, but I found some funtions called by a function missed.
For example, the functino ngx_epoll_done in the file: nginx-release-1.21.6\src\event\modules\ngx_epoll_module.c

static void ngx_epoll_done(ngx_cycle_t *cycle)
{
    if (close(ep) == -1) {
        ngx_log_error(NGX_LOG_ALERT, cycle->log, ngx_errno,
                      "epoll close() failed");
    }

    ep = -1;

#if (NGX_HAVE_EVENTFD)

    if (close(notify_fd) == -1) {
        ngx_log_error(NGX_LOG_ALERT, cycle->log, ngx_errno,
                      "eventfd close() failed");
    }

    notify_fd = -1;

#endif

#if (NGX_HAVE_FILE_AIO)

    if (ngx_eventfd != -1) {

        if (io_destroy(ngx_aio_ctx) == -1) {
            ngx_log_error(NGX_LOG_ALERT, cycle->log, ngx_errno,
                          "io_destroy() failed");
        }

        if (close(ngx_eventfd) == -1) {
            ngx_log_error(NGX_LOG_ALERT, cycle->log, ngx_errno,
                          "eventfd close() failed");
        }

        ngx_eventfd = -1;
    }

    ngx_aio_ctx = 0;

#endif

    ngx_free(event_list);

    event_list = NULL;
    nevents = 0;
}

![image](https://user-images.githubusercontent.com/49545228/182516076-d9af1b4a-7db7-47ea-a790-28dace956a54.png)
The call graph of ngx_epoll_done missed ngx_log_error, ngx_free, close. Can you help me find the problem? Here are the data and the new configuration file.
[data.zip](https://github.com/doxygen/doxygen/files/9247667/data.zip)

**Comment by albert-github** [comment] 2022-08-03 09:31
When running your example under windows I got some messages regarding dot:
```
error: Could not read image 'D:/.../data/html/df/d49/ngx__string_8c_a6839b402bef5763a2156267b585467f6_icgraph.png' generated by dot!
error: Could not read image 'D:/.../data/html/df/d49/ngx__string_8c_a9a1deb0ca794a055db9a74cd997b691d_icgraph.png' generated by dot!
error: Could not read image 'D:/.../data/html/df/d49/ngx__string_8c_ae82357cb61d8c6eb3220d8648c969196_icgraph.png' generated by dot!
error: Could not read image 'D:/.../data/html/df/d74/ngx__string_8h_ae82357cb61d8c6eb3220d8648c969196_icgraph.png' generated by dot!
```

I did some tests with `ngx__string_8c_a6839b402bef5763a2156267b585467f6_icgraph.dot`:
- When I ran, under Windows, with  dot 2.38.0 I got that the resulting file was 0 bytes in size.
- When I ran, under Cygwin, with dot 2.50.0 all went well.
- When I ran, under Windows, with dot 4.0.0 all went well as well.

So I think the problem is that with the 2.38.0 version I ran into a 32-bit memory problem and that you might have had the same problem with the 2.50.0 version generating gif files. Under Cygwin this memory problem was not present.
It looks like in the newer version the memory problem has been solved regarding the Windows 32-bit version though it might be a good idea to install the 64-bit version (Note: there is also a 5.0.0 version available).


The size of the mentioned graph is very large and in my opinion useless due to the fact that everything is very small, I think a better choice might be to have the interactive svg as indicated before.

**Comment by kunzeng-ch** [comment] 2022-08-03 09:49
> When running your example under windows I got some messages regarding dot:
> 
> ```
> error: Could not read image 'D:/.../data/html/df/d49/ngx__string_8c_a6839b402bef5763a2156267b585467f6_icgraph.png' generated by dot!
> error: Could not read image 'D:/.../data/html/df/d49/ngx__string_8c_a9a1deb0ca794a055db9a74cd997b691d_icgraph.png' generated by dot!
> error: Could not read image 'D:/.../data/html/df/d49/ngx__string_8c_ae82357cb61d8c6eb3220d8648c969196_icgraph.png' generated by dot!
> error: Could not read image 'D:/.../data/html/df/d74/ngx__string_8h_ae82357cb61d8c6eb3220d8648c969196_icgraph.png' generated by dot!
> ```
> 
> I did some tests with `ngx__string_8c_a6839b402bef5763a2156267b585467f6_icgraph.dot`:
> 
> * When I ran, under Windows, with  dot 2.38.0 I got that the resulting file was 0 bytes in size.
> * When I ran, under Cygwin, with dot 2.50.0 all went well.
> * When I ran, under Windows, with dot 4.0.0 all went well as well.
> 
> So I think the problem is that with the 2.38.0 version I ran into a 32-bit memory problem and that you might have had the same problem with the 2.50.0 version generating gif files. Under Cygwin this memory problem was not present. It looks like in the newer version the memory problem has been solved regarding the Windows 32-bit version though it might be a good idea to install the 64-bit version (Note: there is also a 5.0.0 version available).
> 
> The size of the mentioned graph is very large and in my opinion useless due to the fact that everything is very small, I think a better choice might be to have the interactive svg as indicated before.

OK！You are right. These pictures really don't do much for me. I only need the dot file. I suspect that the previous problem is also a version problem. Thank you very much for your careful reply.But I have been thinking about this problem for a day and still can't find the reason why the function is missing as https://github.com/doxygen/doxygen/issues/9486#issuecomment-1203435658) discribed.

**Comment by albert-github** [comment] 2022-08-03 09:59
The `close` problem is most likely due to the fact that this is a standard function and that it is not defined in any way in the code (it is of course  declared in a system .h file).
The `ngx_free` problem  is probably similar as this is defined as `free` (Note that there are 2 files that define the `ngx_free`, this might anyway lead to problems).

The `ngx_log_error` has to be investigated a bit further, but this is redefined as `ngx_log_error_core` which looks like a normal function.

**Comment by albert-github** [comment] 2022-08-03 10:50
I've been thinking about the problem and I, vaguely, remember that the problem is cased by the fact that a `define` is used and that this is not taken into account when generating the code (this is also used for generating the call / caller graphs), hence the missing references to ngx_free / free and ngx_log_error / ngx_log_error_core
I think there is already an issue about this matter but I cannot find it.

**Comment by kunzeng-ch** [comment] 2022-08-04 01:15
Is there any way to solve these three problems? In addition to the close function, I found that the other two functions are defined

**Comment by kunzeng-ch** [comment] 2022-08-04 07:47
Hello! I used doxygen to analysis the java codes(log4j2). Howere, after waiting for a long time, no relevant files have been generated. There are only two files index.hhc and index.hhk in the html folder. Here are my codes and configuration file.
Source codes in the url: https://github.com/apache/logging-log4j2/tree/rel/2.17.2
Configuration: [log4j2.zip](https://github.com/doxygen/doxygen/files/9257678/log4j2.zip)

**Comment by albert-github** [comment] 2022-08-04 08:49
Don't mix multiple topics in one issue, when you have a separate issue create a separate issue.
Note a link to a github (or any other repository) is not a good idea as this is a moving target, so a local problem might be solved and at that movement the original problem is not reproducible anymore. Also when the original problem is solved this can not be properly signaled as the issue is polluted with another issue.
Furthermore the complete repository contains a lot of unnecessary files. So please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

I did a quick test and under Windows it looks like doxygen goes into an endless loop (with the 1.9.4 version but also with the self build master, 1.9.5 (5763255ba4fb02b7fa11300515f46fbfda38180e),  version with "Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29914 for x64").
When I ran under Cygwin all looks to be OK

All in all this probler requires a new issue.

**Comment by kunzeng-ch** [comment] 2022-08-04 09:21
I wonder if you still remember how this problem(https://github.com/doxygen/doxygen/issues/9486#issuecomment-1203787956) was solved before. I tried to find the issue, but I have not found it yet.

**Comment by albert-github** [comment] 2022-08-04 09:39
As far as I remember it has not been solved yet.

**Comment by kunzeng-ch** [comment] 2022-08-04 09:44
Can you let me know when the problem is solved, after all, the current graph is incomplete due to the lack of some functions。

**Comment by albert-github** [comment] 2022-08-04 09:53
When a solution is present it most likely will be posted here.

**Closed** 2022-08-26 17:01 UTC
Labels: C/C++, Usage
