### ISSUE TITLE
VHDL attribute 'subtype is not supported and breaks parser

### ISSUE THREAD

**Issue by Fixitfetish** [doxygen/doxygen#7313] opened 2019-10-10 21:05 UTC
**Case 1**  : in file/entity bla1 signal declaration in architecture
179 `signal temp1  : in1'subtype;`

Parsing files
Reading C:/temp/bla1.vhdl...
C:/temp/bla1.vhdl:179: warning: syntax error '''
Reading C:/temp/bla2.vhdl...
Reading C:/temp/bla3.vhdl...

**Case 2**  : in file/entity bla1 variable declaration in procedure
106  `variable temp1  : in1'subtype;`

Parsing files
Reading C:/temp/bla1.vhdl...
C:/temp/bla1.vhdl:106: warning: syntax error '''
C:/temp/bla1.vhdl:110: warning: syntax error 'if'       _(comment: parser already fails at following IF statement within procedure)_
Reading C:/temp/bla2.vhdl...
Reading C:/temp/bla3.vhdl...
…
Computing nesting relations for classes...
C:/temp/bla2.vhdl:65: warning: Internal inconsistency: scope for class bla2::rtl not found!

**PROBLEM** :  In case 2 the bla2 entity and architecture is not generated  correctly and missing, i.e. the entity bla2 parsed after the entity bla1 with ‘subtype has a problem but not the entity bla1

**Temporary work-around ;** use duplicated type with ‘range attribute instead of 'subtype attribute
`signal temp1 : std_logic_vector(in1‘range);` 
`variable temp1 : std_logic_vector(in1‘range);`

**Comment by albert-github** [comment] 2019-10-11 07:58
I see that in the vhdl parser the word "subtype" does exist, so I would expect that it is supported (though there always might be problems):
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problems?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

**Comment by Fixitfetish** [comment] 2019-10-11 10:11
As a first quick feedback ... I am using Doxygen 1.8.16

In VHDL the keyword subtype is used in two ways
1. to declare/define a new type which is a subtype of another type
2. to declare signals/variables which have the same type then another signal/variable

The second uses the subtype attribute and doesn't seem to be supported by doxygen. 

If I find the time I try to provide self contained example.

**Comment by albert-github** [comment] 2019-10-11 10:19
Is the second use new to VHDL, if so is it in the VHDL standard?  or is it in the 'IEEE Std 1076™-2008' (I didn't find it, yet, in this version)?
In the first case please provide a link to the, free, new standard, in the second case please provide the appropriate paragraph number (and name).

An example or a reference to an example is highly appreciated (understatement).

**Comment by Fixitfetish** [comment] 2019-10-11 13:45
Yes, the second is new with VHDL-2008 while the first exists much longer already.
I search for "VHDL 2008 subtype attribute" and found "VHDL-2008 : Just the new stuff" in books.google.de. At the end of chapter 3.1 (page 121) there is a good description and example. 

In the standard 1076-2008 the subtype is listed under "16.2.2 Predefined attributes of types and objects" (Unfortunately I can't share this document for legal reasons.)
**O'SUBTYPE**
Kind : Subtype.
Prefix : Any prefix O that is appropriate for an object, or an alias thereof.
Result : The fully constrained subtype that is the subtype of O, together with constraints defining any index ranges that are determined by application of the rules of 5.3.2.2. (If O is an alias for an object, then the result is determined by the declaration of O, not that of the object.)

**Comment by albert-github** [comment] 2019-10-11 14:01
Thanks.

I edited the link of the example into your comment, looks a nice example (unfortunately no cut and paste).
I also saw the description in the standard.

There are a few more `'` constructs. The type of construct is horrible as doxygen normally sees a `'` in relation to character variables / strings (as a side not I filed this morning an issue #7314 where I was wondering where a certain construct regarding `'` was coming from, looks like you provided the answer, @doxygen is this the use case I asking for?).

I see that there are other constructs with `'` as well in chapter 16, is this a fixed list of "strings/functions" or can the user define also its own "strings/functions" to be used with `'`?

**Comment by albert-github** [comment] 2019-10-11 17:12
I was now able to reproduce the problem buy means of the given example (btw. I think it is not correct as the name of the procedure is not equal to the name with the end statement).

I used another example and put here the procedure in (will not make any VHDL sense, but that is irrelevant for solving the problem).

The example: [example.tar.gz](https://github.com/doxygen/doxygen/files/3718801/example.tar.gz)

This gives the warnings:
```
.../issue_7313/aa.vhdl:23: warning: syntax error '''
.../issue_7313/aa.vhdl:27: warning: syntax error 'temp'
.../issue_7313/aa.vhdl:8: warning: Internal inconsistency: scope for class ex_procedure_simple::behave not found!
```

**Comment by Fixitfetish** [comment] 2019-10-12 17:45
I modified the example so that the keyword `subtype` is used more often. The [example_subtype.zip](https://github.com/doxygen/doxygen/files/3720980/example_subtype.zip) now also compiles with GHDL while the doxygen issue remains .

**Comment by albert-github** [comment] 2019-10-17 13:15
@Fixitfetish I did have a go at the problem and got some output without warnings based on your example. Can you see whether this output is correct? Thanks in advance.

The output I get is: [new_output.tar.gz](https://github.com/doxygen/doxygen/files/3739415/new_output.tar.gz)

**Comment by Fixitfetish** [comment] 2019-10-17 21:31
@albert-github The output concerning the subtype attribute looks good and sufficient to me - nothing to complain about. 

The only thing which is a bit unusual are the "Member Function/Data Documentation" sections at the end of the pages. Looks a bit like C style. I don't see that in VHDL documentations I generate. But this might be just a config setting issue !?

**Comment by albert-github** [comment] 2019-10-18 07:54
The difference might be due to the setting of `OPTIMIZE_OUTPUT_VHDL`, I did set it and this also gives the messages:
```
warning: enabling OPTIMIZE_OUTPUT_VHDL assumes the following settings:
  INHERIT_DOCS           = NO (was YES)
  HIDE_SCOPE_NAMES       = YES (was NO)
  EXTRACT_PRIVATE        = YES (was NO)
  ENABLE_PREPROCESSING   = NO (was YES)
  EXTRACT_PACKAGE        = YES (was NO)
```

**Comment by albert-github** [comment] 2019-10-18 08:22
I've just pushed a proposed patch, pull request #7334

**Comment by Fixitfetish** [comment] 2019-10-18 18:57
Thanks a lot!  Let's hope the fix makes it into the next release.

**Comment by albert-github** [comment] 2019-12-10 20:23
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment] 2019-12-27 19:39
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2019-12-27 19:39 UTC
Labels: VHDL, bug
