### ISSUE TITLE
Using markdown causes wrong error and warning line numbers - v. 1.8.16

### ISSUE THREAD

**Issue by gsokhran** [doxygen/doxygen#7228] opened 2019-08-27 07:57 UTC
A pure markdown file and a source file showing the problem

When markdown is used in a comment or a markdown file, error and warnings produced by doxygen point to the wrong line numbers.

The attached file has 109 lines in total, but doxygen shows warnings on line 174, 178, ..
Warning example: 
`/home/user/MD/single.md:174: warning: multiple use of section label 'labelid' while adding section, (first occurrence: /home/user/MD/single.md, line 174)`

[single.zip](https://github.com/doxygen/doxygen/files/3544907/single.zip)

**Comment by albert-github** [comment] 2019-08-27 08:12
Doxygen is, unfortunately, not good in counting lines in markdown, this is partly due to the fact that the markdown code is processed and a new file is generated, with sometimes extra lines especially with tables, and handed to the real interpreter.
A way to see this is e.g. use option `-d markdown` and catch the output in a file and look at the sections marked '---- output -----' of the given file (does not always work to get the correct line thoiugh).

There is not a lot that can be done about this.

Regarding your mentioned problem, I cannot reproduce the message as supplied by you:
- which version of doxygen did you use
- any special settings in your Doxyfile (please provide Doxyfile).
- I get a message about the line `@ref [Link text](@ref labelid4)` mentioned as line 182 but actually line 105. Also it mentions `labelid4` as not existing (and this message is correct only with wrong line number).

**Comment by gsokhran** [comment] 2019-08-27 10:55
Hi albert-github,

Thanks for the quick replay.
It is good to hear that others are also having the same issue, especially after seeing that this kind of problem has been resolved in the older Doxygen versions.

I am using the latest Doxygen - v. 1.18.16.
I don't care much about the warnings itself, they are there just to demonstrate that there is a line number mismatch.
However, here is a configuration that I am using.
[doxygenConfig.zip](https://github.com/doxygen/doxygen/files/3545723/doxygenConfig.zip)

**Comment by albert-github** [comment] 2019-08-27 12:27
Also in older versions I see that there is a mismatch with line numbers but the difference is smaller (and a difference cannot always be circumvented).
Problem is mainly caused by the fact that in translating the markdown table the tags are more distributed over lines (i.e. debug readability versus line numbers).

**Comment by albert-github** [comment] 2019-08-27 17:10
I've just pushed a proposed patch, pull request #7231 to get line numbers a bit nearer to the lines of the original source.

**Comment by albert-github** [comment] 2019-12-21 12:57
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment] 2019-12-28 10:54
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2019-12-28 10:54 UTC
Labels: enhancement

**Comment by leonardopsantos** [comment] 2020-03-12 15:19
Can we rollback this change? It creates #7493 and #7542, which are more serious. Besides, this issue here having a workaround with '-d markdown'

**Comment by albert-github** [comment] 2020-03-12 15:40
I don't think we should do a rollback but use one of the solutions as given with #7493
