### ISSUE TITLE
external link is incorrect 

### ISSUE THREAD

**Issue by kenyeby** [doxygen/doxygen#6530] opened 2018-09-27 13:53 UTC
when using tag files with ALLEXTERNALS on or off,
 in files.html and hierarchy.html, 
     it will be …   xxxxx.htmlyyyy\</a> for external link, 
    after I insert in between to become … xxxxx.html” target=“_self”>yyyy\</a>  ,
it becomes ok, I can see the links and also can click the link on web browser to external documents generated by doxygen
 
PS, EXT_LINK_WINDOW is NO, 
      I wonder if FTextStream has problem or not.

**Comment by kenyeby** [comment] 2018-09-27 13:54
it becomes ok, I can see the links and also can click to link to external documents generated by doxygen

**Comment by kenyeby** [comment] 2018-09-28 07:57
Dear Sir,     the attached is what you want. execute    doc/ext/ext.bat                   and doc/prj/prj.bat will get doc/ext/html and doc/prj/html 
there are two errors as follows.1. prj.bat, will get html help compiler error.2. you will find that       in hierarchy.html,   …ext.htmlext::ext …         if change to ext.html" target="_self" > ext::ext      it will show up in web browser and with link to ext html. 
thank you very much.BR   kenyeby 

傳送自 Yahoo奇摩電子信箱 Android 版 
 
   在 2018 年 9月 月 27 日週四，時間：22:25 ， albert-github <notifications@github.com> 寫道：   
Can you please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem?
Please also specify the doxygen version used.

**Comment by albert-github** [comment] 2018-09-28 08:40
I'm sorry but I don't see an attachment.

**Comment by kenyeby** [comment] 2018-09-28 11:30
Dear Sir,     the link,https://drive.google.com/file/d/14alHDoxICSpsp8d2LUvuCUwQSYWkOxHo/view?usp=drivesdk , is what you want. execute    doc/ext/ext.bat                   and doc/prj/prj.bat will get doc/ext/html and doc/prj/html 
there are two errors as follows.1. prj.bat, will get html help compiler error.2. you will find that       in hierarchy.html,   …ext.htmlext::ext …         if change to ext.html" target="_self" > ext::ext      it will show up in web browser and with link to ext html. 
thank you very much.BR   kenyeby 



傳送自 Yahoo奇摩電子信箱 Android 版 
 
   在 2018 年 9月 月 28 日週五，時間：16:40 ， albert-github <notifications@github.com> 寫道：   
I'm sorry but I don't see an attachment.

**Comment by albert-github** [comment] 2018-09-28 11:33
Please attach the file as e.g. a zip file to the issue and not a reference to an external place (this is not persistent).

**Comment by kenyeby** [comment] 2018-09-28 11:33
Dear Sir,     the link,https://drive.google.com/file/d/14alHDoxICSpsp8d2LUvuCUwQSYWkOxHo/view?usp=drivesdk , is what you want. execute    doc/ext/ext.bat                   and doc/prj/prj.bat will get doc/ext/html and doc/prj/html 
there are two errors as follows.1. prj.bat, will get html help compiler error.2. you will find that       in hierarchy.html,   …ext.htmlext::ext …         if change to ext.html" target="_self" > ext::ext      it will show up in web browser and with link to ext html. 
thank you very much.BR   kenyeby 
傳送自 Yahoo奇摩電子信箱 Android 版 
 
   在 2018 年 9月 月 28 日週五，時間：16:40 ， albert-github <notifications@github.com> 寫道：   
I'm sorry but I don't see an attachment.

**Comment by kenyeby** [comment] 2018-09-28 12:01
Dear Sir,      Yahoo mail does not allow to send zip or tar.gz     I will use gmail to send.BR   Kenyeby 

傳送自 Yahoo奇摩電子信箱 Android 版 
 
   在 2018 年 9月 月 28 日週五，時間：19:33 ， albert-github <notifications@github.com> 寫道：   
Please attach the file as e.g. a zip file to the issue and not a reference to an external place (this is not persistent).

**Comment by kenyeby** [comment] 2018-09-28 12:36
Dear Sir,      both email does not allow me to sent.    Would you please use the link to download zip file? 
https://drive.google.com/file/d/10ZO3Kn4va4mt_AqthtFEqPuFPvF7CIqJ/view?usp=drivesdk
     thank you very muchBR    Kenyeby 

傳送自 Yahoo奇摩電子信箱 Android 版 
 
   在 2018 年 9月 月 28 日週五，時間：20:26 ， albert-github <notifications@github.com> 寫道：   
Still no attachment, please just upload the zip file using github.

**Comment by albert-github** [comment] 2018-09-28 12:38
Just don't use the email to communicate but directly use github.

**Comment by albert-github** [comment] 2018-09-28 12:43
Use this issue  #6530 and below the comment box you see: the in the comment box you see the line how to add an attachment.

**Comment by kenyeby** [comment] 2018-09-28 12:47
[doxygen.zip](https://github.com/doxygen/doxygen/files/2428213/doxygen.zip)
thank you ,  finally I uploaded.
thank you very much.

**Comment by albert-github** [comment] 2018-09-28 12:53
I can now properly see the attachment.

**Comment by kenyeby** [comment] 2018-09-28 12:55
It is my first time to use github to report  bug. very thanks for your patience.

**Comment by albert-github** [comment] 2018-09-28 13:12
With version 1.8.14 the problem is present. When using the current master version from github the problem is not present anymore.

**Comment by kenyeby** [comment] 2018-09-28 13:13
when it will release the master version ?
thank you

**Comment by albert-github** [comment] 2018-09-28 13:16
The master version can always be used (you have to build it yourself). A schedule for the release of 1.8.15 is not known to me.

**Comment by kenyeby** [comment] 2018-09-28 13:17
got it. thank you very much

**Comment by doxygen** [comment] 2018-12-27 21:48
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2018-12-27 21:48 UTC
