### ISSUE TITLE
ambiguous image detection breaks things

### ISSUE THREAD

**Issue by bgoglin** [doxygen/doxygen#7445] opened 2019-12-14 09:06 UTC
Hello

Since doxygen 1.8.16, I can't build the hwloc doxygen doc anymore because image are ignored because ambiguous, while they are not.

We have a image subdirectory in the source tree that contains some "pre-built" images (directly used by doxygen) and some "image sources" (e.g. xfig files that will be exported to eps/png before given to doxygen).

When building hwloc outside the source tree, IMAGE_PATH must contain srcdir/images (for pre-built images) and builddir/images (for xfig-generated images).
When building hwloc inside the source tree, that same configure-generated IMAGE_PATH ends up containing the same repository twice (srcdir and builddir are identical).
There are also cases where IMAGE_PATH contains two different paths that point to the same directory (through symlinks).

Please either provide an option to ignore this ambiguous non-issue (easy), or detect when images are actually the same in both directories (maybe just use stat and compare the partition+inode numbers?).

Thanks
Brice

**Comment by albert-github** [comment] 2019-12-14 10:18
Just comparing inode numbers etc. won't work as it is not certain that this is available on all platforms. A better comparison would be to check the md5 values.
In your case the ambiguity might be easy, but in most other cases it does signal a potential problem (possible outdated images at different places).

The problem is, when I understand it correctly, that "sometimes" the builds are done inside the source tree (in my opinion this is not good but a project choice).
Is a workaround for you to build outside the source directory and, in e.g. the Makefile, copy the generated images into the source directory?

- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by bgoglin** [comment] 2019-12-14 15:11
Here's a reproducer (as zip since github doesn't like tar.bz2):
[doxygen7445.zip](https://github.com/doxygen/doxygen/files/3963952/doxygen7445.zip)

If you go to /build/, run ../configure and then doxygen doxygen-config.cfg, it works.
If you stay in the /, run ./configure and then doxygen doxygen-config.cfg, it warns and fails.

By the way, building inside the source tree is not a project choice, it's a builder choice offered by autoconf. I personally don't do it but lots of people do.

I am working at on ugly workaround but we won't be able to backport it to all existing stable release series, so we're advising our users to avoid upgrading to doxygen 1.8.16. What's your plan for fixing this?

**Comment by albert-github** [comment] 2019-12-14 15:17
No (time) schedule yet.

As a side note, I would not advise not to upgrade doxygen but would advise them not to build in tree (with as reasons that the source tree is not "clean:" anymore and also that the newer documentation generation with doxygen has problems with it).

**Comment by bgoglin** [comment] 2019-12-14 15:18
Well, distribution packagers are not going to change their packaging...

**Comment by albert-github** [comment] 2019-12-14 18:17
This issue of specifying a directory twice has already been addressed in the current master by means of commit 752753c044af46cc4a22f83be8e4e1ae6be8f373 based on issue #7189

**Comment by bgoglin** [comment] 2019-12-14 20:07
Thanks, that commit indeed seems to resolve my issue.

**Comment by doxygen** [comment] 2019-12-27 19:38
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2019-12-27 19:38 UTC
Labels: bug, enhancement
