### ISSUE TITLE
ALIASES not found when filename has more than one dot

### ISSUE THREAD

**Issue by mneuhaus-cv** [doxygen/doxygen#7262] opened 2019-09-15 08:23 UTC
Hi,

seems that ALIASES are not found, when the filename of the markdown input file contains more than one dot ('.').

i.e. ALIASES work fine in a file named "changes_101_200.md", but are NOT recognized when the filename is chaged to "changes_101_20.0.md".

Best
Mathias

**Comment by albert-github** [comment] 2019-09-15 08:31
I can see that a file with more than 1 dot gives a problem in the current version (1.8.16)  and that this was not a problem in 1.8.15.
Looks like the problem does not appear when using e.g. a `.h` file.


In the future:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

**Comment by albert-github** [comment] 2019-09-15 09:20
I've just pushed a proposed patch, pull request #7263

**Comment by mneuhaus-cv** [comment] 2019-09-17 12:55
thanx a lot;
yes I'm using 1.8.16 - didn't test this against previous versions.

**Comment by albert-github** [comment] 2019-09-18 05:59
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment] 2019-12-27 19:40
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2019-12-27 19:40 UTC
Labels: bug

**Comment by mneuhaus-cv** [comment] 2019-12-27 19:59
Thank You for the ever-continuing support.

Habe a Good New Year!

bis die Tage...
  Mathias

Am 27.12.2019 um 20:40 schrieb Dimitri van Heesch <notifications@github.com>:

﻿

This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).
