### ISSUE TITLE
Unable to connect to the official website

### ISSUE THREAD

**Issue by Namyalg** [doxygen/doxygen#9249] opened 2022-04-04 08:47 UTC
**Describe the bug**
The official websites of doxygen `https://www.doxygen.org/`, `https://www.doxygen.nl/` do not connect.

A `This site can’t be reached` error is thrown

**Screenshots**
![image](https://user-images.githubusercontent.com/53875297/161507971-8b48719a-477e-4c5c-9e32-9e725b1233b7.png)

![image](https://user-images.githubusercontent.com/53875297/161508033-5177c96f-e6d9-4b83-8687-0644c79072eb.png)

**Comment by Namyalg** [comment] 2022-04-04 08:49
@albert-github @doxygen

**Comment by albert-github** [comment] 2022-04-04 08:49
I don't see any problem, I can connect to it without any problems.

**Comment by Namyalg** [comment] 2022-04-04 08:50
I haven't been able to connect to the site for over a week now.

**Comment by albert-github** [comment] 2022-04-04 08:54
Did it land, by accident, in your or your organizations, firewall, blacklist ? 
Maybe @doxygen can see something in the log files.

**Comment by Namyalg** [comment] 2022-04-04 08:57
I don't think, I've tried connecting to it from different networks but it's the same

**Comment by doxygen** [comment] 2022-04-04 19:27
@Namyalg Works fine here, can you try via a proxy server?
For instance this one: https://144.76.183.61/index.html?__cpo=aHR0cHM6Ly93d3cuZG94eWdlbi5ubA

**Comment by Namyalg** [comment] 2022-04-04 19:42
![image](https://user-images.githubusercontent.com/53875297/161619744-f32f4c39-2675-45a1-94c5-dcf7ee2d2901.png)

This is what I get when I try

**Comment by doxygen** [comment] 2022-04-04 19:45
you try some different proxy servers but the problem in on your side.

**Comment by Namyalg** [comment] 2022-04-04 19:47
Alright, it connects when I use a proxy
Thank you !

**Comment by kolappan-n** [comment] 2022-04-07 03:38
I am facing the same issue. Cannot connect to the website from India, but can connect using a online proxy.

**Comment by doxygen** [comment] 2022-04-09 19:18
please send me the IP address from which you are trying to reach the doxygen website, then I check with my hosting company if they are perhaps actively blocking you. Also try a `traceroute` (or `tracert` on windows) to the website and list the results.

**Comment by Namyalg** [comment] 2022-04-09 19:25
My public IP is `124.40.246.36`

Result of `tracert doxygen.nl `
![image](https://user-images.githubusercontent.com/53875297/162588830-b460abcd-2fc2-4b93-b605-351df200b35f.png)

**Comment by kolappan-n** [comment] 2022-04-11 03:40
My public IP: 49.37.215.87
Result of tracert doxygen.nl
```
Tracing route to doxygen.nl [195.5.163.171]
over a maximum of 30 hops:

  1     1 ms    <1 ms     4 ms  reliance.reliance [192.168.29.1]
  2     7 ms     8 ms     4 ms  10.43.8.1
  3    24 ms    24 ms    24 ms  172.16.5.89
  4    22 ms    22 ms    24 ms  192.168.68.144
  5    26 ms    23 ms    23 ms  172.26.77.164
  6    20 ms    20 ms    23 ms  172.26.77.130
  7    23 ms    21 ms    24 ms  192.168.68.136
  8    22 ms    34 ms    20 ms  192.168.68.137
  9    46 ms    46 ms    41 ms  172.31.2.73
 10    41 ms    45 ms    39 ms  103.198.140.176
 11   159 ms   162 ms   166 ms  103.198.140.87
 12   168 ms   168 ms   171 ms  103.198.140.193
 13     *        *        *     Request timed out.
 14     *        *        *     Request timed out.
 15     *        *        *     Request timed out.
```

**Comment by doxygen** [comment] 2022-04-12 18:33
My ISP claims your IP numbers are not being blocked. 
Can you try if the problem is still present? (maybe it was a temporary thing)

**Comment by Namyalg** [comment] 2022-04-12 18:35
Yes, it's still the same

**Comment by kolappan-n** [comment] 2022-04-14 04:18
Still the same.

**Comment by vintas** [comment] 2022-04-28 18:34
I've tried it with 3 different ISPs in two cities. Vodafone, Airtel and Tata Communications at Mumbai and Bengaluru failed to connect to the website.

**Comment by doxygen** [comment] 2022-04-28 18:38
I contacted my ISP, but they seem to be unable to help me ☹️
Not sure what I can do.

**Comment by VORMie** [comment] 2022-05-03 08:55
Having the same issue, and from what I can gather from all the comments before me, it's probably just our Internet Regulations that are ass. Although since this issue is relatively new, maybe it is temporary.
Either that or this website somehow got flagged by some govt system, and hence private ISPs have been ordered to ban it.

**Comment by doxygen** [comment] 2022-05-03 18:25
I contacted my ISP again, and finally someone admitted that at least the IP's mentioned above are indeed blocked. They did not really offer a solution though other than me having to switch to a privately hosted server. If the problem persists, I may decide to switch to a different ISP. Their service has deteriorated over the years anyway.

**Comment by 1vanK** [comment] 2022-05-04 08:03
Same problem. I can't even connect via TOR

**Comment by tan-wei** [comment] 2022-05-05 12:43
Unavailable for me for several weeks. I try to use different VPN nodes to access, but still the same.

**Comment by albert-github** [comment] 2022-05-05 13:42
@1vanK , @tan-wei 
As it is not known from where you connect is is important to add to your comments the `tracert` /  `traceroute` information.

**Comment by 1vanK** [comment] 2022-05-05 13:51
```
11    45 ms    47 ms    45 ms  be3376.ccr21.sto03.atlas.cogentco.com [130.117.50.225]
 12    55 ms    54 ms    55 ms  be2555.rcr21.cph01.atlas.cogentco.com [154.54.61.237]
 13    56 ms    57 ms    56 ms  be2496.ccr41.ham01.atlas.cogentco.com [154.54.61.221]
 14    64 ms    64 ms    63 ms  be2815.ccr41.ams03.atlas.cogentco.com [154.54.38.205]
 15    64 ms    64 ms    64 ms  be3457.ccr21.ams04.atlas.cogentco.com [130.117.1.10]
 16    64 ms    64 ms    64 ms  be2476.rcr02.b015515-0.ams04.atlas.cogentco.com [130.117.1.50]
 17    65 ms    64 ms    64 ms  80.249.213.162
 18     *        *        *     Превышен интервал ожидания для запроса.
 19     *        *        *     Превышен интервал ожидания для запроса.
 20     *        *        *     Превышен интервал ожидания для запроса.
 21     *        *        *     Превышен интервал ожидания для запроса.
 22     *        *        *     Превышен интервал ожидания для запроса.
 23     *        *        *     Превышен интервал ожидания для запроса.
 24     *        *        *     Превышен интервал ожидания для запроса.
 25     *        *        *     Превышен интервал ожидания для запроса.
 26     *        *        *     Превышен интервал ожидания для запроса.
```

**Comment by albert-github** [comment] 2022-05-05 13:59
@1vanK Why didn't you provide the first 10 lines as well, they probably would give the clue to your problem.

**Comment by 1vanK** [comment] 2022-05-05 14:03
I do not plan to deanonymize in Internet

**Comment by doxygen** [comment] 2022-05-06 17:50
I'm in the process of switching to a different hosting provider, which hopefully offers a better service. It will probably take a week or so until the domain has moved and DNS servers have been updated. I'll keep you informed.

**Comment by karthikeyann** [comment] 2022-05-06 20:06
Site [www.doxygen.nl](http://www.doxygen.nl/) is accessible again. (Location Bangalore, India) 
Thank you👍

**Comment by doxygen** [comment] 2022-05-07 11:08
@karthikeyann Transferring the domain went smoother than expected. Very good to hear it solved the problem.
@1vanK, @vintas, @VORMie, @kolappan-n, @tan-wei. @Namyalg can you please check if the access problems are fixed for you as well?

**Comment by doxygen** [comment] 2022-05-07 11:10
@karthikeyann I've also requested transfer for www.doxygen.org, but apparently this takes a bit more time.

**Comment by 1vanK** [comment] 2022-05-07 11:41
I can read documentation from http://www.doxygen.nl/ now (but can't download from www.doxygen.org)

**Comment by kolappan-n** [comment] 2022-05-07 12:05
I am able to access https://www.doxygen.nl/ again.

**Comment by vintas** [comment] 2022-05-07 19:45
I can connect to [doxygen.nl](https://www.doxygen.nl/) and it currently gives the IP 45.82.188.211 while [doxygen.org](https://www.doxygen.org/) is still inaccessible with IP 195.5.163.171.

**Comment by vintas** [comment] 2022-05-08 12:09
I now get a 301 redirect from any [doxygen.org](https://www.doxygen.org/) path like download link to the appropriate [doxygen.nl](https://www.doxygen.nl/) url and everything is accessible now.

**Comment by tan-wei** [comment] 2022-05-09 13:40
So I can access the website again! Gloria!

**Comment by Namyalg** [comment] 2022-05-09 16:07
Yes, I am able to connect to the [website](https://www.doxygen.nl/) too!

**Comment by Namyalg** [comment] 2022-05-13 14:45
Works for me

**Comment by kolappan-n** [comment] 2022-05-16 03:21
> By now also [www.doxygen.org](http://www.doxygen.org) should also be migrated, so for people that still had problems accessing that URL, please check on more time if everything is now working, so I can close this issue.

Both .org and .nl works fine for me now.

**Comment by vintas** [comment] 2022-05-16 04:38
[doxygen.org](https://www.doxygen.org/) is accessible now.

**Comment by Laendrun** [comment] 2022-10-28 09:16
Sorry to reopen (not really) this issue, but I'm having trouble connecting to the website (either doxygen.nl or doxygen.org) I get the following error message `DNS_PROBE_FINISHED_NXDOMAIN`.
I searched for a bit trying to know if it's on my side or not and apparently this means the domain is unknown.
Do you guys have any idea of what I can (maybe) do on my side ?

**Comment by doxygen** [comment] 2022-10-28 09:17
See https://github.com/doxygen/doxygen/issues/9652

**Comment by albert-github** [comment] 2022-10-30 07:38
The problem mentioned here has been solved, switching to other ISP.

**Closed by albert-github** 2022-10-30 07:38 UTC
Labels: website
