### ISSUE TITLE
`typedef` of unspecified type causes friend function documentation to be not documented

### ISSUE THREAD

**Issue by scott-zhong** [doxygen/doxygen#10847] opened 2024-05-01 17:26 UTC
**Describe the bug**
`typedef` of unspecified type causes friend function documentation to be not documented.

```
/**
 * \relates A
 *
 * An unspecified type.
 */
typedef unspecified my_type;

/**
 * A docs
 */
class A
{
public:
    friend void fun(my_type);
};

/**
 * fun docs
 */
void fun(my_type);
```

`fun()` is not documented and the warning `warning: Member fun(my_type) (friend) of class A is not documented.` is produced

**Screenshots**
1.8.9.1 - trunk (85eb55d1b32bfeb474be6485c88348ef5d5d7fd8)
![image](https://github.com/doxygen/doxygen/assets/32584126/dbaa9200-53ec-44ce-82aa-5b111779a62a)

**To Reproduce**
[testcase.zip](https://github.com/doxygen/doxygen/files/15179466/testcase.zip)

**Expected behavior**
`fun()` is documented.

**Comment by paule32** [comment] 2024-05-01 18:31
you define a type **my_type** based on unspecified.
so, either **unspecified** must be exists before you define my_type or you use an already existing type.
the next problem I see is, that you don't give the type an argument for the member declaration.
should it not be **void fun(my_type arg1)** ?

I think it is a usage problem.

**Comment by scott-zhong** [comment] 2024-05-01 19:23
Argument name isn't required, especially if the function doesn't use the argument (you'll get a compiler warning about unused variable if you do). 

I don't think this is a usage problem because even if we define `unspecified` type, Doxygen still thinks that it is an undocumented member.  For example

```
struct unspecified
{
};

/**
 * \relates A
 *
 * An unspecified type.
 */
typedef unspecified my_type;

/**
 * A docs
 */
class A
{
public:
    friend void fun(my_type);
};

/**
 * fun docs
 */
void fun(my_type);
```

`fun()` would still be undocumented. Whereas if we switch to an `int` type then `fun()` is now documented.

```
/**
 * A docs
 */
class A
{
public:
    friend void fun(int);
};

/**
 * fun docs
 */
void fun(int);
```

**Comment by doxygen** [comment] 2024-05-12 13:10
@scott-zhong The problem is the `\relates` command, which makes doxygen treat the typedef as a member of `A`, but then when resolving the type in `fun`'s declaration it searches for the type in the global scope where it is not found, while for the friend declaration it is found. 

In older versions of doxygen, the scope resolution was less strict and the member could still be found (which sometimes led to links to the wrong symbol).

**Comment by doxygen** [comment] 2024-05-12 13:22
@scott-zhong Please verify if the referenced commit fixes the problem for you. Do not close the issue, this will be done automatically when the next official release becomes available.

**Comment by scott-zhong** [comment] 2024-05-13 23:28
@doxygen verified the fix. Thank you!!!

**Closed** 2024-05-20 09:52 UTC
Labels: bug, C/C++
