### ISSUE TITLE
Build: cache.h:53:14: error: 'exchange' is not a member of 'std'

### ISSUE THREAD

**Issue by kekePower** [doxygen/doxygen#9312] opened 2022-05-06 07:01 UTC
**Describe the bug**
When building on Mageia Cauldon using GCC 12.1.0 I get the mentioned message.

```shell
[ 49%] Building CXX object addon/doxywizard/CMakeFiles/doxywizard.dir/moc_inputstrlist.cpp.o
cd /home/iurt/rpmbuild/BUILD/doxygen-1.9.4/build/addon/doxywizard && /usr/bin/c++ -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_XML_LIB -DUNICODE -I/home/iurt/rpmbuild/BUILD/doxygen-1.9.4/addon/doxywizard/. -I/home/iurt/rpmbuild/BUILD/doxygen-1.9.4/libversion -I/home/iurt/rpmbuild/BUILD/doxygen-1.9.4/build/generated_src -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtXml -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fasynchronous-unwind-tables -DNDEBUG -fvisibility=hidden -fvisibility-inlines-hidden -fPIC -std=gnu++17 -MD -MT addon/doxywizard/CMakeFiles/doxywizard.dir/moc_inputstrlist.cpp.o -MF CMakeFiles/doxywizard.dir/moc_inputstrlist.cpp.o.d -o CMakeFiles/doxywizard.dir/moc_inputstrlist.cpp.o -c /home/iurt/rpmbuild/BUILD/doxygen-1.9.4/build/addon/doxywizard/moc_inputstrlist.cpp
In file included from /home/iurt/rpmbuild/BUILD/doxygen-1.9.4/src/doxygen.h:24,
                 from /home/iurt/rpmbuild/BUILD/doxygen-1.9.4/src/message.cpp:21:
/home/iurt/rpmbuild/BUILD/doxygen-1.9.4/src/cache.h: In member function 'V* Cache<K, V>::insert(const K&, V&&)':
/home/iurt/rpmbuild/BUILD/doxygen-1.9.4/src/cache.h:53:14: error: 'exchange' is not a member of 'std'
   53 |         std::exchange(it->second->second,value);
      |              ^~~~~~~~
```
and the build fails.

There is this commit from 8 days ago that introduces this code: https://github.com/doxygen/doxygen/commit/fe58686503d386afb5269e7a2799c0457c743092

**Expected behavior**
Well, it would be nice to see the source compile.

**To Reproduce**
Install Mageia Cauldron fully updated and try to successfully compile the source.

**Version**
Trying to build version 1.9.4

**Stack trace**
N/A

**Additional context**
N/A

**Comment by doxygen** [comment] 2022-05-06 07:58
@kekePower Looks like a missing `#include` statement that all other compilers I tested included implicitly. Can you please verify it works with the referenced commit?

**Comment by kekePower** [comment] 2022-05-06 09:33
@doxygen I can confirm that the fix works.

Thank you :-)

**Comment by doxygen** [comment] 2022-08-26 16:56
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.5.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2022-08-26 16:56 UTC
Labels: bug

**Comment by Becheler** [comment] 2022-11-25 05:22
Hello. I am running into the same issues using Doxygen 1.9.4 installed from the conan package manager with gcc-12 https://conan.io/center/doxygen
The version 1.9.5 is not available on the repo yet, is there any way around?

**Comment by albert-github** [comment] 2022-11-25 09:17
@Becheler 
- are you compiling yourself? The issue is about the compilation of doxygen.
- In case you wan to compile yourself just get the latest version from the github repository or from https://www.doxygen.nl/download.html

**Comment by Becheler** [comment] 2022-11-25 16:02
@albert-github 
Thank you for your answer! 
- Yes, I am compiling it myself, as I included it in the tool_requires section of the conan dependency manager. 
- I don't know how to ask Conan to get doxygen from github rather than Conancenter
- I just downgraded to Doxygen 1.9.2, and it compiles fine :) 
Thank you!

**Comment by albert-github** [comment] 2022-11-25 16:50
Regarding pushing Conan I cannot help and as you use the Conan Dependency Manager it will probably hard to overrule. 
Maybe you should create an issue in https://github.com/conan-io/conan-center-index/issues and asking them to create doxygen 1.9.5 for Conan seen the problem you have with 1.9.4. downgrading is always a last resort as you will loose new features and bug fixes etc. (and some new bugs 😄 )
