### ISSUE TITLE
Doxywizard 1.9.x doesn't start up properly

### ISSUE THREAD

**Issue by DNKpp** [doxygen/doxygen#8355] opened 2021-01-24 22:05 UTC
**Describe the bug**
Today I updated doxygen to 1.9.1, but the doxywizard window didn't appear, but a process was running.
I de-installed and reinstalled it -> didn't fix it
I reverted to 1.9.0 -> didn't fix it
I reverted to 1.8.20 -> now it seems fine.

I would like to add some logs or even dig through them by myself, but I wasn't able to find them. Perhaps someone can tell me where to search for them.

Greetings

**Comment by albert-github** [comment] 2021-01-25 08:58
- There are no logs.
- Where did you get the installation from
- Which OS are you using?

**Comment by DNKpp** [comment] 2021-01-25 09:25
Hey, there. I've downloaded the files from doxygen.nl (seems to be the official page) and was redirected to sourcefourge in cases of older releases.
Sry, I completely missed that out. My OS is windows 10 pro.
I've quickly reinstalled 1.9.1 to check if it runs from console and yes, it works.

**Comment by albert-github** [comment] 2021-01-25 09:41
- I assume the "I've quickly reinstalled 1.9.1 to check if it runs from console and yes, it works" means that doxygen itself runs, that is at least positive.
- I can run the doxywizard without problems. 
- Did you run the doxywizard by double clicking or by starting it from the command line (to check were it is installed: where doxywizard, mine is located at "d:\Program Files\doxygen\bin\doxywizard.exe")
- Symptoms look a bit like a missing dll but normally Windows would show a message box about this. You said the doxywizard process is running so something must have started already (I also assume that you kill, as a test, all doxywizard processes running before running the wizard as a test).
- maybe you can run a "dependency" checker on the executable to see what is wrong.

**Comment by DNKpp** [comment] 2021-01-25 11:33
* yes, indeed
* that's fine
* both. The outcoming is equally (process starts, but no window is created)
* I compared the results of the "dependencies" tool from both versions, but they are looking very similar.

I tried debugging it or build it from source, but it does take too much time for me to get it work.

**Comment by albert-github** [comment] 2021-01-25 11:40
I can imagine the "I tried debugging it or build it from source, but it does take too much time for me to get it work." but unfortunately as I can run the doxywizard without problems it is hard to tell what goes wrong.

- Do you start the doxywizard with or without an initial  Doxyfile i.e. `doxywizard Doxyfile` or `doxywizard`?

**Comment by DNKpp** [comment] 2021-01-25 11:45
The latter. As I was using doxygen in previous versions, the 1.8.20 starts-up with the last opened project. That should then also be the case for the 1.9.x versions (which I can't see).

**Comment by albert-github** [comment] 2021-01-25 11:50
In the handling of the Doxyfile a number of changes have been made, maybe we have here a corner case.
Can you attach:
- the original Doxyfile
- the result of the command `doxygen -x Doxyfile` (i.e. result from the 1.9.1 version).

**Comment by DNKpp** [comment] 2021-01-25 11:54
Well, I found the "clear recent list" option under the settings menu. I used it in the 1.8.20 version, upgraded to 1.9.1 and now doxywizard starts-up correctly.

**Comment by albert-github** [comment] 2021-01-25 11:59
OK good that it is working for you now,
Must be some nasty problem, I know there was some problem with the wizard and the clear recent list i.e #8252 but this should work properly in 1.9.0 / 1.9.1 but maybe the original list had some flaws.

It is a bit hard to categorize thus issue so probably best is that I set it to usage.

**Comment by mrutkowsk** [comment] 2021-03-31 08:52
> 
> 
> **Describe the bug**
> Today I updated doxygen to 1.9.1, but the doxywizard window didn't appear, but a process was running.
> I de-installed and reinstalled it -> didn't fix it
> I reverted to 1.9.0 -> didn't fix it
> I reverted to 1.8.20 -> now it seems fine.
> 
> I would like to add some logs or even dig through them by myself, but I wasn't able to find them. Perhaps someone can tell me where to search for them.
> 
> Greetings

the same problem here :)

**Comment by albert-github** [comment] 2021-03-31 09:00
@mrutkowsk 
- a message as "the same problem here " is very vague and you should at least mention what you tried, also in the light of the solution given in https://github.com/doxygen/doxygen/issues/8355#issuecomment-766764099

- did you try the solution as given in https://github.com/doxygen/doxygen/issues/8355#issuecomment-766764099 ?

**Comment by MetricManifold** [comment] 2021-04-18 15:28
I am also getting this problem with Windows 10. When I install 1.9.1, I can't open the wizard; only the (32-bit) process is running and no window appears. 1.8.20 runs fine. 

Trying the solution didn't help me.

**Comment by albert-github** [comment] 2021-04-18 16:21
@MetricManifold 

Please describe exactly which steps you took:
- deinstall 1.9.1, install 1.8.20
- run wizard
  - clear recent list
  - also set "Use current settings at statup"
- stop 1.8.20 wizard
- run wizard 1.8.20 again
  - check that the recent list is empty
- deinstall 1.8.20 / install 1.9.1
- check again

**Comment by MetricManifold** [comment] 2021-04-18 16:22
I didn't verify that the recent list is empty, but I will do so now.

**Comment by MetricManifold** [comment] 2021-04-18 16:24
I cleared the recent list (twice, to ensure that I did it correctly) and reset all settings. Now I can open 1.9.1 wizard.

**Comment by onlysonim** [comment] 2021-08-14 19:26
I had a same issue #8355 and tried @MetricManifold 's the way ("clear-and-reset") a couple of times, 
But didn't work for me.  ( I had been used 1.8.20 with win10 pro x64)

So I tried like below : 
1. Uninstall an old one (1.8.20). 
2. Delete manually all the registry keys of Doxygen at :
 	__"\HKEY_CURRENT_USER\SOFTWARE\Doxygen.org"__ 
 3. Installed a new version (1.9.1).

Yes, It does work in my case.  :)

**Comment by tterho** [comment] 2021-11-04 12:32
I had the same issue with 1.9.2 (updated from 1.8.19). Removing _Doxygen.org_ entry from the Windows registry under HKEY_CURRENT_USER\Software helped.

**Comment by SirHesti** [comment] 2021-12-31 19:42
i only delete the registry ... works

**Comment by albert-github** [comment] 2022-01-01 18:25
Reopening the issue as the problems are not just for one person.

The problem here was that the "wizard/loadsetting" key in the registry is set (Using a set of settings defined by the user as a "default" set of settings) in an older version and that some of the keys didn't yet exist in that version but were required in the current version.

To Reproduce:
1. take an old version of doxywizard (e.g. the 1.8.20 version)
   -  start the version
   - set "Use current settings at startup" from "Settings"
   - exit this doxywizard
2. take the current version of the doxywizard (1.9.3)
   -  start it 
   - it hangs, so you will have to kill the doxywizard process
 
Workaround (choose either):
1. In the old version
    - Save the current settings as a new doxygen settings file as so you can load them again in the new version (without really loosing the settings)
    - set "Reset to factory defaults"
2. In regedit (so extreme caution!!):
   - there will be no way to save the user "default" settings
   - set the key `Computer\HKEY_CURRENT_USER\SOFTWARE\Doxygen.org\Doxywizard\wizard\loadsettings` to `false`

I've just pushed a proposed patch, pull request #8997

**Comment by albert-github** [comment] 2022-01-01 18:31
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by ryandesign** [comment] 2022-01-04 08:08
> Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

Looks like doxygen 1.9.3 was originally released without this fix, then 1.9.3 was re-released including this fix. (See https://trac.macports.org/ticket/64354.)

**Comment by ryandesign** [comment] 2022-01-04 08:13
The [download page](https://www.doxygen.nl/download.html) says 1.9.3 was released December 31th 2021 but in fact the file currently there was Last-Modified yesterday:
```
$ curl -IL https://www.doxygen.nl/files/doxygen-1.9.3.src.tar.gz
HTTP/1.1 200 OK
Date: Tue, 04 Jan 2022 08:11:44 GMT
Server: Apache/2
Last-Modified: Mon, 03 Jan 2022 09:55:15 GMT
ETag: "4e9d9c-5d4aa846fc6c0"
Accept-Ranges: bytes
Content-Length: 5152156
Vary: User-Agent
Content-Type: application/x-gzip
Content-Encoding: x-gzip
```

**Comment by albert-github** [comment] 2022-01-04 08:13
@ryandesign 
That is correct, we found the problem and seen the problems noticed by users and an update of this was done without changing the version number. It is only available in the packages on www.doxygen.org and not under the 1.9.3 tag in the repository

**Comment by ryandesign** [comment] 2022-01-04 08:32
Ok thanks for confirming that was intentional. I guess this issue can be closed then, since you said above it is only open pending a release, which has now happened.

I trust you can understand how disruptive and confusing it is when a project re-releases a version of their software, so I hope the doxygen project will not do so again in the future.

**Comment by doxygen** [comment] 2022-01-04 08:36
@ryandesign I'll keep it in mind. I've also made it more clear on the download page.

> The latest version of doxygen is 1.9.3 (release date 31 december 2021, updated 3th of January 2022).

**Closed by doxygen** 2022-01-04 08:36 UTC
Labels: bug, fixed but not released, doxywizard
