### ISSUE TITLE
Comment in group ignored if it does not belong to member

### ISSUE THREAD

**Issue by Rubyfi** [doxygen/doxygen#10764] opened 2024-03-22 12:35 UTC
**Describe the bug**
Comments are ignored if they  cannot be assigned to a member (variable, function, class, etc).

Examples:
- *does not work*
  ```
  /// My Comment
  <EOF>
  ```

- *does work*
  ```
  /// My Comment
  unit8 test = 0;
  <EOF>
  ```

This is even the case, if the comment is nested in an ```addtogroup``` scope.
In this case, you have to explicitly mark the block again.

Examples:
- *does not work*
  ```
  /// @addtogroup mygroup
  /// @{

  ...

  /// My Comment

  /// @}
  <EOF>
  ```

- *does work*
  ```
  /// @addtogroup mygroup
  /// @{

  ...

  /// @addtogroup mygroup
  /// My Comment

  /// @}
  <EOF>
  ```

- *does work*
  ```
  /// @addtogroup mygroup
  /// @{

  ...

  /// My Comment
  unit8 test = 0;

  /// @}
  <EOF>
  ```

**To Reproduce**
[doxygen_demo.zip](https://github.com/doxygen/doxygen/files/14722548/doxygen_demo.zip)
In the generated output, the ignored comments only show up in the source html.
The working comments show up in the file/group documentation as well.

**Expected behavior**
The currently ignored comments should be assigned to the file documentation or the group documentation respectively.

**Version**

- 1.9.6 (Windows 10, 64bit)
- 1.10.0 (Windows 10, 64bit)

**Comment by doxygen** [comment] 2024-03-27 20:33
> Expected behavior
The currently ignored comments should be assigned to the file documentation or the group documentation respectively.

File documentation requires the use of `@file` command and group documentation requires either a `@addgroup` to add documentation to an existing group, or a documented group member (like an int or class) with documentation. Otherwise the documentation is indeed not attached to anything and ignored.

So I think the problem is usage.

**Closed** 2024-05-20 10:02 UTC
Labels: Usage
