### ISSUE TITLE
Lots of new parser warnings in our Doxygen testsuite after the merges two days ago

### ISSUE THREAD

**Issue by lrineau** [doxygen/doxygen#6583] opened 2018-10-29 14:31 UTC
In the CGAL open source project, we recently got a lot of (1 thousand) warnings in our documentation testsuite, because of the bug fixed by PR #6558. But, since two days ago, we now have 10 thousand warnings. The regression occurred in the range d94c105..3a42bcf. The new warnings are like:
```
/build/CGAL-4.14-I-29/doc/AABB_tree/PackageDescription.txt:43: warning: end of comment block while expecting command </div>
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:42: warning: Unknown option '_linebr' after \image command, expected 'width' or 'height'
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:43: warning: Illegal command \ref as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:45: warning: Unexpected token TK_HTMLTAG found as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:47: warning: Illegal command @section as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:65: warning: Unexpected token TK_LISTITEM found as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:68: warning: Unexpected token TK_LISTITEM found as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:70: warning: Unexpected token TK_LISTITEM found as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:73: warning: Unexpected token TK_LISTITEM found as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:79: warning: Unexpected token TK_LISTITEM found as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:87: warning: Unexpected token TK_LISTITEM found as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:89: warning: Unexpected token TK_LISTITEM found as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:92: warning: Unexpected token TK_LISTITEM found as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:109: warning: Illegal command \warning as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:111: warning: Unexpected token TK_HTMLTAG found as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:111: warning: Unexpected token TK_HTMLTAG found as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:115: warning: Illegal command @section as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:117: warning: Illegal command @subsection as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:125: warning: Unexpected token TK_HTMLTAG found as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:125: warning: Illegal command \ref as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:125: warning: Illegal command \include as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:127: warning: Illegal command @subsection as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:134: warning: Unexpected token TK_HTMLTAG found as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:134: warning: Unexpected token TK_HTMLTAG found as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:141: warning: Unexpected token TK_HTMLTAG found as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:141: warning: Illegal command \ref as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:141: warning: Illegal command \include as part of a image
/build/CGAL-4.14-I-29/doc/AABB_tree/aabb_tree.txt:144: warning: Illegal command @subsection as part of a image
```
It seems those two commits are related to the parser, and were merged two days ago:
- dff7c1af `Renamed command and moved duplicated code into a macro` and
- a68e6c07 `Correcting warning messages and echoing unknown command`.

Might it be another consequence of PR #6558, revealed by a68e6c07, or is it a regression of Doxygen?

@albert-github Remember you can compile the documentation of CGAL by yourself, with the instructions from @sloriot, here: https://github.com/doxygen/doxygen/pull/6548#issuecomment-430016442

Cc: @maxGimeno @afabri

**Comment by albert-github** [comment] 2018-10-29 15:41
I do remember (fortunately I documented also my steps and the directory still existed)
Pull request #6558 has not yet been merged so some messages are expected but this amount ...

I just ran it on the master source stack from October 15, 2018.
 - without the change from #6558 I get a lot of messages as well.
 - when incorporating the change from #6558 I only get 2 message (one about a parameter and one about a not documented member).

I did a pull request so uptodate at October 28, 2018 around 16.00.
 - without the change from #6558, I didn't try
 - when incorporating the change from #6558 I get messages like:
    -  221 times `warning: unable to resolve reference to '...' for \ref command` (first run, second none)
    - 3 times `warning: unable to resolve link to '...' for \link command` (first run, second none)
    - one about a parameter
    - one about a not documented member

So I think the problem is solved when issue #6558 is merged. I contacted Dimitri for this as well (@doxygen)

@lrineau Can you confirm this?

**Comment by sloriot** [comment] 2018-10-30 07:46
I confirm that #6558 fixes the issues.

**Comment by albert-github** [comment] 2018-10-30 08:30
Duplicate of #6548

**Closed by albert-github** 2018-10-30 08:30 UTC
Labels: bug

**Comment by sloriot** [comment] 2018-10-30 09:20
IMHO, an issue in the master branch shouldn't be marked as a duplicate of a PR merged 17 days ago :)
