### ISSUE TITLE
Remove Nav. Panel / Bar

### ISSUE THREAD

**Issue by paule32** [doxygen/doxygen#11197] opened 2024-10-22 14:22 UTC
Hi,

how can I remove the Panel / Bar on all Sites ?

[packed.zip](https://github.com/user-attachments/files/17477734/packed.zip)

![grafik](https://github.com/user-attachments/assets/3553aa39-2b6f-47d3-a368-94f8fa8ad7ef)

**Comment by albert-github** [comment] 2024-10-22 14:42
- I'm not able to reproduce the image as shown, looks like the components are present but probably something is missing
- from the image it is not clear what exactly you want to remove, probably the treeview and have a footer without info or ...

**Comment by paule32** [comment] 2024-10-22 16:25
you can serve to https://fpc.kallup.net/ there are the working public site.
on upper part of the site, you can see:
- **Hauptseite**  and
- **Themen**
translated to English:
- **Mainpage**
- **Topics**
in the Panel / Bar ...
and this Panel should not be appear

**Comment by albert-github** [comment] 2024-10-22 16:46
Without the possibility to locally reproduce the problem it is hardly possible to give some advice.
It looks like that something has to be done with the css `class"tabs"` or with the `id="navrow1"` but this might also have an effect on other pages.
So it is necessary to have an example with which it is possible to reproduce the behavior locally.

**Comment by paule32** [comment] 2024-10-23 09:38
I have packed all the results in the attached file below:
[packed.zip](https://github.com/user-attachments/files/17488550/packed.zip)

tested and pass with IIS - Microsoft Internet Information Server

**Comment by doxygen** [comment] 2024-10-23 19:26
@paule32 I don't check the example yet, but did you already try `DISABLE_INDEX = YES`

**Comment by paule32** [comment] 2024-10-23 19:50
100 Points.
This solved my problem - Thank you

**Comment by doxygen** [comment] 2024-10-23 19:52
Good to hear. Closing the issue.

**Closed by doxygen** 2024-10-23 19:52 UTC
Labels: Usage
