### ISSUE TITLE
Make failed when building layout.cpp

### ISSUE THREAD

**Issue by Lawliar** [doxygen/doxygen#8269] opened 2020-12-22 04:47 UTC
**Describe the bug**
Platform: WSL2 with Ubuntu 18.04
In the default make procedure for the latest commit `1e72202`,
the make for `src/CMakeFiles/doxymain.dir/layout.cpp.o` failed

**Expected behavior**
Make for `src/CMakeFiles/doxymain.dir/layout.cpp.o` should be successful.

**Screenshots**
![image](https://user-images.githubusercontent.com/13535995/102850020-6ae71400-43e6-11eb-9777-f9399b245437.png)

**To Reproduce**
Clone the latest commit, 
make 'cmake -G"Unix Makefiles" ..
make

**Version**
doxygen version :1.9.0
platform: WSL2, Ubuntu 18.04.5 LTS

**Stack trace**
None

**Additional context**
None

**Comment by albert-github** [comment] 2020-12-22 08:53
Strange situation, we have no problems building doxygen. The `layout_default.xml.h` is an automatically generated file. 
The file that I have is 226 lines long, it looks like your file is more or less double in size.
Please remove the file `generated_src/layout.xml.h` and rerun the compilation / link phase i.e. the `make`.

In case the problem persists, please attach the newly generated file, in a tar or zip file and attach it to the issue. Please don't add external links as they might not be persistent.

**Comment by doxygen** [comment] 2020-12-22 15:26
@Lawliar Since you run Linux under Windows apparently, also make sure the no Windows style line endings (i.e  \r\n instead of \n) have been introduced in layout_default.xml (that might explain the doubling in size and missing "). Best to extract the source archive on Linux with `tar zxvf tarball`, instead of with zip under Windows.

**Comment by Lawliar** [comment] 2020-12-23 02:55
@doxygen @albert-github 
Thank you for the insights, it turned out it's indeed the line's ending's fault.

Both at the WSL2 Ubuntu terminal,
1. if I git clone the repo, normal text files will be in windows style(even if I execute `git clone` within WSL2 VM). More specifically, the result of `file layout_default.xml.h` will be `exported SGML document, ASCII text, with CR, LF line terminators`, and a normal text file in this setting is `ASCII text, with CRLF line terminators`
2. if I download the same package and decompress myself, both of them are simply `ASCII text`.

For your reference, I attached a normal text file and the layout_default.xml.h in the trouble-some setting(setting one).
[bug-triggering-files.tar.gz](https://github.com/doxygen/doxygen/files/5733011/bug-triggering-files.tar.gz)

Thanks again for your help!

**Comment by doxygen** [comment] 2020-12-23 08:44
@Lawliar you can configure git to keep the original line endings using `git config --global core.autocrlf input`, see also https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration for more details.

**Comment by albert-github** [comment] 2020-12-23 12:43
Even tough I agree that the problem is more usage than a bug, I don't think the problem should surface (as it is quite difficult to see what is really wrong).

So I've just pushed a proposed patch, pull request #8273

**Comment by albert-github** [comment] 2020-12-23 14:28
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment] 2020-12-27 19:16
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2020-12-27 19:16 UTC
Labels: Usage, install/build
