### ISSUE TITLE
crash when clang enable

### ISSUE THREAD

**Issue by 1989wanghang** [doxygen/doxygen#10546] opened 2024-01-09 01:43 UTC
```
diff --git a/src/clangparser.cpp b/src/clangparser.cpp
index b431f6a7b..7e8e34857 100644
--- a/src/clangparser.cpp
+++ b/src/clangparser.cpp
@@ -33,7 +33,7 @@ static std::mutex g_clangMutex;
 ClangParser *ClangParser::instance()
 {
   std::lock_guard<std::mutex> lock(g_clangMutex);
-  if (s_instance!=nullptr) s_instance = new ClangParser;
+  if (s_instance==nullptr) s_instance = new ClangParser;
   return s_instance;
 }
```

**Comment by albert-github** [comment] 2024-01-09 09:55
Well caught.

It is a regression due to:
```
Commit: 6b70d803fea8771c03e6479d968a8d7c497573a8 [6b70d80]
Date: Tuesday, December 26, 2023 12:50:05 PM
Fixing warnings like: `Use the "nullptr" literal`

Fixing sonar cloud warnings like: `Use the "nullptr" literal`
```

I checked the other files in the commit as well, but didn't find further problems.

I've just pushed a proposed patch, pull request #10547 


In future:
- Please also specify the **full** doxygen version used (`doxygen -v`). In this ccase it was still present in `1.11.0 (9b836cfd47ebd9152509e77990b7a8bb71c188ad)`
- Please provide a proposed pull request.

**Comment by albert-github** [comment] 2024-01-10 08:46
Code has been integrated in master on GitHub (closing issue as it only occurred in the master version).

**Closed by albert-github** 2024-01-10 08:46 UTC
Labels: bug
