### ISSUE TITLE
HTML in markdown headers is improperly escaped

### ISSUE THREAD

**Issue by hemberger** [doxygen/doxygen#7649] opened 2020-03-19 19:57 UTC
This affects doxygen version 1.8.16+.

When HTML is used in a markdown header, it is escaped and displayed as raw HTML. This also affects markdown that generates HTML, such as a markdown link (i.e. `[link text](href)`).

For example, take the following file `main.dox`:
```
/**

\page main

# [link](main.html)

[link](main.html)

*/
```
Running `doxygen main.dox` creates a file `html/main.html` that displays as follows:
<img src="https://user-images.githubusercontent.com/846186/77107767-69fbfe80-69de-11ea-8d60-e5e0c3347ac3.png" width="80%" />

In earlier versions (up to 1.8.15), it would have displayed like this:

<img src="https://user-images.githubusercontent.com/846186/77108220-0faf6d80-69df-11ea-99fb-6560deb5be8e.png" width="37%" />

**Comment by albert-github** [comment] 2020-03-20 09:57
I think this is a duplicate of #6998

**Closed** 2020-04-13 11:51 UTC
Labels: duplicate
