### ISSUE TITLE
Bug 796734 - warning: documented symbol `xxx' was not declared or defined 

### ISSUE THREAD

**Issue by Kochise** [doxygen/doxygen#6606] opened 2018-11-06 15:39 UTC
```
///
/// \fn	toto
///
__STATIC_INLINE
__OPTIMIZE("O3")
void toto(void)
{
	;
}
```

Looks like function decoration is not properly handled. Same error with 1.8.6.

**Comment by albert-github** [comment] 2018-11-06 18:22
I did a small test but didn't get a warning message. In general these decorations are unknown to doxygen (which language is this? C?) see also the preproccesing part of the manual (http://www.doxygen.org/manual/preprocessing.html) especially the part about `__dllspec`
Can you explain / show the exact error message that you get from doxygen.

Can you complete this to a more complete example and add attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem?

**Comment by Kochise** [comment] 2018-11-07 07:53
gnu gcc arm none eabi 7 2018 q2 update win32 : 

```
#if !defined(__STATIC)
	#define __STATIC	static
#endif	// defined(__STATIC)

#if !defined(__INLINE)
	#define __INLINE	inline
#endif	// defined(__INLINE)

#if !defined(__STATIC_INLINE)
	#define __STATIC_INLINE	__STATIC __INLINE
#endif	// defined(__STATIC_INLINE)

#if !defined(__OPTIMIZE)
	#define __OPTIMIZE(x)	__attribute__((optimize( x )))
#endif	// defined(__OPTIMIZE)
```

**Comment by albert-github** [comment] 2018-11-07 09:32
Looks indeed like something in respect to the __attribute__, but see for this the preproccesing part of the manual (http://www.doxygen.org/manual/preprocessing.html) especially the part about __dllspec.

Furthermore also please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem?

**Comment by dhmartin** [comment] 2022-01-26 21:39
I am getting this same warning in a different context: PHP standalone file. I have squeezed my code to a simple file to reproduce this meaningless warning:
```
<?php

/**
 * @file
 * Easy text.
 */

/** Useless variable */
$myvar = 5;

for($i=0; $i<10; $i++) {
	print("Some text\n");
}

// print("Hi\n");
$myvar = 4;
?>
```
Launch it with defaults options and latest Doxygen 1.9.3
```
$> doxygen -g
$> doxygen > docs.log
example.php:16: warning: documented symbol 'for' was not declared or defined.
```
¿Suspicious about the commented "print" after the loop? If you remove the whole line the warning survives. If you just remove the comment slashes, the warning goes away! The warning seems to be associated with a variable used before and straight after a "for", "if" or "foreach" block. The HTML text produced to describe the variable also seems to be wrong:
```
Variable Documentation
◆ $myvar
for ( $i=0;$i< 10;$i++) $myvar = 5
```
Regards,
David

**Comment by PackmanDude** [comment] 2023-08-12 15:26
It's broken with the GCC attributes, how do I compile my code and generate a documentation without changing the code in-between? Doxygen tries to search a variable in "argument list" that's not an argument list at all! Literally uncompilable.

**Comment by albert-github** [comment] 2023-08-12 16:11
@PackmanDude 
- which GCC attribute?
- did you read what is written in https://github.com/doxygen/doxygen/issues/6606#issuecomment-436561624
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.
- Please also specify the **full** doxygen version used (`doxygen -v`).

**Comment by PackmanDude** [comment] 2023-08-12 16:46
@albert-github

I would like to send an example to my problem, but it got resolved by some shenanigans or I'm not sure what really happend.

**Comment by albert-github** [comment] 2023-08-13 10:03
The, original, problem as mentioned by @Kochise (and repeated by @PackmanDude) I think is usage
The problem mentioned by @dhmartin is a completely different problem and should / has been reported in a new issue.

**Closed** 2023-08-25 13:58 UTC
Labels: Usage
