### ISSUE TITLE
Class functions defined outside the class using :: not accessible

### ISSUE THREAD

**Issue by Namyalg** [doxygen/doxygen#9262] opened 2022-04-07 14:45 UTC
**Describe the bug**

The file `src/main.cpp` has
```
/**
 * @file 
 * ******/

#include "./include/main.h"
#include<iostream>

namespace a{
    namespace b{
        namespace c{
            /**
             * @brief Constructor.
             * ****************/

            void sample::sample(){
                std::cout<< "This is the constructor " << "\n";
            }
        }
    }
}

```
The file `src/include/main.h` has

```
#include<iostream>

namespace a{
    namespace b{
        namespace c{
            class sample{
                public:
                    sample();
            };
        }
    }
}
```

The documentation for the constructor `sample::sample` is not shown in the doxygen page created for `main.cpp` .
Only the namespaces are visible.
Configuration of the Doxyfile

EXTRACT_ALL = YES
INPUT = src
RECURSIVE = YES

**Expected behavior**
Documentation for the function `sample::sample` is expected to be on the documentation page of `main.cpp`

**Version**
Doxygen version used is 1.9.1

**Comment by albert-github** [comment] 2022-04-08 09:31
I thought I'd written a comment, though it must have landed somewhere in the bit bucket.

I think the output is correct, `sample::sample` is not an element of the file it is the constructor of the class `sample` and hence an element of the class `sample` and shown there. 

So I think the problem is an interpretation of the output and hence usage.

**Comment by ferdymercury** [comment] 2022-04-08 11:02
> void sample::sample(){
>                 std::cout<< "This is the constructor " << "\n";
>             }

This does not seem to be a constructor. Constructor do not return void. If you try to compile the code, it gives:
```
main.cpp:15:33: error: return type specification for constructor invalid
             void sample::sample(){
```
I you remove the "void" keyword, then it compiles fine, and the constructor appears correctly in the Doxygen documentation:

![image](https://user-images.githubusercontent.com/10653970/162423149-97e0f6d6-d1cb-411f-b5a5-af4598eab83b.png)

Find attached a reproducer with the fixed signature.
[constr.zip](https://github.com/doxygen/doxygen/files/8451247/constr.zip)

**Comment by Namyalg** [comment] 2022-04-08 14:05
Thank you @ferdymercury for the help!

**Comment by Namyalg** [comment] 2022-04-08 14:11
main.cpp

```/**
 * @file 
 * ******/

#include "main.h"
#include<iostream>

namespace a{
    namespace b{
        namespace c{
            /**
             * @brief Constructor.
             * ****************/

            sample::sample(){
                std::cout<< "This is the constructor " << "\n";
            }

            /**
             * @brief Sum.
             * 
             * This calculated the sum of 2 numbers
             * 
             * @param a int
             * @param b int
             * @return int
             * ****************/
            int add(int a, int b){
                return (a + b);
            }
        }
    }
}
```

main.h

```
#include<iostream>

namespace a{
    namespace b{
        namespace c{
            class sample{
                public:
                    sample();
                    int add(int, int);
            };
        }
    }
}

```
However, under the `class sample`, only the constructor sample is documented, while the function add has no documentation

![image](https://user-images.githubusercontent.com/53875297/162452777-1fef79ce-065e-4d52-bd04-568852529d58.png)


Only in the namespaces -> all functions the entire documentation of the function is visible

![image](https://user-images.githubusercontent.com/53875297/162453225-bef99e43-5d8f-49b7-8a29-3fea2ff577b7.png)


Is there a way to include all the functions of a class together with complete documentation ?

**Comment by ferdymercury** [comment] 2022-04-08 14:13
Mmm try maybe using in the cpp:

`int sample::add(int a, int b)`

**Comment by Namyalg** [comment] 2022-04-08 14:20
Right, I missed that.
Under the class reference, I am getting the documented functions, which is as expected!

**Closed** 2022-05-05 19:55 UTC
Labels: C/C++, Usage
