### ISSUE TITLE
Newer version using a lot of RAM compared to older version

### ISSUE THREAD

**Issue by macawkitty** [doxygen/doxygen#10253] opened 2023-08-22 12:49 UTC
**Describe the bug**
Doxygen 1.9.7 is using upwards of 20GB RAM compared to 1.9.1 which uses ~11GB with the same config and on the same machine.

**Expected behavior**
Newer version needs RAM at most as much as the older version needed.

**Comment by albert-github** [comment] 2023-08-22 16:09
Without knowing which OS , where you got the exectables (and type of executables: release, debug, ...),  and example it is hard to tell what the problem is.

> Newer version needs RAM at most as much as the older version needed.

cannot be guaranteed by any program due to e.g. new features, bug fixes etc.

**Comment by doxygen** [comment] 2023-08-23 13:51
To make it easier to quantify the issue, I ran doxygen on its own code with version 1.9.1 and then again on master using valgrind's [massif](https://valgrind.org/docs/manual/ms-manual.html) tool.

Version 1.9.1 shows a relatively small memory usage peak after parsing (148 MB):

<img width="1333" alt="massif_1 9 1" src="https://github.com/doxygen/doxygen/assets/1300762/c0dd347b-9d60-43f1-a810-c2d6800d3a07">

The latest version has a significantly higher peak (430 MB)

<img width="1339" alt="massif_1 9 8" src="https://github.com/doxygen/doxygen/assets/1300762/755fd8e9-3d81-47d6-9c72-de1ae4fe9303">

After that the memory usage is still higher, but not extremely so (162MB &rarr; 208MB, or a 28% increase).

Still need to investigate why the difference is so big and if it can be reduced. 
Note that version 1.9.1 was still using qtools, whereas later versions switched to STL classes.
Note also that I set `NUM_PROC_THREADS` to 1 and `HAVE_DOT` to `NO` to prevent threading or external tool impact.

**Comment by albert-github** [comment] 2023-08-23 14:05
> To make it easier to quantify the issue, I ran doxygen on its own code with version 1.9.1 and then again on master using valgrind's [massif](https://valgrind.org/docs/manual/ms-manual.html) tool.

It is not 100% clear to me what you computed, did you compute:
1. either
   - doxygen 1.9.1 on the doxygen 1.9.1 code
   - doxygen master on the doxygen master code
2. or 
   - doxygen 1.9.1 on the doxygen 1.9.1 code
   - doxygen master on the doxygen 1.9.1code
3. or
   - doxygen 1.9.1 on the doxygen master code
   - doxygen master on the doxygen master code


(as version 1. would not make any sense, in my opinion, for comparing the results).

**Comment by doxygen** [comment] 2023-08-23 17:59
With the referenced commit, the memory profile looks a lot better, and more similar to version 1.9.1:

<img width="1564" alt="massif_1 9 8_fix" src="https://github.com/doxygen/doxygen/assets/1300762/5d4c9e08-622e-4c70-9da5-26aceb8978ba">

@macawkitty Can you check if this also makes a significant difference in your project?

**Comment by doxygen** [comment] 2023-08-25 13:50
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.8.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2023-08-25 13:50 UTC
