### ISSUE TITLE
latest doxygen create a HUGE amount of errors/warnings on an error/warning free project

### ISSUE THREAD

**Issue by aotto1968** [doxygen/doxygen#11269] opened 2024-12-11 10:46 UTC
```
> doxygen -V
1.13.0 (396e81da3b44b9bb156ffbc5fd263e17f8f638a8)
    with sqlite3 3.42.0.
```

I use the new doxygen on an existing target ... 
- now I get >2.000 warnings etc . something which was message-free before.

problems:

1. Initial starting with: `.../LibMkKernel_mk.h:12128: warning: unbalanced grouping commands`  - a file with 13.000 lines of code I now have to scan for this thing … Task: add DEBUG option for unbalanced GROUPS
2. `#define __parser__(...)` seems to be broken the ... as multiple arguments list is NOT parsed → I want to ignore this. I have the `PREDEFINED +=  "__parser__(...)="` which seems to be ignored.

attachment:
1. Task: NO special debug option to focus on grouping error

> doxygen -d
Developer parameters:
  -m          dump symbol map
  -b          making messages output unbuffered
  -c <file>   process input file as a comment block and produce HTML output
  -d <level>  enable a debug level, such as (multiple invocations of -d are possible):
        alias
        cite
        commentcnv
        commentscan
        entries
        extcmd
        filteroutput
        formula
        fortranfixed2free
        layout
        lex
        lex:code
        lex:commentcnv
        lex:commentscan
        lex:configimpl
        lex:constexp
        lex:declinfo
        lex:defargs
        lex:doctokenizer
        lex:fortrancode
        lex:fortranscanner
        lex:lexcode
        lex:lexscanner
        lex:pre
        lex:pycode
        lex:pyscanner
        lex:scanner
        lex:sqlcode
        lex:vhdlcode
        lex:xml
        lex:xmlcode
        markdown
        nolineno
        plantuml
        preprocessor
        printtree
        qhp
        rtf
        sections
        stderr
        tag
        time

**Comment by albert-github** [comment] 2024-12-11 10:56
Looks like a bit of a missing closing grouping command (like `\}`) but without an example / where to find `LibMkKernel_mk.h` it is hard to tell where, so:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

or
- provide the missing information (including used settings file!)


I agree that it would be nice to have the probable line where the corresponding open command (`\{`) is .

**Comment by albert-github** [comment] 2024-12-11 11:10
Looking at the code it looks like there are more group closing commands (`\}`) than group opening (`\{`) commands and that the extra closing command is at line 12128. So best is to do a grep something like:
```
grep -n "[\\@][{}]" LibMkKernel_mk.h
```
and do some extra processing on it (will be a bit tedious...)

Furthermore I now see that you mention 2 problems in 1 issue **don't do it** for the second issue create a new issue with a small example.

**Comment by aotto1968** [comment] 2024-12-11 11:10
with `PREDEFINED +=  "__parser__(...)="` I get now huge amount of 

```

> mention below

/// @brief Non-inline replacement for @RMkNs{BflN} …
__parser__(inline=MkBflN,class=MkBufferListC,doc-group=Define,doc-index=Class,hide=yes,prefix=Class,static=yes,alias=MkBflN)
MK_EXTERN MK_BFLN MK_DECL MkBflNP (MK_MNGN mng);

> create this

theKernel/c/gen/kernel_inline_mk.h:119: warning: no matching file member found for
__parser__(inline=MkBflN, class=MkBufferListC, doc- group=Define, doc- index=Class, hide=yes, prefix=Class, static=yes, alias=MkBflN)
Possible candidates:
  '#define __parser__(...)' at line 326 of file theKernel/c/LibMkKernel_mk.h
  '__parser__(inline=MkBuf, class=MkBufferC, doc-group=Define, doc-index=Class, hide=yes, prefix=Class, static=yes, alias=MkBuf) MK_EXTERN MK_BUF MK_DECL MkBufP(MK_MNG mng)' at line 31 of file theKernel/c/gen/kernel_inline_mk>
  '__parser__(inline=MkBufferHandleResolve_RT, class=MkBufferC, doc-group=_ignore_, doc-index=Class, doc-name=Export, flags=new, static=yes, alias=MkBufferHandleResolve, runtime=MkBufferHandleResolve) MK_EXTERN MK_BUF MK_DECL MkBufferHandleResolveP(MK_>
  '__parser__(inline=MkBufferHandleGet_RT, INSTANCE=buf, class=MkBufferC, class-overload=MkObjectHandleGet, doc-group=_ignore_, doc-index=Class, doc-name=Export, alias=MkBufferHandleGet, runtime=MkBufferHandleGet) MK_EXTERN MK_HDL MK_DECL MkBufferHandl>
  '__parser__(inline=MkBufferNext, INSTANCE=buf, class=MkBufferC, doc-index=Class, doc-name=Introspection, flags=new, no-rpc=yes, null-return-allow=yes, alias=MkBufferNext) MK_EXTERN MK_BUF MK_DECL MkBufferNextP(MK_BUF const buf)' at line 72 of file /h>
  '__parser__(inline=MkBufferInstances_RT, class=MkBufferC, doc-index=Class, doc-name=Introspection, flags=new, no-rpc=yes, null-return-allow=yes, static=yes, alias=MkBufferInstances, runtime=MkBufferInstances) MK_EXTERN MK_BUF MK_DECL MkBufferInstance>
  '__parser__(inline=MkBufferGetNull, class=MkBufferC, doc-group=_ignore_, doc-index=Class, doc-name=Misc, flags=new, null-return-allow=yes, static=yes, alias=MkBufferGetNull) MK_EXTERN MK_BUF MK_DECL MkBufferGetNullP(void)' at line 92 of file /home/de>
  '__parser__(inline=MkErrorDEFAULT_RT, class=MkErrorC, doc-group=System, static=yes, alias=MkErrorDEFAULT, runtime=MkErrorDEFAULT) MK_EXTERN MK_ERR MK_DECL MkErrorDEFAULTP(MK_PARSER_RT_ONLY)' at line 335 of file theKernel/c/>
  '__parser__(inline=MkErrorPANIC_RT, class=MkErrorC, doc-group=System, hide=yes, static=yes, alias=MkErrorPANIC, runtime=MkErrorPANIC) MK_EXTERN MK_ERR MK_DECL MkErrorPANICP(MK_PARSER_RT_ONLY)' at line 341 of file theKernel/>
  '__parser__(inline=MkBinaryCreate, hide=yes, static=yes, alias=MkBinaryCreate) MK_EXTERN MkBinaryR MK_DECL MkBinaryCreateP(MK_SIZE size' at line 360 of file theKernel/c/gen/kernel_inline_mk.h
  '__parser__(inline=MkBinaryCreateSlice, RET-ATTR=M, hide=yes, static=yes, alias=MkBinaryCreateSlice) MK_EXTERN MkBinaryR MK_DECL MkBinaryCreateSliceP(MkBinaryR const bin' at line 363 of file theKernel/c/gen/kernel_inline_mk>
  '__parser__(inline=MkBinaryDup_RT, hide=yes, static=yes, alias=MkBinaryDup, runtime=MkBinaryDup) MK_EXTERN MkBinaryR MK_DECL MkBinaryDupP(MK_PARSER_RT MkBinaryR const bin)' at line 426 of file theKernel/c/gen/kernel_inline_>
  '__parser__(inline=MkErrorE_ToInt, class=MkKernel, doc-group=Enum, doc-index=_ignore_, no-rpc=yes, prefix=EnumFunc, static=yes, alias=MkErrorE_ToInt) MK_EXTERN MK_I32 MK_DECL MkErrorE_ToIntP(enum MkErrorE value)' at line 390 of file /home/dev1usr/Pro>
  '__parser__(inline=MkStringSplit, DEFAULT-ARGS=len_out str_out, hide=yes, static=yes, alias=MkStringSplit) MK_EXTERN void MK_DECL MkStringSplitP(MkStringR strR' at line 436 of file theKernel/c/gen/kernel_inline_mk.h
  '__parser__(inline=MkObjectNext, INSTANCE=obj, class=MkObjectC, doc-index=Class, doc-name=Introspection, no-rpc=yes, null-return-allow=yes, alias=MkObjectNext) MK_EXTERN MK_OBJ MK_DECL MkObjectNextP(MK_OBJ const obj)' at line 552 of file /home/dev1us>
  '__parser__(inline=MkObjectInstances_RT, class=MkObjectC, doc-index=Class, doc-name=Introspection, no-rpc=yes, null-return-allow=yes, static=yes, alias=MkObjectInstances, runtime=MkObjectInstances) MK_EXTERN MK_OBJ MK_DECL MkObjectInstancesP(MK_PARSE>
  '__parser__(inline=MkObjectGetNull, class=MkObjectC, doc-group=_ignore_, doc-index=Class, doc-name=Misc, null-return-allow=yes, static=yes, alias=MkObjectGetNull) MK_EXTERN MK_OBJ MK_DECL MkObjectGetNullP(void)' at line 572 of file /home/dev1usr/Proj>
  '__parser__(inline=MkObjectToError_RT, INSTANCE=obj, alias=MkObjectToError, runtime=MkObjectToError) MK_EXTERN MK_ERR MK_DECL MkObjectToErrorP(MK_PARSER_RT MK_OBJ const obj)' at line 584 of file theKernel/c/gen/kernel_inlin>
  '__parser__(inline=MkObjectHandleGetOfType, INSTANCE=obj, alias=MkObjectHandleGetOfType) MK_EXTERN MK_HDL MK_DECL MkObjectHandleGetOfTypeP(MK_OBJ const obj)' at line 589 of file theKernel/c/gen/kernel_inline_mk.h
  '__parser__(inline=MkRefGet, INSTANCE=obj, doc-no=yes, hide=yes, keep=yes, prefix=MkObj, alias=MkRefGet) MK_EXTERN MK_I32 MK_DECL MkRefGetP(MK_OBJ const obj)' at line 605 of file theKernel/c/gen/kernel_inline_mk.h
  '__parser__(inline=MkRefIncrSelf, INSTANCE=obj, hide=yes, prefix=MkObj, alias=MkRefIncrSelf) MK_EXTERN void MK_DECL MkRefIncrSelfP(MK_OBJ const obj' at line 608 of file theKernel/c/gen/kernel_inline_mk.h
  '__parser__(inline=MkSelfExists, INSTANCE=obj, const=yes, hide=yes, prefix=MkObj, alias=MkSelfExists) MK_EXTERN MK_BOOL MK_DECL MkSelfExistsP(MK_OBJN obj)' at line 617 of file theKernel/c/gen/kernel_inline_mk.h
  '__parser__(inline=MkSelfNew_RT, INSTANCE=obj, hide=yes, prefix=MkObj, alias=MkSelfNew, runtime=MkSelfNew) MK_EXTERN enum MkErrorE MK_DECL MkSelfNewP(MK_PARSER_RT MK_OBJ obj' at line 630 of file theKernel/c/gen/kernel_inlin>
  '__parser__(inline=MkRefIncr, hide=yes, prefix=MkObj, static=yes, alias=MkRefIncr) MK_EXTERN void MK_DECL MkRefIncrP(MK_OBJ obj)' at line 635 of file theKernel/c/gen/kernel_inline_mk.h
  '__parser__(inline=MkRuntimeHandleResolve_RT, class=MkRuntimeC, doc-group=_ignore_, doc-index=Class, doc-name=Export, flags=new, hide=yes, static=yes, alias=MkRuntimeHandleResolve, runtime=MkRuntimeHandleResolve) MK_EXTERN MK_RT MK_DECL MkRuntimeHand>
  '__parser__(inline=MkRuntimeHandleGet_RT, INSTANCE=rt, class=MkRuntimeC, class-overload=MkObjectHandleGet, doc-group=_ignore_, doc-index=Class, doc-name=Export, hide=yes, alias=MkRuntimeHandleGet, runtime=MkRuntimeHandleGet) MK_EXTERN MK_HDL MK_DECL >
  '__parser__(inline=MkRuntimeNext, INSTANCE=rt, class=MkRuntimeC, doc-index=Class, doc-name=Introspection, flags=new, hide=yes, no-rpc=yes, null-return-allow=yes, alias=MkRuntimeNext) MK_EXTERN MK_RT MK_DECL MkRuntimeNextP(MK_RT const rt)' at line 692>
  '__parser__(inline=MkRuntimeInstances_RT, class=MkRuntimeC, doc-index=Class, doc-name=Introspection, flags=new, hide=yes, no-rpc=yes, null-return-allow=yes, static=yes, alias=MkRuntimeInstances, runtime=MkRuntimeInstances) MK_EXTERN MK_RT MK_DECL MkR>
  '__parser__(inline=MkRuntimeGetNull, class=MkRuntimeC, doc-group=_ignore_, doc-index=Class, doc-name=Misc, flags=new, hide=yes, null-return-allow=yes, static=yes, alias=MkRuntimeGetNull) MK_EXTERN MK_RT MK_DECL MkRuntimeGetNullP(void)' at line 712 of>
  '__parser__(inline=MkRuntimeGet, doc-group=Config, hide=yes, static=yes, alias=MkRuntimeGet) MK_EXTERN MK_RT MK_DECL MkRuntimeGetP(void)' at line 724 of file theKernel/c/gen/kernel_inline_mk.h
  '__parser__(inline=MkRuntimeGetDebug, doc-group=Config, static=yes, alias=MkRuntimeGetDebug) MK_EXTERN MK_I32 MK_DECL MkRuntimeGetDebugP(void)' at line 733 of file theKernel/c/gen/kernel_inline_mk.h
  '__parser__(inline=MkRuntimeGetErrorCode_RT, doc-group=Config, error-ignore=yes, static=yes, alias=MkRuntimeGetErrorCode, runtime=MkRuntimeGetErrorCode) MK_EXTERN enum MkErrorE MK_DECL MkRuntimeGetErrorCodeP(MK_PARSER_RT_ONLY)' at line 736 of file /h>
  '__parser__(inline=MkRuntimeSetIsSilent_RT, doc-group=Config, static=yes, alias=MkRuntimeSetIsSilent, runtime=MkRuntimeSetIsSilent) MK_EXTERN void MK_DECL MkRuntimeSetIsSilentP(MK_PARSER_RT MK_BOOL silent)' at line 748 of file /home/dev1usr/Project/N>

obvious the `__parser__` is **not** ignored
```

**Comment by albert-github** [comment] 2024-12-11 11:24
What do the lines : 
```
>> /*
```
and 
```
>> */
```

https://github.com/doxygen/doxygen/issues/11269#issuecomment-2535555658  ...

**Comment by albert-github** [comment] 2024-12-11 11:39
In the code I see `...` but I assume that there is more documentation comment, but hat this has been removed to et a briefer "example". I would like to see the complete block that is between the "hints" `>>`  better the original code without your tests / amendments. It is not for nothing that we nearly always ask  for:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

it is to be **sure** we are talking about the same problem and can reproduce the problem on both side. Sone problems might be quite subtle!

**Comment by aotto1968** [comment] 2024-12-11 11:47
just to be clear `#define __parser__(...)` is the C syntax for `__parser__` with any number of arguments and this parsing seems to be changed. **NOW** the `__parser__` are read as "C" command and destroy all the syntax.

→ I want that `__parser__(...)` is ignored.

**Comment by aotto1968** [comment] 2024-12-11 12:55
"usage" ore "bug" ? 

In history the `EXPAND_AS_DEFINED` was applied to the macro definition in the source-file and __not__ in the config-file and now the `PREDEFINED` also require this?

```
#---------------------------------------------------------------------------
# Configuration options related to the preprocessor
#---------------------------------------------------------------------------

# If the ENABLE_PREPROCESSING tag is set to YES, Doxygen will evaluate all
# C-preprocessor directives found in the sources and include files.
# The default value is: YES.

ENABLE_PREPROCESSING   = YES

# If the MACRO_EXPANSION tag is set to YES, Doxygen will expand all macro names
# in the source code. If set to NO, only conditional compilation will be
# performed. Macro expansion can be done in a controlled way by setting
# EXPAND_ONLY_PREDEF to YES.
# The default value is: NO.
# This tag requires that the tag ENABLE_PREPROCESSING is set to YES.

MACRO_EXPANSION        = YES

# If the EXPAND_ONLY_PREDEF and MACRO_EXPANSION tags are both set to YES then
# the macro expansion is limited to the macros specified with the PREDEFINED and
# EXPAND_AS_DEFINED tags.
# The default value is: NO.
# This tag requires that the tag ENABLE_PREPROCESSING is set to YES.

EXPAND_ONLY_PREDEF     = YES

# If the MACRO_EXPANSION and EXPAND_ONLY_PREDEF tags are set to YES then this
# tag can be used to specify a list of macro names that should be expanded. The
# macro definition that is found in the sources will be used. Use the PREDEFINED
# tag if you want to use a different macro definition that overrules the
# definition found in the source code.
# This tag requires that the tag ENABLE_PREPROCESSING is set to YES.

EXPAND_AS_DEFINED      = ...

```

**Comment by albert-github** [comment] 2024-12-11 13:06
When I understand you correctly your impression is that the expansion was correct in doxygen version 1.12.0 and is faulty in the current master (1.13.0 (401de7aa290e21f557e28515a5887fc40a092f62)), to be able to see where the difference comes from (doing some bisecting) it is absolutely necessary to have an example that reproduces the problem! Otherwise there is **NO** way to see what might have caused the difference, so:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

**Comment by aotto1968** [comment] 2024-12-11 13:31
I understand your problem, **but** if i setup an easy example than it works as expected and only in the *really-large-project* it show the bug from above.

**Comment by albert-github** [comment] 2024-12-11 13:46
> I understand your problem, but if i setup an easy example than it works as expected and only in the really-large-project it show the bug from above.

So there might also be another problem ...

Looking at the warnings there are a number of files mentioned like:
- theKernel/c/LibMkKernel_mk.h
- theKernel/c/gen/kernel_inline_mk.h

together wit the settings file might already show the problem. When this is not the case the full project might be necessary, though maybe playing a bit with the `INPUT` setting (i.e. reducing the number of directories / files) might already give an indication.

Btw. how long does it take to build the documentation for the entire project ?

**Comment by aotto1968** [comment] 2024-12-11 13:52
ok, later I try to extract the whole project ...

**Comment by aotto1968** [comment] 2024-12-12 11:56
## it become even worser 

now I changed my SW to avoid `PREDEFINED` and switch to `EXPAND_AS_DEFINED` and 3 of 4 project compiled and *doxygen* well … __BUT__ ... the last project stopped working with *doxygen* go into an infinity event loop

![image](https://github.com/user-attachments/assets/83044d3a-0775-4c1e-9168-6a0d8bf876d6)

**Comment by albert-github** [comment] 2024-12-20 17:56
> ok, later I try to extract the whole project ...

any success? Can you otherwise share the entire tree, 5000 files is a lot but without an example / anything it is not possible to say / solve anything. 
Regarding the possible endless loop it is impossible to say anything about it without an example / full project and the fact that you wrote:
> now I have the feeling I spend more time debugging doxygen as doing real work on my project.

So please share an example / whole project / repository where we can find the project.

**Comment by doxygen** [comment] 2024-12-22 09:01
@albert-github If I purely look at the changes in `pre.l` since 1.12.0 the only thing related to define processing is https://github.com/doxygen/doxygen/pull/11220. Without reproduction scenario, it is hard to check. @aotto1968 Maybe you can check if it makes a difference if you undo this one line change.

**Comment by albert-github** [comment] 2024-12-22 09:07
@doxygen could it be that one of the 2 filenames is a full path and the other is not (or that one is a link?) but without an example it is indeed impossible to tel what is the problem.

**Closed** 2024-12-28 09:24 UTC
Labels: needinfo, Usage
