### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by reavessm** [doxygen/doxygen#6517] opened 2018-09-16 17:07 UTC
Doxygen does a great job creating webpages based on markdown files, could it also render the emojis in the files?

I have some files where I would like `:smiley:` to show up as :smiley:, for example.

**Comment by albert-github** [comment] 2018-09-17 12:52
Is there anywhere a, free, translation table between the `:smiley:` syntax and the corresponding Unicode character `&#x1F600;` ? 
Analogous also for other formats, especially LaTeX?

There is a nice Unicode list (https://unicode.org/emoji/charts/full-emoji-list.html) with all Emoji characters.
There are also tables with the `:smiley:` syntax (e.g. https://www.webpagefx.com/tools/emoji-cheat-sheet/ or https://gist.github.com/rxaviers/7360908)

**Comment by albert-github** [comment] 2018-09-17 13:28
That is the same list as the first list I mentioned in my comment.

I'm looking for a table that translates the e.g. `:smiley:` to `&#x1F600` or `U+1F600`

**Comment by albert-github** [comment] 2018-09-17 14:42
That table (https://api.github.com/emojis) looks very interesting, it is not 100% complete (but that is probably a minor detail. missing at least Scotland, England, Wales but they are easily added).
There are a few culprits in the table like `:man-wrestling:` pointing to https://assets-cdn.github.com/images/icons/emoji/unicode/1f93c-2642.png?v8 so it looks lake 2 codes but in fact it are 4: U+1F93C U+200D U+2642 U+FE0F but comparing this table with the https://unicode.org/emoji/charts/full-emoji-list.html table should do the trick.
This gives a good starting point, translation of this table should not be a big issue for me.

**Comment by reavessm** [comment] 2018-09-17 14:46
Yeah there definitely are some holes, but here is a json with the unicodes from the table
[emojis.json.txt](https://github.com/doxygen/doxygen/files/2389003/emojis.json.txt)

**Comment by t-b** [comment] 2018-09-17 14:48
Aren't the github names just the unicode "CLDR Short Name" names all lower case and with `_` instead of spaces? Standardzing on some arbitrary github names does not sound like a good solution.

**Comment by lrineau** [comment] 2018-09-17 14:53
[**@t-b**](https://github.com/t-b) commented on [Sep 17, 2018, 4:48 PM GMT+2](https://github.com/doxygen/doxygen/issues/6517#issuecomment-422047156 "2018-09-17T14:48:35Z - Replied by Github Reply Comments"):
> Aren't the github names just the unicode "CLDR Short Name" names all lower case and with `_` instead of spaces? Standardzing on some arbitrary github names does not sound like a good solution.

No. For example, `:grin:` gives :grin:, that is U+1F601 with the short name "beaming face with smiling eyes".

**Comment by albert-github** [comment] 2018-09-17 14:57
@reavessm thanks for the table, looks like besides the 3 countries there are some more items missing (in the latest file I see 1508 items and the unicode table has 1644 items), not a big issue I;ll have to look into it.

@t-b I was already typing, but you found it as well. No the names are not just the "CLDR Short Name" names all lower case and with _" e.g. code U-1F604 has `:smile:` as "github name" and "grinning face with smiling eyes" as "CLDR Short Name"

**Comment by t-b** [comment] 2018-09-17 15:49
@lrineau @albert-github Thanks for the correction.

**Comment by albert-github** [comment] 2018-10-01 17:03
I've just pushed a proposed patch, pull request #6534

**Comment by albert-github** [comment] 2018-11-07 18:48
When integrating pay attention to #6608 as here also a new command is added (multiple numbers in cmdmapper.h).

**Comment by albert-github** [comment] 2018-11-11 13:52
Code has been integrated in master on github.

**Comment by sloriot** [comment] 2018-11-12 10:05
@albert-github Looks like there are some regression introduced (not sure if I should open a new issue).
For example I got these warnings:
models:2: warning: Unsupported emoji ':Surface_mesh_approximation:' found while handling command \ref
models:3: warning: Unsupported emoji ':Surface_mesh_approximation:' found while handling command \ref
And this output:
![screenshot from 2018-11-12 11-02-55](https://user-images.githubusercontent.com/1224632/48340422-e0f6e980-e66a-11e8-9551-b2f52d5d5ab1.png)

Let me know if you need more details.

**Comment by albert-github** [comment] 2018-11-12 11:08
Thanks for bringing this to our attention.

At first I thought:
In the new update there is the possibilities for emoji, and `:Surface_mesh_approximation:` is not an emoji so the message is correct. For cases like these the command `\:` has been introduced: the way to specify this is `\:Surface_mesh_approximation\:`.

But I see in the image I see that in some cases it looks like the `::` part is not handled properly.

So I do think it is a regression, please file a new issue.
I can build the full documentation but this takes some time, please add to the issue:
- a name of output file where you see the problem
- how to generate documentation of 1 subdirectory (`make doc` generates all), when easily possible of course

**Comment by sloriot** [comment] 2018-11-12 13:49
Thanks, see #6612

**Comment by doxygen** [comment] 2018-12-27 21:48
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2018-12-27 21:48 UTC
Labels: enhancement
