### ISSUE TITLE
The Doxygen uses too much memory (or has probably a memory leak)

### ISSUE THREAD

**Issue by sl42** [doxygen/doxygen#7954] opened 2020-08-11 06:10 UTC
Hello!

I am sorry, but something seems wrong with the Doxygen memory usage under Windows 10. 
I am using Doxygen for a large project and I am really happy for this wonderful tool. Thank you for the Doxygen tool. 

Unfortunately I am experiencing a weird behaviour since one or two weeks. Doxygen seems to become slower and slower and finally quits its processing with an 'Out of memory' message. 
I am using Doxygen with the clang parser option to create the documentation with interactive SVG images. 
When I controlled Doxygen using the MicroSoft Process Explorer and the Windows Task Manager I detected that its committed memory size is extremely high. With the latest official Windows 64 bit version 1.8.19 (downloaded from http://doxygen.nl/files/doxygen-1.8.19.windows.x64.bin.zip) I got the following values:

`.\doxygen.exe --version
1.8.19 (21742756bdcc961f1542d168e64e17ee30694b62)`

![memory_consumption_official_1_8_19](https://user-images.githubusercontent.com/25041107/89860837-ae15b880-dba4-11ea-8e7f-140b1830af9d.png)

This happens already in a very early stage of the processing when Doxygen prints out the messages 
`Parsing file ...`
`Processing file ...`

The last self built version where the memory consumption was OK for exactly the same project with exactly the same `.dox`file was the following version:
`.\doxygen.exe --version
1.8.19 (d5916c06fba9667911a19cf658e7c5ab54daf72c)`
The committed memory stayed there at 5 GB during the whole Doxygen run.

![memory_consumption_last_working_version](https://user-images.githubusercontent.com/25041107/89861452-2d57bc00-dba6-11ea-993a-0d21c47e4d20.png)

Now I would like to ask if you to have a look at this strange behaviour. It looks to me as if the libclang internal  parsing data is not properly freed when the parsing of one `.h`or `.cpp`file is finished (I am just guessing).

This strange effect occurs on a Windows 10 64 bit PC.
The attached test.dox file is the kind of Doxygen configuration file which is usually use for processing C++ projects.

Best regards and thank you for your help

[test_dox.zip](https://github.com/doxygen/doxygen/files/5055100/test_dox.zip)

**Comment by albert-github** [comment] 2020-08-11 08:45
A bit strange that you mention twice the same version. I think the official released version is:
1.8.19 (21742756bdcc961f1542d168e64e17ee30694b62)

**Comment by sl42** [comment] 2020-08-11 09:46
Sorry, your are absolutely right:  I got confused with the version numbers and mixed them up:. Here are the correct verion numbers:

The last working version was: 
`.\doxygen.exe --version
1.8.19 (d5916c06fba9667911a19cf658e7c5ab54daf72c*)`

The offical version was:
`.\doxygen.exe --version
1.8.19 (21742756bdcc961f1542d168e64e17ee30694b62)`

**Comment by doxygen** [comment] 2020-08-13 18:11
@sl42 Assuming it is indeed a memory leak in the clang parser part, can you check when disabling `CLANG_ASSISTED_PARSING` the memory usage is normal again?

Also the most likely candidate commit to cause this is https://github.com/doxygen/doxygen/commit/50fdb591d4abfdf88bfdda96ffd832cc4c024963. Can you check that until this commit it was still ok (so until here https://github.com/doxygen/doxygen/commit/cbf83033232f8c76836bd8f086bfad146ed74e00) and with the commit included you see the problem?

**Comment by sl42** [comment] 2020-08-14 20:55
Checkin 50fdb59 was not the cause for the problem. 
.\doxygen.exe --version
1.8.19 (50fdb591d4abfdf88bfdda96ffd832cc4c024963*)

After 5000 Lines (doxygen.log)
![image](https://user-images.githubusercontent.com/25041107/90289756-d808fc80-de7c-11ea-8332-0043fe77c4bc.png)

Also the checkin cbf8303 was not the problem:

.\doxygen.exe --version
1.8.19 (cbf83033232f8c76836bd8f086bfad146ed74e00*)

After 5000 Lines (doxygen.log)
![image](https://user-images.githubusercontent.com/25041107/90289843-05ee4100-de7d-11ea-9a60-1c6820948ec1.png)

Finally I tested the original 1.8.19 version with `CLANG_ASSISTED_PARSING = NO`
(Commit 21742756...)

After 5000 Lines (doxygen.log)
![image](https://user-images.githubusercontent.com/25041107/90289985-52398100-de7d-11ea-98ec-c98b774c1ff0.png)

This also hadn't any effect onto the memory consumption.

 **Finally** I found out, that the problem was introduced by commit  `ff5ebce...`

https://github.com/doxygen/doxygen/commit/ff5ebce0649b5e1fbef2660234f5cc8184e80148

After 5000 Lines (doxygen.log)
![image](https://user-images.githubusercontent.com/25041107/90290095-8c0a8780-de7d-11ea-94dd-e8404a0bc848.png)

The commit before (i.e. commit  `4f28f62`) showed a normal memory consumption behaviour.  
https://github.com/doxygen/doxygen/commit/4f28f621b67d96c3f9eb78f01009867377695558

After 5000 Lines (doxygen.log)
![image](https://user-images.githubusercontent.com/25041107/90290222-c1af7080-de7d-11ea-8707-8597920895e9.png)


I hope this helps a little bit. Nevertheless I am still not quite sure if I build doxygen correctly on Windows. Therefore I am always using the official binary to crosscheck the result.

Best regards

--------------- 8< ----------------------------------------------------------
This is the way how I compile libclang and doxygen: 

open a powershell instance
`mkdir c:\work                                                                                              `
`cd c:\work                                                                                                 `
`git clone https://github.com/llvm/llvm-project.git                                                         `
`cd llvm-project                                                                                            `
`mkdir build                                                                                                `
`cd build                                                                                                   `
`cmd.exe                                                                                                    `
`"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"            `
`cmake -DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra -g "Visual Studio 16 2019" -A x64 -Thost=x64 ..\llvm  `
`devenv.exe .\LLVM.sln                                                                                      `
Then I start the compilation manually.

**Afterwards I build Doxygen:**
open a powershell instance
`cd C:\work                                                                                       `
`git clone https://github.com/doxygen/doxygen                                                     `
`cd doxygen                                                                                       `
`mkdir build                                                                                      `
`cd build                                                                                         `
`cmd.exe                                                                                          `
`"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"  `
`cmake -G "Visual Studio 16 2019" -A x64 -Duse_libclang=ON -Dstatic_libclang=ON -Denlarge_lex_buffers=524287 -DLLVM_DIR=C:\work\llvm-project\build\lib\cmake\llvm  -DClang_DIR=C:\work\llvm-project\build\lib\cmake\clang "-DCMAKE_CXX_FLAGS=-I C:\work\llvm-project\clang\include -I c:\work\llvm-project\build\tools\clang\include"   c:\work\doxygen `
`devenv.exe .\doxygen.sln `
Then I start the compilation manually.

Finally I copy the created DLL `C:\work\llvm-project\build\Release\bin\libclang.dll` and `C:\work\doxygen\build\bin\doxygen.exe` into one directory and that is it.

**Comment by albert-github** [comment] 2020-08-15 09:47
You wrote:
> With the latest official Windows 64 bit version 1.8.19 (downloaded from http://doxygen.nl/files/doxygen-1.8.19.windows.x64.bin.zip) I got the following values: ...

What happens when you use the 32-bit version from the official release:  http://doxygen.nl/files/doxygen-1.8.19.windows.bin.zip

**Comment by doxygen** [comment] 2020-08-15 11:10
@sl42 Thanks for finding out which commit caused this. So far I did not see any memory leaks, but I could be that more memory is used by the way things are restructured. I'm doing some more experiments myself. One thing that would be interesting to know: if you run doxygen on its own sources (with Doxyfile in the root of the distribution) do you then also see the same difference in memory use between the versions?

**Comment by sl42** [comment] 2020-08-15 20:35
Sorry for my late answer. 

I ran both versions and created the doxygen_docs using the `Doxyfile` file. Here is the screenshot with the version where everything worked fine (commit '4f28f62'):

<img width="582" alt="memory_usage_doxyfile_commit_4f28f62" src="https://user-images.githubusercontent.com/25041107/90320667-57610380-df43-11ea-9270-ddeac1e6368c.png">

The memory usage with the new version (commit 'ff5ebce') looked like this:

<img width="583" alt="memory_usage_doxyfile_commit_ff5ebce" src="https://user-images.githubusercontent.com/25041107/90320809-77dd8d80-df44-11ea-85c0-d24bc5d484c0.png">

This was not the kind of difference I expected. Then I thought , the different parameters `RECURSIVE`, `BUILTIN_STL_SUPPORT` or `CLASS_DIAGRAMS`could have caused that effect.. This was also not the case.

Maybe the `include_path` paths could play a role here because there are many libraries added like boost and so on. 

The only other minor differences I found between the config files would be the following parameters:

<img width="523" alt="different_settings" src="https://user-images.githubusercontent.com/25041107/90321048-980e4c00-df46-11ea-8498-439cafc4aee1.png">

Could it be that these flags play a role here? I haven't tested it until now. Sorry

I hope my info helps a little bit.

Best regards and thank you for your help

**Comment by doxygen** [comment] 2020-08-16 08:58
@sl42 Looks like the `INCLUDE_PATH` can trigger the problem. I've now made a `test.cpp` which just includes all public boost headers and nothing else. When I run doxygen on this file and point `INCLUDE_PATH` to where the boost header are located I do see I huge memory usage with 1.8.19 and not with the previous version. I'll investigate further.

**Comment by doxygen** [comment] 2020-08-16 19:32
@sl42 Can you please verify if the problem is solved with the fix I just committed?

**Comment by sl42** [comment] 2020-08-17 06:32
I started a Doxygen run with the large project again with the latest committed Doxygen version 
`1.9.0 (e61a4fb14adedcbffdb0f1627295ade83db34484*)`.

After 5000 Lines (doxygen.log) the Process Explorer showed this memory usage:
<img width="485" alt="memory_usage_doxyfile_commit_e61a4fb" src="https://user-images.githubusercontent.com/25041107/90363936-c2096080-e063-11ea-80b7-774c3c1fa25b.png">

This latest commit shows now the same memory consumption as the old version. The problem is definitely fixed for me.

Thank you very much for your help. 

Best regards

**Comment by doxygen** [comment] 2020-08-17 20:49
Found some inaccuracies in the administration that keeps track which macros are available in which files. These should be addressed in the new commit. Memory usage should not increase significantly (processing time may go up a bit, but should also not exceed that of version 1.8.18).

**Comment by sl42** [comment] 2020-08-19 07:51
I currently tested it with my large project and it showed no memory consumption anomalies. Thanks for these improvements.

**Comment by doxygen** [comment] 2020-08-24 13:35
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.20.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2020-08-24 13:35 UTC
Labels: bug
