### ISSUE TITLE
I'd like a man output configuration option like HTML_TIMESTAMP for footers. (Origin: bugzilla #646436)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4225] opened 2018-07-02 05:29 UTC
status NEW severity *enhancement* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-04-01 12:35:29 +0000, Manuel L. Pereira GarcÃ­a wrote:

    Good afternoon:
    
    I'd like a man output configuration option like HTML_TIMESTAMP for footers.
    Actually the footer shows the version, the generation date and the manpage
    identification. Well, it is good, but it will be better if one could choose
    between showing the generation date or the project name and its version.
    
    Reasons for including it:
      Sometimes the date is not interesting. For example: if the project has
    reached certain stability and is considered finished. Nevertheless, if
    certain people tends to think that if the date is shown is because this is
    an important thing.
    
    Thank you for your attention and for your work.
    
    Carefully,
    Manuel L. Pereira GarcÃ­a.

**Comment by albert-github** [comment] 2023-05-15 13:26
This looks like a duplicate of bug 750447 (#5797)

**Closed** 2023-05-18 20:30 UTC
Labels: duplicate, enhancement, Man
