### ISSUE TITLE
Don't warn about missing parameter documentation for deleted functions

### ISSUE THREAD

**Issue by fwalch** [doxygen/doxygen#6607] opened 2018-11-07 13:11 UTC
I have a class with deleted functions, i.e:

```cpp
class A {
public:
A(const A&) = delete;
A& operator=(const A&) = delete;
}
```

`WARN_NO_PARAMDOC` is set to `YES`.

From Doxygen 1.8.10 to 1.8.12, this does not give any warnings for the deleted members. Starting from Doxygen 1.8.13, warnings are shown:

```
test.cpp:3: warning: parameters of member A::A are not (all) documented
test.cpp:4: warning: parameters of member A::operator= are not (all) documented
```

Related: #5772

**Comment by albert-github** [comment] 2018-11-07 14:14
I can reproduce the problem as indicated.
The problem comes from the addition of the lines:

```
  else if (!isDetailedSectionLinkable())
  {
    warnIfUndocumentedParams();
  }
```

on December 29, 2016, (git identification: https://github.com/doxygen/doxygen/commit/bae3c91812f8a6f845337f8c32d55495c4aa3522) in the function `void memberDef::warnIfUndocumented()` lines 3251.

I'm not sure about the possible fix.

**Comment by carlosgalvezp** [comment] 2019-04-08 11:34
Are there any updates on this?

**Comment by albert-github** [comment] 2019-04-08 12:14
I've just pushed a proposed patch, pull request #6918

**Comment by albert-github** [comment] 2019-04-22 08:05
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment] 2019-08-08 17:49
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2019-08-08 17:49 UTC
Labels: C/C++, bug

**Comment by Mi-La** [comment] 2019-08-28 20:36
Hi, I observe similar behavior also for return type of a deleted method.

C++:
```MyClass& MyClass::operator=(const MyClass&) = delete;```
Doxygen warning:
```warning: return type of member MyClass::operator= is not documented```

Will this be also fixed within this issue?

**Comment by albert-github** [comment] 2019-08-29 09:04
@Mi-La Which version of doxygen did you use to test your problem?

**Comment by Mi-La** [comment] 2019-08-29 10:55
I had quite old version 1.8.10. But I just tested it with 1.8.16 and it seems to be fixed. Thanks!
