### ISSUE TITLE
Feature: Add EXTERNAL_NAMESPACES configuration option, or similar

### ISSUE THREAD

**Issue by oblivioncth** [doxygen/doxygen#10234] opened 2023-08-15 17:17 UTC
I initially requested that external namespaces from tags not appear in the namespace index, at least by default, with #9241 which was actioned on. Later, in 1.9.6 the entries returned, albeit with an appropriate "[external]" designation. It appears (as kindly pointed out by @albert-github) that this was due to the work for #9602. 

I can understand why some might want these namespaces to appear in the index in certain circumstances, like when the tags in question belong to related projects, particularly those also controlled by the same author; however, in my case I am only using tags to link to Qt documentation, which of course is a well known project with its own documentation that can easily be perused independently and so I don't want its namespaces (which often aren't even used directly in user code) appearing in my documentation.

**Expected behavior**
Given we already have configurations like:

- EXTERNAL_GROUPS
- EXTERNAL_PAGES

which affect the presence of other entities in their respective indices of the current project, I figure it would be reasonable to also have an option (i.e. EXTERNAL_NAMESPACES) that also controls whether or not external namespaces appear in the index.

Ultimately, I think user's should be able to control whether or not namespaces from tags appear here in one way or another, regardless of the particular method.

**Screenshots**
![image](https://github.com/doxygen/doxygen/assets/24661585/fb8c13b2-0acd-4104-b16d-437d9f7b3268)

**To Reproduce**
Use any project with tags that have documented namepsaces. If a sample project is needed, the one form #9241 should still suffice.

**Version**
1.9.7

**Comment by oblivioncth** [comment] 2023-08-16 14:21
Summary of SO discussion with albert:

- This is not a matter of correctness, but rather a matter of cleanliness/style, and being able to decide what is relevant from external resources for a given project
- Downstream projects of course cannot control what is included in a tag file (without manual stripping), so if I want *something* from a tag file I need to take in *everything* from it. Anything Doxygen can do to help filter out some content from said tags that I don't consider pertinent to my project is appreciated.
- The concern for this particular project is that the inclusion of these extraneous entries feels random, haphazard, and distracting; almost like an ugly implementation detail. Especially the android related namespace since this lib doesn't even support Qt Android
- Doxygen already allows controlling the presence of other external tokens from tags in various indices (i.e. classes, groups, etc), so it's natural that namespaces might also have this option
- Doxygen is already able to identify that a namespace is external, so hiding it from the index should (admittedly I'm assuming here) be somewhat trivial.
- Albert suggested that a more complete, albeit more involved solution to handling this, might be added the ability to filter tag inclusions with doxygen via syntax similar to `TAGS_EXCLUDE = namespace:QtAndroidPrivate`

**Comment by albert-github** [comment] 2023-08-17 10:15
@doxygen 
In the documentation we see:
> `ALLEXTERNALS`
>
> If the `ALLEXTERNALS` tag is set to `YES`, all external class will be listed in the class index. If
set to `NO`, only the inherited external classes will be listed.
> The default value is: `NO`.

Though when looking in the code we see that `ALLEXTERNALS` also looks like to be used file files (see util.cpp).
- is the documentation incomplete?
- should namespaces also be added here?


Besides the idea of `TAGS_EXCLUDE = namespace:QtAndroidPrivate` an idea might be to use `EXCLUDE_SYMBOLS` also in respect to tag files (might be a bit complicated as we have to have consider the full scope of of entities).
- how about these ideas?

**Comment by doxygen** [comment] 2023-08-18 12:46
Assuming `ALLEXTERNALS=NO`, then my idea is that the external references should appear in lists/trees only if they are needed to properly show internal items, e.g.

- A Base class `BExt` imported via a tag file, should be shown only if an internal class `CInt` derives from it.
- A namespace `NExt` imported via a tag file, should be shown only if an internal namespace `Bext::NInt` exist that nests inside it.

If `ALLEXTERNALS=YES` it makes sense to show all external container symbols in lists/trees.

So the current behavior is not correct.

Not sure about the need for more fine-grained controls (given the huge amount of options doxygen already has, and the difficultly that brings with testing/avoiding regression).

**Comment by doxygen** [comment] 2023-08-19 11:18
@oblivioncth Please verify if the referenced commit fixes the problem for you. Do not close the issue, as this will be done automatically when the next official release is out.

**Comment by oblivioncth** [comment] 2023-08-19 13:14
That did the trick in terms of `ALLEXTERNALS = NO`.

Of course more granular options would always be nice, but I understand the hesitation given the additional complexity. 

For now this accomplishes exactly what I wanted.

**Comment by doxygen** [comment] 2023-08-25 13:51
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.8.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2023-08-25 13:51 UTC
