### ISSUE TITLE
Don't split type name in member table in LaTeX documentation (Origin: bugzilla #784759)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#6229] opened 2018-07-02 13:02 UTC
status NEW severity *minor* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2017-07-10 17:10:55 +0000, Thadeus Fleming wrote:

    In the member tables in the LaTeX documentation, the first column is the
    name of the member's type. Due to the insertion of "\+" in various places,
    even very short type names like "uint8_t" get split across lines. It looks
    like this might be fixed by setting insideTabbing = true in the appropriate
    location.

**Comment by albert-github** [comment] 2021-08-21 17:11
The underscore is a natural place to split a word. and this can have an unexpected  / unwanted split for e.g. `uint8_t`.
The placing of the `\+` is done regardless of the content so that also types like `this_is_a_user_specified_long_type` is still a bit readable.

Unfortunately no example is given , so it It is unclear where this problem occurs.

Seen the initial explanation, I think this can be marked as not a bug.

**Closed** 2021-12-31 11:07 UTC
Labels: invalid, Usage
