### ISSUE TITLE
Automatic links not working in examples that use C++ source [Potential Bug]

### ISSUE THREAD

**Issue by jpgarza93** [doxygen/doxygen#9274] opened 2022-04-12 14:53 UTC
**Describe the bug**
I have a C++ API that I document with Doxygen and C++ & C# examples that use that API (we swig the C++ API to make it available to C# users). 

I am seeing an issue where my example functions do not auto-link to the C++ API.  My guess is that it has to do with the namespaces.

**Screenshots**
[![c# autolink issue][1]][1]
![c++ no autolinks](https://user-images.githubusercontent.com/79015116/163013908-c67a0899-92b6-4f3f-84b4-ddcbbdbcaad9.png)

**EDIT**: Verified C++ auto link worked on previous version 1.8.20 (c# autolink still broken)
![image](https://user-images.githubusercontent.com/79015116/163018282-e3a5f78c-7dcc-4e9b-adf3-161a7da8fd3d.png)

**Expected behavior**
Auto links should work even when the namespace is not specified before the class when calling the function.

**To Reproduce**
 I have created a small sample app with a total of 4 files where this is reproduced (download zip or see below):
[tmp.zip](https://github.com/doxygen/doxygen/files/8490583/tmp.zip)

File 1: Doxyfile
```
# Doxyfile 1.9.2

DOXYFILE_ENCODING      = UTF-8
PROJECT_NAME           = "My Project"
PROJECT_NUMBER         =
PROJECT_BRIEF          =
PROJECT_LOGO           =
OUTPUT_DIRECTORY       = C:\tmp\doxylinktest\output
CREATE_SUBDIRS         = NO
ALLOW_UNICODE_NAMES    = NO
OUTPUT_LANGUAGE        = English
BRIEF_MEMBER_DESC      = YES
REPEAT_BRIEF           = YES
ABBREVIATE_BRIEF       = "The $name class" \
                         "The $name widget" \
                         "The $name file" \
                         is \
                         provides \
                         specifies \
                         contains \
                         represents \
                         a \
                         an \
                         the
ALWAYS_DETAILED_SEC    = NO
INLINE_INHERITED_MEMB  = NO
FULL_PATH_NAMES        = YES
STRIP_FROM_PATH        =
STRIP_FROM_INC_PATH    =
SHORT_NAMES            = NO
JAVADOC_AUTOBRIEF      = NO
JAVADOC_BANNER         = NO
QT_AUTOBRIEF           = NO
MULTILINE_CPP_IS_BRIEF = NO
PYTHON_DOCSTRING       = YES
INHERIT_DOCS           = YES
SEPARATE_MEMBER_PAGES  = YES
TAB_SIZE               = 4
ALIASES                =
OPTIMIZE_OUTPUT_FOR_C  = NO
OPTIMIZE_OUTPUT_JAVA   = NO
OPTIMIZE_FOR_FORTRAN   = NO
OPTIMIZE_OUTPUT_VHDL   = NO
OPTIMIZE_OUTPUT_SLICE  = NO
EXTENSION_MAPPING      =
MARKDOWN_SUPPORT       = YES
TOC_INCLUDE_HEADINGS   = 5
AUTOLINK_SUPPORT       = YES
BUILTIN_STL_SUPPORT    = NO
CPP_CLI_SUPPORT        = NO
SIP_SUPPORT            = NO
IDL_PROPERTY_SUPPORT   = YES
DISTRIBUTE_GROUP_DOC   = NO
GROUP_NESTED_COMPOUNDS = NO
SUBGROUPING            = YES
INLINE_GROUPED_CLASSES = NO
INLINE_SIMPLE_STRUCTS  = NO
TYPEDEF_HIDES_STRUCT   = NO
LOOKUP_CACHE_SIZE      = 0
NUM_PROC_THREADS       = 1

EXTRACT_ALL            = NO
EXTRACT_PRIVATE        = NO
EXTRACT_PRIV_VIRTUAL   = NO
EXTRACT_PACKAGE        = NO
EXTRACT_STATIC         = NO
EXTRACT_LOCAL_CLASSES  = YES
EXTRACT_LOCAL_METHODS  = NO
EXTRACT_ANON_NSPACES   = NO
RESOLVE_UNNAMED_PARAMS = YES
HIDE_UNDOC_MEMBERS     = NO
HIDE_UNDOC_CLASSES     = NO
HIDE_FRIEND_COMPOUNDS  = NO
HIDE_IN_BODY_DOCS      = NO
INTERNAL_DOCS          = NO
CASE_SENSE_NAMES       = NO
HIDE_SCOPE_NAMES       = NO
HIDE_COMPOUND_REFERENCE= NO
SHOW_HEADERFILE        = YES
SHOW_INCLUDE_FILES     = YES
SHOW_GROUPED_MEMB_INC  = NO
FORCE_LOCAL_INCLUDES   = NO
INLINE_INFO            = YES
SORT_MEMBER_DOCS       = YES
SORT_BRIEF_DOCS        = NO
SORT_MEMBERS_CTORS_1ST = NO
SORT_GROUP_NAMES       = NO
SORT_BY_SCOPE_NAME     = NO
STRICT_PROTO_MATCHING  = NO
GENERATE_TODOLIST      = YES
GENERATE_TESTLIST      = YES
GENERATE_BUGLIST       = YES
GENERATE_DEPRECATEDLIST= YES
ENABLED_SECTIONS       =
MAX_INITIALIZER_LINES  = 30
SHOW_USED_FILES        = YES
SHOW_FILES             = YES
SHOW_NAMESPACES        = YES
FILE_VERSION_FILTER    =
LAYOUT_FILE            =
CITE_BIB_FILES         =

QUIET                  = NO
WARNINGS               = YES
WARN_IF_UNDOCUMENTED   = YES
WARN_IF_DOC_ERROR      = YES
WARN_IF_INCOMPLETE_DOC = YES
WARN_NO_PARAMDOC       = NO
WARN_AS_ERROR          = NO
WARN_FORMAT            = "$file:$line: $text"
WARN_LOGFILE           =

INPUT                  = C:\tmp\doxylinktest
INPUT_ENCODING         = UTF-8
FILE_PATTERNS          = *.c \
                         *.cc \
                         *.cxx \
                         *.cpp \
                         *.c++ \
                         *.java \
                         *.ii \
                         *.ixx \
                         *.ipp \
                         *.i++ \
                         *.inl \
                         *.idl \
                         *.ddl \
                         *.odl \
                         *.h \
                         *.hh \
                         *.hxx \
                         *.hpp \
                         *.h++ \
                         *.l \
                         *.cs \
                         *.d \
                         *.php \
                         *.php4 \
                         *.php5 \
                         *.phtml \
                         *.inc \
                         *.m \
                         *.markdown \
                         *.md \
                         *.mm \
                         *.dox \
                         *.py \
                         *.pyw \
                         *.f90 \
                         *.f95 \
                         *.f03 \
                         *.f08 \
                         *.f18 \
                         *.f \
                         *.for \
                         *.vhd \
                         *.vhdl \
                         *.ucf \
                         *.qsf \
                         *.ice
RECURSIVE              = NO
EXCLUDE                =
EXCLUDE_SYMLINKS       = NO
EXCLUDE_PATTERNS       =
EXCLUDE_SYMBOLS        =
EXAMPLE_PATH           = C:\tmp\doxylinktest
EXAMPLE_PATTERNS       = *
EXAMPLE_RECURSIVE      = NO
IMAGE_PATH             =
INPUT_FILTER           =
FILTER_PATTERNS        =
FILTER_SOURCE_FILES    = NO
FILTER_SOURCE_PATTERNS =
USE_MDFILE_AS_MAINPAGE =

SOURCE_BROWSER         = NO
INLINE_SOURCES         = NO
STRIP_CODE_COMMENTS    = YES
REFERENCED_BY_RELATION = NO
REFERENCES_RELATION    = NO
REFERENCES_LINK_SOURCE = YES
SOURCE_TOOLTIPS        = YES
USE_HTAGS              = NO
VERBATIM_HEADERS       = YES
CLANG_ASSISTED_PARSING = NO
CLANG_ADD_INC_PATHS    = YES
CLANG_OPTIONS          =
CLANG_DATABASE_PATH    =

ALPHABETICAL_INDEX     = YES
IGNORE_PREFIX          =

GENERATE_HTML          = YES
HTML_OUTPUT            = html
HTML_FILE_EXTENSION    = .html
HTML_HEADER            =
HTML_FOOTER            =
HTML_STYLESHEET        =
HTML_EXTRA_STYLESHEET  =
HTML_EXTRA_FILES       =
HTML_COLORSTYLE_HUE    = 220
HTML_COLORSTYLE_SAT    = 100
HTML_COLORSTYLE_GAMMA  = 80
HTML_TIMESTAMP         = NO
HTML_DYNAMIC_MENUS     = YES
HTML_DYNAMIC_SECTIONS  = NO
HTML_INDEX_NUM_ENTRIES = 100
GENERATE_DOCSET        = NO
DOCSET_FEEDNAME        = "Doxygen generated docs"
DOCSET_BUNDLE_ID       = org.doxygen.Project
DOCSET_PUBLISHER_ID    = org.doxygen.Publisher
DOCSET_PUBLISHER_NAME  = Publisher
GENERATE_HTMLHELP      = NO
CHM_FILE               =
HHC_LOCATION           =
GENERATE_CHI           = NO
CHM_INDEX_ENCODING     =
BINARY_TOC             = NO
TOC_EXPAND             = NO
GENERATE_QHP           = NO
QCH_FILE               =
QHP_NAMESPACE          = org.doxygen.Project
QHP_VIRTUAL_FOLDER     = doc
QHP_CUST_FILTER_NAME   =
QHP_CUST_FILTER_ATTRS  =
QHP_SECT_FILTER_ATTRS  =
QHG_LOCATION           =
GENERATE_ECLIPSEHELP   = NO
ECLIPSE_DOC_ID         = org.doxygen.Project
DISABLE_INDEX          = NO
GENERATE_TREEVIEW      = NO
FULL_SIDEBAR           = NO
ENUM_VALUES_PER_LINE   = 4
TREEVIEW_WIDTH         = 250
EXT_LINKS_IN_WINDOW    = NO
HTML_FORMULA_FORMAT    = png
FORMULA_FONTSIZE       = 10
FORMULA_TRANSPARENT    = YES
FORMULA_MACROFILE      =
USE_MATHJAX            = NO
MATHJAX_VERSION        = MathJax_2
MATHJAX_FORMAT         = HTML-CSS
MATHJAX_RELPATH        =
MATHJAX_EXTENSIONS     =
MATHJAX_CODEFILE       =
SEARCHENGINE           = YES
SERVER_BASED_SEARCH    = NO
EXTERNAL_SEARCH        = NO
SEARCHENGINE_URL       =
SEARCHDATA_FILE        = searchdata.xml
EXTERNAL_SEARCH_ID     =
EXTRA_SEARCH_MAPPINGS  =

GENERATE_LATEX         = NO
LATEX_OUTPUT           = latex
LATEX_CMD_NAME         =
MAKEINDEX_CMD_NAME     = makeindex
LATEX_MAKEINDEX_CMD    = makeindex
COMPACT_LATEX          = NO
PAPER_TYPE             = a4
EXTRA_PACKAGES         =
LATEX_HEADER           =
LATEX_FOOTER           =
LATEX_EXTRA_STYLESHEET =
LATEX_EXTRA_FILES      =
PDF_HYPERLINKS         = YES
USE_PDFLATEX           = YES
LATEX_BATCHMODE        = NO
LATEX_HIDE_INDICES     = NO
LATEX_BIB_STYLE        = plain
LATEX_TIMESTAMP        = NO
LATEX_EMOJI_DIRECTORY  =

GENERATE_RTF           = NO
RTF_OUTPUT             = rtf
COMPACT_RTF            = NO
RTF_HYPERLINKS         = NO
RTF_STYLESHEET_FILE    =
RTF_EXTENSIONS_FILE    =

GENERATE_MAN           = NO
MAN_OUTPUT             = man
MAN_EXTENSION          = .3
MAN_SUBDIR             =
MAN_LINKS              = NO

GENERATE_XML           = NO
XML_OUTPUT             = xml
XML_PROGRAMLISTING     = YES
XML_NS_MEMB_FILE_SCOPE = NO

GENERATE_DOCBOOK       = NO
DOCBOOK_OUTPUT         = docbook

GENERATE_AUTOGEN_DEF   = NO

GENERATE_PERLMOD       = NO
PERLMOD_LATEX          = NO
PERLMOD_PRETTY         = YES
PERLMOD_MAKEVAR_PREFIX =

ENABLE_PREPROCESSING   = YES
MACRO_EXPANSION        = NO
EXPAND_ONLY_PREDEF     = NO
SEARCH_INCLUDES        = YES
INCLUDE_PATH           =
INCLUDE_FILE_PATTERNS  =
PREDEFINED             =
EXPAND_AS_DEFINED      =
SKIP_FUNCTION_MACROS   = YES

TAGFILES               =
GENERATE_TAGFILE       =
ALLEXTERNALS           = NO
EXTERNAL_GROUPS        = YES
EXTERNAL_PAGES         = YES

DIA_PATH               =
HIDE_UNDOC_RELATIONS   = YES
HAVE_DOT               = NO
DOT_NUM_THREADS        = 0
DOT_FONTNAME           = Helvetica
DOT_FONTSIZE           = 10
DOT_FONTPATH           =
CLASS_GRAPH            = YES
COLLABORATION_GRAPH    = YES
GROUP_GRAPHS           = YES
UML_LOOK               = NO
UML_LIMIT_NUM_FIELDS   = 10
DOT_UML_DETAILS        = NO
DOT_WRAP_THRESHOLD     = 17
TEMPLATE_RELATIONS     = NO
INCLUDE_GRAPH          = YES
INCLUDED_BY_GRAPH      = YES
CALL_GRAPH             = NO
CALLER_GRAPH           = NO
GRAPHICAL_HIERARCHY    = YES
DIRECTORY_GRAPH        = YES
DOT_IMAGE_FORMAT       = png
INTERACTIVE_SVG        = NO
DOT_PATH               =
DOTFILE_DIRS           =
MSCFILE_DIRS           =
DIAFILE_DIRS           =
PLANTUML_JAR_PATH      =
PLANTUML_CFG_FILE      =
PLANTUML_INCLUDE_PATH  =
DOT_GRAPH_MAX_NODES    = 50
MAX_DOT_GRAPH_DEPTH    = 0
DOT_TRANSPARENT        = NO
DOT_MULTI_TARGETS      = NO
GENERATE_LEGEND        = YES
DOT_CLEANUP            = YES

```

File 2: foo.h (C++ API)
```c++
namespace Foo
{
    /// Foo.Bar namespace. aka Foo::Bar namespace
    namespace Bar
    {
            /// HyperLinkMe class.
            class HyperLinkMe
            {
                public:
                    /// HelloWorld() tells the world hello.
                    /// @sa IWantALinkHere
                    int HelloWorld()
                    {
                        int i = 0;
                        i++;
                        return i;
                    }

                    /// please give me a hyperlink on this method too
                    /// @sa HelloWorld
                    void IWantALinkHere()
                    {
                    }
            }
    }
}
```

File 3: foosimplesample.cs (C# Example)
```cs
/// @example foosimplesample.cs

using  Foo.Bar;

/// static main void thing
static void Main()
{
    HyperLinkMe hyperLinkMe = new HyperLinkMe();
    int hello = hyperLinkMe.HelloWorld();
}
```

File 4: foosimplesample.cpp (C++ Example)
```cpp
/// @example foosimplexsample.cpp

#include "foo.h"
using namespace Foo::Bar;

static void Main()
{
    HyperLinkMe* hyperLinkMe = new HyperLinkMe();
    hyperLinkMe->HelloWorld();
}
```

**Version**:
```
doxygen -v
1.9.3

doxygen -x
# Difference with default Doxyfile 1.9.3
OUTPUT_DIRECTORY       = C:\tmp\doxylinktest\output
SEPARATE_MEMBER_PAGES  = YES
INPUT                  = C:\tmp\doxylinktest
EXAMPLE_PATH           = C:\tmp\doxylinktest
GENERATE_LATEX         = NO
```

  [1]: https://i.stack.imgur.com/LSze2.png

**Comment by jpgarza93** [comment] 2022-04-14 14:47
Hello @albert-github, I am just wondering why I haven't received a response. Should I be providing more info? Is this a known issue?

**Comment by jpgarza93** [comment] 2022-04-14 15:50
- saw responses on other issues and I was wondering if maybe the no response was due to (maybe me having to improve the question info).

I will include a zip file with a self-contained example.

I appreciate your time to reply and all the effort you put into the repo.

**Comment by jpgarza93** [comment] 2022-04-18 21:04
This seems to be a namespace issue with Doxygen versions 1.9.x

Other things I noticed:

Building with doxywizard v1.9.3, namespace gets appended
![image](https://user-images.githubusercontent.com/79015116/163877553-2510f0bb-4012-4cef-8886-e82338aabab7.png)

vs. Building with doxywizard v1.8.2, namespace clean
![image](https://user-images.githubusercontent.com/79015116/163877687-10d68099-9709-4b10-a5cd-fdb6054fceaf.png)

Building with doxywizard v1.9.3, no examples on class page
![image](https://user-images.githubusercontent.com/79015116/163877890-8449ba46-495b-46f0-9163-c52fbed13815.png)

vs. Building with doxywizard v1.8.2, example links are visible
![image](https://user-images.githubusercontent.com/79015116/163877848-4d0a883f-78fc-44bc-94eb-8aa39a83d9e8.png)

**Comment by albert-github** [comment] 2022-04-19 07:40
The changes mentioned in https://github.com/doxygen/doxygen/issues/9274#issuecomment-1101766800 will have a different cause (for the first problem did you look at the setting of `HIDE_SCOPE_NAME`?), so please create separate issues for them and as they don't directly follow from the original issue. It is also not possible to reproduce these problems with the original example so for  the new issues:
- please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by jpgarza93** [comment] 2022-04-21 18:25
[tmp.zip](https://github.com/doxygen/doxygen/files/8490583/tmp.zip)

**Comment by albert-github** [comment] 2022-04-22 09:03
Did you remove a comment (dated April 19, 2022)? Now the comment https://github.com/doxygen/doxygen/issues/9274#issuecomment-1102215154 points a bit into thin air.

**Comment by jpgarza93** [comment] 2022-04-22 20:48
I did. My understanding was you wanted me to create a new post for it.

**Comment by albert-github** [comment] 2022-04-23 07:49
Only thing I see is the new tmp.zip file but in here there is no reference to a treeview and in the removed post I see:
![image](https://user-images.githubusercontent.com/5223533/164885511-d7f7d843-e3d1-4bf7-9fe5-baadee5a75f8.png)
![image](https://user-images.githubusercontent.com/5223533/164885521-34782631-dd2f-4ee8-b356-f1ed249a2ad8.png)

In the issues list I don't see any new post regarding this, so I'm now quite confused.

**Comment by jpgarza93** [comment] 2022-04-23 13:44
I removed that comment because you tagged it as a different issue. The tmp.zip is the same provided in the first comment. We can discard what you tagged as "2nd issue" and just focus on the "first issue" one from the first comment (which appears to be a bug that could affect many others using c++)

Is this okay or do you have a different suggestion?

**Comment by albert-github** [comment] 2022-04-23 13:47
Best is to leave it in the current state and decide at the moment there is a proposed patch or another solution.
Best is indeed to focus on the initial issue.

**Comment by jpgarza93** [comment] 2022-04-29 18:04
Anything else I can do to help with this issue?

**Comment by doxygen** [comment] 2022-04-29 18:41
The problem is that doxygen currently does not process using statements in code used for examples. 

A complicating factor is that this needs to added in such a way that it does not influence the actual code (i.e. the symbols introduced need to be kept local to the example). I'll see if I can implement something to make this work.

**Comment by jpgarza93** [comment] 2022-04-29 20:34
I see. Did something change from Doxygen version 1.8.x to 1.9.x? Auto link while it didn't work for some C# files it did use to work for C++

**Comment by doxygen** [comment] 2022-04-30 19:06
@jpgarza93 Please verify if the referenced commit fixes the problem for you.

**Comment by albert-github** [comment] 2022-05-01 08:36
The example as indicated in https://github.com/doxygen/doxygen/issues/9274#issuecomment-1105608258 by tmp,.zip looks like to work, though the original example (even after setting `EXTRACT_ALL=YES` and `EXTRACT_STATIC=YES`) doesn't look like to work.
In the example we see `using  Foo.Bar;` and in the example the `Foo` and `Bar` are separately underlined as hyperlinks, in the cpp example we have `using namespace Foo::Bar;` and the `Foo::Bar;` is underlined as one hyperlink. The link to `Bar` in `Foo.Bar` is correct though.

Looks to me that the `.` as namespace / class operator in C# code is not handled correctly.

**Comment by doxygen** [comment] 2022-05-01 12:00
@albert-github Good catch and correct observation. Should be fixed in the new commit.

**Comment by albert-github** [comment] 2022-05-01 12:11
@doxygen Did you also have a look at the dead code message from coverity in respect to:
```
        if (cd!=0 || md!=0) break;
```
in
```
    if (cd==0 && md==0)
    {
      // also check via using directive
      for (const auto &kv : yyextra->theUsingContext)
      {
        checkForClass(kv.second);
        if (cd!=0 || md!=0) break;
      }
    }
```
I'm not sure whether the intention is correct and the message is a false positive in the coverity output (it looks like it is due to the lambda function).

**Comment by doxygen** [comment] 2022-05-01 12:43
@albert-github The coverity warning looks like a false positive as `cd` and `md` can be changed by `checkForClass` as these variables are captured by reference. That said, it still maybe a good idea to make them explicit parameters, for better understandability of the code...

**Comment by albert-github** [comment] 2022-05-01 13:12
I tried to test the #8487 but it looks like that the
```
Example.FooNamespace.Foo foo2 = new Foo();
Example.BarNamespace.Bar bar2 = foo2.GetBar();
```
does not yet work as it should
- no link to `GetBar` (although `foo2` should be of type `Foo`)
- the items of `Example.FooNamespace.Foo` are here also separately underlined.

**Comment by jpgarza93** [comment] 2022-05-02 22:01
Thank you for investing some time in this. I can confirm this works with the tmp.zip project. But I still see some issues when I run my project. for now, I will close this as the question's issue got resolved. I will wait for a new release until I post any further findings. Thank you !

**Comment by doxygen** [comment] 2022-05-05 19:47
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.4.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2022-05-05 19:47 UTC
Labels: bug, C#
