### ISSUE TITLE
Doxygen incorrectly puts [noexcept] tag on noexcept(false) or noexcept(conditional) functions (Origin: bugzilla #759301)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5915] opened 2018-07-02 11:50 UTC
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.13* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-12-10 13:45:28 +0000, Jonathan Wakely wrote:

    /// Something
        struct ting
        {
          /** @brief ffffffff
           *
           * more blah blah
           */
          void f() noexcept(false) { }
        };
    
    For this code the documentation says:
    
    Member Function Documentation
       void ting::f () [inline],  [noexcept]
           ffffffff more blah blah
    
    But it is not noexcept.
    
    The [noexcept] tag should only be added for 'noexcept' or 'noexcept(true)'
    functions, or noexcept(constant expression evaluating to true) functions,
    but I doubt Doxygen is capable of doing that evaluation (another reason to
    use libclang).

On 2017-11-20 15:38:56 +0000, Daniel Boles wrote:

    Indeed. While the summary doc is OK because it copies the specifier in full,
    the detailed one gets reduced to just noexcept, which implies noexcept(true)
    and is therefore misleading.

On 2017-11-20 15:40:00 +0000, Daniel Boles wrote:

    *** Bug 789329 has been marked as a duplicate of this bug. ***

**Comment by albert-github** [comment] 2023-03-05 10:27
In case of `noexcept(false)` this gives in the 1.8.13 output indeed the qualifies / label "noexcept" in the current version this label is gone.
The issue is a duplicate of https://github.com/doxygen/doxygen/issues/9582 and fixed in https://github.com/doxygen/doxygen/pull/9583 see also for the limitations at https://github.com/doxygen/doxygen/issues/9582#issuecomment-1238151979.

I think problem is a duplicate and solved in the mean time.

**Comment by jwakely** [comment] 2023-03-05 12:20
Nice, thanks for the fix

**Closed** 2023-05-18 20:26 UTC
Labels: bug, duplicate, C/C++, solved in the mean time
