### ISSUE TITLE
`std`:: hypertext link if a class documents `std()` function

### ISSUE THREAD

**Issue by scott-zhong** [doxygen/doxygen#10962] opened 2024-06-24 18:07 UTC
**Describe the bug**
`std`:: hypertext link if a class documents `std()` function

```
/**
 * \code{.cpp}
 *   std::cout << ((1==1) ? "true" : "false") << std::endl;
 * \endcode
 */
template <class T>
class Test {
 public:
  /**
   * std
   */
  void std() {}
};
```

**Screenshots**
Doxygen 1.9.6 ("std" is not linked)
![image](https://github.com/doxygen/doxygen/assets/32584126/255eb938-1419-4a55-8d1d-37239af1642a)

Doxygen 1.9.7 - trunk (38ee114a4563fd91ea547c262d120cf361b83039)
![image](https://github.com/doxygen/doxygen/assets/32584126/1d3a1541-6048-4e3c-9cf2-168ce86402fc)

**To Reproduce**
[testcase.zip](https://github.com/user-attachments/files/15959708/testcase.zip)

**Expected behavior**
"std" part of "std::" is not linked.

**Comment by albert-github** [comment] 2024-06-27 12:01
It looks like the commit:
```
Commit: b80a0b98a40c22b5e4f4e0140f2031846ec66172 [b80a0b9]
Date: Saturday, February 18, 2023 7:52:01 PM

issue #9783: Some functions are not listed in "referenced by"
```
causes the problem where the code:
```
<MemberCall,MemberCall2,FuncCall>[;:]   { // recover from unexpected end of call
                                          unput(*yytext);
                                          BEGIN(CallEnd);
                                        }
```
is added to `code.l`.

The problem looks like to be that now the `:` of the ternary operator (`... ? ... : ...`) triggers "recover from unexpected end of call" whilst we are here not in a function call.

@doxygen Do you see a solution (bracket counting?)?

**Comment by doxygen** [comment] 2024-06-30 09:59
@scott-zhong Please verify if the referenced commit fixes the problem for you. Do not close the issue, this will be done automatically when the next official release becomes available.

**Comment by scott-zhong** [comment] 2024-07-01 17:39
@doxygen @albert-github the change does address the testcase in the issue but it looks like it causes `:` to be left out in the generated documentation for the following testcase

```
/**
 * \code{.cpp}
 *   std::cout << "test does "
 *             << (test.contains(key) ? " " : " not ")
 *             << "contain the key " << key << std::endl;
 * \endcode
 */
template <class T>
class Test {
 public:
  /**
   * contains
   */
  void contains();

  /**
   * std
   */
  void std();
};
```
Doxygen 1.9.6:
![image](https://github.com/doxygen/doxygen/assets/32584126/d9449c5d-cdf4-4568-9630-2ca9f4a4e1fc)


trunk (4a9be1303830cb78f8def8b60888cd6e23afd34d):
![image](https://github.com/doxygen/doxygen/assets/32584126/58ea8db0-47ad-4c6b-9f88-4ca4e42306c0)

**Comment by albert-github** [comment] 2024-07-02 10:02
Regarding the regression mentioned in https://github.com/doxygen/doxygen/issues/10962#issuecomment-2200694384 I've just pushed a proposed patch, pull request #10974

**Comment by albert-github** [comment] 2024-07-03 07:46
The regression code fix has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by scott-zhong** [comment] 2024-07-03 15:08
@doxygen @albert-github I have verified the fix. Thank you!!!

**Comment by doxygen** [comment] 2024-08-07 09:36
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.12.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2024-08-07 09:36 UTC
Labels: bug, C/C++, has pull request
