### ISSUE TITLE
Button Show HTML-Output doesn't work

### ISSUE THREAD

**Issue by Wernickel** [doxygen/doxygen#9003] opened 2022-01-04 07:35 UTC
I loaded an older Doxyfile and created the HTML files.
This worked as usual. The button "Show HTML Output" was enabled.
Pressing it doesn't perform any action.
While starting the index.html file via Windows Explorer opens the generated documentation.

**Comment by albert-github** [comment] 2022-01-04 08:35
- Which version of the doxywizard are you using?
- With Which version did you make the old Doxyfile?
- Anything special in the old Doxyfile? (Just publish it as an attachment as a compressed tar or zip file).

**Comment by Wernickel** [comment] 2022-01-04 08:44
[Doxyfile.zip](https://github.com/doxygen/doxygen/files/7806379/Doxyfile.zip)

- I just have downloaded and installed Doxywizard Version 1.9.3
- The doxyfile was created with version 1.8.3 ( Doxywizard) - I think, it's some time  ago...

**Comment by albert-github** [comment] 2022-01-04 14:43
The problem is independent of the used Doxyfile (I just tested it with an empty Doxyfile and no source files)
- with the official executable I can reproduce the problem
- with my own build executable I could not reproduce the problem.

Note: I assume the problem to occur under Windows as the "Windows Explorer" has been used (I tested myself with FireFox).

**Comment by petko** [comment] 2022-03-10 12:29
I also have the same problem with all Doxygen versions since 1.9. Clicking on Show HTML Output does something (I can see Doxywizard being blocked for a second), but does not open the generated help files. I use Firefox as my default browser under Windows 10.

**Comment by albert-github** [comment] 2022-03-10 12:37
@petko You say you use Doxygen versions since 1.9 , as noted in the previous comments a fix has been made in the version 1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473). You can see  the version you have by means of the following commands on the command line:
- `doxygen -v`

or
- `doxywizard --version`


So please specify the exact version you are using. When you are using 1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473) update to this, see https://www.doxygen.nl/download.html)

**Comment by petko** [comment] 2022-03-10 12:44
I use 1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473). The problem still happens for me there as described above.

**Comment by albert-github** [comment] 2022-03-10 12:57
Oops I overlooked that this issue is fixed in the master version but is not yet released (I thought, by head, this was fixed in the 1.9.3 (c0b9eafbfb53286ce31e75e2b6c976ee4d345473version).

I've just tried my local master version and this is working
- you can build doxygen yourself
- get the latest master from the github artifacts, e.g. from https://github.com/doxygen/doxygen/actions/runs/1959365921 and replace the released doxywizard version with the doxywizard from the artifact (you have to do this by hand, there won't be an installer). When replacing the doxywizard I would also replace the  doxygen executable to keep a more consistent system (though the later is not necessary).

**Comment by doxygen** [comment] 2022-05-05 19:59
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.4.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2022-05-05 19:59 UTC
Labels: bug, doxywizard

**Comment by petko** [comment] 2022-05-09 06:52
Just to confirm, it works properly now.

**Comment by Wernickel** [comment] 2022-05-09 07:11
Fixed, it works now.
Thank you!
