### ISSUE TITLE
Failed to build "master" branch

### ISSUE THREAD

**Issue by SchweinDeBurg** [doxygen/doxygen#10790] opened 2024-04-11 04:01 UTC
I've tried to build from "master" branch and after commit [aa55cc88](https://github.com/doxygen/doxygen/commit/aa55cc88df4d63425946725357b4b93e0aafedbf) got the following error:
```
FAILED: doc/language.dox /home/elijah/.local/rpmbuild/BUILD/doxygen/x86_64-redhat-linux-gnu/doc/language.dox 
cd /home/elijah/.local/rpmbuild/BUILD/doxygen/x86_64-redhat-linux-gnu/doc && /usr/bin/python3.8 translator.py --doc /home/elijah/.local/rpmbuild/BUILD/doxygen

Unexpected token 'id' on the line 31 in '/home/elijah/.local/rpmbuild/BUILD/doxygen/src/translator.h'.
status = 2 in collectPureVirtualPrototypes()
ninja: build stopped: subcommand failed.
error: Bad exit status from /var/tmp/rpm-tmp.57KjKz (%build)
```

**Comment by albert-github** [comment] 2024-04-11 08:51
I saw the same problem with the GitHub Actions.

I've just pushed a proposed patch, pull request #10791

**Comment by SchweinDeBurg** [comment] 2024-04-11 09:21
I've tried to use proposed patch and got the following error:
```
Unexpected token 'lpar' on the line 31 in '/home/elijah/.local/rpmbuild/BUILD/doxygen/src/translator.h'.
status = 1 in collectPureVirtualPrototypes()
```

**Comment by albert-github** [comment] 2024-04-11 09:35
Strange
- I tried it and had no problems
- GitHub actions https://github.com/doxygen/doxygen/actions/runs/8644051197 had no problems
- I see in the new code around line 717:
  ```
              elif status == 18:    # start of the ABSTRACT_BASE_CLASS
                if tokenId == 'lpar':
                    pass
                elif tokenId == 'rpar':
                    status = 2
                elif tokenId == 'id':
                    pass
                else:
                    self.__unexpectedToken(status, tokenId, tokenLineNo)
  ```
  So a `lpar` test is present as far as I can see.

Can you place a print statement at line 574 (i.e. direct after `                elif tokenId == 'id' and tokenStr == 'ABSTRACT_BASE_CLASS':`):
```
  print("Found ABSTRACT_BASE_CLASS")
```
and after (new) line 718 (i.e. directly after `            elif status == 18:    # start of the ABSTRACT_BASE_CLASS`):
```
 print(f'id = {tokenId" Str = {tokenStr} line = tokenLineNo}');
```

**Comment by SchweinDeBurg** [comment] 2024-04-11 09:43
```
FAILED: doc/language.dox /home/elijah/.local/rpmbuild/BUILD/doxygen/x86_64-redhat-linux-gnu/doc/language.dox 
cd /home/elijah/.local/rpmbuild/BUILD/doxygen/x86_64-redhat-linux-gnu/doc && /usr/bin/python3.8 translator.py --doc /home/elijah/.local/rpmbuild/BUILD/doxygen
  File "translator.py", line 719
    print(f'id = {tokenId" Str = {tokenStr} line = tokenLineNo}');
          ^
SyntaxError: f-string: unterminated string
```

**Comment by SchweinDeBurg** [comment] 2024-04-11 09:45
Previous diff is exactly the same as PR:
```
diff --git a/doc/translator.py b/doc/translator.py
index e2037ac651..991d4570e6 100755
--- a/doc/translator.py
+++ b/doc/translator.py
@@ -570,6 +570,8 @@ class Transl:
                     pass
                 elif tokenId == 'rcurly':
                     status = 11         # expected end of class
+                elif tokenId == 'id' and tokenStr == 'ABSTRACT_BASE_CLASS':
+                    status = 1
                 else:
                     self.__unexpectedToken(status, tokenId, tokenLineNo)

@@ -712,6 +714,16 @@ class Transl:
                 else:
                     self.__unexpectedToken(status, tokenId, tokenLineNo)

+            elif status == 18:    # start of the ABSTRACT_BASE_CLASS
+                if tokenId == 'lpar':
+                    pass
+                elif tokenId == 'rpar':
+                    status = 2
+                elif tokenId == 'id':
+                    pass
+                else:
+                    self.__unexpectedToken(status, tokenId, tokenLineNo)
+
```

**Comment by SchweinDeBurg** [comment] 2024-04-11 09:48
I am a stupid!!!
```
+                    status = 1
```
instead of
```
+                    status = 18
```

**Comment by albert-github** [comment] 2024-04-11 09:50
Also my debug statement was not correct the double quote (`"`) should have been a curly bracket close (`}`)

**Comment by SchweinDeBurg** [comment] 2024-04-11 09:54
@albert-github I am very sorry for my mistake, with your patch  everything is fine. Thank you!

**Comment by albert-github** [comment] 2024-04-12 07:36
Code has been integrated in master on GitHub.
Closing issue as the problem was a regression on the current master version and this was not yet released.

**Closed by albert-github** 2024-04-12 07:36 UTC
Labels: bug, install/build, documentation
