### ISSUE TITLE
Doxygen Fortran: prevent automatic coversion of names to all lower-case names

### ISSUE THREAD

**Issue by shahmoradi** [doxygen/doxygen#8768] opened 2021-09-08 03:14 UTC
**Describe the bug**
Fortran code becomes all lower-case in HTML files. This includes procedure names, and the internals of code sections (anything that appears between `\code{fortran} ... \endcode` other than the procedure interface).

**Expected behavior**
Preserve the case sensitivity in the output HTML files. This is highly desired because some projects follow the CamelCase coding convention, which makes the Doxygen documentation unreadable.

**Screenshots**
Here is an example namespace header generated by Doxygen for a module named `DistMultiNormLoggammaMix`: 
`distmultinormloggammamix Module Reference`

**To Reproduce**
[test.zip](https://github.com/doxygen/doxygen/files/7125503/test.zip)

**Version**
Doxygen version 1.9.2 (caa4e3de211fbbef2c3adf58a6bd4c86d0eb7cb8)    

**Additional context**

**Comment by albert-github** [comment] 2021-09-08 13:17
I think this issue is a duplicate of issue #5114

**Comment by shahmoradi** [comment] 2021-09-08 15:20
I managed to fix this "all-to-lower-case" behavior in a fork of Doxygen last night. I can make a PR for this if it is likely to be accepted, but I think it would be better to understand why such "all-to-lower-case" behavior was enforced in the first place. I think the reason might be related to the fact that Fortran is case-insensitive, so different writings of the same keyword or object name should be regarded as the same, but that is not the case in HTML and this causes problems for hyper-linking and references. This was likely a bit of work to implement, so the reason why the original authors decided to lower the case everywhere as a quick solution.

**Comment by albert-github** [comment] 2021-09-08 15:40
Unfortunately without knowing what you changed to solve the problem it is hard to tell whether or not it will be accepted, so you should make a PR out of it.

The exact reasoning for the usage of the choice of Fortran lowercase is not known to me, but to solve the problem one of course needs a standardized form of the different names and here there was chosen for the lowercase version and one has to store 2 versions of the name i.e. the name to display as used in the definition (e.g the definition of a subroutine i.e. the CamelCase name in your case) and the name to use in (internal) searches (i.e. the all lowercase name).
- What happens when the case of the definition is different from the case in e.g. a call (it is a violation of your coding conventions, but it can happen and is OK for Fortran)
- did you take the ISO C binding (i.e. bind(C,...) into consideration?

**Comment by shahmoradi** [comment] 2021-09-13 01:45
Okay, Thank you. I will do so, but given your suggested desired solution, I am not sure people will find my workaround acceptable. My suggestion is to enforce case-sensitivity in Doxygen documentation of Fortran codebase as opposed to either lowering all cases and living with almost unreadable documentation or going the difficult route you suggested (for which I do not have a straightforward solution at the moment). While it is true that Fortran is case-insensitive, modern-Fortran programmers (and even the old-schools) hardly modify the case of Fortran entities throughout their codebase. So, if a decision is to be made on whether to keep case sensitivity, the readability of the generated documentation should be given more weight than the remote scenario where a Fortran developer uses mixed-case coding. In particular, there are ample Fortran codebases that use the CameCase style which becomes unreadable when Doxygen lowers the case of all letters. In my branch of the Doxygen repository, I resolved the issue by simply removing all lowering of the cases of the Fortran entities. This effectively means that Doxygen treats Fortran code as case-sensitive, and Fortran users of Doxygen should respect case sensitivity.

I have also made the following enhancements to the Fortran syntax highlighting rules of Doxygen:

+ Over 500 new names of Fortran intrinsic functions, subroutines, modules, named constants, and specifiers (e.g., intrinsic procedure argument names) are now recognized and properly highlighted by Doxygen. The new set effectively covers all Fortran keywords in the latest Fortran standard 2018, and covers all keywords in 5 older standards F2008, F2003, F95, F90, F77.

+   Syntax recognition for MPI subroutines and entities, OpenMP directives, and Intel Fortran Compiler
    directives are now added.

+   The `real` and `logical` intrinsic functions are now properly recognized and highlighted as intrinsic functions or type declarations where appropriate.

+   Syntax recognition for Fortran `submodule`s and `module (function|subroutine|procedure)` now added.

+   Syntax recognition for Fortran intrinsic modules, including IEEE modules and their entities, `iso_fortran_enc` and `iso_c_binding` and their entities are now added.

+   Syntax recognition for new and modern Fortran constructs now added, for example, `block` and `associate` constructs.

+   Syntax recognition for all Fortran intrinsic Coarray parallel procedures and entities now added.

+   syntax recognition for new procedure attributes added (e.g., IMPURE, `(non_)?overridable`, ...).

+   The Fortran component separator symbol `%` is now recognized and highlighted. This is
    very useful for enhanced readability of Fortran codes as `%` is a rather busy symbol.
    
+   All Fortran intrinsic operators are now properly recognized and highlighted.

[Here is an example of Fortran documentation built with the modified Doxygen-Fortran](https://cdslaborg.github.io/paramonte-kernel-doc/html/Array__mod_8f90_source.html). I will make a PR in hope of a merge. thanks for the great work and support of Fortran.

**Closed** 2021-12-31 11:09 UTC
Labels: duplicate, enhancement, Fortran
