### ISSUE TITLE
Using an alias within an alias

### ISSUE THREAD

**Issue by eseiler** [doxygen/doxygen#10193] opened 2023-07-25 11:31 UTC
**Describe the bug**
We have aliases that take one argument and will return some HTML stuff using the argument.
Because the argument is optional, we also want to be able to just use the alias without argument and basically have a default argument.

A reduced example:

```cpp
/*!\brief A struct.
 * \details
 *
 * \myalias{with_arg}
 *
 * \myalias
 */
struct S{};
```

Using a default Doxyfile (current master), with following adjustments:
```diff
diff --git a/../Doxyfile.default b/Doxyfile
index 7b3458f..ee677c4 100644
--- a/../Doxyfile.default
+++ b/Doxyfile
@@ -40,7 +40,8 @@ PYTHON_DOCSTRING       = YES
 INHERIT_DOCS           = YES
 SEPARATE_MEMBER_PAGES  = NO
 TAB_SIZE               = 4
-ALIASES                =
+ALIASES                = "myalias{1}=\1" \
+                         "myalias=\myalias{no_arg}"
 OPTIMIZE_OUTPUT_FOR_C  = NO
 OPTIMIZE_OUTPUT_JAVA   = NO
 OPTIMIZE_FOR_FORTRAN   = NO
```

**Expected behavior**
Prior to 6b20feb17b8b542149d1f524982745d3e90153ba, it worked as we expected. `\myalias` resolved to `\myalias{no_arg}`, which then resolved to `no_arg`.

After 2777acd99c6bce2b2d0d1fa2c148c75bcf61a7fd, `test.hpp:6: warning: Found unexpanded alias '\myalias'. Check if number of arguments passed is correct.` is emitted and the output is `\myalias{no_arg}`.

I played around with escaping various parts of the alias value part, but with no luck.

Personally, I'm fine with this use case being not intended and the resolution being to just copy/paste the alias value (in the example: `myalias=no_arg`).

**Screenshots**
<details><summary>Click to show output on Doxygen 1.9.7</summary>

![doxygen_197](https://github.com/doxygen/doxygen/assets/12967715/b2cc3e00-147d-445d-ae45-33a3b87eb699)
</details>
<details><summary>Click to show output on Doxygen master</summary>

![doxygen_master](https://github.com/doxygen/doxygen/assets/12967715/48fd10be-7d80-4ce5-95af-dbf9df3e98d8)
</details>

**To Reproduce**
[example.tar.gz](https://github.com/doxygen/doxygen/files/12160482/example.tar.gz)

**Version**
Doxygen: `1.9.8 (2777acd99c6bce2b2d0d1fa2c148c75bcf61a7fd)`
I did not bisect between 6b20feb17b8b542149d1f524982745d3e90153ba and 2777acd99c6bce2b2d0d1fa2c148c75bcf61a7fd.
OS: `Ubuntu 22.04.2 LTS`
Compiled myself.

**Comment by albert-github** [comment] 2023-07-25 14:01
I think this problem is a regression as also found for CGAL in https://github.com/doxygen/doxygen/pull/10179#issuecomment-1649553770

**Comment by doxygen** [comment] 2023-07-27 19:26
@eseiler Please verify if the referenced commit fixes the problem for you.

**Comment by eseiler** [comment] 2023-07-28 14:54
I can confirm that the commit fixes the issue for me. The warning is gone, and the output is as expected.

Thank you!

**Comment by albert-github** [comment] 2023-07-28 16:36
Since this problem is not appearing in any official release and is fixed before the next release I'll close the issue.

**Closed by albert-github** 2023-07-28 16:36 UTC
Labels: bug
