### ISSUE TITLE
\ref fails to resolve reference to a member of a struct nested in a class template specialization (C++)

### ISSUE THREAD

**Issue by krivenko** [doxygen/doxygen#10559] opened 2024-01-14 14:36 UTC
**Describe the bug**

Doxygen 1.9.5 introduced a regression which affects `\ref`'s ability to resolve members of structures that are defined within a class template specialization.

```c++
/// Outer class template
template<bool B, typename T> class Outer {};

/// Specialization of Outer
template<typename T> class Outer<true, T> {

public:
    /// Inner structure
    struct Inner {
        /// Data member
        int x;

        /// Return
        /// 1. @ref Outer<true, T>::Inner::x
        /// 2. @ref Inner::x
        /// 3. @ref x
        int get_x() const { return x; }
    };
};
```
Doxygen 1.9.4 generates correct links from all the 3 instances of `@ref` here, while 1.9.5 fails to do so.
```
issue.hpp:14: warning: unable to resolve reference to 'Outer<true, T>::Inner::x' for \ref command
issue.hpp:15: warning: unable to resolve reference to 'Inner::x' for \ref command
issue.hpp:16: warning: unable to resolve reference to 'x' for \ref command
```

The exact commit where the regression was introduced is b290399fab92df45376103d7c094f053f24495fa.

**Expected behavior**

Proper link generation, the way it was in 1.9.4.

**To Reproduce**

[ref_struct_in_class_spec.zip](https://github.com/doxygen/doxygen/files/13931839/ref_struct_in_class_spec.zip)

**Version**

Doxygen 1.9.5 (b290399fab92df45376103d7c094f053f24495fa*)
Gentoo Linux x86_64
Doxygen built from git sources, GCC 13.2.1

**Comment by albert-github** [comment] 2024-01-14 14:56
Problem is also still present in the current master 1.11.0 (48a3670d34fe00447a81aa6b50b0441b7fa77b57)

**Comment by doxygen** [comment] 2024-01-18 20:14
@krivenko Please verify if the referenced commit fixes the problem for you. Do not close the issue, this will be done automatically when the next official release becomes available.

**Comment by krivenko** [comment] 2024-01-19 10:30
@doxygen Thank you for the quick response!

The example I posted gives the expected result with db523de. That said, I still cannot make Doxygen generate correct links in my own project.

It turns out, the problem still manifests itself with a slightly more complex example where everyting is placed in a namespace.
```c++
namespace ns {

/// Outer class template
template<bool B, typename T> class Outer {};

/// Specialization of Outer
template<typename T> class Outer<true, T> {

public:
    /// Inner structure
    struct Inner {
        /// Data member
        int x;

        /// Return
        /// 1. @ref ns::Outer<true, T>::Inner::x
        /// 2. @ref Outer<true, T>::Inner::x
        /// 3. @ref Inner::x
        /// 4. @ref x
        int get_x() const { return x; }
    };
};

}
```
(Doxygen 1.9.4 still works fine here).

**Comment by doxygen** [comment] 2024-01-20 20:00
@krivenko Thanks for the feedback. Adding the namespace indeed revealed some issues with the fix. I've pushed another commit, which should hopefully address these. Let me know if it works in your project now.

**Comment by albert-github** [comment] 2024-01-21 09:59
@doxygen 
By chance I ran yesterday in a, probably, similar problem with the worker 5.0.1 package from Fossies.
When running with 1.11.0 (dc6385cd1325a473bfa58e4c08a30d6a362df30d) I get here:
```
.../worker_types.cc:42: warning: no matching file member found for
unsigned int WorkerTypes::getAvailListColsSize
Possible candidates:
  'unsigned int getAvailListColsSize()' at line 53 of file .../worker_types.h
.../worker_types.cc:47: warning: no matching file member found for
int WorkerTypes::getAvailListColEntry(WorkerTypes::listcol_t type)
Possible candidates:
  'int getAvailListColEntry(listcol_t type)' at line 54 of file .../worker_types.h
```

A small example: [example.tar.gz](https://github.com/doxygen/doxygen/files/14000746/example.tar.gz)

**Comment by doxygen** [comment] 2024-01-21 10:51
@albert-github The issue in example.tar.gz has a different cause (The redundant struct keyword in the `struct A N::B` construct was seen as `struct A N:` making the scanner go off-track looking for a base class), but since it is reported here, I've added the fix for it here as well.

**Comment by albert-github** [comment] 2024-01-21 11:02
The problem for "worker_types" has been solved.
Running the full package again I saw another (probably similar one, but I'm happy with it when I have to write a new issue for it) in "fiellistview":
```
.../fieldlistview.cc:2473: warning: no matching class member found for
  void FieldListView::setSelectHandler(void(*nsh)(FieldListView *, int p))
Possible candidates:
  'void FieldListView::setSelectHandler(void(*nsh)(FieldListView *, int element))' at line 121 of file .../fieldlistview.h
  'void FieldListView::setSelectHandler(std::function< void(FieldListView *, int element) > cb)' at line 122 of file .../fieldlistview.h
```

Example: [example_4.tar.gz](https://github.com/doxygen/doxygen/files/14000989/example_4.tar.gz)

**Comment by doxygen** [comment] 2024-01-21 11:15
@albert-github Yes, please create a different issue. Without trying the example, I can already see the problem is the parameter matching on function pointers. Doxygen sees `void(*)(FieldListView *, int p)` as the type of the variable, and this type does not match `void(*)(FieldListView *, int element)` because of the difference in parameter names that are embedded in the type. This is a known limitation of function pointer matching.

**Comment by krivenko** [comment] 2024-01-21 12:54
> @krivenko Thanks for the feedback. Adding the namespace indeed revealed some issues with the fix. I've pushed another commit, which should hopefully address these. Let me know if it works in your project now.

@doxygen Thanks a lot, I can now confirm that 1cbe096cf917e924082aebcefcef0927be26a3c1 solves the issue for me.

**Closed** 2024-05-20 09:54 UTC
Labels: bug, C/C++
