### ISSUE TITLE
doxygen unable to work under path containing unicode character in Windows (Origin: bugzilla #605565)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3614] opened 2018-07-02 03:11 UTC
status NEW severity *major* in component *build* for *---*
Reported in version *1.6.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-12-27 20:23:17 +0000, supercoolman@gmail.com wrote:

    I'm not sure if same problem exist for other OS, but under windows it's
    unable to support path containing Unicode or double-byte characters.
    
    doxygen 1.6.1
    E:\å¯«ç¨å¼\doxygen1.6.1\doxygen.exe
    E:\å¯«ç¨å¼\project_1+3\main.c
    E:\å¯«ç¨å¼\project_1+3\interrupt.c
    E:\å¯«ç¨å¼\project_1+3\interrupt.h
    
    
    first, doxygen is unable to generate default config file with command
    "E:\å¯«ç¨å¼\doxygen1.6.1\doxygen.exe" -g
    "E:\å¯«ç¨å¼\project_1+3\doxy\default.doxy"
    
    second, if I made that config file myself and launch doxygen with that file,
    doxygen complaints that the file does not exist.
    
    These two problems are resolved if I rename å¯«ç¨å¼ into "temp" or
    "programs". However, that broke all of my projects because I have eclipse
    projects and other projects created by other IDEs all with absolute path
    configuration in that directory.

On 2009-12-28 09:30:16 +0000, Dimitri van Heesch wrote:

    Seems like a windows only issue indeed, as I cannot reproduce it on my Mac.

**Comment by albert-github** [comment] 2022-12-26 18:17
I think this problem is a duplicate of #1166 (Read error when multi-byte characters in file path name). 

A small test revealed that with 1.9.5 the attached example fails but with the current master(1.9.6 (2b6657b02b6441433f01e4da13a2228c27127be7)) it works probably due to commit e002e293d9dc956a0634b3a4bcc8d93e655582d5 

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/10304442/example.tar.gz)

**Closed** 2022-12-27 10:23 UTC
Labels: bug, duplicate
