### ISSUE TITLE
\copydoc do not include comments within function (Origin: bugzilla #662606)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4446] opened 2018-07-02 06:18 UTC
status NEW severity *normal* in component *build* for *---*
Reported in version *1.8.2-SVN* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-10-24 13:40:11 +0000, Marcin Bajer wrote:

    For funciton like this:
    
    /**
     * Test
     * 
     * Test function description
     */
    void foo(void)
    {
    /// First think done in the function
    
    /// Second think done in the function
    }
    
    The documentation of function will include comments within the function, but
    when I will use \copydoc or \copydetails the comments inside function will
    be skipped. I think it should be added, or new command should be added for
    adding it.

On 2012-11-18 11:07:23 +0000, Dimitri van Heesch wrote:

    Changed version 'latest' to '1.8.2-SVN' so I can remove 'latest' as an
    option as it is a moving target.

**Comment by albert-github** [comment] 2019-06-08 12:29
As far as I can see this is a duplicate of #3610:
`\copydetails omits in-body docs (Origin: bugzilla 604576)`

**Closed** 2019-12-28 11:05 UTC
Labels: duplicate
