### ISSUE TITLE
qhp/qch broken in master

### ISSUE THREAD

**Issue by sandsmark** [doxygen/doxygen#8789] opened 2021-09-21 11:11 UTC
f74a0c5caf7be77c33721eb20dfcaef5f96eaf2e broke the qhp generation, `<keywords></keywords>` is now always completely empty.

Seems reproducible with any (c++) source tree.

Found by git bisect.

**Comment by albert-github** [comment] 2021-09-21 13:20
@doxygen looks like an order problem. When moving `addToIndices` to just before `"finalizing index lists...\n"` in `doxygen.cpp` I get the top level of items, but I'm still missing the second level items (and maybe deeper levels).
I tried just with `doxygen.cpp` and `GENERATE_QHP           = YES`.

- any idea?

**Comment by albert-github** [comment] 2021-09-22 09:30
Note with the chm we have the same problem, here the complete relevant content in `index.hhk` is missing.

**Comment by sandsmark** [comment] 2021-09-24 13:49
Not sure tbh., I know that at least the qhp generator needs to get everything in the exact order it's supposed to be written (its XML generator is pretty simplistic), but not sure if that's related?

I started on a patch to fix another problem with it (it references html files that doesn't exist, [which after a lot of stuff ends up creating duplicate entries in Qt Assistant referring to the css files](https://bugs.kde.org/show_bug.cgi?id=442768)), which modifies it  to write out the XML at the end, but that didn't change this behavior.

**Comment by albert-github** [comment] 2021-09-24 13:56
In the linked kde question you refer to a product `ecm` but without knowing how its documentation is generated it is hard to tell what the problem is. One problem I can think of is that maybe `ecm` uses a tag file to the Qt documentation to generate its own documentation, but as said as no information about the generation of the `ecm` documentation is present this is hard to tell (and thus a wild guess).

**Comment by doxygen** [comment] 2021-12-31 11:10
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2021-12-31 11:10 UTC
Labels: bug
