### ISSUE TITLE
Fortran source file that contains the character literal "import" or 'import'

### ISSUE THREAD

**Issue by DrK** [doxygen/doxygen#8867] opened 2021-11-01 13:03 UTC
**Describe the bug**
The Doxygen source viewer is having problems with some, but not all, character literals that contain "import"

**Screenshots**
See this code snippet
![image](https://user-images.githubusercontent.com/409588/139673009-d6f351aa-d507-46c8-8d22-3bf48a830926.png)

And look at how it comes out:
![image](https://user-images.githubusercontent.com/409588/139673191-3156a1dd-bac6-458e-b405-f00496ea1f88.png)

I have played with different combinations of '"import' and results vary, for instance...

![image](https://user-images.githubusercontent.com/409588/139673730-8911e1e3-b1de-4ac0-a4c2-edc2f60cb9ad.png)

and this comes out as follows ( note the word import has been replicated!)
![image](https://user-images.githubusercontent.com/409588/139674068-0f7b52d6-2946-488b-8358-1e9393137c89.png)

In both the above examples other instances of "import" are behaving normally

In this second example, there is a second issue on the line after "if ( me % use_oo_api ) then"

**Version**
Initially noticed on 1.9.1
Example shown is 1.9.2

**Additional context**
Note that I am running Doxygen on Windows on source code that has already been preprocessed with Intel /FPP so I have ENABLE_PREPROCESSING   = NO in the Doxyfile

Note also that I am not using submodules, to generate the Doxygen output I have already run preprocessor macros that #include the submodule files having removed the relevant SUBMODULE and END SUBMODULE statements with the preprocessor

I have not yet attempted to create a small reproducer, but I was tracking down other problems with Doxygen when I noticed this little fellow.  I am reluctant to try a reproducer just now - other deadlines...

BW & stay safe

**Comment by albert-github** [comment] 2021-11-01 13:19
The import keyword is probably not supported in all code fragments yet.
From screenshots it is impossible to get the context and get a good example so:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by albert-github** [comment] 2021-11-01 14:02
Even though no case was attached (created a minimal case, see #8868).

I've just pushed a proposed patch, pull request #8868

I could not reproduce the second mentioned problem, but seen the generic solution I think the problem might be solved as well, still a test / test case should be executed / provided.

**Comment by DrK** [comment] 2021-11-01 17:24
Working on test but failing to reproduce the problem, will keep trying

**Comment by albert-github** [comment] 2021-11-01 17:25
Best to try the patch on the original code.

**Comment by DrK** [comment] 2021-11-01 17:44
OK it was a struggle, but see attached

Thanks for your help

[Doxyfile import example.zip](https://github.com/doxygen/doxygen/files/7455161/Doxyfile.import.example.zip)

**Comment by DrK** [comment] 2021-11-01 17:45
OK now I have seen your comment "Best to try the patch on the original code.", do I have to be able to build Doxygen from source?

**Comment by albert-github** [comment] 2021-11-01 17:49
Depends on the OS you are using. In case of Windows, MacOS and Ubuntu there are executables available under Github Actions (see: https://github.com/doxygen/doxygen/actions/runs/1408291812 under Artifacts) , otherwise you have to build from source.

**Comment by albert-github** [comment] 2021-11-01 17:56
I quickly ran the code through the doxygen version 1.9.2 and the patched version

**doxygen 1.9.2**
![image](https://user-images.githubusercontent.com/5223533/139717363-fbba9fc6-c4cd-40e8-9e6b-07f53d0fea94.png)

**patched version**
![image](https://user-images.githubusercontent.com/5223533/139717501-20dbf21a-e3e5-4df7-9dd8-f9576507956f.png)


Looks to me that the patched version is OK.

Full results for the 1.9.2 and patched version: 
[results.tar.gz](https://github.com/doxygen/doxygen/files/7455228/results.tar.gz)

**Comment by DrK** [comment] 2021-11-01 18:43
I have run the patch on the full code, and it seems to have fixed this problem

Thank you, so much & stay safe

**Comment by albert-github** [comment] 2021-11-01 20:12
The proposed pull request is not in an official release yet.
Reopening issue, please don't close the issue as this will be done at the moment of an official release.

**Comment by albert-github** [comment] 2021-11-04 09:08
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment] 2021-12-31 10:58
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.3.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2021-12-31 10:58 UTC
Labels: bug, Fortran
