### ISSUE TITLE
Constructors lack "referenced by" information (Origin: bugzilla #337487)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2110] opened 2018-07-01 21:31 UTC
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-04-06 12:12:37 +0000, Timo Saarinen wrote:

    It would be very helpfull if generated constructor document had similar
    "referenced by" line as normal methods. Of course this could be renamed as
    "constructed by".

**Comment by albert-github** [comment] 2023-11-21 17:57
This looks like a duplicate of ""Referenced by" relations never generated for ctor/dtor (Origin: bugzilla #143559)" i.e. #1141

**Closed** 2023-12-25 11:15 UTC
Labels: duplicate, C/C++
