### ISSUE TITLE
missing jquerry scrollTo leads to endless loop of timer setting

### ISSUE THREAD

**Issue by kfessel** [doxygen/doxygen#8204] opened 2020-11-25 14:53 UTC
https://github.com/doxygen/doxygen/blob/6de91dc5e32e6d97a557fe6910a6cbf1d453ad9c/templates/html/navtree.js#L259-L264

https://github.com/doxygen/doxygen/blob/6de91dc5e32e6d97a557fe6910a6cbf1d453ad9c/templates/html/navtree.js#L263

**Describe the bug**
This seems wrong to me, the line says: if this fails do the same thing again (but expect a different result)
there is a saying credited to Albert Einstein about that.
Even more bad do this as fast as possible (timeout = 0).

If ScrollTo is missing this fails and will continue to fail making this an endless loop of timer setting and function handling.

See: https://github.com/RIOT-OS/RIOT/issues/15503

**Expected behavior**
 no circular calls/ rapid timer self triggering

**To Reproduce**
https://github.com/RIOT-OS/RIOT/issues/15503

**Comment by albert-github** [comment] 2020-11-25 17:06
I see that you used / refer to the latest doxygen master 1.9.0 (6de91dc).

The reference you give is to https://github.com/RIOT-OS/RIOT/pull/15503 and the fix is in https://github.com/RIOT-OS/RIOT/pull/15505 though the fix confuses me a little bit as here I see:
```
...    
    <script src="$relpath^jquery.min.js"></script>
    <script src="$relpath^jquery.powertip.min.js"></script>
    <script src="$relpath^jquery-ui.min.js"></script>

    <script src="$relpath^doxy-jquery.js"></script>
    <script src="$relpath^dynsections.js"></script>
...
```
and I see that you added:
```
    <script src="$relpath^jquery.scrollTo.min.js"></script>
```

But when looking in the doxygen repository I see in the file `templates/html/header.html` jus the lines:
```
<script type="text/javascript" src="$relpath^jquery.js"></script>
<script type="text/javascript" src="$relpath^dynsections.js"></script>
```

- Is there a reason why not using just `jquery.js` ?
- What happens when using `jquery.js`?

**Comment by doxygen** [comment] 2020-11-25 20:40
@albert-github I think the confusion may come from this: https://github.com/doxygen/doxygen/tree/master/jquery (i.e. doxygen's `jquery.js` is actually bundle of jquery + other jquery based scripts which includes the scrollTo package). 

So this is only a problem if use doxygen generated output with a standard (non doxygen generated) jquery script.

**Comment by albert-github** [comment] 2020-11-25 21:03
So actually is is not a doxygen problem but caused by the fact that an own header.html is used with the separate jquery based scripts.

- So best would be to use the jquery.js as provided by doxygen, as this will be consistent with the way doxygen uses it.
- Wouldn't it be better to document the the doxygen provided jquery.js  is actually a bundle of  jquery + other jquery based scripts and mention the bundled scripts?

**Comment by kfessel** [comment] 2020-11-26 15:24
may be the generated file should not be called `jquery.js`. I would expect jquery in that file and not jquery and a whole lot of other stuff. `bundle.js` might be a good name.

**Comment by albert-github** [comment] 2020-11-30 11:03
Renaming the `jquery.js` is currently not a good idea as this would break a lot of packages that use their own `HTML_HEADER`, of course when running a package with a version of doxygen one should adopt ones own `HTML_HEADER` to the new situation.

I saw that the information about the used jquery and the used packages is present in the doxygen repository in the directory `jquery` (parallel to e.g. `src`), the information is not present in the documentation (but I'm not sure / I don't think that it should be present there. We have a similar situation with LaTeX and the `tabu` package where doxygen ships its own versions as well, though here a rename strategy has been applied).

**Closed** 2020-12-27 19:28 UTC
Labels: HTML, Usage, needinfo
