### ISSUE TITLE
The prefix &#х202А; for files is displayed incorrectly in the file names.

### ISSUE THREAD

**Issue by piratkin** [doxygen/doxygen#8246] opened 2020-12-13 00:01 UTC
The prefix `&#х202А;` for files is displayed incorrectly in the file names.

![x202a](https://user-images.githubusercontent.com/14215246/101999490-971bda00-3cee-11eb-9b5c-8c8454df87d7.png)

I found this place in the source code of (`src/docparser.cpp`):

```с++
QCString getHtmlDirEmbeddingChar(QString::Direction textDir)
{
  if (textDir == QString::DirLTR)
    return "&#x202A;";
...
```

I'm guessing it's about the settings, here's my:

<details>
<summary>Doxyfile</summary>
<p>

```c#
DOXYFILE_ENCODING      = UTF-8
PROJECT_NAME           = ""
PROJECT_NUMBER         = ""
PROJECT_BRIEF          = ""
PROJECT_LOGO           = logo.png
OUTPUT_DIRECTORY       = docs
CREATE_SUBDIRS         = NO
ALLOW_UNICODE_NAMES    = NO
OUTPUT_LANGUAGE        = English
OUTPUT_TEXT_DIRECTION  = Context
BRIEF_MEMBER_DESC      = YES
REPEAT_BRIEF           = YES
ABBREVIATE_BRIEF       = "The $name class" \
                         "The $name widget" \
                         "The $name file" \
                         is \
                         provides \
                         specifies \
                         contains \
                         represents \
                         a \
                         an \
                         the
ALWAYS_DETAILED_SEC    = NO
INLINE_INHERITED_MEMB  = NO
FULL_PATH_NAMES        = YES
STRIP_FROM_PATH        = include src
STRIP_FROM_INC_PATH    =
SHORT_NAMES            = YES
JAVADOC_AUTOBRIEF      = NO
JAVADOC_BANNER         = NO
QT_AUTOBRIEF           = NO
MULTILINE_CPP_IS_BRIEF = NO
PYTHON_DOCSTRING       = YES
INHERIT_DOCS           = YES
SEPARATE_MEMBER_PAGES  = NO
TAB_SIZE               = 4
ALIASES                =
OPTIMIZE_OUTPUT_FOR_C  = NO
OPTIMIZE_OUTPUT_JAVA   = NO
OPTIMIZE_FOR_FORTRAN   = NO
OPTIMIZE_OUTPUT_VHDL   = NO
OPTIMIZE_OUTPUT_SLICE  = NO
EXTENSION_MAPPING      =
MARKDOWN_SUPPORT       = YES
TOC_INCLUDE_HEADINGS   = 5
AUTOLINK_SUPPORT       = YES
BUILTIN_STL_SUPPORT    = NO
CPP_CLI_SUPPORT        = NO
SIP_SUPPORT            = NO
IDL_PROPERTY_SUPPORT   = YES
DISTRIBUTE_GROUP_DOC   = NO
GROUP_NESTED_COMPOUNDS = NO
SUBGROUPING            = YES
INLINE_GROUPED_CLASSES = NO
INLINE_SIMPLE_STRUCTS  = NO
TYPEDEF_HIDES_STRUCT   = NO
LOOKUP_CACHE_SIZE      = 0
NUM_PROC_THREADS       = 1
EXTRACT_ALL            = NO
EXTRACT_PRIVATE        = NO
EXTRACT_PRIV_VIRTUAL   = NO
EXTRACT_PACKAGE        = NO
EXTRACT_STATIC         = NO
EXTRACT_LOCAL_CLASSES  = YES
EXTRACT_LOCAL_METHODS  = NO
EXTRACT_ANON_NSPACES   = NO
HIDE_UNDOC_MEMBERS     = NO
HIDE_UNDOC_CLASSES     = NO
HIDE_FRIEND_COMPOUNDS  = NO
HIDE_IN_BODY_DOCS      = NO
INTERNAL_DOCS          = NO
CASE_SENSE_NAMES       = NO
HIDE_SCOPE_NAMES       = NO
HIDE_COMPOUND_REFERENCE= NO
SHOW_INCLUDE_FILES     = YES
SHOW_GROUPED_MEMB_INC  = NO
FORCE_LOCAL_INCLUDES   = NO
INLINE_INFO            = YES
SORT_MEMBER_DOCS       = YES
SORT_BRIEF_DOCS        = NO
SORT_MEMBERS_CTORS_1ST = NO
SORT_GROUP_NAMES       = NO
SORT_BY_SCOPE_NAME     = NO
STRICT_PROTO_MATCHING  = NO
GENERATE_TODOLIST      = YES
GENERATE_TESTLIST      = YES
GENERATE_BUGLIST       = YES
GENERATE_DEPRECATEDLIST= YES
ENABLED_SECTIONS       =
MAX_INITIALIZER_LINES  = 30
SHOW_USED_FILES        = YES
SHOW_FILES             = YES
SHOW_NAMESPACES        = YES
FILE_VERSION_FILTER    =
LAYOUT_FILE            =
CITE_BIB_FILES         =
QUIET                  = NO
WARNINGS               = YES
WARN_IF_UNDOCUMENTED   = YES
WARN_IF_DOC_ERROR      = YES
WARN_NO_PARAMDOC       = NO
WARN_AS_ERROR          = NO
WARN_FORMAT            = "$file:$line: $text"
WARN_LOGFILE           =
INPUT                  = README.md include src
INPUT_ENCODING         = UTF-8
FILE_PATTERNS          = *.c \
                         *.cc \
                         *.cxx \
                         *.cpp \
                         *.c++ \
                         *.java \
                         *.ii \
                         *.ixx \
                         *.ipp \
                         *.i++ \
                         *.inl \
                         *.idl \
                         *.ddl \
                         *.odl \
                         *.h \
                         *.hh \
                         *.hxx \
                         *.hpp \
                         *.h++ \
                         *.cs \
                         *.d \
                         *.php \
                         *.php4 \
                         *.php5 \
                         *.phtml \
                         *.inc \
                         *.m \
                         *.markdown \
                         *.md \
                         *.mm \
                         *.dox \
                         *.doc \
                         *.txt \
                         *.py \
                         *.pyw \
                         *.f90 \
                         *.f95 \
                         *.f03 \
                         *.f08 \
                         *.f18 \
                         *.f \
                         *.for \
                         *.vhd \
                         *.vhdl \
                         *.ucf \
                         *.qsf \
                         *.ice
RECURSIVE              = YES
EXCLUDE                =
EXCLUDE_SYMLINKS       = NO
EXCLUDE_PATTERNS       =
EXCLUDE_SYMBOLS        =
EXAMPLE_PATH           =
EXAMPLE_PATTERNS       = *
EXAMPLE_RECURSIVE      = NO
IMAGE_PATH             =
INPUT_FILTER           =
FILTER_PATTERNS        =
FILTER_SOURCE_FILES    = NO
FILTER_SOURCE_PATTERNS =
USE_MDFILE_AS_MAINPAGE =
SOURCE_BROWSER         = YES
INLINE_SOURCES         = NO
STRIP_CODE_COMMENTS    = YES
REFERENCED_BY_RELATION = NO
REFERENCES_RELATION    = NO
REFERENCES_LINK_SOURCE = YES
SOURCE_TOOLTIPS        = YES
USE_HTAGS              = NO
VERBATIM_HEADERS       = YES
ALPHABETICAL_INDEX     = YES
COLS_IN_ALPHA_INDEX    = 5
IGNORE_PREFIX          =
GENERATE_HTML          = YES
HTML_OUTPUT            = html
HTML_FILE_EXTENSION    = .html
HTML_HEADER            =
HTML_FOOTER            =
HTML_STYLESHEET        =
HTML_EXTRA_STYLESHEET  =
HTML_EXTRA_FILES       =
HTML_COLORSTYLE_HUE    = 220
HTML_COLORSTYLE_SAT    = 100
HTML_COLORSTYLE_GAMMA  = 80
HTML_TIMESTAMP         = NO
HTML_DYNAMIC_MENUS     = YES
HTML_DYNAMIC_SECTIONS  = NO
HTML_INDEX_NUM_ENTRIES = 100
GENERATE_DOCSET        = NO
DOCSET_FEEDNAME        = "Doxygen generated docs"
DOCSET_BUNDLE_ID       = org.doxygen.Project
DOCSET_PUBLISHER_ID    = org.doxygen.Publisher
DOCSET_PUBLISHER_NAME  = Publisher
GENERATE_HTMLHELP      = NO
CHM_FILE               =
HHC_LOCATION           =
GENERATE_CHI           = NO
CHM_INDEX_ENCODING     =
BINARY_TOC             = NO
TOC_EXPAND             = NO
GENERATE_QHP           = NO
QCH_FILE               =
QHP_NAMESPACE          = org.doxygen.Project
QHP_VIRTUAL_FOLDER     = doc
QHP_CUST_FILTER_NAME   =
QHP_CUST_FILTER_ATTRS  =
QHP_SECT_FILTER_ATTRS  =
QHG_LOCATION           =
GENERATE_ECLIPSEHELP   = NO
ECLIPSE_DOC_ID         = org.doxygen.Project
DISABLE_INDEX          = NO
GENERATE_TREEVIEW      = YES
ENUM_VALUES_PER_LINE   = 4
TREEVIEW_WIDTH         = 250
EXT_LINKS_IN_WINDOW    = NO
HTML_FORMULA_FORMAT    = svg
FORMULA_FONTSIZE       = 10
FORMULA_TRANSPARENT    = YES
FORMULA_MACROFILE      =
USE_MATHJAX            = NO
MATHJAX_FORMAT         = HTML-CSS
MATHJAX_RELPATH        = https://cdn.jsdelivr.net/npm/mathjax@2
MATHJAX_EXTENSIONS     =
MATHJAX_CODEFILE       =
SEARCHENGINE           = NO
SERVER_BASED_SEARCH    = NO
EXTERNAL_SEARCH        = NO
SEARCHENGINE_URL       =
SEARCHDATA_FILE        = searchdata.xml
EXTERNAL_SEARCH_ID     =
EXTRA_SEARCH_MAPPINGS  =
GENERATE_LATEX         = NO
LATEX_OUTPUT           = latex
LATEX_CMD_NAME         =
MAKEINDEX_CMD_NAME     = makeindex
LATEX_MAKEINDEX_CMD    = makeindex
COMPACT_LATEX          = NO
PAPER_TYPE             = a4
EXTRA_PACKAGES         =
LATEX_HEADER           =
LATEX_FOOTER           =
LATEX_EXTRA_STYLESHEET =
LATEX_EXTRA_FILES      =
PDF_HYPERLINKS         = YES
USE_PDFLATEX           = YES
LATEX_BATCHMODE        = NO
LATEX_HIDE_INDICES     = NO
LATEX_SOURCE_CODE      = NO
LATEX_BIB_STYLE        = plain
LATEX_TIMESTAMP        = NO
LATEX_EMOJI_DIRECTORY  =
GENERATE_RTF           = NO
RTF_OUTPUT             = rtf
COMPACT_RTF            = NO
RTF_HYPERLINKS         = NO
RTF_STYLESHEET_FILE    =
RTF_EXTENSIONS_FILE    =
RTF_SOURCE_CODE        = NO
GENERATE_MAN           = NO
MAN_OUTPUT             = man
MAN_EXTENSION          = .3
MAN_SUBDIR             =
MAN_LINKS              = NO
GENERATE_XML           = NO
XML_OUTPUT             = xml
XML_PROGRAMLISTING     = YES
XML_NS_MEMB_FILE_SCOPE = NO
GENERATE_DOCBOOK       = NO
DOCBOOK_OUTPUT         = docbook
DOCBOOK_PROGRAMLISTING = NO
GENERATE_AUTOGEN_DEF   = NO
GENERATE_PERLMOD       = NO
PERLMOD_LATEX          = NO
PERLMOD_PRETTY         = YES
PERLMOD_MAKEVAR_PREFIX =
ENABLE_PREPROCESSING   = YES
MACRO_EXPANSION        = NO
EXPAND_ONLY_PREDEF     = NO
SEARCH_INCLUDES        = YES
INCLUDE_PATH           =
INCLUDE_FILE_PATTERNS  =
PREDEFINED             =
EXPAND_AS_DEFINED      =
SKIP_FUNCTION_MACROS   = YES
TAGFILES               =
GENERATE_TAGFILE       =
ALLEXTERNALS           = NO
EXTERNAL_GROUPS        = YES
EXTERNAL_PAGES         = YES
CLASS_DIAGRAMS         = YES
DIA_PATH               =
HIDE_UNDOC_RELATIONS   = YES
HAVE_DOT               = YES
DOT_NUM_THREADS        = 2
DOT_FONTNAME           = Helvetica
DOT_FONTSIZE           = 10
DOT_FONTPATH           =
CLASS_GRAPH            = YES
COLLABORATION_GRAPH    = YES
GROUP_GRAPHS           = YES
UML_LOOK               = NO
UML_LIMIT_NUM_FIELDS   = 10
TEMPLATE_RELATIONS     = NO
INCLUDE_GRAPH          = YES
INCLUDED_BY_GRAPH      = YES
CALL_GRAPH             = NO
CALLER_GRAPH           = NO
GRAPHICAL_HIERARCHY    = YES
DIRECTORY_GRAPH        = YES
DOT_IMAGE_FORMAT       = svg
INTERACTIVE_SVG        = NO
DOT_PATH               =
DOTFILE_DIRS           =
MSCFILE_DIRS           =
DIAFILE_DIRS           =
PLANTUML_JAR_PATH      =
PLANTUML_CFG_FILE      =
PLANTUML_INCLUDE_PATH  =
DOT_GRAPH_MAX_NODES    = 50
MAX_DOT_GRAPH_DEPTH    = 0
DOT_TRANSPARENT        = NO
DOT_MULTI_TARGETS      = NO
GENERATE_LEGEND        = YES
DOT_CLEANUP            = YES
```

</p>
</details> 

Software version:
1.8.20-1 (4.4 MiB 16.5 MiB)

Operating system:
Linux 5.9.13-arch1-1
x86_64 GNU / Linux

**Comment by albert-github** [comment] 2020-12-13 09:36
I tried it on Windows (FireFox, Chrome, Edge) and here everything looks OK.

![tree](https://user-images.githubusercontent.com/5223533/102007495-e2071300-3d29-11eb-81bf-40185d4bb7af.png)

- Which browser are you using?
- A thing that is strange is that you use `STRIP_FROM_PATH        = include src` but still I see the `include` in the tree. I only got the `include` again by disabling the `STRIP_FROM_PATH`
- Another strange thing is the form of the pointers in front of "Classes"
- I used the following project: [example.tar.gz](https://github.com/doxygen/doxygen/files/5684380/example.tar.gz)

Please try my example as well,. In case the problem persists please attach the problem plus the HTML output (in a tar or zip) so we can inspect results? Please don't add external links as they might not be persistent.

**Comment by piratkin** [comment] 2020-12-13 14:59
The project `example.tar.gz` is displayed fine, but if I add one file from my project, the same error occurs:

![x202a_1](https://user-images.githubusercontent.com/14215246/102015369-506cc500-3d6c-11eb-80b2-307d7e4ffaea.png)

I do not understand what the problem is, my text editor says that everything is fine with the encoding (`utf-8`).

[example2.tar.gz](https://github.com/doxygen/doxygen/files/5684763/example2.tar.gz)

Maybe a bug occurs as a result of the presence or absence of a BOM, unfortunately I did not check it.

**Comment by albert-github** [comment] 2020-12-13 16:42
The problem look like to be introduced with version 1.8.15 and looks like to have to do with the fact that there is no documentation that is picked up by doxygen (Same happens even with a completely empty file, e.g. touch afx3.h).

**Comment by piratkin** [comment] 2020-12-13 22:13
Found some way if set:
```ini
EXTRACT_ALL = YES
```
in this case, this bug does not appear

**Comment by albert-github** [comment] 2020-12-14 10:18
Interesting observation and good that you found a workaround, though we still have here a problem in doxygen and as such the issue should remain open till a fix has been added to an official release.

**Comment by albert-github** [comment] 2020-12-14 12:11
I've just pushed a proposed patch, pull request #8249

**Comment by albert-github** [comment] 2020-12-15 09:23
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment] 2020-12-27 19:16
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2020-12-27 19:16 UTC
Labels: bug

**Comment by GeDe-DE** [comment] 2021-04-17 08:47
Hi,

I had the similar problem documenting my Fortran project. I was not able to include images in my documentation. So I had a look at the generated html-code. In index.html I found that doxygen had generated for each pathname the code "&#x202A" (for example: <p><img src="**&#x202A**;MVP-direkt.png" alt="caption11" title="title 1" class="inline"/></p>). So [the](url) browser was not able to locate the image file.

 &#x202A is in PHP the command for "left-to-right embedding". I remembered that in doxygen there is a possibility in the OUTPUT_TEXT_DIRECTION parameter (in topics Project) to choose between -none, LTR, RTL, context -. In my case this parameter had the value -LTR-. I changed the parameter to -none- and the problems including images disappeared.

**Comment by albert-github** [comment] 2021-04-17 09:07
- which version of doxygen are you using
- Note: the setting `OUTPUT_TEXT_DIRECTION` exists in the released version but will be removed in the next version as it was not maintained and probably incomplete, furthermore without knowledge languages that use the RTL way of writing it is not possible to test it.
- Interesting would be to have a small project, so can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by GeDe-DE** [comment] 2021-04-17 09:52
- I use doxygen 1.9.1
   - O.K.
   - A small project is included. The project file is named doxyfile. If
   you change OIUTPUT_TEXT_DIRECTIOn to -none- everything works fine. In case
   of -LTR- there are included a lot of &#x202A in the html-output as you can
   see in generated index.html.




Am Sa., 17. Apr. 2021 um 11:07 Uhr schrieb albert-github <
***@***.***>:

**Comment by albert-github** [comment] 2021-04-17 09:58
>  A small project is included. 

Unfortunately I don't see the included project (did you use the reply from your email as in the past I've heard of problems with attachments when using email replies, it apparently only works in the GitHub website).

**Comment by GeDe-DE** [comment] 2021-04-17 10:13
So I try once again ...
[Github.zip](https://github.com/doxygen/doxygen/files/6329016/Github.zip)

**Comment by albert-github** [comment] 2021-04-17 10:36
Thanks got the file.

The difference I see with the version with LTR and the version with NONE is that the image "error.jpg" is shown with the NONE version but is not shown with the LTR version on the index.html page. Looking at the html code the difference in this respect is:
```
70,71c70,71
< <p class="DocNodeLTR">The following image shows a part of the index.html from an other project.</p>
< <p class="DocNodeLTR"><img src="&#x202A;error.jpg" alt="" class="inline" title="caption1"/> </p>
---
> <p>The following image shows a part of the index.html from an other project.</p>
> <p><img src="error.jpg" alt="" class="inline" title="caption1"/> </p>
```

where the real problem is the `&#x202A;` in the `src="&#x202A;error.jpg"`, this is one of the problems as indicated in my earlier comment.

This is indeed a bug in the 1.9.1 version, but this is solved in the master version (as OUTPUT_TEXT_DIRECTION is not supported anymore). For the German language it doesn't make sense to set the LTR direction, this is the default direction anyway (just not explicitly set).
