### ISSUE TITLE
Python docstring parsed incorrect

### ISSUE THREAD

**Issue by joo0ne** [doxygen/doxygen#10191] opened 2023-07-21 18:12 UTC
**Describe the bug**
I was trying to process the sources of the pandas library.
doxygen found the substring "class maxspeed" in the example, in the method description and interpreted it as a class.

**Expected behavior**
Correctly read the description of the method.

**Screenshots**
1. Classes list
![изображение](https://github.com/doxygen/doxygen/assets/32714006/6dfca17b-496a-49f1-ac98-7ad36e483a6a)

2. Source of one of "maxspeed" class with selected subject
![изображение](https://github.com/doxygen/doxygen/assets/32714006/6f4fd0ed-1b84-4071-8c93-05621b367307)

I'm attaching the config just in case.
[Doxyfile.gz](https://github.com/doxygen/doxygen/files/12131328/Doxyfile.gz)

**To Reproduce**
Parse pandas source. 

**Version**
`doxygen --version
1.9.4`

`lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux trixie/sid
Release:	n/a
Codename:	trixie`

binary that comes with the distribution.

**Comment by albert-github** [comment] 2023-07-21 19:47
Images are good for indicating some problems etc. but are not suitable for showing code to reproduce a problem, so 
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by joo0ne** [comment] 2023-07-21 20:05
Here is a sample code from pandas.
[frame.py.gz](https://github.com/doxygen/doxygen/files/12134334/frame.py.gz)

Settings are already attached in the start message.

**Comment by albert-github** [comment] 2023-07-22 07:57
I ran the problem with doxygen 1.9.4 and saw on the hierarchy.html page:
![image](https://github.com/doxygen/doxygen/assets/5223533/daee46df-fe49-413e-bb7a-c90265962783)

Running the same problem with the current doxygen version (1.9.7) I get:
![image](https://github.com/doxygen/doxygen/assets/5223533/99d9fc62-adfb-4e45-94e5-30182a3283b4)


So it looks like the problem is solved and you should upgrade your doxygen version or did I look at the wrong place?

**Comment by joo0ne** [comment] 2023-07-22 08:50
The problem is that there is no such class "max_speed". Doxygen takes this name from the docstring.
If you follow the link and find the "Detailed description" section, there will be a link to the source code. And this link leads inside the description line, where an example is given with "class max_speed" sequence. But this is not even a class definition, but just a list of dataset field names.

**Comment by albert-github** [comment] 2023-07-22 09:20
I see the problem you indicated, but the file `frame.py` is a bit large (12030 lines) so it will take a while. We also see class names like `a`, `and`,  `an` so it looks a bit like there is somewhere a construct in the python file that is incorrect or not understood by doxygen.

**Comment by joo0ne** [comment] 2023-07-22 09:44
I reduced the size of the file on which the error is reproduced
[frame.py.gz](https://github.com/doxygen/doxygen/files/12136108/frame.py.gz)

**Comment by albert-github** [comment] 2023-07-22 09:55
Thanks, I also was able to reduce the file a bit (to 61 lines) but I see that your file contains also the same info as mine.
Looks a bit like the line
```
>>> df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
```
is problematic or better said the closing round bracket (`)`) when used in the comment in a "attribute" (`@...`), I'll dive into the code ...

**Comment by albert-github** [comment] 2023-07-22 10:53
I think I found the real problem, doxygen does not like comment sections inside "decorators" (i.e. the rule at line 370 in pyscanner.l, `"@"{SCOPE}{CALL}?` is a bit greedy).

**Comment by albert-github** [comment] 2023-07-22 13:14
I've just pushed a proposed patch, pull request #10192

**Comment by joo0ne** [comment] 2023-07-22 15:52
Thank you. Looks like the patch fixes it.

**Comment by albert-github** [comment] 2023-07-23 07:43
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment] 2023-08-25 13:51
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.8.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2023-08-25 13:51 UTC
Labels: bug, Python
