### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by dpergarc** [doxygen/doxygen#10564] opened 2024-01-17 09:10 UTC
Hi all,

I am currently in charge of projects which are develop in C, C++, C#, Java, Python and Kotlin languages (there are some exceptions, but it is not the general rule). Besides, I have automation tools in Gitlab/Github (CI/CD) in order to generate all the documentation using doxygen (both website and PDF), which is quite useful.

This procedure is working perfectly for all projects but except from Koltin, where I have to use dokka instead of doxygen. I would like to know if there is a chance of having kotlin support in the nearby future, so as I can study a migration in order to standardize the pipeline in one unique process.

Thanks beforehand, sorry for the inconveniences and looking forward to hearing from you.

Kind regards.
Daniel.

**Comment by albert-github** [comment] 2024-01-17 09:20
I think the status is still the same as the status mentioned in #6629 and I have no knowledge of Kotlin.
Maybe something is possible by writing a filter that transfers the Kotlin code to a language that doxygen does understand (though resulting documentation might be poor).

I think this issue is a duplicate of #6629

**Comment by dpergarc** [comment] 2024-01-18 11:33
Hi albert,

Oh, my bad, sorry! I did not notice it. 

Anyway, it seems to be a very old post (2018) with almost two years from the last reply... therefore, it is highly likely there is no intention to integrate this language in the nearby future.

What you suggests is viable, but I guess I will keep using dokka for the time being, since I would need time to develop the "translator" program, and at this moment, it will not be possible.

Thanks for the feedback.

Kind regards.
Daniel.

**Closed** 2024-05-20 10:03 UTC
Labels: duplicate, enhancement
