### ISSUE TITLE
Generating chm file in 1.8.16 fails

### ISSUE THREAD

**Issue by dconnet** [doxygen/doxygen#7225] opened 2019-08-24 20:12 UTC
v1.8.15 previously worked.
- https://github.com/dconnet/AgilityBook
- With the .dox file, I simply run "doxygen AgilityBook.dox" from the main directory on Windows 10 (in a cmd shell)
- Doxygen, hhc, and graphwiz are all in my PATH

The generated hhc file is pretty much blank (basic frame, no content)

If I reinstall 1.8.15, everything once again works.

**Comment by albert-github** [comment] 2019-08-25 08:51
The problem is caused by an empty `FILE_PATTERNS` setting, this should automatically be filled by all doxygen known extensions but is in 1.8.16 not the case.
The problem has been noted  as #7190 and been fixed in master by #7193 
Workaround for 1.8.16 is to list the required / all extensions (note extension .txt and .doc are not mentioned in the list, but probably for you of no relevance, certainly the .doc not as these are in you case Word documents).

So it think the problem is a duplicate and fixed but not released.

**Comment by doxygen** [comment] 2019-12-28 10:54
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2019-12-28 10:54 UTC
Labels: bug, duplicate
