### ISSUE TITLE
mismatch between page title in sqlite3 and other (at least XML) outputs at 1.8.16+

### ISSUE THREAD

**Issue by abathur** [doxygen/doxygen#7746] opened 2020-05-02 17:47 UTC
**Additional context**
It may help to have context first: I've found time between projects to update/package/release a Python API I wrote to leverage (and test) the improvements I contributed to sqlite3gen back in #6482 (released in 1.8.15) and noticed a new break (in my module's tests) when using 1.8.16+. 

Its test suite runs Doxygen on the files in doxygen/examples and validates some entities in the database against the XML output for the same entity.

**Describe the bug**
I'm not sure if this is the only manifestation of the issue, but I identified it when a query for the page `mypage1` defined in `examples/group.cpp` found no result. Here's what the XML looks like in this test set:
```xml
<!-- xml/group__group5_mypage1.xml -->
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.17">
  <compounddef id="group__group5_mypage1" kind="page">
    <compoundname>mypage1</compoundname>
    <title>This is a section in group 5</title>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
<para>Text of the first section </para>
    </detaileddescription>
  </compounddef>
</doxygen>

<!-- /xml/group__group5_mypage2.xml -->
<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.17">
  <compounddef id="group__group5_mypage2" kind="page">
    <compoundname>mypage2</compoundname>
    <title>This is another section in group 5</title>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
<para>Text of the second section </para>
    </detaileddescription>
  </compounddef>
</doxygen>
```

In the database, these pages look like:
```
sqlite> select * from def where kind='page' and name like '%mypage%';
rowid       refid                  kind        name        summary                     
----------  ---------------------  ----------  ----------  ----------------------------
228         group__group5_mypage1  page        mypage0     This is a section in group 5
229         group__group5_mypage2  page        mypage@     This is another section in g
```
The refids are correct, but the names are not.

**Expected behavior**
The names set as `mypage0` and `mypage@` should instead be `mypage1` and `mypage2`.

**To Reproduce**
Git bisect identified 960bae7191faf07f142b1ae5b0038905d33e2b1f as the source. I'm using Nix for these builds; I'm not sure if you have it installed, so I went ahead and set up good/bad CI runs for reference.

- The [bad run](https://travis-ci.org/github/abathur/doxygen/builds/682340018) is built from my branch https://github.com/abathur/doxygen/tree/960bae71 and based based on the bisect-identified Doxygen commit 960bae7191faf07f142b1ae5b0038905d33e2b1f.
- The [good run](https://travis-ci.org/github/abathur/doxygen/builds/682339902) is built from my branch https://github.com/abathur/doxygen/tree/79ace061 and based based on the parent Doxygen commit 79ace06168f1e09fce00515248d83571302a67ae.

If you do have Nix, you should be able to check out these branches locally and run `nix-build` from the doxygen root. If you use `nix-build --keep-failed`, Nix will keep the build directory and print its path on the 3rd-to-last line (e.g. `note: keeping build directory '...'`) of the build output. As long as it got far enough, the build directory will contain the output `xml/` and `doxygen_sqlite3.db`.

The Doxygen configuration in [examples.conf](https://github.com/abathur/doxygen/blob/960bae71/examples.conf) should be the same across both branches.

The bisect and CI test scripts simplify to something like (here's the actual [CI test shell script](https://github.com/abathur/doxygen/blob/960bae71/default.nix#L12) in default.nix):

```bash
doxygen examples.conf
# show that the name is right in XML
head -n 20 xml/group__group5_mypage1.xml
# test whether it's right in sqlite3 db
sqlite3 doxygen_sqlite3.db "select name from def where kind='page' and name='mypage1'" | grep mypage1
```

FWIW, I tried to skim the identified commit for a cause, but it's a monster, and my Doxygen contributions account for most of my c++ experience. The refactor may also just be exposing a latent issue in sqlite3gen.

**Comment by albert-github** [comment] 2020-05-03 11:54
I took the 1.8.15, 1.8.16. 1.8.17 and 1.8.18 versions of doxygen, the config file as shown in this issue as well as the file group.cpp from the examples directory.

Running 1.8.15 and 1.8.17 or1.8.18 versions the results look quite similar to me.
The results between 1.8.15 and 1.8.16 are quite different (by head I think 1.8.16 had some problems with an empty list of FILE_PATTERNS).

- For Cygwin I don't always build the executable with sqlite3 (or keep the executable and for Windows I never did build with sqlite3 either). When building the master with sqlite3 and executing the given sqlite3 plus grep on it it outputs: "mypage1", is this expected or should theer be more?

- You wrote that the problems are in 1.8.16+ and give the results for 1.8.17. How would the version for 1.8.15 look like and what are you missing in the 1.8.17 file compared to the 1.8.15 version?
- I don't see any setting

**Comment by abathur** [comment] 2020-05-03 18:43
> * For Cygwin I don't always build the executable with sqlite3 (or keep the executable and for Windows I never did build with sqlite3 either). When building the master with sqlite3 and executing the given sqlite3 plus grep on it it outputs: "mypage1", is this expected or should theer be more?

"mypage1" is correct. I've added a new linux CI build based on master that still exhibits the issue (linked at the end of this post).

> * You wrote that the problems are in 1.8.16+ 

In case the extra detail helps: I said 1.8.16+ because `Release_1_8_16` is the first tagged release GitHub indicates that the bisect-identified commit is part of. I actually get a compile failure (local and on CI) for tag `Release_1_8_16` itself. I have not tried to debug it, since 1.8.17 and 1.8.18 both compile, and still show the same behavior as the bisect-identified commit. I can't _swear_ the behavior is present in 1.8.16; I'm just assuming it is.

> and give the results for 1.8.17. 

I just provided the XML as a reference to show the XML appears to be correct, so I pulled it from an arbitrary build. The XML for the 2 pages I included is roughly the same for all of the compiling versions I've tried. I knocked the Doxygen version numbers out to diff them, and the only difference I see is that the paragraph inside the briefdescription is present at `79ace061 ` and `960bae71` but missing at `Release_1_8_17` and `Release_1_8_18`. (I'm not sure if this change in the XML is intentional/correct or not, but I don't think it's related to this issue). Here's a diff:

```diff
--- 960bae71
+++ 1_8_17
@@ -1,12 +1,11 @@
 ==> xml/group__group5_mypage1.xml <==
 <?xml version='1.0' encoding='UTF-8' standalone='no'?>
-<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.16">
+<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.17">
   <compounddef id="group__group5_mypage1" kind="page">
     <compoundname>mypage1</compoundname>
     <title>This is a section in group 5</title>
     <briefdescription>
-<para>Text of the first section. </para>
     </briefdescription>
     <detaileddescription>
 <para>Text of the first section </para>
@@ -16,12 +15,11 @@
 
 ==> xml/group__group5_mypage2.xml <==
 <?xml version='1.0' encoding='UTF-8' standalone='no'?>
-<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.16">
+<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.17">
   <compounddef id="group__group5_mypage2" kind="page">
     <compoundname>mypage2</compoundname>
     <title>This is another section in group 5</title>
     <briefdescription>
-<para>Text of the second section. </para>
     </briefdescription>
     <detaileddescription>
 <para>Text of the second section </para>
```

> How would the version for 1.8.15 look like and what are you missing in the 1.8.17 file compared to the 1.8.15 version?

I updated the test script to add more output. It now also outputs index.xml, and the rowid, kind, refid, and name for everything in SQL). For reference, it runs:

    # show the XML
    head -n -0 xml/index.xml xml/group__group5_*.xml

    # show the sql
    sqlite3 doxygen_sqlite3.db -column -header ".width 5 5 0 40" "select rowid, kind, refid, name from def"

I re-ran the existing CI runs with this script, and added new builds based on versions 1.8.15-1.8.18 (though, as mentioned previously, 1.8.16 failed to compile), and a current-ish master (I forgot to pull before I did this--it's based on 1708261ebe54b03c45a4bfe3c1e78581779b2a80). 

You can see all of these builds at https://travis-ci.org/github/abathur/doxygen/branches, but here's a link directly to the line SQL output begins on for each build:

- `Release_1_8_15`: https://travis-ci.org/github/abathur/doxygen/builds/682636500#L1643
- `79ace061` (last good per bisect): https://travis-ci.org/github/abathur/doxygen/builds/682636409#L1641
- `960bae71` (first bad per bisect): https://travis-ci.org/github/abathur/doxygen/builds/682636287#L1641
- `Release_1_8_17`: https://travis-ci.org/github/abathur/doxygen/builds/682636599#L1839
- `Release_1_8_18`: https://travis-ci.org/github/abathur/doxygen/builds/682636682#L12630
- `test_master`: https://travis-ci.org/github/abathur/doxygen/builds/682654006#L13276

A few observations from looking over the larger set:
- In the output for `Release_1_8_15` and `79ace061`, the name of each entity is populated (except, for reasons I'm unsure of, the directory entry; but I suspect it's a separate issue). 
- In all of the other builds:
    - Only a few _members_ have names populated at all, but the ones that are do appear to be correct.
    - File compounds appear to have consistent, correctly-populated names. Example compounds may also be correct, but it's hard to know from one sample.
    - It looks like about half of the remaining compound types are blank, and about half have populated names. Some of the populated names are correct, but some have incorrect/junk data.
    - In the Linux CI builds, the *specific* data in the name column appears to be consistent across builds, but I do see slightly different data in the name column on macOS (also consistent across builds).

**Comment by albert-github** [comment] 2020-05-04 13:05
I ran the group example with the versions 1.8.15, 1.8.17 and 1.8.18 all compiled with sqlite support.
I renamed the db files so I could easily reference / use them and I also ran sqlite3 on it with the command:
```
sqlite3 doxygen_sqlite3.db -column -header ".width 5 5 0 40" "select rowid, kind, refid, name from def"
```
and placed the results in `rr_*`.

I don't see any difference between the different `rr_*` files,.

This might come from my (too) simple example, in the later case a complete self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem is very much appreciuated.  Please don't add external links as they might not be persistent.

The results: [results.tar.gz](https://github.com/doxygen/doxygen/files/4574777/results.tar.gz)

**Comment by albert-github** [comment] 2020-05-04 14:57
I'm not sure whether or not this is related but I wanted to see the doxygen version information in the latest master version so that I would have something like:
```
1.8.19 (82cb93c033c83b5a184cd450d86b0f712e0870b3*)
```
so I got the doxygen_version from the meta table and got: `4 2020 16:41:28`
where it should be the doxygen version information.
Looking in the code, I saw the statement:
```
  bindTextParameter(meta_insert,":doxygen_version",getFullVersion());
```
where `getFullVersion()` returns a `QCString` and `bindTextParameter` expects a `char *`. So I replaced it with `getFullVersion().data()` and now the output of the doxygen_version is: `1.8.19 (82cb93c0A`.

A bit strange as the other meta fields also get `QCString` as an input, though might it be that this is a random effect?
Do have `KEY` a limited length?
(in the output from your travis runs I some strange characters as well, maybe this is leading to the cause of the problem).

**Comment by abathur** [comment] 2020-05-04 16:33
> I'm not sure whether or not this is related but I wanted to see the doxygen version information in the latest master version so that I would have something like:
> 
> ```
> 1.8.19 (82cb93c033c83b5a184cd450d86b0f712e0870b3*)
> ```
> 
> so I got the doxygen_version from the meta table and got: `4 2020 16:41:28`
> where it should be the doxygen version information.
> Looking in the code, I saw the statement:
> 
> ```
>   bindTextParameter(meta_insert,":doxygen_version",getFullVersion());
> ```
> 
> where `getFullVersion()` returns a `QCString` and `bindTextParameter` expects a `char *`. So I replaced it with `getFullVersion().data()` and now the output of the doxygen_version is: `1.8.19 (82cb93c0A`.
> 
> A bit strange as the other meta fields also get `QCString` as an input, though might it be that this is a random effect? 
> ...
> (in the output from your travis runs I some strange characters as well, maybe this is leading to the cause of the problem).

I think these are all related; it looks like the same underlying issue (and may be the reason why you aren't seeing the same with a minimal run against just the group example). The partial datetime you got from getFullVersion looks like part of what would normally be in `meta.generated_at`.

When I was authoring the update, I superstitiously added `.data()` calls all over the place to ward off these sorts of issues. 

I don't have a full understanding of what is "correct" here (nor why some fields appear to be stable without these calls but others do not). Since the other generators do not use them much outside of log/debug messages, I went back late in the process and removed any `.data()` calls that appeared to have no affect on the output quality (using a codebase with thousands of files as a test case).

I made a distinct commit with a longer commit message for this because I found this a little confusing, and also kept my un-squashed working branch around in case any issues popped up, so you can see it here: https://github.com/abathur/doxygen/commit/59ad8cafbbd2fb2d9df6c29ca7753dc2ee753614

I suspect my heuristic for which instances "should" have a `.data()` call had implicit dependencies on other code sites, and that the refactor in the bisect-identified bad commit (https://github.com/doxygen/doxygen/commit/960bae7191faf07f142b1ae5b0038905d33e2b1f) shifted which instances "need" a `.data()` call to avoid inserting corrupt data.

Is it "correct" to have these calls *everywhere* a QCString is passed to bindTextParameter? If so, I can audit/update, test to see if it fixes the issue, and PR if it does.

**Comment by albert-github** [comment] 2020-05-04 17:34
I think indeed that a number of problems are hidden in the small example I used (but it looks like the version information gave a good clue).

I think it has to do with how the (text?) values are created and what is done in the routines:
```
bindTextParameter
```
and more precise in:
```
int rv = sqlite3_bind_text(s.stmt, idx, value, -1, _static==TRUE?SQLITE_STATIC:SQLITE_TRANSIENT);
```
From the sqlite3 documentation:
> If the fifth argument has the value SQLITE_TRANSIENT, then SQLite makes its own private copy of the data immediately, before the sqlite3_bind_*() routine returns.

When looking at `getFullVersion()` the result is created locally and given back to the calling routine (so a stack operation that quickly can go out of scope and the location can be overwritten again). The same would accounts for the `dateToString` . When looking at the 2 calls to `dateToString` we see that they have `FALSE` in their calls so a copy has to be made by `bindTextParameter` / `sqlite3_bind_text` but `getFullversion` has (the default) `TRUE`.

A quick test setting:
```
int rv = sqlite3_bind_text(s.stmt, idx, value, -1, SQLITE_TRANSIENT);
```
gave the correct (and full!) version information.

- Why didn't `Config_getString(PROJECT_NAME)` have problems? Well to the best of my knowledge this goes directly back to the variable that stores the value and thus is persistent / static in the sqlite3 sense.
- is `.data()` necessary, no as the conversion should normally occur automatically from `QCString` to `char *`. Does it hurt, no I don't think so.
- Is it an idea to use always `SQLITE_TRANSIENT`? It is a safe way but it requires (a lot?) of extra memory as the data for the data for the database is copied in memory again.
- I don't think the problem might be occur for `sqlite3_bind_int` as the description speaks about string binding interfaces and about the 5th parameter.

**Comment by albert-github** [comment] 2020-05-04 17:49
As a complete side note.

When I tried to regenerate a test, the db didn't change. How could this happen?, in the code we see:
```
  if (stat (outputDirectory+"/doxygen_sqlite3.db", &buf) == 0)
  {
    msg("doxygen_sqlite3.db already exists! aborting sqlite3 output generation!\n");
    msg("If you wish to re-generate the database, remove or archive the existing copy first.\n");
    return NULL;
  }
```

and when running with the setting `QUIET=YES`  these messages are suppressed, so I missed them completely.

Better is to use the `err` routine (or the `term` routine, see `message.cpp`).

**Comment by abathur** [comment] 2020-05-04 20:35
Thanks. I think I follow most of this; I'll look at applying it soon. A few follow-up questions:

> is `.data()` necessary, no as the conversion should normally occur automatically from `QCString` to `char *`. Does it hurt, no I don't think so.

Not sure I get why calling `.data()` seems to fix the same problem, if the conversion should happen automatically? Is it just a coincidence arising from where (in the stack?) the `.data()` call is compared to where the automatic conversion takes place? 

> Is it an idea to use always `SQLITE_TRANSIENT`? It is a safe way but it requires (a lot?) of extra memory as the data for the data for the database is copied in memory again.

At least in the cases where the QCString is converted, bound, and inserted before its data is overwritten, would calling `.data()` on it also result in an extra copy in memory, or is there something more nuanced going on?

If the `.data()` call only fixes this by coincidence and would also result in an extra copy in memory, I assume the most-correct approach is to use `SQLITE_TRANSIENT`?

I'll try to keep an eye on how it impacts memory use, regardless.

**Comment by albert-github** [comment] 2020-05-05 13:28
I don't think the `.data()` solves the problem, it might give the impression it does but it just returns the pointer to the character data and this adheres still to the rules of going out of scope of the underlying data.

I think the easiest way is just to use `SQLITE_TRANSIENT` at the costs of some extra memory usage. It is also the safest as it protects against future changes where some variables might be "local" variables which are now "global".
The extra memory usage should be investigated separately, but the important thing is now to have (as done in #7750) the correct results.

**Closed** 2020-05-09 18:08 UTC
Labels: bug
