### ISSUE TITLE
Parsing error with C++20 requires clause if at the end of the function declaration

### ISSUE THREAD

**Issue by lieser** [doxygen/doxygen#10485] opened 2023-12-15 10:26 UTC
**Describe the bug**
If a C++20 requires clause is at the end of the function declaration it seems to mess up the parsing and leads to strange follow errors.

**Expected behavior**
Doxygen can correctly parse the requires clause.

**To Reproduce**

[doxygen-requires.zip](https://github.com/doxygen/doxygen/files/13684030/doxygen-requires.zip)
(minimal example from https://github.com/randombit/botan/blob/3dcf8af5a77e9e7643cc58cd5498d3950c1470ef/src/lib/rng/rng.h)

```c++
#include <concepts>
#include <span>
#include <type_traits>

/**
* An interface to a cryptographic random number generator
*/
class RandomNumberGenerator {
   public:
      /**
      * Incorporate some additional data into the RNG state.
      */
      template <typename T>
      void add_entropy_T(const T& t)
         requires std::is_standard_layout<T>::value && std::is_trivial<T>::value
      {
         return;
      }

   protected:
      /**
      * Generic interface to provide entropy to a concrete implementation and to
      * fill a given buffer with random output. Both @p output and @p input may
      * be empty and should be ignored in that case. If both buffers are
      * non-empty implementations should typically first apply the @p input data
      * and then generate random data into @p output.
      *
      * This method must be implemented by all RandomNumberGenerator sub-classes.
      *
      * @param output  Byte buffer to write random bytes into. Implementations
      *                should not read from this buffer.
      * @param input   Byte buffer that may contain bytes to be incorporated in
      *                the RNG's internal state. Implementations may choose to
      *                ignore the bytes in this buffer.
      */
      virtual void fill_bytes_with_input(std::span<uint8_t> output, std::span<const uint8_t> input) = 0;
};
```

Results in the error:
```
/mnt/c/work/test/doxygen-requires/test.h:36: warning: Found ';' while parsing initializer list! (doxygen could be confused by a macro call without semicolon)
```

**Version**

Version: 1.9.8 (c2fe5c3e4986974eb2a97608b24086683502f07f)
Platform: Ubuntu 22.04.3 LTS
Binary from https://www.doxygen.nl/download.html

**Additional context**

A workaround is to put the requires clause after the template parameter list, which at least newer versions of doxygen can parse (see also https://github.com/doxygen/doxygen/issues/8980)

**Comment by albert-github** [comment] 2023-12-15 11:22
In most but not all examples in the draft 2023 standard I see that in case of `&&` (or `||`) usage the clause is embedded in round brackets like instead of:
```
requires std::is_standard_layout<T>::value && std::is_trivial<T>::value
```
it is written:
```
requires (std::is_standard_layout<T>::value && std::is_trivial<T>::value)
```
applying the round brackets to the code and running the doxygen 1.9.8 version results also in no warning and, in my opinion, correct documentation.
Still I think it should work without the round brackets.

**Comment by lieser** [comment] 2023-12-15 11:41
Thanks for the fast reply, can confirm that adding brackets helps too.
Note that `&&` and `||` are not the only things causing problems.

E.g. the following has the same problem (from https://github.com/randombit/botan/blob/3dcf8af5a77e9e7643cc58cd5498d3950c1470ef/src/lib/utils/mem_ops.h):
```c++
template <typename T>
inline constexpr void typecast_copy(T& out, const uint8_t in[])
   requires std::is_trivial<typename std::decay<T>::type>::value
{
   // asserts that *in points to the correct amount of memory
   typecast_copy(out, std::span<const uint8_t, sizeof(T)>(in, sizeof(T)));
}
```

**Comment by albert-github** [comment] 2023-12-15 11:45
My impression at the moment, after a quick look in the code, that the problem is the, last, `::` of each expression.

**Comment by albert-github** [comment] 2023-12-15 12:03
I've just pushed a proposed patch, pull request #10486

**Comment by albert-github** [comment] 2023-12-16 10:43
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment] 2023-12-25 11:04
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.10.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2023-12-25 11:04 UTC
Labels: bug, C++20

**Comment by brightprogrammer** [comment] 2024-01-14 08:14
Similar parsing error appears when a field name in a struct is named `requires`.

```c
typedef struct JVM_ModuleAttribute {
    ... other fields

    /**
     * @brief Dependencies Specification in Requires Table.
     *
     * Each entry in the requires table represents a dependence of the current module.
     * Dependencies specified in this table indicate modules that the current module relies on.
     * The `requires` table provides a comprehensive list of dependencies for the module,
     * facilitating a clear understanding of the module's requirements.
     *
     * @sa JVM_ModuleRequiresInfo.
     * @sa JVM_ClassFile.
     */
    JVM_ModuleRequiresInfo* requires;

    ...  other fields
} JVM_ModuleAttribute;
```

This is producing wrong output in both html and latex. The field is completely removed in the list of types, and the type `JVM_ModuleRequiresInfo*` is merged with the type of field appearing directly after this one.

I've tried enabling and disabling the "OPTIMIZE_OUTPUT_FOR_C" feature in "Doxyfile" as well. Nothing changes.

**Comment by brightprogrammer** [comment] 2024-01-14 08:20
> This issue was previously marked 'fixed but not released',
   which means it should be fixed in doxygen version 1.10.0.
   
@doxygen My current installed doxygen version is 1.10.0
> Generated by doxygen 1.10.0

**Comment by albert-github** [comment] 2024-01-14 09:01
In C++ the word `requires` is a keyword (see e.g. https://en.cppreference.com/w/cpp/keyword), though your code is written in C and here `requires` is not a keyword (see e.g. https://en.cppreference.com/w/c/keyword).
The `OPTIMIZE_OUTPUT_FOR_C` setting only has some influence on, some terms in, the generated output.
The doxygen scanner does not distinguish between C++ and C and gears more towards C++, hence the problem.
Complicating factor is also that e.g. `.h` files are used for `C++` as well as for `C`.

I think it is hard / not possible to solve this in doxygen, though best is to create a new issue for this (as the current issue is for the requires clause in C++).

Note the issue was introduced in version 1.9.2
