### ISSUE TITLE
\snippet does not add any code 

### ISSUE THREAD

**Issue by prince-chrismc** [doxygen/doxygen#10517] opened 2023-12-27 17:20 UTC
**Describe the bug**
Describe what you see that (you think) is wrong.

When adding a `\snippet example.cpp marker` to a comment block the code in between those too marks should be added as a code block. Currently there is only an empty code block.

Using `\include` correctly puts the entire file content.

I first tried following the documentation https://www.doxygen.nl/manual/commands.html#cmdsnippet but the marker syntax `\\! [marker]` seems to be out of date? Having found the tests 

https://github.com/doxygen/doxygen/blob/866971154fe08984de39ae45e481c0255967bb8f/testing/049_snippet.cpp#L7
https://github.com/doxygen/doxygen/blob/866971154fe08984de39ae45e481c0255967bb8f/testing/snippet_test.cpp#L11

https://stackoverflow.com/questions/28891967/documenting-code-snippets-with-snippet-in-doxygen#comment-46105666

**Expected behavior**
Describe what you would have expected or think is correct.

There is no example documentation for this feature, so I am not 100% what it should look like

**Screenshots**
If useful, add screenshots to help explain your problem.

## Using `\snippert`

![image](https://github.com/doxygen/doxygen/assets/16867443/283e3950-5816-4fc9-81d6-7536b1c45471)

## Using `\include`

![image](https://github.com/doxygen/doxygen/assets/16867443/2869a6a8-28b3-4abb-86b0-7b9cb9c31c95)

(shorten cotnent from repo)

**To Reproduce**
Attach a self contained example that allows us to reproduce the problem.
Such an example typically exist of some source code (can be dummy code) and a doxygen configuration file used (you can strip it using `doxygen -s -u`). After you verified the example demonstrates the problem, put it in a zip (or tarball) and attach it to the bug report. Try to avoid linking to external sources, since they might disappear in the future.

[bug-report.tgz](https://github.com/doxygen/doxygen/files/13780146/bug-report.tgz)

Contains the follow (with the build output I recieved)

![image](https://github.com/doxygen/doxygen/assets/16867443/33ee5fcb-a190-4f96-82f5-3d6f4800b596)

and can be generate using `doxygen docs/Doxyfile`

**Version**
Mention the version of doxygen used (output of `doxy
gen --version`) and the platform on which you run doxygen (e.g. Windows 10, 64 bit). If you run doxygen under Linux please also mention the name and version of the distribution used (output of `lsb_release -a`) and mention if you compiled doxygen yourself or that you use a binary that comes with the distribution or from the doxygen website.  

doxygen version 1.10.0
Macos 14.2 ARM M2 (installed from brew)

**Stack trace**
If you encounter a crash and can build doxygen from sources yourself with debug info (`-DCMAKE_BUILD_TYPE=Debug`), a stack trace can be very helpful (especially if it is not possible to capture the problem in a small example that can be shared).

**Additional context**

**Comment by albert-github** [comment] 2023-12-27 17:48
There is between the 1.9.8 and 1.10.0 release indeed a difference, that should not happen.
When there are multiple lines it works (I tried with an extra empty line between the markers and also splitting the statement after the `=` sign, but this is just a workaround).

Note you also have:
```
\include example/rsa-verify.cpp input
```
but the `\include` statement doesn't work with markers and the text `input` is written as normal text to the output (but probably just a copy / paste error to generate the example for this issue).

**Comment by prince-chrismc** [comment] 2023-12-27 23:32
> probably just a copy / paste error to generate the example for this issue

Yes you are spot on, I was not expecting that to use just a section. the `\include` was to ensure my paths were correctly being picked up 😄 

***

The work around should be sufficient for my use case, I was just trying a simple one but most of my snippets will be more then one line

**Comment by albert-github** [comment] 2024-04-14 10:26
In respect with the 1.10.0 there have been some changes in the current master version in respect to the snippet handling.
As far as I can tell the problem has been solved (tested with 1.11.0 (eb110639dcc32804b59abdf0dcb343abde211b1e) so it is fixed but not released.
(please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment] 2024-05-20 09:55
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.11.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2024-05-20 09:55 UTC
Labels: bug

**Comment by MarkCallow** [comment] 2024-06-21 10:26
I just updated to 1.11 from 1.9.7 and all our snippets, which all have more than one line and are all `@snippet{doc}` are now being rendered as empty code blocks. If I change to `include` then the whole file is shown so my paths are correct.

This is an example of one of the shorter ones

```
@snippet{doc} ktx/encode_utils_basis.h command options_basis_encoders
```

and the lines from the file

```
/**
//! [command options_basis_encoders]
<dl>
    <dt>
        basis-lz:
    </dt>
    <dd>
        Supercompress the image data with transcodable ETC1S / BasisLZ.
        RED images will become RGB with RED in each component (RRR). RG
        images will have R in the RGB part and G in the alpha part of
        the compressed texture (RRRG). When set, the following BasisLZ-related
        options become valid, otherwise they are ignored.
    </dd>
    <dt>
        uastc:
    </dt>
    <dd>
        Create a texture in high-quality transcodable UASTC format.
    </dd>
</dl>
//! [command options_basis_encoders]
*/
```

It looks like the fix broke something else.

**Comment by albert-github** [comment] 2024-06-21 11:14
With the 1.9.6 version I see:
![image](https://github.com/doxygen/doxygen/assets/5223533/cbbcf574-fbf2-41b8-abc3-3bbc26a33b56)

With the 1.11. version:
![image](https://github.com/doxygen/doxygen/assets/5223533/ec1a51fa-3689-414a-a819-4ae53c4e7e07)


so a bit extra white space.

With the current master (1.12.0 (7673d22af1cea4d84bdc00164d9c9a25d693a714)) I again see:
![image](https://github.com/doxygen/doxygen/assets/5223533/b3f4b946-0cbf-4b14-984c-c2cbf878d45d)

So it is a bit unclear what you mean with:
> It looks like the fix broke something else.

except for a little bit more white space

**Comment by MarkCallow** [comment] 2024-06-21 13:06
Hmm. I am seeing empty code blocks just like the OP. The text you see in the image is the text before the `@snippet` command.

<img width="2109" alt="Screenshot 2024-06-21 at 22 00 02" src="https://github.com/doxygen/doxygen/assets/2244683/0fdf19c2-b097-4558-989a-4d450bc91fd8">

That is what I mean by "broke something else".

I will have to try to create a minimal reproducer. @albert-github please post here the files you used to create the images you posted. Maybe I can spot something different in what you have done and what we are doing.

**Comment by albert-github** [comment] 2024-06-21 13:13
The attached example is what I used:

**Comment by MarkCallow** [comment] 2024-06-21 14:05
If you add the line

```
/// @page Foo foo
```

to `aa.h` before the `@snippet` line, the snippet contents are not shown in the output.

**Comment by MarkCallow** [comment] 2024-06-21 14:07
Should I create a new issue or do you want to reopen this one?

**Comment by albert-github** [comment] 2024-06-21 14:21
Even with the line you wrote in https://github.com/doxygen/doxygen/issues/10517#issuecomment-2182823608 I cannot reproduce the problem with the 1.11.0 version, so:
- Can you please attach a, small, **self contained example (source+configuration file in a, compressed, tar or zip file!)** that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).

I´n not sure whether this is a new issue ar that there is already an issue that is looking into this issue(I have an issue in mind).

**Comment by MarkCallow** [comment] 2024-06-22 06:44
> Even with the line you wrote in https://github.com/doxygen/doxygen/issues/10517#issuecomment-2182823608 I cannot reproduce the problem with the 1.11.0 version

Sorry about that. The line I wrote moved the info from the page for file `aa.h` to a new Related Page "Foo". I looked only at the `aa.h` page and found it empty. Indeed the info is still there but in "Foo".

Here is a reproducer: [missing-snippets.tar.gz](https://github.com/user-attachments/files/15935622/missing-snippets.tar.gz). After running Doxygen, open `html/index.html` and navigate to the "ktx create" page. You will see lots of empty snippets. Sources for all are included in the reproducer.

**Comment by albert-github** [comment] 2024-06-22 07:40
Thanks for the example, with this I can reproduce the problem (and it is still present in the current master, 1.12.0 (7673d22af1cea4d84bdc00164d9c9a25d693a714), the problem is still visible.

Running with `doxygen -d commentcnv` reveals that the `\snippet{doc}`is not translated:

```
@section ktx\_create\_options OPTIONS
  @subsection ktx\_create\_options\_general General Options
    The following are available:
    <dl>
        <dt>\--format &lt;enum&gt;</dt>
        <dd>KTX format enum that specifies the data format of the images in the created texture.
            The enum names are matching the VkFormats without the VK_FORMAT_ prefix.
            The VK_FORMAT_ prefix is ignored if present. Case insensitive. Required.</dd>
        <dd>If the format is an ASTC format a texture object with the target format
            @c R8G8B8_{SRGB,UNORM} or  @c R8G8B8A8_{SRGB,UNORM} is created
            then encoded to the specified ASTC format. The latter format is chosen if alpha
            is present in the input. @c SRGB or @c UNORM is chosen depending on the
            specified ASTC format. The ASTC-specific and common encoder options listed
            @ref ktx_create_options_encoding "below" become valid, otherwise they are ignored.
            <!--This matches the functionality of the @ref ktx_encode "ktx encode" command
            when an ASTC format is specified.<br /> --></dd>
        <dd>When used with @b \--encode it specifies the target format before the encoding step.
            In this case it must be one of:
            <ul>
                <li>R8_UNORM</li>
                <li>R8_SRGB</li>
                <li>R8G8_UNORM</li>
                <li>R8G8_SRGB</li>
                <li>R8G8B8_UNORM</li>
                <li>R8G8B8_SRGB</li>
                <li>R8G8B8A8_UNORM</li>
                <li>R8G8B8A8_SRGB</li>
            </ul></dd>
        <dd>The format will be used to verify and load all input files into a texture before
            performing any specified encoding.
        </dd>
        <dt>\--encode basis-lz | uastc</dt>
        <dd>Encode the texture with the specified codec before saving it.
            This option matches the functionality of the ktx_encode "ktx encode" command.
            With each choice, the specific and common encoder options listed
            @ref ktx_create_options_encoding "below"  become valid, otherwise they
            are ignored. Case-insensitive.

            @snippet{doc} ktx/encode_utils_basis.h command options_basis_encoders
        <dt>\--1d</dt>
```

I think this is indeed a new issue so best is to file a new issue for it.

**Comment by MarkCallow** [comment] 2024-06-22 08:09
> reveals that the \snippet{doc}is not translated:

I don't understand what this means. Anyway I'll open a new issue.

**Comment by albert-github** [comment] 2024-06-22 08:57
Thanks for the new issue.
> I don't understand what this means

That is understandable but it was meant for other developers a a first indication of what might be wrong-
