### ISSUE TITLE
No output when run doxygen in high level directory

### ISSUE THREAD

**Issue by ramseyxu** [doxygen/doxygen#9500] opened 2022-08-11 06:43 UTC
**Describe the bug**
I have generated a config and set EXTRACT_ALL = YES

I run "doxygen Doxyfile" in the code path, command successfully, and output directory is created with content(index.html, etc). 
No substantial content in it.

doxygen works well when generating a document in a low-level directory with cpp files.
But in high-level project directory, doxygen doesn't works.

**Expected behavior**
Document in the output directory

**Screenshots**
<img width="937" alt="image" src="https://user-images.githubusercontent.com/4744175/184077428-3174f17d-12e2-435a-9827-2bf9aa365f53.png">
<img width="318" alt="image" src="https://user-images.githubusercontent.com/4744175/184077550-6310833a-4df8-4f4f-ab0a-220da2f904e3.png">

**To Reproduce**
Use default Doxyfile with EXTRACT_ALL = YES, and indicate am output path
put the Doxyfile in Clickhouse/src  (https://github.com/ClickHouse/ClickHouse)
run "doxygen Doxyfile"

**Version**
1.9.3

**Comment by ramseyxu** [comment] 2022-08-11 07:16
Set parameter RECURSIVE = YES can solve this issue.

Maybe can add a warning for this scenario?

**Comment by albert-github** [comment] 2022-08-12 15:58
The problem with a  warning here would be that in that case runs with e.g. `WARN_AS_ERROR=YES` or `WARN_AS_ERROR=FAIL_ON_WARNINGS` would fail. 

I think the problem is usage.

**Comment by ramseyxu** [comment] 2022-08-15 06:48
For a beginner, the most intuitive usage is to generate a default config, put it in the project's root path, and run `doxygen Doxyfile`.

In this scenario, no warning or error leads me to set RECURSIVE = YES
I struggled for half day to find the right usage.
It's not reasonable for a beginner to understand every parameter.

My suggestion is to throw a warning when no single class has been parsed, instead of finishing successfully

**Comment by albert-github** [comment] 2022-08-15 07:26
A project with only markdown files does not have any classes.

**Comment by doxygen** [comment] 2022-08-15 07:30
I think the check should be if no input files have been found that need to be parsed during the "Parsing files" step. If so then doxygen could stop early with an error/warning.

**Comment by albert-github** [comment] 2022-08-15 10:18
I've just pushed a proposed patch, pull request #9512

**Comment by albert-github** [comment] 2022-08-15 11:13
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment] 2022-08-26 16:54
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.5.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2022-08-26 16:54 UTC
Labels: enhancement
