### ISSUE TITLE
pdflatex: File namespaces.tex not found

### ISSUE THREAD

**Issue by braggpeaks** [doxygen/doxygen#6391] opened 2018-07-12 06:59 UTC
When running make.bat, I run into the following error:

`! LaTeX Error: File 'namespaces.tex' not found.`

This has obviously been introduced with 1.8.14, as 1.8.12 still works with the same setup.
Running on most current Windows 10 with most current MikTeX packages.

**Comment by albert-github** [comment] 2018-07-12 08:38
To the best of my knowledge this problem has been solved , but due to a missing, small, example it is hard to test. So can you please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem?

**Comment by braggpeaks** [comment] 2018-07-12 14:37
I was not able to reproduce with a minimal example. I will try with the next release and keep you updated, ok?

**Comment by albert-github** [comment] 2018-07-12 14:40
OK. You can test it by getting the current source code from github, compile it and run it and see it is fixed or not.

 In the mean time I'll set the problem to being solved in the next version.

**Comment by braggpeaks** [comment] 2018-07-12 18:29
The error can be cleared and the output is still fine, so it is not a major issue (at least for me) - I am not sure what the implications are. I will update the thread as soon as I tested with the new release.

**Comment by FordMustangTeled** [comment] 2018-07-26 15:36
On a RHEL 7.5 64bit workstation with the doxygen-1.8.5-3.el7 package install, I see the "! LaTeX Error: File `namespaces.tex' not found. "  That's the latest package as of July 26, 2018.  I can't find the generated file on RHEL 6.8 64bit workstations.  Could this be a similar issue that had been previously solved as stated above, or a RHEL 7.5 config issue with texlive 2013 el7 package or some other el7 package.   RHEL 7.5 machine gets subscription updates.

[1{/usr/share/texlive/texmf/fonts/map/pdftex/updmap/pdftex.map}] [2] [3]
[4]
Chapter 1.

! LaTeX Error: File `namespaces.tex' not found.

**Comment by albert-github** [comment] 2018-07-26 15:56
This is probably the same issue as stated above.

The version 1.8.5 is quite old (release date 23-08-2013), but this is, unfortunately, not uncommon with Red Hat. The current doxygen version is 1.8.14 (but still has the problem).
Also the TexLive version (the 2013 version) is quite old, the current version is version 2018 (but this is unrelated to the problem you see).

As shown with the labels, the problem has been fixed for the upcoming release (no date known yet).

At the moment there are some possibilities that I see:
 - do a touch on 'namespaces.tex' and hope that the build comes through (maybe with a page with just a header); NOT tested and NOT an advised solution.  
  - create a private version of the latex header file (doxygen -w latex headerFile footerFile styleSheetFile) in which the input line for namespaces.tex will be commented out as well as the chapter command just above it (don't forget to set `LATEX_HEADER` in the doxygen configuration Doxyfile)
  - clone the current version of the repository and build the executable yourself.

**Comment by FordMustangTeled** [comment] 2018-07-26 16:49
Thank you for the update about the upcoming release info with a TBD release date.   The pdf does get generated on RHEL 7.5 with version 1.8.5 that contains header, body and footer information, but where should the generated namespace.tex file be located on the RHEL7.5 workstation.  I searched the RHEL7 packages/system, and other RHEL6 machines, too.  
Thank you for the quick response, and I'll try the other possibilities.

**Comment by albert-github** [comment] 2018-07-26 16:53
On its regular place in the 'latex' directory (note it is namespace**s**.tex)

**Comment by FordMustangTeled** [comment] 2018-07-26 16:54
I had a typo.  Thanks.

**Comment by doxygen** [comment] 2018-12-28 09:45
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2018-12-28 09:45 UTC
Labels: LaTeX
