### ISSUE TITLE
Java: Issue if a method is called ``requires``

### ISSUE THREAD

**Issue by Stewori** [doxygen/doxygen#8883] opened 2021-11-08 20:21 UTC
**Describe the bug**
Processing Java code
```
public class Test {
    public int requires() {
        return 0;
    }
}
```
results in the following xml snippet:
```
  <memberdef kind="variable" id="classTest_1aaaa29ac04931d61af626f2b79fa5f771" prot="public" static="no" mutable="no">
    <type></type>
    <definition>Test.int</definition>
    <argsstring></argsstring>
    <name>int</name>
    <initializer>{
    return 0</initializer>
    <briefdescription>
    </briefdescription>
    ...
  </memberdef>
```
Doxygen does not recognize it as a method but sets ``kind="variable"``. Somehow it is confused by the name ``requires``. Also note the wrong name, missing type and the strange "initializer". If the method body is more populated things get even stranger.
If I simply declare ``public void requires() {}`` the method is not recognized as a member at all, not even as a variable.

**Expected behavior**
I expect that the resulting code snippet would be
```
<memberdef kind="function" id="classTest_1aaaa29ac04931d61af626f2b79fa5f771" prot="public" static="no" const="no" explicit="no" inline="yes" virt="non-virtual">
    <type>int</type>
    <definition>int Test.requires</definition>
    <argsstring>()</argsstring>
    <name>requires</name>
    <briefdescription>
    </briefdescription>
    ...
  </memberdef>
```

**To Reproduce**
Find a Java file and doxygen config attached. The issue is demonstrated like mentioned above.
After running doxygen on the example, the files in the subfolder ``xml`` contain the snippet shown above.
[issue_Java_requires.zip](https://github.com/doxygen/doxygen/files/7499866/issue_Java_requires.zip)

**Version**
Tested with doxygen clone from 2021-11-08:
```
/blah/doxygen/build/bin/doxygen -v
1.9.3 (096a1c10e1e0b86edc8c561f49b5fd7881776ba7)
```

`lsb_release -a`:
```
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	LinuxMint
Description:	Linux Mint 18 Sarah
Release:	18
Codename:	sarah
```

**Additional context**
TBH I did not check for duplicates. Please excuse if this is a known issue.

**Comment by Stewori** [comment] 2021-11-09 11:47
Maybe related to #8726 (however no duplicate since #8726 is marked as "fixed but not released" and I used a very recent clone). I suspect, in a way Doxygen misconcepts the method name as a ``requires`` clause. Is parsing of such clauses not sufficiently guarded as C++-only?

**Comment by albert-github** [comment] 2021-11-09 12:54
This is a duplicate of the issue #8882 (it has the same root cause).

**Closed** 2021-12-31 11:09 UTC
Labels: bug, duplicate, Java
