### ISSUE TITLE
Correct typedef is documented as a variable

### ISSUE THREAD

**Issue by eepp** [doxygen/doxygen#7306] opened 2019-10-09 16:49 UTC
Doxygen 1.8.16, with a C file, documents this typedef as a variable:

    typedef const uint8_t *bt_uuid;

However, it documents this one (equivalent) as a typedef:

    typedef uint8_t const *bt_uuid;

Ironically, in the generated HTML documentation, the latter shows like this:

    typedef const uint8_t * bt_uuid

**Comment by albert-github** [comment] 2019-10-09 17:32
I see some differences as well, but I don't see the `<space>`. To be 100% sure we are talking about the same:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by eepp** [comment] 2019-10-09 18:06
> * Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

Sure.

`Doxyfile`:

```
INPUT = test.h
```

`test.h`:

```c
/*!
@file
*/

/*!
@brief Is this a typedef?
*/
typedef const int *hello;

/*!
@brief And this?
*/
typedef int const *meow;
```

Look at the HTML result in the documentation of `test.h`:

![](http://ss.0x3b.org/dreich319.png)

**Comment by eepp** [comment] 2019-10-10 13:29
I don't get which problem you saw with "<space>"?

**Comment by albert-github** [comment] 2019-10-10 13:32
In the last line in your original question I see a space between the `*` and `bt_uuid`:

    typedef const uint8_t * bt_uuid

**Comment by eepp** [comment] 2019-10-10 13:36
That was just my way of showing how Doxygen renders this in HTML (space indicates a different table column).

That's not an issue at all.

I only wanted to point out that by putting "const" after the type, Doxygen parses it as a typedef, but then it renders it in the order I'd like it to be parsed in the first place, hence the irony.

**Comment by tomaskrizek** [comment] 2020-04-14 13:08
This issue becomes even more painful when attempting to use breathe with Sphinx version 3+, since having keywords (such as `typedef`) in the variable definition results in the following warning:
```
Invalid C declaration: Expected identifier in nested name, got keyword: typedef
```

**Comment by albert-github** [comment] 2020-04-14 13:20
Given the example, with version 1.8.16  (and 1.8.17) I see:

![result_1_8_16](https://user-images.githubusercontent.com/5223533/79229396-40aa8300-7e63-11ea-82f8-cfc895ada14c.jpg)

and with current version 1.8.18 I see:

![result_1_8_18](https://user-images.githubusercontent.com/5223533/79229409-443e0a00-7e63-11ea-8f10-00c4daf9d607.jpg)

- Looks like that in the current version the problem has been solved, correct?
- @tomaskrizek which version of doxygen did you use?

**Comment by tomaskrizek** [comment] 2020-04-14 13:49
Right, this seems to be fixed in 1.8.18. I'm still using 1.8.17. Thanks!

**Comment by albert-github** [comment] 2020-04-14 13:52
Thanks for the feedback, so problem has been solved in the mean time.

(I don't blame you for "still" using 1.8.17, 1.8.18 was released yesterday).

**Closed** 2020-08-08 17:22 UTC
Labels: bug, solved in the mean time

**Comment by sboukortt** [comment] 2024-02-23 13:33
As far as I can tell, 1.9.4 is affected by a similar issue:

```c
typedef struct MyParams MyParams;
```
-> typedef

```c
struct MyParams typedef MyParams;
```
-> variable

**Comment by albert-github** [comment] 2024-02-23 13:51
@sboukortt 

As this problem is a bit different from the original issue can you please
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
- where would you think the both parts should be?

Note the current doxygen version is 1.10.0
