### ISSUE TITLE
"Failed to create output directory" on second run if "CREATE_SUBDIRS = YES"

### ISSUE THREAD

**Issue by tttapa** [doxygen/doxygen#7860] opened 2020-06-18 12:36 UTC
After upgrading to the latest master version today (d0f24b762e23b1b0c069209978aa403acc027cdf), Doxygen fails to create the output directories with the option `CREATE_SUBDIRS = YES` when the directory already exists.  
This wasn't an issue a couple of months ago (I don't have the exact commit, but it was a master version after the 1.8.18 release).  
If the default option `CREATE_SUBDIRS = NO` is used, it works fine as well.

### Error message
```
[...]
Counting members...
Counting data structures...
Resolving user defined references...
Finding anchors and sections in the documentation...
Transferring function references...
Combining using relations...
Adding members to index pages...
Correcting members for VHDL...
error: Failed to create output directory 'd0'
Exiting...
exit status 1
```

### Reproduction
Simply enable `CREATE_SUBDIRS = YES` and run Doxygen twice. The first time, it works fine, because the output directories don't exist yet. The second time, it fails with the error message above.

A workaround is removing the `html` folder every time before running Doxygen.

Full Doxyfile, code and output: [**Doxygen-7860.zip**](https://github.com/doxygen/doxygen/files/4798535/Doxygen-7860.zip)

### Version
1.8.19 (d0f24b762e23b1b0c069209978aa403acc027cdf), Ubuntu 20.04 LTS, compiled from source (master) earlier today.

**Comment by albert-github** [comment] 2020-06-18 12:44
I have an idea what the cause of this problem might be. Recently some changes were made in checking the creation of directories and probably this is a side effect.

**Comment by tttapa** [comment] 2020-06-18 12:45
It seems like this issue was introduced in e6a6e65d46196125a5baad4aeb1942aa043236fa. The commit before it (fa4e3f5f955e602f02545e049361510f3334cfff) works fine.

**Comment by tttapa** [comment] 2020-06-18 13:43
I opened a pull request that checks if the directory exists before trying to create it.  
I tried [`QDir::mkpath`](https://doc.qt.io/archives/qt-4.8/qdir.html#mkpath) first (it returns true if the folder already exists), but it doesn't seem to be included with the version of `Qt` that Doxygen ships with.

**Comment by albert-github** [comment] 2020-06-18 13:54
It is strange that the test was forgotten here (it looks like that the test is present at all other places). 
Doxygen uses for its kernel indeed a quite old Qt version with some corrections.

**Comment by tttapa** [comment] 2020-06-18 14:53
I'm glad it works now :)  
Thanks a lot for the quick response and the work you're doing!

**Comment by albert-github** [comment] 2020-06-19 08:12
Code has been integrated in master on github (closing issue as it only occurred in the master version)

**Closed by albert-github** 2020-06-19 08:12 UTC
Labels: bug
