### ISSUE TITLE
Incremental Build (Origin: bugzilla #687888)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4945] opened 2018-07-02 08:11 UTC
status NEW severity *normal* in component *general* for *---*
Reported in version *unspecified* on platform *Other*
Assigned to: Dimitri van Heesch

On 2012-11-07 23:07:20 +0000, Tony wrote:

    I have quite a large C++ project that I use Doxygen on and due to its size a
    Doxygen run can take a long time. This makes incremental builds impossible
    if developers want to tweak something here and there, build their changes
    and look at the documentation to see it is reflected properly.
    
    I am familiar with the Tag feature of Doxygen but there are limitations on
    what they can be used for. They feel more suited for external libraries and
    not for partitioning a single large project that you really want to generate
    unified documentation for.
    
    I have been thinking of ways that Doxygen can be sped up and I would like to
    see an incremental build option built into Doxygen. I am thinking that this
    could work by a user perform a complete Doxygen run on a project where as
    part of the run Doxygen can store metadata about all the files that were
    inspected.  Upon subsequent runs, Doxygen would leverage this metadata to
    determine what file have changed and generate documentation only for the
    changes made. This, I believe, would greatly reduce the time it takes to run
    Doxygen on very large projects.

On 2018-06-28 17:59:54 +0000, albert wrote:

    *** Bug 647714 has been marked as a duplicate of this bug. ***

**Comment by albert-github** [comment] 2023-09-21 10:43
I think that this is a duplicate of: Implement differential generation of documentation (Origin: bugzilla 341581) #2138

**Closed** 2023-12-25 11:15 UTC
Labels: duplicate
