### ISSUE TITLE
<i> tag not recognized? (Origin: bugzilla #137323)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#1038] opened 2018-07-01 14:29 UTC
status NEW severity *normal* in component *general* for *---*
Reported in version *1.3.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2004-03-16 03:15:06 +0000, jdemail@yahoo.com wrote:

    When comment text has <i>the i tag</i>, doxygen replaces the angle 
    brackets rather than pass them on to HTML as-is.

On 2004-03-17 00:42:07 +0000, jdemail@yahoo.com wrote:

    THIS IS NOT A BUG in the code; is it a bug in documentation?
    
    The cause was that the HTML expression was within quotes:
    
      /**
      #include "<i>path</i>\xyz.h"
      */
    
    Workaround (note the \\ change, too):
    
      /**
      #include &quot;<i>path</i>\\xyz.h&quot;
    
    Is this documented anywhere in the doxygen manual?
    
    John
    
    
    
    

On 2018-05-18 14:41:44 +0000, albert wrote:

    There are a number of characters that need to be escaped in comments as they
    are used by doxygen for special purposes, an excerpt here (these commands
    are all documented in the chapter "Special Commands"):
    - \ -> \\ backslash has to be escaped in some cases
    because doxygen uses it to detect commands.
    - # -> \# This character has to be escaped in some cases, because it is
    used to refer to documented entities.
    - " -> \" This character has to be escaped in some cases, because it is
    used in pairs to indicate an unformatted text fragment.
    
    When the escape sequences are used the <i> ... </> is recognized as well.
    
    I think this report can be closed as not a bug.

**Comment by albert-github** [comment] 2019-02-19 17:27
Se the old comment, to be closed as not a bug.

**Closed** 2019-08-08 18:14 UTC
Labels: Usage
