### ISSUE TITLE
Autolinks to functions do not take effect in @name scope and file scope.

### ISSUE THREAD

**Issue by st-masa** [doxygen/doxygen#9587] opened 2022-09-07 12:58 UTC
**Describe the bug**

From 1.9.5, some patterns of [Links to functions](https://doxygen.nl/manual/autolink.html#linkfunc) are not linked.
1. `<functionName>"("<argument-list>")"` -> not linked
2. `<functionName>"()"` -> not linked
3. `"::"<functionName>` -> not linked
4. `(<className>"::")n<functionName>"("<argument-list>")"` -> linked
5. `(<className>"::")n<functionName>"("<argument-list>")"<modifiers>` -> not checked... but maybe linked
6. `(<className>"::")n<functionName>"()"` -> linked
7. `(<className>"::")n<functionName>` -> linked

**Expected behavior**
All patterns of links are linked correctly.

**Screenshots**
![MissingAutolinks](https://user-images.githubusercontent.com/79039413/188884932-0ea39b21-1826-4956-9210-a2ecfbf5ea22.png)

**To Reproduce**

Extract the attachment [AutolinksToFunctionsSample.zip](https://github.com/doxygen/doxygen/files/9506349/AutolinksToFunctionsSample.zip) and execute doxygen with its DoxyFile.

```
    @details
    - Link to namespaceFunction(int arg1, int arg2) without reference cmd. 
    - Link to namespaceFunction() without reference cmd.
    - Link to ::namespaceFunction without reference cmd and brackets.
    - Link to namespaceFunction without reference cmd and brackets. (not autolinked by design.)
    - Link to @ref namespaceFunction(int arg1, int arg2) with reference cmd.
    - Link to @ref namespaceFunction() with reference cmd.
    - Link to @ref namespaceFunction with reference cmd but without brackets.
    - Link to sample::namespaceFunction(int arg1, int arg2) without reference cmd.
    - Link to sample::namespaceFunction() without reference cmd.
    - Link to sample::namespaceFunction without reference cmd and brackets.
    - Link to @ref sample::namespaceFunction(int arg1, int arg2) with reference cmd.
    - Link to @ref sample::namespaceFunction() with reference cmd.
    - Link to @ref sample::namespaceFunction with reference cmd but without brackets.
```

**Version**
1.9.5 on Windows 10 (64 bit) and MacOSX.
Maybe other OS should be the same.

**Additional context**

The refactored `getDefsNew()` in [Refactoring: reimplement getDefs using symbol resolver](https://github.com/doxygen/doxygen/commit/b290399fab92df45376103d7c094f053f24495fa) seems to cause this issue.

**Comment by albert-github** [comment] 2022-09-07 13:21
I think the results as shown by doxygen i.e. 

![image](https://user-images.githubusercontent.com/5223533/188887564-6c0af514-cecb-42e2-8bf3-8e3551b72223.png)

is correct as  the `namespaceFunction` is located in the namespace `sample` and in the given lines there is no reference to this namespace neither is there in the header file `header.h`. I think that in the documentation the word `classname` should maybe extended a bit so it includes namespace names as well.
I think the result from the 1.9.5 version is even better as here we get the extra warning:
```
header.h:18: warning: unable to resolve reference to 'namespaceFunction()' for \ref command
```

**Comment by st-masa** [comment] 2022-09-08 12:14
Thank you for advising.
As you mentioned, [AutolinksToFunctionsSample.zip](https://github.com/doxygen/doxygen/files/9506349/AutolinksToFunctionsSample.zip)'s function links without namespace should not be linked because of their ambiguities.

I have created another sample which contains two classes with same-named methods.
[AutoLinkSample2.zip](https://github.com/doxygen/doxygen/files/9526624/AutoLinkSample2.zip)

Links below `@name` command cause warnings like:
```
sample1.h:84: error: explicit link request to 'Function2()' could not be resolve
```
And function links sample1_8h.html and sample2_8h.html are not enabled.

**Comment by st-masa** [comment] 2022-09-08 12:21
When too many header files are set to`INPUT`, I observed some autolink symbols are not linked.
(using previous`getDefsOld` it is ok.)

But, it's not easy to make minimized sample to reproduce...

**Comment by albert-github** [comment] 2022-09-08 13:56
I have my doubt about the links `::Functio2()` etc though as I understood this should go to the global namespace, but in this case there is nothing of that kind (the file `header.h` is excluded.

Even with the `getDefsOld` I still see one message (per file), though all links look like to go to sensible places. 

@doxygen any idea?

**Comment by doxygen** [comment] 2022-09-18 13:13
Looks like the main problem is that the member group documentation (i.e. the documentation associated with `@name`) is rendered twice, once for the namespace documentation and once more for the file documentation. The links in the file documentation were incorrectly evaluated in file context (thus requiring a fully qualified names in order to be resolved and incorrectly resolving to global functions of the same name if present).

A secondary problem was that the line numbers of the warnings were incorrect, because the end of the member group marker `/// @}` was overwriting the "start" line number of the documentation block.

Both problems should be addressed in the attached commit. So please verify if this indeed fixes the problem.

**Comment by st-masa** [comment] 2022-09-19 05:55
@doxygen 
Thank you for the fix.
I have verified the issue posted [here](https://github.com/doxygen/doxygen/issues/9587#issuecomment-1240635599) is fixed.

As of now, I do not come up with ideas to reproduce the issue posted [here](https://github.com/doxygen/doxygen/issues/9587#issuecomment-1240642991).
So I will file another issue if I can find how to reproduce.

**Comment by doxygen** [comment] 2022-12-27 10:16
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.6.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2022-12-27 10:16 UTC
Labels: bug

**Comment by luftaquila** [comment] 2023-02-01 07:46
`<functionName>"()"` form still does not linked at 1.9.6

**Comment by albert-github** [comment] 2023-02-01 08:32
@luftaquila 

The message is a bit unclear in which case the linking does not work,
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by yous** [comment] 2023-10-04 10:44
Hi, I've made an example where `<functionName>"()"` doesn't get linked properly.

- [AutolinkSeeAlso.tar.gz](https://github.com/doxygen/doxygen/files/12802394/AutolinkSeeAlso.tar.gz)

<img width="1274" alt="Screenshot 2023-10-04 19 43 16" src="https://github.com/doxygen/doxygen/assets/853977/157fca8b-4df3-46fc-ba5b-6fe06f019904">

**Comment by albert-github** [comment] 2023-10-04 13:08
@yous
I assume that you mean that there are no links to the see also function in the "own" file functions (i.e. a missing link from `src1_function2` in the description of `src1_function1` and from `src1_function1` in the description of `src1_function2`
- which version of doxygen did you use? (although I see the problem I assume you meant also with the 1.9.8 version and the current doxygen master (1.10.0 (e1fdc53218b7f5868d9c34503094b2ee01968ad0))).

@luftaquila 
- were you already able to create an example of the problem you saw?

**Comment by yous** [comment] 2023-10-04 13:09
I used 1.9.8 from Homebrew. I'll test with the current master, too.

**Comment by yous** [comment] 2023-10-04 13:13
With the current master `1.10.0 (e1fdc53218b7f5868d9c34503094b2ee01968ad0*)`, the result is same. Some functions in see also section don't have links.

**Comment by luftaquila** [comment] 2023-10-04 13:44
I'm sorry, I don't have access to the source at this time and cannot reproduce the problem.

**Comment by albert-github** [comment] 2023-10-07 11:09
@yous
Did some investigations and saw the the documentation of the files `src1.c` and `src2.c` don't turn up in the documentation, we only see the source code, solution for the problem (giving also the requested links in the output):
- use in the `.c` files the command `\file`
- set the setting `EXTRACT_ALL = YES`.

**Comment by yous** [comment] 2023-10-08 17:52
@albert-github Thanks, it works on Doxygen.

I got another problematic example:
- [SameNameStructAndFunction.tar.gz](https://github.com/doxygen/doxygen/files/12841327/SameNameStructAndFunction.tar.gz)

``` c
/**
 * @file    header.h
 * @brief   description header file
 */

#ifndef HEADER_H
#define HEADER_H

/**
 * @struct foo
 * @brief struct named foo
 *
 * @sa foo()
 */
struct foo {
    int x;
    int y;
};

/**
 * @brief function named foo
 *
 * @sa @link foo @endlink
 */
int foo(int a, int b);

#endif /* HEADER_H */
```

<img width="458" alt="Screenshot 2023-10-09 02 48 12" src="https://github.com/doxygen/doxygen/assets/853977/ea4d9f8d-ffdf-4a61-b50c-e49ec5202f63">

In the documentation of `struct foo`, `foo()` links to `struct foo` itself, not the function `foo()`.

Is there a way to disambiguate these references?

**Comment by yous** [comment] 2023-10-08 18:00
I can reproduce this problem on 1.9.8, 1.10.0 (73874def7998419647a6281ec4b39c4261d4d18f*).

I tried `foo()`, `foo(int,int)`, and `foo(int a, int b)`. All of them linked to `struct foo`.

**Comment by albert-github** [comment] 2023-10-09 11:06
I see the problem, though I think this is a completely different issue from the issue of this issue (#9587) so please create a new issue for this.
