### ISSUE TITLE
Parameter table does not split table if table is too long

### ISSUE THREAD

**Issue by KKyang** [doxygen/doxygen#8083] opened 2020-10-08 12:44 UTC
**Describe the bug**
If the table is too long, it will not automatically split in 2 parts with the second part on the next page.

**Expected behavior**
It should split into multiple partial tables.

**Screenshots**
![Inkedunnamed_LI_Moment](https://user-images.githubusercontent.com/2676255/95459759-a86f0000-09a6-11eb-88de-ee0fd6eb315e.jpg)

**To Reproduce**
```
doxygen -g
doxygen
cd latex
make
```

Open refman.pdf

**Version**
1.8.17-0ubuntu2 on Ubuntu 20.04.1

pdflatex is installed with the following command

```
sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
```

**Stack trace**
N/A

**Additional context**
Can I overwrite the latex style sheet to resolve this problem?

**Comment by albert-github** [comment] 2020-10-08 12:57
Unfortunately this is sometimes the case for tables that overflow just with a few lines, but very hard to reproduce.
Actually this report is a duplicate of #6532

> Can I overwrite the latex style sheet to resolve this problem?

Yes, but I would not overwrite the doxygen.sty style sheet  but create an`LATEX_EXTRA_STYLESHEET` where you redefine the relevant command / environment.

**Comment by KKyang** [comment] 2020-10-08 13:01
I don't know how to write LaTeX. I've tried LATEX_EXTRA_STYLESHEET with ``renewenivroment`` but still no luck.

```
  320 % Used by parameter lists
  321 \newenvironment{DoxyParams}[2][]{%
  322     \tabulinesep=1mm%
  323     \par%
  324     \ifthenelse{\equal{#1}{}}%
  325       {\begin{longtabu*}spread 0pt [l]{|X[-1,l]|X[-1,l]|}}% name + description
  326     {\ifthenelse{\equal{#1}{1}}%
  327       {\begin{longtabu*}spread 0pt [l]{|X[-1,l]|X[-1,l]|X[-1,l]|}}% in/out + name + desc
  328       {\begin{longtabu*}spread 0pt [l]{|X[-1,l]|X[-1,l]|X[-1,l]|X[-1,l]|}}% in/out + type + name + desc
  329     }
  330     \multicolumn{2}{l}{\hspace{-6pt}\bfseries\fontseries{bc}\selectfont\color{darkgray} #2}\\[1ex]%
  331     \hline%
  332     \endfirsthead%
  333     \multicolumn{2}{l}{\hspace{-6pt}\bfseries\fontseries{bc}\selectfont\color{darkgray} #2}\\[1ex]%
  334     \hline%
  335     \endhead%
  336 }{%
  337     \end{longtabu*}%
  338     \vspace{6pt}%
}
```

Is this the correct function to redefine?

**Comment by albert-github** [comment] 2020-10-08 13:05
By head yes this is the right environment.

I assume you placed the renew code in a file and mentioned that file in `LATEX_EXTRA_STYLESHEET`.

What kind of error message do you get or do you mean that you have no way found yet to split the table?

**Comment by KKyang** [comment] 2020-10-08 13:10
No error message. I folllowed the tutorial here

https://texblog.org/2011/05/15/multi-page-tables-using-longtable/

Add ``endfoot`` and ``endlastfoot``, and replace ``longtable`` with ``longtabu*``.

**Comment by albert-github** [comment] 2020-10-08 13:23
Interesting article.
Important lines are:
> \endfoot: Last line(s) to appear at the bottom of every page (except last)
> \endlastfoot: Last line(s) to appear at the end of the table

but this is about how the footers of a table appear, I think the problem that is in doxygen is that the footers are the page footers and the that the table is not split properly.

**Comment by KKyang** [comment] 2020-10-12 01:18
Is it possible to use ``/needspace`` package or ``zref`` and check if every generated line exceeds ``/bodyheight``?

**Comment by albert-github** [comment] 2020-10-12 09:50
As I don't know the `needspace` and `zref` packages it is hard to judge though:
- looks like the `needspace` hasn't been updated since 2013 (at least for MikTex), so not really a candidate.
- the `zref` package looks more promising (as it is now maintained by "Oberdiek Package Support Group"
- the:
  > check if every generated line exceeds `/textheight`

  might have serious speed consequences. Though I don't think doxygen should fix this but this should be fixed in the underlying table software. The later will probably be a bit hard as the `tabu` package is currently unmaintained (doxygen uses its own copy as otherwise it would crash with the newer *TeX versions), but the same problem is probably present in environments like `(long)tabular` and might be ported back to `tabu`.

My suggestions:
- check what you can accomplish with `zref`
- check the speed with `zref`
- share the resulting code with doxygen so it can be reviewed and it can be decided whether or not the code can be incorporated into doxygen.

**Closed** 2020-12-27 19:29 UTC
Labels: LaTeX, bug, duplicate
