### ISSUE TITLE
\copydoc not working - HTML (Origin: bugzilla #678899)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4772] opened 2018-07-02 07:32 UTC
status NEW severity *major* in component *general* for *---*
Reported in version *1.8.1.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[test.zip](https://sourceforge.net/projects/doxygen/files/attachments/bug678899_217310_test.zip/download/download)_ (ID 217310)

On 2012-06-26 16:12:10 +0000, Fabrizio Da Ros wrote:

    Hello,
    
    I made some comparison between the HTML generated by v1.8.1.1 and v1.7.6.1
    
    I would like to use the \copydoc command applied to pages to separate
    documentation into files (no source code involved)
    
    The result with v1.7.6.1 is what one is expect to have, while it is
    different and even broken with v1.8.1.1 (and v1.8.1 too)
    
    file test1.doxy <<<
    /**
    \mainpage   Activities
    
    \section id_1    Section 1
    
    Text of section 1
    
    \copydoc id_test2
    
    Text in between
    
    \copydoc id_test3
    
    Hello
    
    - \copydoc  id_test2
    - \copydoc  id_test3
    - Ending
    
    Same page linked as subpage \subpage id_test3
    
    */
    >>>
    
    file test2.doxy <<<
    /**
    \page   id_test2   Test 2
    
    This is page test2
    
    */
    >>>
    
    file test3.doxy <<<
    /**
    \page   id_test3   Test 3
    
    This is page test3.
    
    And this text is below the previous one.
    \n Carriage return!
    
    \section id_4   Section inside Test 3 page
    
    Section text
    
    */
    >>>
    
    -----------
    v1.8.1.1
    \copydoc is not working properly since it places twice the page content.
    
    \copydetails (replace all \copydoc with it) on the other side gives
    consistent result but it does not respect paragraphs separation of id_test3.
    
    The result is correct (in my opinion) in v1.7.6.1
    
    This problem is blocking me in migrating to v1.8.1.1
    
    
    Thank you in advance!
    Fabrizio

On 2012-06-26 16:13:44 +0000, Fabrizio Da Ros wrote:

    Created attachment 217310
    source files and doxyfile

**Comment by albert-github** [comment] 2021-12-24 13:53
This is a duplicate of #5074

**Closed** 2021-12-31 11:09 UTC
Labels: bug, duplicate
