### ISSUE TITLE
call graph (with dot) doesn't be generated in calling order

### ISSUE THREAD

**Issue by karlzheng** [doxygen/doxygen#8153] opened 2020-11-03 10:47 UTC
**Describe the bug**
call graph (with dot) doesn't be generated in calling order:

the calling order is:
	a2dp_audio_heap_realloc
	a2dp_audio_heap_free

but the generated dot file order is:
	a2dp_audio_heap_free
	a2dp_audio_heap_realloc

**Expected behavior**
generate call graph in calling order

**Screenshots**

source code:

<img width="598" alt="image" src="https://user-images.githubusercontent.com/2570701/97976685-f6d8b880-1e05-11eb-85c5-8b3eca225d6e.png">

generated dot picture:

<img width="995" alt="image" src="https://user-images.githubusercontent.com/2570701/97976281-65694680-1e05-11eb-9e7b-ef651fc48987.png">

**To Reproduce**
[files.zip](https://github.com/doxygen/doxygen/files/5480741/files.zip)

**Version**
macOS 10.14.6 (18G4032)
Doxygen version 1.8.16

**Additional context**
it seems same as:
https://github.com/doxygen/doxygen/issues/4145

**Comment by kosa215** [comment] 2020-11-26 20:49
This appears to have been working (ordered by calling order) from release 1.7.5 to 1.8.15, and anything before that or after that orders alphabetically. I can't track down a specific change that does this but I am also not so experienced with the project. For my purposes I plan to use release 1.8.15 in the meantime.

**Comment by albert-github** [comment] 2020-11-27 18:13
Looking at the original problem:
With version 1.7.4 I see the order "free" "realloc".
With the 1.7.5 version I see the order "realloc" "free"  with version 1.7.5.1 I again see the order "free" "realloc".
In the 1.8.15 version I also see the "wrong" order "free" "realloc" and also in the 1.8.20 version I see this order (also in the current master (1.9.0 (6de91dc5e32e6d97a557fe6910a6cbf1d453ad9c)).

I think this problem is also mentioned in #4379 which is for version 1.7.5.1

@kosa215 
From your description it looks like you have another problem (as you mention that version 1.8.15 is still OK), so:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by doxygen** [comment] 2020-11-27 18:42
Also be aware that doxygen produces a graph (nodes + arrows) and then the dot tool of the GraphViz package does the layout using some layout algorithm, there is no guarantee that the order will be displayed in the calling order even if the input to the dot tool is in that order.

**Comment by kosa215** [comment] 2020-11-27 22:21
@albert-github , I added a sample at the bottom of this comment, but I think it behaves the same as karl's. You need to add your path to the source code, and your DOT_PATH for it to work I think.

I'm now quite confused. I think what I am seeing is different graph behavior, on different nights of testing given the same version of doxygen. For both 1.8.15 and 1.8.14, I yesterday noted that they produced graphs in calling order (non-alphabetical); today I try them again and both yield alphabetical graphs. For context, when I am switching between versions, I use Windows 'Add or remove programs' to uninstall the previous version, then use the setup.exe of the next version to install the next version. Almost seems like something is being carried between versions, (or maybe something isn't resetting within Graphviz?). I guess that could make sense based on Dimitri/doxygen's answer. 

[doxy.zip](https://github.com/doxygen/doxygen/files/5609707/doxy.zip)

**Comment by albert-github** [comment] 2020-11-28 10:39
@kosa215 
Note that the dot files are not always regenerated (as md5 files are stored to prevent regeneration in case that dot files are still the same), therefore it is always good to to remove the HTML directory between tests like this.

I tested your example as well and only with 1.7.5 I got the "calling sequence" order

**Comment by kosa215** [comment] 2020-11-28 18:52
@albert-github That probably explains it. I was not always clearing the HTML directory. I'll try again when I get the chance but I think after doing that I'll see what you saw. Sorry for the diversion.

**Comment by boellner** [comment] 2023-02-07 20:16
Hello, is this still active?

**Comment by albert-github** [comment] 2023-02-08 10:54
I don't think this issue is active anymore, what is the exact reason you are asking?

There are a number of things to be considered here:
- the fact that the `dot` tool can do some reordering, which is outside the scope of doxygen, see also https://github.com/doxygen/doxygen/issues/8153#issuecomment-734949884
- the fact it says call / caller graphs and that this means in the doxygen sense: give an overview of functions called by this function / the functions by which this function is called. Note here that in case we have e.g. 
   ```
   void fie()
   {
      fie_x();
      fie_a();
      fie_x();
   }
   ```
   The function `fie_x` will only be mentioned once, so here we would also have a problem with the order. Another example would be (example just for purpose of showing the problem):
   ```
   void fie(int inp)
   {
      for (i = 1; i < 10 ; i++)
      {
         if (inp == i)
                fie_x();
         else
                fie_a();
        }
   }
   ```
   due to the different paths and the dependency on the input value it is not possible to determine the order.


So I don't see this not as a problem but as an interpretation problem of the result.

**Comment by Dipesh-kayastha** [comment] 2023-02-24 10:32
Is this https://github.com/doxygen/doxygen/issues/8153#issue-735214120 resolved in the updated doxygen version?

**Comment by albert-github** [comment] 2023-02-24 11:40
@Dipesh-kayastha I think the situation has been explained  a.o. in https://github.com/doxygen/doxygen/issues/8153#issuecomment-1422405166

**Comment by Dipesh-kayastha** [comment] 2023-02-24 12:22
@albert-github I have tried with the sample program, in that I have used function_1 which is calling function_z,function_c,function_b and function_a sequentially in code, but when we see the call graph of doxygen it is not showing it like it is actually calling. It is taking as per the ASCII I think. Could you please guide me how to generate doxygen call graph with the sequential calls as we calling in actual code? I am attaching the screenshot here for reference.

<img width="1451" alt="Screenshot 2023-02-24 at 5 46 43 PM" src="https://user-images.githubusercontent.com/104245831/221178008-b44859c9-f2a9-4a48-897e-4c4ab821ec40.png">

**Comment by albert-github** [comment] 2023-02-24 12:29
@Dipesh-kayastha I don't think it is possible as explained in the mentioned comment. The call graph is a graph that, attempts to, show the functions that are called noting about the order about the of the calling.

**Closed** 2023-05-18 20:30 UTC
Labels: Usage
