### ISSUE TITLE
markdown css attribute after css comment not detected

### ISSUE THREAD

**Issue by arcturus140** [doxygen/doxygen#7088] opened 2019-06-28 15:14 UTC
Doxygen does not parse Markdown correctly when it starts with a comment - the CSS attribute `mainpage` is ignored. 

# Test Case

Doxygen receives the following file as input:
**test.md**
```
<!--
this is a multiline comment
-->

# test {#mainpage}

some text
```

# Expected Result

The text should appear as mainpage in the generated HTML output. Instead, it only appears in `Related Pages`.

# Observation

The desired outcome can be achieved moving the comment below CSS attribute:

**test.md**
```
# test {#mainpage}
<!--
this is a multiline comment
-->

some text
```

# Versions
- `1.8.11`
- `1.8.16` from master branch.

**Comment by albert-github** [comment] 2019-06-28 15:35
This look to me a duplicate of "Page title not using heading when comment starts page in markdown" (#6908 and the proposed patch #6909)

**Closed** 2019-12-28 11:05 UTC
Labels: Markdown, bug, duplicate
