### ISSUE TITLE
bug - include start with empty line

### ISSUE THREAD

**Issue by aotto1968** [doxygen/doxygen#11267] opened 2024-12-09 19:02 UTC
**Describe the bug**
look to the screenshot

**Screenshots**
![image](https://github.com/user-attachments/assets/804051cb-3d2b-4ccf-9768-f5529ec805e0)

**To Reproduce**
use attachment -> 
[doxygen_bug__include_start_with_empty_line.tar.gz](https://github.com/user-attachments/files/18067290/doxygen_bug__include_start_with_empty_line.tar.gz)

**Version**
1.13.0 (8007b6cfff3fdbafb38c15b484afeac12b2bb812*)

**Comment by aotto1968** [comment] 2024-12-09 20:53
the core problem is the `*` at the end of `namespace import tclmkkernel::*`.
doxygen has **no** feature to treat an statement as **DO-NOT-PARSE**.
either ```` nor `<tt>...</tt>` is able to handle `namespace import tclmkkernel::*` proper

**Comment by aotto1968** [comment] 2024-12-10 09:13
I update my doxygen recently to:
```
> doxygen -V
1.13.0 (8007b6cfff3fdbafb38c15b484afeac12b2bb812*)
    with sqlite3 3.42.0.
```

**Comment by aotto1968** [comment] 2024-12-10 09:18
now
```
> doxygen -V
1.13.0 (396e81da3b44b9bb156ffbc5fd263e17f8f638a8*)
    with sqlite3 3.42.0.
```
same result
![image](https://github.com/user-attachments/assets/87d3fc4a-d223-427c-8f69-ac1c5a6a58af)

**Comment by albert-github** [comment] 2024-12-10 09:40
That is strange. I just retested it and with the current master (1.13.0 (396e81da3b44b9bb156ffbc5fd263e17f8f638a8))  it looks all OK to me.
It looks a bit like using an older version in your test.
- did you run your test on your complete code base

  or
- did you run your test just on the example (like I did).


> -> the '*' problem on end is still open.

- You mean the extra whitespace you see and I don't see ? 
  Otherwise please clarify which `*` it is and what you expected.

**Comment by albert-github** [comment] 2024-12-10 10:05
Looking at the provided doxygen.out it looks like you used there the version:
```
Doxygen version used: 1.13.0 (8007b6cfff3fdbafb38c15b484afeac12b2bb812*)
```
and when I run that version it is OK as well.

Note: seen the line just after the "Synopsis" it looks like that the file you used and that I used are slightly different.

**Comment by aotto1968** [comment] 2024-12-10 10:10
```
> which doxygen
.../Project/NHI1/bin/doxygen
> ls -al .../Project/NHI1/bin/doxygen
lrwxrwxrwx 1 dev1usr users 14 22. Jun 10:07 .../Project/NHI1/bin/doxygen -> doxygen-1.12.0
> which doxygen-1.12.0
.../Project/NHI1/bin/doxygen-1.12.0
> ls -al .../Project/NHI1/bin/doxygen-1.12.0
lrwxrwxrwx 1 dev1usr users 43 14. Jun 19:25 .../Project/NHI1/bin/doxygen-1.12.0 -> .../src/doxygen/build/bin/doxygen
> ls -al .../src/doxygen/build/bin/doxygen
-rwxr-xr-x 1 dev1usr users 29225840 10. Dez 10:24 .../src/doxygen/build/bin/doxygen
> .../src/doxygen/build/bin/doxygen -V
1.13.0 (396e81da3b44b9bb156ffbc5fd263e17f8f638a8*)
    with sqlite3 3.42.0.
```

**Comment by albert-github** [comment] 2024-12-10 10:22
I ran your updated / second example (from https://github.com/doxygen/doxygen/issues/11267#issuecomment-2531097782) and got:
![image](https://github.com/user-attachments/assets/30c18ebd-01f8-4a92-a438-99f566afffcb)

This looks all OK to me

**Comment by aotto1968** [comment] 2024-12-10 11:09
Now it works:
→ there is a __MASSIVE__ bug in `github`

I had the environment variable `GIT_WORK_TREE` set and **some** checkout `git pull origin master` go into directory specified in `GIT_WORK_TREE` **but** the compilation seems to ignore parts of the *new* files and end up in a *good* executable (`doxygen -V` was right) missing *essential* updates → this create a huge amount of __disorder__ probably for *all* updates of `git` code.

![image](https://github.com/user-attachments/assets/49df0614-83fe-4eaa-914a-9565c6e98395)

**Comment by albert-github** [comment] 2024-12-10 11:16
Good that you found the cause of the differences between my results and your results. Git is quite difficult to understand and intransparent  (at least in my opinion). Maybe google for `GIT_WORK_TRE` and see why you needed it once and what it does (maybe https://stackoverflow.com/a/5283457/1657886).

**Comment by aotto1968** [comment] 2024-12-10 11:18
you should check for `GIT_WORK_TREE` and stop compiling if this is set.

**Comment by albert-github** [comment] 2024-12-10 11:29
> you should check for `GIT_WORK_TREE` and stop compiling if this is set.

I'm not sure about this
- the setting is the responsibility of the user.
- the `GIT_WORK_TREE` might be set in the environment / terminal where the user does the checkout but not in the environment / terminal where the user does the compilation so this might lead to strange effects as well (e.g I do the checkout under Cygwin but I compile under Windows and under Cygwin from the same  source tree into different build directories.)


> The problem with `GIT_WORK_TREE` is, also after deleting this environment variable the git still say it was up-do-date

One of the hard to understand / strange things from git ...

**Comment by aotto1968** [comment] 2024-12-11 10:42
now I use the new *doxygen* on another target ... and **now** I get >2.000 warnings etc . something which was *message-free* before. 

problems:
1. initial starting with: `.../LibMkKernel_mk.h:12128: warning: unbalanced grouping commands` -> a file with 13.000 lines of code I now have to scan for this thing … Task: add DEBUG option for unbalanced GROUPS
2. `#define __parser__(...)` seems to be broken the `...` as multiple arguments list is **NOT** parsed → I want to ignore this. I have the `PREDEFINED +=  "__parser__(...)="` which seems to be ignored.

Task: NO special debug option to focus on grouping error
```
> doxygen -d
Developer parameters:
  -m          dump symbol map
  -b          making messages output unbuffered
  -c <file>   process input file as a comment block and produce HTML output
  -d <level>  enable a debug level, such as (multiple invocations of -d are possible):
        alias
        cite
        commentcnv
        commentscan
        entries
        extcmd
        filteroutput
        formula
        fortranfixed2free
        layout
        lex
        lex:code
        lex:commentcnv
        lex:commentscan
        lex:configimpl
        lex:constexp
        lex:declinfo
        lex:defargs
        lex:doctokenizer
        lex:fortrancode
        lex:fortranscanner
        lex:lexcode
        lex:lexscanner
        lex:pre
        lex:pycode
        lex:pyscanner
        lex:scanner
        lex:sqlcode
        lex:vhdlcode
        lex:xml
        lex:xmlcode
        markdown
        nolineno
        plantuml
        preprocessor
        printtree
        qhp
        rtf
        sections
        stderr
        tag
        time
```
does NOT exists

**Comment by doxygen** [comment] 2024-12-28 09:18
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.13.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2024-12-28 09:18 UTC
Labels: bug
