### ISSUE TITLE
Doxygen 1.8.17 unable to expand C preprocessor macros properly

### ISSUE THREAD

**Issue by madmurphy** [doxygen/doxygen#7573] opened 2020-02-05 22:38 UTC
In [my project][1] I have two constants ([#1][2], [#2][3]) which are expanded from preprocessor macros.

Until version 1.8.16 Doxygen was able to expand these macros correctly and show their computed results, as the following snapshot shows:

![correct][4]

But things have changed with version 1.8.17. Now Doxygen seems to stop parsing after `INI_MULTILINE_EVERYWHERE`, and the following snapshot shows the result:

![wrong][5]

How to reproduce the bug:

1. Open a terminal in the top level directory of [the package][6]
2. Launch `doxygen autostuff/doxygen/doxyfile.conf`

I know that there are other "problems" in my documented code, but they are mostly due to the fact that Doxygen considers an apostrophe following a backtick as a `</code>` tag, despite this is something completely foreigner to markdown (sorry guys, I will stick to the standard). These imperfections though can be easily fixed with a shell script, which is what I regularly do. But now I had to extend the shell script in order to face this new bug, which was not present in previous versions.

--madmurphy

  [1]: https://madmurphy.github.io/libconfini/html/index.html
  [2]: https://github.com/madmurphy/libconfini/blob/f73008412ecfd567ccf0b608a1394d4847278cb0/src/confini.h#L487
  [3]: https://github.com/madmurphy/libconfini/blob/f73008412ecfd567ccf0b608a1394d4847278cb0/src/confini.h#L495
  [4]: https://user-images.githubusercontent.com/9403693/73888517-aed03980-4865-11ea-8bf0-f35368aa0368.png
  [5]: https://user-images.githubusercontent.com/9403693/73887798-3d43bb80-4864-11ea-90da-0ef7c02a6f79.png
  [6]: https://github.com/madmurphy/libconfini/tree/f73008412ecfd567ccf0b608a1394d4847278cb0

**Comment by albert-github** [comment] 2020-02-06 09:26
I checked with version 1.8.16, 1.8.17  and the current master version (93245ad926ce01720eb35b9cf000992a44ac85c0).
The problem is shown in `confini_8h.html`, with version 1.8.16 the `INI_DEFAULT_FORMAT` and `INI_UNIXLIKE_FORMAT` are expaned and with version 1.8.17 they are not. With the current master the variables are expanded again (there have been some fixes regarding the preprocessor).

I ran your complete package (I don't like to do this) and fortunately it was quite fast but in future please try to make a bit a smaller package and please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem.  Please don't add external links as they might not be persistent.
It is also useful to mention the page (here `confini_8h.html``) that shows the problem.

I think the problem has been fixed but not released.

**Comment by madmurphy** [comment] 2020-02-06 10:58
Thank you, Albert.

**Comment by doxygen** [comment] 2020-04-13 11:48
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.18.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2020-04-13 11:48 UTC
Labels: bug
