### ISSUE TITLE
LaTeX output of Markdown tables broken

### ISSUE THREAD

**Issue by c-lipka** [doxygen/doxygen#6843] opened 2019-02-17 21:42 UTC
This self-contained example demonstrates how LaTeX output is broken when Markdown tables are used:

[doxygen-issue-markdowntable.zip](https://github.com/doxygen/doxygen/files/2873443/doxygen-issue-markdowntable.zip)

With MiKTeX 2.9 I get the following error message:

~~~
! Missing } inserted.
<inserted text>
                }
l.12 \end{longtabu}
~~~

(Doxygen 1.8.15)

**Comment by albert-github** [comment] 2019-02-18 08:59
@c-lipka did you recently update your MikTeX distribution (i.e. after mid of December 2018) ?

This is a duplicate of #6769

**Closed by albert-github** 2019-02-18 08:59 UTC

**Comment by c-lipka** [comment] 2019-02-18 09:07
Yes - I just had to update MiKTeX because Doxygen 1.8.15 seems to have added the requirement for another LaTeX package, and the package manager of the old MiKTeX install could not contact the server anymore.
