### ISSUE TITLE
Misplaced, incomplete function description (Origin: bugzilla #561303)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3177] opened 2018-07-02 01:32 UTC
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-11-18 03:55:04 +0000, relson@osagesoftware.com wrote:

    Please describe the problem:
    Doxygen is creating incomplete function definitions and putting in the wrong
    html file.
    
    Steps to reproduce:
    1. Unpack attached tarball
    2. run Doxygen
    
    Actual results:
    Functions AcnIsrThread, AcnIsr_0, and AcnIsr_1 are all defined in
    acn_sample_8c.html although the 2nd & 3rd functions belong in
    acn_drv_8c.html. AcnIsrThread is correctly handled (with code, caller, and
    call graphs).  AcnIsr_0 and AcnIsr_1 have caller graphs but lack code and
    call graphs.
    
    
    Expected results:
    
    
    Does this happen every time?
    yes
    
    Other information:
    doxygen version 1.5.7.1 running on linux

On 2008-11-19 20:44:21 +0000, Christian Kirbach wrote:

    moving to correct product 'doxygen'

**Comment by albert-github** [comment] 2019-04-01 10:12
The issue is missing the mentioned "Unpack attached tarball" (also on bugzilla).
The description is to limited to see what the problem is.

Issue should be closed as incomplete.

**Closed** 2019-08-08 18:13 UTC
Labels: invalid
