### ISSUE TITLE
Segfault after a8bf5d3

### ISSUE THREAD

**Issue by eseiler** [doxygen/doxygen#8139] opened 2020-10-29 09:37 UTC
**Describe the bug**
After the mentioned commit, I get segfaults when running doxygen.

**Expected behavior**
No segfault :)

**To Reproduce**
I couldn't reduce the problem yet (I just built the complete documentation of https://github.com/seqan/seqan3), log looks like:
```console
Searching for enumerations...
Searching for documented typedefs...
Searching for members imported via using declarations...
Searching for included using directives...
Searching for documented variables...
Segmentation fault
```

However, the commit diff shows:
https://github.com/doxygen/doxygen/commit/a8bf5d3c8ef905581122a7ac3cba36a13cc948d0#diff-2febfc8b9bd51f32694ec80f19df8c447374a21342e56b92c309772f7bc0f413L2445

In particular, the check wether fd is a `nullptr` is gone after the change. This is also the line where the debugger points me to regarding the segfault.
Adding it back:
```cpp
else if (fd != nullptr && (fd->name().right(2)==".c" || fd->name().right(2)==".h"))
```

solves the issue for me.

**Version**
a8bf5d3c8ef905581122a7ac3cba36a13cc948d0

**Comment by albert-github** [comment] 2020-10-29 09:43
A crash should not happen, though it is a bit strange that it is dependent on the way you start your executable, I assume that you double checked that the executable from the path and from /usr/local/bin are the same executables.

**Comment by eseiler** [comment] 2020-10-29 09:49
> I assume that you double checked that the executable from the path and from /usr/local/bin are the same executables.

I double checked, and it might be that I reset the variable at some point... So maybe disregard this until I can check again later today.

I don't know what the class does, but apparently `fd` may be a `nullptr`. The case was handled beforehand, but isn't now.

**Comment by albert-github** [comment] 2020-10-29 09:56
One thing is important:, you wrote "I just built the complete documentation", I did find the `seqan3_doxygen_cfg.in` but it always good to have the exact `Doxyfile` used and also the directory from where doxygen was started

**Comment by albert-github** [comment] 2020-10-29 12:09
I could reproduce the problem with the aid of another package (@doxygen CGAL documentation) problem was on Windows as well as on cygwin. So I created a proposed pull request (with proposed fix in the issue):
I've just pushed a proposed patch, pull request #8140

**Comment by albert-github** [comment] 2020-10-29 12:12
Code has been integrated in master on github.

**Comment by eseiler** [comment] 2020-10-29 13:10
Thank you for investigating and fixing, I was in a hurry and couldn't write you how to build our docs.

**Comment by doxygen** [comment] 2020-10-30 18:02
Since this problem is not appearing in any official release and is fixed before the next release I'll close the issue.

**Closed by doxygen** 2020-10-30 18:02 UTC
Labels: bug
