### ISSUE TITLE
Trouble with C# findmembers in 1.9.6? 

### ISSUE THREAD

**Issue by therealchjones** [doxygen/doxygen#9812] opened 2023-01-23 12:58 UTC
**Describe the bug**
Unchanged code, new error when running Doxygen 1.9.6 compared to 1.9.5:
`/Users/chjones/Development/Marvel Future Fight/mffer/src/classes/GameObject.cs:457: warning: member with no name found.`

**Expected behavior**
Build as before without warning or error

**To Reproduce**
First, my apologies for not including a smaller self-contained example; I've been unable to determine how to separately reproduce the error outside my code or edit my code so that the error no longer presents.

Using Doxygen 1.9.5 and the attached Doxyfile (stripped, only where differing from defaults), and the attached source tree (full repo also found at https://github.com/therealchjones/mffer/tree/9304715963044922e25d1f3e1dc93f50c6db497f), all runs as expected with the output log `log-1.9.5.txt`. Doing the same with Doxygen 1.9.6 results in `log-1.9.6.txt` including the above error. Adding `-d findmembers` to the runs result in some odd findMember calls in the 1.9.6 version (e.g., searching for an unnamed function with arguments '[instance initializer]').

Happy to attempt any further troubleshooting you can recommend. Thanks for all your help.

**Version**
Doxygen 1.9.6 on macOS Ventura 13.1, formal release from website

[Doxyfile.txt](https://github.com/doxygen/doxygen/files/10479848/Doxyfile.txt)
[source.tar.gz](https://github.com/doxygen/doxygen/files/10479876/source.tar.gz)
[log-1.9.5.txt](https://github.com/doxygen/doxygen/files/10479890/log-1.9.5.txt)
[log-1.9.6.txt](https://github.com/doxygen/doxygen/files/10479888/log-1.9.6.txt)
[log-with-findmembers-1.9.5.txt](https://github.com/doxygen/doxygen/files/10479889/log-with-findmembers-1.9.5.txt)
[log-with-findmembers-1.9.6.txt](https://github.com/doxygen/doxygen/files/10479887/log-with-findmembers-1.9.6.txt)

**Comment by albert-github** [comment] 2023-01-23 13:57
With the current master version (1.9.7 (b7c51315fa62100f1bd0dd866c3e2145042f00af)) the warning does not appear.
Most likely cause is issue #9756 Doxygen produces invalid output for many C# interpolated strings which is fixed by #9759 

Please check with the current master.

I think the problem is fixed but not released

**Comment by doxygen** [comment] 2023-05-18 20:31
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.7.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2023-05-18 20:31 UTC
Labels: bug, C#
