### ISSUE TITLE
HTML layout: a full sidebar overlaps with breadcrumbs

### ISSUE THREAD

**Issue by JasperCraeghs** [doxygen/doxygen#9430] opened 2022-06-28 11:25 UTC
The sidebar overlaps with breadcrumbs when using the following configuration:

[DISABLE_INDEX](https://www.doxygen.nl/manual/config.html#cfg_disable_index) = YES
[GENERATE_TREEVIEW](https://www.doxygen.nl/manual/config.html#cfg_generate_treeview) = YES
[FULL_SIDEBAR](https://www.doxygen.nl/manual/config.html#cfg_generate_treeview) = YES

It looks like the heights of `div#side-nav` and `div#nav-tree` are calculated by JavaScript but they are too large. They don't take the height of `div#nav-path` (footer)  into account. However, according to https://www.doxygen.nl/manual/customize.html, the breadcrumbs footer shall take the width of the sidebar into account. Instead, it uses the full page width.

![Screenshot_20220628_125316](https://user-images.githubusercontent.com/28319872/176162124-578bf07a-8226-477e-ae9d-6fefa23bce56.png)

I used Doxygen 1.9.4 to produce this example.

I would prefer the footer to use the full width of the page (and have a slightly shorter sidebar) because the breadcrumbs can contain long paths.

**Comment by albert-github** [comment] 2022-06-28 11:30
Looks like some customization has been done (header / footer / css / ... files?)
To be able to reproduce the problem:
- Can you please attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file) that allows us to reproduce the problem? Please don't add external links as they might not be persistent.

**Comment by JasperCraeghs** [comment] 2022-06-28 14:09
Apologies. I removed the custom header, footer and CSS file but kept `FULL_SIDEBAR = YES`. The problem persists.

![Screenshot_20220628_155047](https://user-images.githubusercontent.com/28319872/176195692-80b46cfe-0cb1-4d97-9828-2edddb7e78ac.png)

Don't you experience this problem when building Doxygen's documentation with a full sidebar?

**Comment by albert-github** [comment] 2022-06-28 14:52
I just tried with the doxygen 1.9.4 version and the current doxygen master version (1.9.5 (c50f335cc831356fc4046d70a2174c5649171e1e) and this looks like what I see in the documentation: https://www.doxygen.nl/manual/customize.html#minor_tweaks_treeview

Strange that you see in the breadcrum still (part) of the path.

**Comment by JasperCraeghs** [comment] 2022-06-28 15:05
The rest of the path is hidden behind the overlapping sidebar. If I collapse the sidebar, i.e., slide it all the way to the left, the entire path becomes visible.

So, you see that `<div id="nav-path" class="navpath">` does not take up the full width of the page and respects the width of the full sidebar? 
![layout_noindex_and_sidebar](https://user-images.githubusercontent.com/28319872/176212183-f6182c19-3d32-42f4-86ee-09a9b56d32ae.png)

**Comment by albert-github** [comment] 2022-06-28 15:31
The breadcrum looks OK for me when I use the settings you specified:

- [DISABLE_INDEX](https://www.doxygen.nl/manual/config.html#cfg_disable_index) = YES
- [GENERATE_TREEVIEW](https://www.doxygen.nl/manual/config.html#cfg_generate_treeview) = YES
- [FULL_SIDEBAR](https://www.doxygen.nl/manual/config.html#cfg_generate_treeview) = YES

though as said I don't see (part) of the path in the breadcrum like you do, but it made me think so I moved the (right hand side) divider of the treeview to the left an now I see part of the path as well:

![image](https://user-images.githubusercontent.com/5223533/176219711-4b0dc66a-9081-4b90-9243-13e8b5db195e.png)


(I had to move quite far as I have apparently not the long paths you have).

@doxygen any idea ?

**Comment by doxygen** [comment] 2022-07-02 12:14
@JasperCraeghs Please verify if the referenced commit fixes the problem for you.

**Comment by JasperCraeghs** [comment] 2022-07-04 16:44
I have verified that the referenced commit fixes the problem for me. Thank you.

**Comment by doxygen** [comment] 2022-08-26 16:55
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.5.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2022-08-26 16:55 UTC
Labels: bug, HTML
