### ISSUE TITLE
Private members are documented in XML when EXTRACT_PRIVATE = NO (Origin: bugzilla #666100)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#4504] opened 2018-07-02 06:32 UTC
status NEW severity *normal* in component *general* for *---*
Reported in version *1.7.6.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2011-12-13 16:47:36 +0000, Paul A. Bristow wrote:

    when EXTRACT_PRIVATE = NO
    
    then private members are correctly not documented in html
    
    BUT are still documented in XML
    
    For example
    class test
    {
    private:
        /*!
          This is a dummy private function.
          \return zero always.
          \warning This should not be documented if the Doxygen option is
    selected.
        */
        int private_function(int z)
        {
          return 0;
        }
    }
    
    produces XML containing this:
    
    -<sectiondef kind="private-func"> -<memberdef prot="private" kind="function"
    id="classtest_1a9d5eb4b1d44630a644a2a85b9ec83c78" virt="non-virtual"
    inline="yes" explicit="no" const="no" static="no"> <type>int</type>
    <definition>int test::private_function</definition> <argsstring>(int
    z)</argsstring> <name>private_function</name> -<param> <type>int</type>
    <declname>z</declname> </param> <briefdescription> </briefdescription>
    -<detaileddescription> -<para>This is a dummy private function. -<simplesect
    kind="return"><para>zero always. </para></simplesect> -<simplesect
    kind="warning"><para>This should not be documented if the Doxygen option is
    selected. </para></simplesect> </para> </detaileddescription>
    <inbodydescription> </inbodydescription> <location line="35" file="I:/boost-
    sandbox/quickbook/boost/quickbook/quickbook_demo.hpp" bodyend="37"
    bodystart="34" bodyfile="I:/boost-
    sandbox/quickbook/boost/quickbook/quickbook_demo.hpp"/> </memberdef>
    </sectiondef>
    
    Is this a feature?
    
    Is there some other option that I need to select to prevent private
    documentation appearing the XML output?
    
    
    I have tried to supress using \internal thus:
    
    //! \internal
    private:
        /*!
          This is a dummy private function.
          \return zero always.
          \warning This should not be documented if the Doxygen option is
    selected.
        */
        int private_function(int z)
        {
          return 0;
        }
    //! \endinternal
    
    but the XML still contains the private information.
    
    
    (This is unwanted behaviour because the XML is post-processed).

**Comment by jwakely** [comment] 2019-05-07 11:09
Duplicate of #2405 ?

**Closed** 2019-12-28 11:05 UTC
Labels: duplicate
