### ISSUE TITLE
HTML: Opening a reference link in a new tab does not scroll to the content

### ISSUE THREAD

**Issue by eepp** [doxygen/doxygen#7412] opened 2019-11-20 02:19 UTC
When you put a link to some section, subsection, anchor, etc. like this:

    \ref some-id

Opening the generated link in a new tab (middle-clicking it, for example) opens the correct page, but the scroll position stays at 0: it does not scroll to the content.

However, I noticed that if I open a new, fresh tab and go to the reference URL, it scrolls correctly.

It also works when you go to the reference within the same tab.

**Comment by albert-github** [comment] 2019-11-20 08:57
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

**Comment by eepp** [comment] 2019-11-20 16:29
Here you go: [`doxygen-bug-anchor-no-scroll.zip`](https://github.com/doxygen/doxygen/files/3870250/doxygen-bug-anchor-no-scroll.zip).

Just do:

    $ doxygen Doxyfile

and open the _Hello section_ link on the main page in a new tab (middle-click it, for example). Notice that in the new tab, the scroll bar is at the top.

Now open the link in the same tab. Notice that the scroll position is correct for the _Hello section_ section.

It only does this with `GENERATE_TREEVIEW = YES`.

Using Doxygen 1.8.16.

**Comment by eepp** [comment] 2019-11-20 17:03
By the way, a related issue is that, again with `GENERATE_TREEVIEW = YES`, if you refresh the page, the scroll bar returns to the top.

**Comment by albert-github** [comment] 2019-11-21 14:07
I tried different scenarios but I was not able to reproduce the problem.
Which browser did you use?
Which OS did you use?

**Comment by eepp** [comment] 2019-11-21 16:21
> Which browser did you use?

Chromium 78.0.3904.97

It just tried with Firefox 70.0.1 and there's no issue with it.

> Which OS did you use?

Arch Linux

**Comment by albert-github** [comment] 2019-11-21 16:52
I used the mentioned Firefox  version (on Windows), I'll give Chromium a try later on (needs some updating).

**Comment by albert-github** [comment] 2019-11-21 17:48
I tried with Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

- without treeview everything looks OK to me
  - in old and new tab with and without refresh scrollbar is at bottom position
- with treeview
  - new tab
    - the scroll bar is at the top position
    - refresh set in the new tab the scrollbar at the top position
  - in "old"  tab
    - the scroll bar is at the bottom position
    - refresh set in the new tab the scrollbar at the top position

**Comment by eepp** [comment] 2019-11-21 18:25
Yes that's it.

**Comment by doxygen** [comment] 2019-12-10 20:24
Could you please verify if the commit I just pushed fixes the problem?

**Comment by albert-github** [comment] 2019-12-11 13:42
When using FireFox and <ctrl><left mouse> on the "Hello Section" a new tab opens with title: "javascript:void(0)" and the page is empty.
In Chrome we get a new tab but the scrollbar is at the top. When cliking in the "normal" text it looks OK.
When in Chrome already in the hello page and we click in the treeview to get a new tab we don't get a new tab.

**Comment by doxygen** [comment] 2019-12-27 19:38
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2019-12-27 19:38 UTC
