### ISSUE TITLE
"warning: return type of member ... is not documented" for static void and virtual void functions

### ISSUE THREAD

**Issue by dweindl** [doxygen/doxygen#7411] opened 2019-11-19 20:40 UTC
Doxygen from master (2972f6ddc491f615f814b1277ec715b6f707c419) complains about undocumented return types for `static void` and `virtual void` functions. For regular void functions everything works as expected.

Example `test.cpp`:
```
/** @file test.cpp */

/**
 * @brief This works
 */
void works() {}

/**
 * @brief This fails
 */
static void fails() {}

/**
 * @brief test class
 */
class Test {
    /**
    * @brief This works
    */
    void works() {}

    /**
    * @brief This fails
    */
    virtual void virtualfails() {}

    /**
    * @brief This fails
    */
    static void staticfails() {}
}
``` 

With default Doxyfile and:
```
EXTRACT_PRIVATE        = YES
EXTRACT_PRIV_VIRTUAL   = YES
EXTRACT_PACKAGE        = YES
EXTRACT_STATIC         = YES
WARN_NO_PARAMDOC       = YES
```

Results in:
```
[...]
test.cpp:11: warning: return type of member fails is not documented
[...]
test.cpp:25: warning: return type of member Test::virtualfails is not documented
test.cpp:30: warning: return type of member Test::staticfails is not documented
[...]
```

**Comment by albert-github** [comment] 2019-11-21 13:54
The reported problem looks like to be a consequence of issue issue "1.8.16: Function returning void pointer generates warning" (#7212), the resulting pull request (#7213) and making it more strict.

The mentioned functions have return types:
- virtual void
- static void

but we also have to take into consideration the examples as mentioned in the pull request #7213.

**Comment by SteffenSeckler** [comment] 2020-01-16 13:29
This is also broken for:
```c++
constexpr void f()
```
And will be broken in c++20 for:
```c++
consteval void f();
constexpr virtual void f();
consteval virtual void f();
```

**Comment by Crayon2000** [comment] 2020-01-16 13:56
I'm getting the same error with:
```c
INLINE void f()
```

The INLINE macro is something similar to:
```c
#ifndef INLINE
# if __GNUC__ && !__GNUC_STDC_INLINE__
#  define INLINE extern inline
# else
#  define INLINE inline
# endif
#endif
```
From: http://www.greenend.org.uk/rjk/tech/inline.html

But this can be fixed by using PREDEFINED with
```text
INLINE=
```

**Comment by SteffenSeckler** [comment] 2020-01-16 14:02
@Crayon2000 is this also fixed using 
```
MACRO_EXPANSION        = YES
```
?

**Comment by Crayon2000** [comment] 2020-01-16 14:13
I have changed to following in my file:
```
MACRO_EXPANSION        = YES
EXPAND_ONLY_PREDEF     = YES
PREDEFINED             = INLINE=
```

I think the global rule should that 'ANYTHING void' should be considered like a function / method that doesn't return a value. So no need for a return type documentation!

**Comment by albert-github** [comment] 2020-01-16 14:21
@Crayon2000 
You wrote "ANYTHING void"  but how about "void *fie(void)" or is this not "ANYTHING void" in your definition (it is unclear for me whether you mean: as soon as the word void appears or something else)?

**Comment by SteffenSeckler** [comment] 2020-01-16 14:26
well as discussed in #7483 the return type should not actually include anything like static or virtual, but instead should be just void.
From what I see the function findMember() and similar functions from doxygen.cpp might be intended to do this:
```c++
...
do
  {
    done=TRUE;
    if (funcDecl.stripPrefix("friend ")) // treat friends as related members
    {
      isFriend=TRUE;
      done=FALSE;
    }
    if (funcDecl.stripPrefix("inline "))
    {
      spec|=Entry::Inline;
      done=FALSE;
    }
    if (funcDecl.stripPrefix("explicit "))
    {
      spec|=Entry::Explicit;
      done=FALSE;
    }
    if (funcDecl.stripPrefix("mutable "))
    {
      spec|=Entry::Mutable;
      done=FALSE;
    }
    if (funcDecl.stripPrefix("virtual "))
    {
      done=FALSE;
    }
  } while (!done);
...
```
all these stripPrefixes are probably intended to strip all of these specifiers from the return type.

**Comment by albert-github** [comment] 2020-02-09 11:14
Commit 6c10868a2b31076e8f5e42af0036b43e7f39d2b2 has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by SteffenSeckler** [comment] 2020-02-09 11:15
there is a typo in that commit `constexp` should be `constexpr`!

**Comment by doxygen** [comment] 2020-02-09 12:12
@SteffenSeckler good catch! Fixed now.

**Comment by carlosgalvezp** [comment] 2020-03-10 09:03
Hi,

I get this error also for explicit function template instantiation:

```
// a.h
template <typename T>
void foo(T);
```

```
// a.cpp
template <typename T>
void foo(T t)
{
...
}

// Explicit instantiation
template void foo(float);
template void foo(int);
```

It complains in the .cpp file that the return type of `foo` is not documented.

**Comment by carlosgalvezp** [comment] 2020-03-10 09:12
Also with CUDA specifiers like `__host__ __device__`:

```
__host__ __device__ void foo();
```

**Comment by albert-github** [comment] 2020-03-10 11:18
I tried to reproduce your first issue from but I didn't succeed:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.
- Please also specify the doxygen version used.

Regarding the `__host__ __device__ void foo();` what happens when you set `PREDEFINED` like:
```
PREDEFINED = __host__=
PREDEFINED += __device__=
```
(see also: http://doxygen.nl/manual/preprocessing.html , the part about `__attribute__` and `__declspec`

**Comment by rianquinn** [comment] 2020-03-23 12:45
Once this is fixed, please roll a release as this is a huge blocker for the current release. I had to roll back as a result of this as all template functions returning void generate this warning if they are marked as constexpr (which in modern code could be almost all of them).

**Comment by albert-github** [comment] 2020-03-23 12:50
@rianquinn looks like that this has been fixed in the current master.

- did you try the current master?
- when not fixed in the current master:
  - please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

When you cannot create the current master, add a, small, self contained example so we can have a quick look whether or not the problem has been solved.

**Comment by jpboivin** [comment] 2020-03-23 13:59
@albert-github I might be wrong, but I think his point was more to release a new version of doxygen as soon as possible with the fix. We are in the same boat as him, we cannot use the latest release due to that bug, and previous versions had other bugs impacting us. In the end, we had to rollback to 1.8.14 to have something working.

**Comment by albert-github** [comment] 2020-03-23 14:16
@jpboivin  This is most likely true, I just wanted to be sure that the problems as seen bu @rianquinn are solved by means of a new release i.e. by testing the master version this could be checked. Same ofcourse accounts for you.

**Comment by rianquinn** [comment] 2020-03-23 17:58
@albert-github and @jpboivin You are correct. I need a version that other users can just install as well as something for our CI to use. Although this might be fixed in master, we really need a release rolled. For now, 1.8.15 seems to be working, but there doesn't seem to be any links on GitHub or the website for this (I found a version of this on SourceForge).

**Comment by albert-github** [comment] 2020-03-23 18:01
@rianquinn I don't know when the next release is planned, but it would at least be valuable to know that your problems are solved in the master (might expedite a release, but not guaranteed).

**Comment by rianquinn** [comment] 2020-03-23 19:46
@albert-github I added that to my list of Todos as I definitely can compile it myself and give it a test to see if it is working.

**Comment by doxygen** [comment] 2020-04-13 11:49
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.18.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2020-04-13 11:49 UTC
Labels: bug

**Comment by spdw** [comment] 2020-05-07 08:45
@albert-github 
> @Crayon2000
> You wrote "ANYTHING void" but how about "void *fie(void)" or is this not "ANYTHING void" in your definition (it is unclear for me whether you mean: as soon as the word void appears or something else)?

I assume it means everything that ends with "` void`". The mentioned "`void *fie(void)`" has a closing round bracket `)` at the end and thus does not end with "` void`". When following that approach it is possible to have "information" just before the `void`. For Qt this is important to generate the `Q_INVOKABLE` https://doc.qt.io/qt-5/qobject.html#Q_INVOKABLE into the output.

In https://github.com/doxygen/doxygen/blob/master/src/memberdef.cpp#L4074
```
bool isVoidReturn = returnType=="void";
```
could be changed to
```
bool isVoidReturn = (returnType=="void") || (returnType.right(5)==" void");
```
With change it would be possible to correctly detect the void return type for signatures like `Q_INVOKABLE void invokableMethod();` **and** have the `Q_INVOKABLE` in the generated output. With the `PREDEFINED = Q_INVOKABLE =` solution it is not visible in the output anymore.

**Comment by albert-github** [comment] 2020-05-07 08:56
I just did a quick test with a default doxygen configuration file and `Q_INVOKABLE void invokableMethod();` and I did see the `Q_INVOKABLE` as part of the type in the documentation (doxygen version 1.8.18).

I case you think there still is a problem or that I missed something please open a **new** issue with a small example etc.
