### ISSUE TITLE
html output from markdown: cannot use formatted text in section titles

### ISSUE THREAD

**Issue by AndyHeather** [doxygen/doxygen#7135] opened 2019-07-22 12:01 UTC
Adding markdown formatters to section titles produces html where the formatter tags are rendered verbosely, e.g. the following input

    # TEST   {#mainpage}

    [TOC]

    ## Section 1 {#section1}

    Some text for Section 1

    ## Section with **strong** content  {#section2}

    Some more text  

    ## Section with *italic* content  {#section3}

    Some more text  

generates:

![output](https://user-images.githubusercontent.com/11627707/61630669-3a92c780-ac80-11e9-8094-2eca3119d48d.png)

It also appears to not render the TOC?

Running code at commit 527fa741

Test case: [issue-section-titles.tar.gz](https://github.com/doxygen/doxygen/files/3417217/issue-section-titles.tar.gz)

**Comment by albert-github** [comment] 2019-07-22 12:03
This looks to me a duplicate of #6998

**Comment by AndyHeather** [comment] 2019-07-22 12:55
Agreed - and missing TOC?

**Comment by albert-github** [comment] 2019-07-22 13:03
You mean the in page TOC on the right hand side?

In your `Doxyfile` I see
```
TOC_INCLUDE_HEADINGS=0
```
this should have a value of 5 (the default value of `0` was a bug and has been corrected in the mean time to a default value of `5`, but old `Doxyfile`s still will have `0` even after a `doxygen -u`.

**Comment by AndyHeather** [comment] 2019-07-22 14:31
thanks - missed that one

**Closed** 2019-12-28 11:05 UTC
Labels: duplicate
