### ISSUE TITLE
Unexpected <br /> placement after function body comments in HTML

### ISSUE THREAD

**Issue by danderson023546** [doxygen/doxygen#6593] opened 2018-11-02 15:39 UTC
When using C-Style comments of the format: /** - ... */ inside function bodies, the HTML output produced places excess `<br />`'s for each comment. Eg. If there are 10 comments within the body of the function, the first comment in the HTML layout will be followed by 10 `<br />`, the next by 9, then 8, etc.

The expected behavior of this is to print the comments in a list, one after another, without excess white space printed between them.

**Comment by albert-github** [comment] 2018-11-02 15:41
Can you please attach a, small, self contained example (source+config file in a tar or zip) that allows us to reproduce the problem?
Please also specify the doxygen version used.

**Comment by danderson023546** [comment] 2018-11-02 18:02
I did attach it to the E-Mail, as GitHub wasn't appearing to attach the file. I'll attempt to attach it to this response in the GitHub GUI itself, now.

**Comment by danderson023546** [comment] 2018-11-02 18:12
Incase it has not worked, I've uploaded the zip to a dropbox. https://www.dropbox.com/s/4xfd2k4bcmoi7hg/ExampleProblem.zip?dl=0

**Comment by albert-github** [comment] 2018-11-02 19:18
I don't see it directly on github. The problem with dropbox is that I have to create an account but just by selecting the dropbox a second time the log-in window doesn't appear, maybe it was only a friendly reminder.

You can attach it to github just drag&drop or use the link (the 2 oval symbols in the header of a comment).

**Comment by albert-github** [comment] 2018-11-02 19:28
I checked with version 1.8.14 and I see the described behavior.
With the current master the problem is gone:
![result_master](https://user-images.githubusercontent.com/5223533/47936321-942e4880-dedd-11e8-95bc-398c43eec9b1.png)


So I think the problem has been solved but is not yet released.

**Comment by doxygen** [comment] 2018-12-27 21:47
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.15.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2018-12-27 21:47 UTC
Labels: bug
