### ISSUE TITLE
Italic doesn't italicize parentheses

### ISSUE THREAD

**Issue by Hi-Angel** [doxygen/doxygen#10696] opened 2024-02-28 14:39 UTC
**Describe the bug**

While writing non-code markdown documentation I noticed that Doxygen has failed to render many `*`-symbols all over the text. Upon reducing this to a minimal testcase it turns out Doxygen fails with it meets this syntax: `some text *(some remark about the text)*`. As I always italize remarks, these asterixes are all over the place.

**Expected behavior**

In the opened browser window the `(italic)` part of text is italic.

**To Reproduce *(in terms of terminal commands)***

```haskell
λ cat mainpage.md
# Test

This is *(italic)*.
λ doxygen -g Doxyconfig


Configuration file 'Doxyconfig' created.

Now edit the configuration file and enter

  doxygen Doxyconfig

to generate the documentation for your project
λ sed -i 's/^USE_MDFILE_AS_MAINPAGE\s*=/USE_MDFILE_AS_MAINPAGE = mainpage.md/g' Doxyconfig
λ doxygen Doxyconfig
[…]
λ xdg-open html/index.html
```

**Version**
* doxygen version `1.10.0 (GIT-NOTFOUND)`, from the Archlnux repo
* `lsb_release -a`
    ```
    LSB Version:    n/a
    Distributor ID: Arch
    Description:    Arch Linux
    Release:        rolling
    Codename:       n/a
    ```

**Comment by albert-github** [comment] 2024-02-28 17:36
The problem is originating from `markdown.cpp`:
```
int Markdown::Private::processEmphasis(std::string_view data,size_t offset)
{
  AUTO_TRACE("data='{}' offset={}",Trace::trunc(data),offset);
  const size_t size = data.size();

  if ((offset>0 && !isOpenEmphChar(data.data()[-1])) || // invalid char before * or _
      (size>1 && data[0]!=data[1] && !(isIdChar(data[1]) || extraChar(data[1]) || data[1]=='[')) || // invalid char after * or _
      (size>2 && data[0]==data[1] && !(isIdChar(data[2]) || extraChar(data[2]) || data[2]=='[')))   // invalid char after ** or __
  {
    return 0;
  }
```
and 
```
#define extraChar(c) \
  (c=='-' || c=='+' || c=='!' || \
   c=='?' || c=='$' || c=='@' || \
   c=='&' || c=='*' || c=='%')
```

@doxygen Is there a reason why `(` as not in this list of allowed extraChar characters?
Especially as `[` is explicitly added  (could be in the #define!)

**Comment by Hi-Angel** [comment] 2024-03-12 09:03
@doxygen ping

**Comment by Hi-Angel** [comment] 2024-03-21 08:02
@albert-github I did some research. The `define` you're referring to was added in commit a95c07ecc0. This commit was fixing a problem similar to this bugreport, specifically that `__-1__` was not getting highlighted *(and `_-1_` or `*-1*` too for that matter)*.

The commit fixed the problem by adding a macro enlisting allowed non-alphabetic characters. So to answer your question:

> @doxygen Is there a reason why `(` is not in this list of allowed extraChar characters?

It's just an omission, it wasn't on purpose.

Thankfully Doxygen has a good commit history, so we can dig into it and answer the question without bothering the original author 😊

**Comment by Hi-Angel** [comment] 2024-05-29 18:41
@albert-github I hope you don't mind: it's been 2.5 months with no reply, so I went ahead and made a PR 😊

I tested the change and it fixes the problem.

**Comment by albert-github** [comment] 2024-05-30 07:21
I have no objections, though:
- It is not only the `(` that has problems but also some more, see the issue #8900, so I think an even more general approach would be better
- you used  the the fix with the number of the related issue, due to the "magic" of GitHub adds a link to the issue (good) but it also adds a link that will automatically close the issue when this proposed Pull Request is integrated:
  ![image](https://github.com/doxygen/doxygen/assets/5223533/3b2a1583-c235-428a-afd9-3b2539cde7c7)
  doxygen leaves the issues open and will  automatically close the issue with a new release , please remove this automatic closing  "merge" link.

**Comment by Hi-Angel** [comment] 2024-05-30 19:23
@albert-github I think I addressed everything, please see if it's okay now.

Regarding the issue you linked: I fixed it in a separate commit, and one another. There are still problematic places with rendering, but I decided to fix the low-hanging fruit for now.

As a side note: I didn't include into the characters list a `<`, because I am afraid of potential regressions in case the `<` was meant to be an html code opening tag. It may or may not work, but I decided to be on the safe side for now and leave that as is.

**Comment by Hi-Angel** [comment] 2024-05-30 19:26
As a side-note, the whole `isIdChar(data[1]) || extraChar(data[1])` action should be instead a list of "unallowed characters", because their amount is far less than those that are allowed. But I'm afraid of commiting to such change myself at the moment.

**Closed** 2024-10-23 08:48 UTC
Labels: bug, Markdown
