### ISSUE TITLE
///<[in] looses [in] (Origin: bugzilla #751278)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5807] opened 2018-07-02 11:26 UTC
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.9.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-06-21 13:48:22 +0000, William Roeder wrote:

    :
        * @param   [out] aValues  Array Enlarged if necessary.
    */
       bool     copy_series(double& aValues[],
                            INDEX    buffer,  ///< [in] Which indicator buffer.
                            INDEX    iEnd,    //!<[in] One past the end.
                            INDEX    iBegin=0,///<[in] Starting position.
                            string   msg=__FUNCTION__)/**<[in]
    Diagnostic.*/MUTABLE{
    
    produces:
    Parameters
        [out]	aValues	Array Enlarged if necessary.
    
    Parameters
        buffer	Which indicator buffer.
        iEnd	One past the end.
        iBegin	Starting position.
        msg	Diagnostic.

**Comment by albert-github** [comment] 2019-12-26 12:22
I tried to reproduce the problem based on the given information, but I always see the `[in]`. with the 1.8.9.1 version as well as with older versions (and with the current version).

Based on the information I think it should be closed as I think the problem is not reproducible / invalid.

**Closed** 2019-12-27 19:53 UTC
Labels: invalid
