### ISSUE TITLE
1.8.16: Image inclusion is inconsistent

### ISSUE THREAD

**Issue by dkageff** [doxygen/doxygen#7210] opened 2019-08-19 16:51 UTC
I am including several images in the generated documentation using the \image command.  when I first generate the document, the images show up.  However, when I change anything in the source files (not any \image lines) and regenerate the document, the images do not show up even though no image files or \image commands have changed.  I can only get them to show up again if I delete all of the files in the html folder.  Version 1.8.15 does not exhibit this problem.

**Comment by albert-github** [comment] 2019-08-19 17:00
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by dkageff** [comment] 2019-08-19 17:22
[Issue example files.zip](https://github.com/doxygen/doxygen/files/3516938/Issue.example.files.zip)
Hopefully these files help

**Comment by dkageff** [comment] 2019-08-19 17:23
Accidently closed the issue

**Comment by albert-github** [comment] 2019-08-19 17:47
I see indeed some problems e.g. on the main page (i.e. spec/html/index.html
A difference between the html output in one loop and 2 loops gives:
```
125c125
< <img src="BT cluster HW blk.png" alt=""/>
---
> <img src="" alt=""/>
137c137
< <img src="BT_cluster_system_seq_diagram.png" alt=""/>
---
> <img src="" alt=""/>
```
so in the second loop the  result is set to `<img src="" alt=""/>`.
And in the 2 loops case also the images like:
```
Only in spec\html: BT cluster HW blk.png
Only in spec\html: BT_cluster_system_seq_diagram.png
```
are gone.

To be investigated.

**Comment by albert-github** [comment] 2019-08-19 18:09
Looks like it has to do with the "ambiguous" message in the warnings log file (new in doxygen 1.8.16):
```
.../issue_7210/App/Design/doxy_mainpage.h:49: warning: image file name BT cluster HW blk.png is ambiguous.
Possible candidates:
   .../issue_7210/App/Design/spec/html/BT cluster HW blk.png
   .../issue_7210/Design/diagrams/BT cluster HW blk.png
```
so doxygen at the moment cannot decide which one of the images to take. It is still a bit strange that the images are gone.

The problem is caused by the fact that in the `IMAGE_PATH`  the current directory (`.`) is searched as well as its subdirectories. 
Removing the current directory solves the problem.

So I think the problem is usage, though I also see some potential for improvement, i.e. in case all the potential images are identical we have no ambiguity so we could use the image.

**Comment by doxygen** [comment] 2019-08-19 18:59
This is probably due to [this change](https://github.com/doxygen/doxygen/commit/b676f2009ba9e6e953f9e3a999342b7dad79b1bf). I think for images that are found more than once, we should still use it (old behavior) *and* generate a warning, instead of only giving a warning.

**Comment by albert-github** [comment] 2019-08-20 08:54
The result can be that a wrong image is shown in the documentation.

Note: my remark regarding " It is still a bit strange that the images are gone." was caused by the fact that I had a (html_one) directory with the results of the results of the one pass test when I did the two pass test so that the searching found already a ambiguous situation.

**Comment by albert-github** [comment] 2019-08-20 10:37
I've just pushed a proposed patch, pull request #7211

**Comment by albert-github** [comment] 2019-08-20 17:00
As as side note.

When searching for the INPUT files and INCLUDE directories the `EXCLUDE_PATTERNS` tag is used. In the code though the `HTML_OUTPUT`, `LATEX_OUTPUT` etc. directories are automatically added to this list (depending on the `GENERATE_...` setting). See currently at line 11300 of doxygen.c (comment says: "prevent search in the output directories")

For other search lists, like `IMAGE_PATH`, `EXAMPLE_PATH` / `EXAMPLE_PATTERNS` etc. the output directories are not excluded, this looks a bit inconsistent.

@doxygen Question is now: should we also exclude the appropriate output directories for `IMAGE_PATH` etc. as well?

**Comment by albert-github** [comment] 2019-12-24 10:52
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Closed** 2019-12-27 19:54 UTC
Labels: Usage, bug, fixed but not released
