### ISSUE TITLE
Force line buffering

### ISSUE THREAD

**Issue by RedDwarf69** [doxygen/doxygen#8329] opened 2021-01-12 17:25 UTC
**Describe the bug**
When running Doxygen in Jenkins (or in a terminal, but redirecting stdout/stderr to a file or any other non-interactive device) the output of stdout and stderr is interleaved and difficult to read. This can cause Jenkins builds to fail if they are, for example, using the Warning NG plugin since it will complain it can't find a file named `/ho/home/user/file.c` or similar.

**Expected behavior**
The output is readable even if sent to a non-interactive device.
It's maybe controllable with an option, but I'm not sure there is a need for it.

**To Reproduce**
Get a project generating warnings and run `doxygen &>output`.

**Version**
1.9.2

**Comment by albert-github** [comment] 2021-01-12 17:40
I think you are talking about the interleaving of the warning messages and progress output.

The warnings are going to stderr and the progress output is going to stdout, when not redirecting both streams they will appear interleaved like they are outputted by doxygen. When using a redirection it is depending on the used OS how they are interleaved due to the buffering used by the OS.

There are a number of possibilities:
- redirect stdout and / or stderr to separate files and show the redirected output when doxygen finished
- set the stdout and stderr for the OS in the OS to unbuffered
- suppress the progress output by setting `QUIET=YES`
- redirect the warnings etc. by means of the setting if `WARN_LOGFILE`
- use a combination of the above.

I think the right choice is up to the user.

**Comment by RedDwarf69** [comment] 2021-01-12 18:07
> I think you are talking about the interleaving of the warning messages and progress output.

Yes.

I only really know glibc's behaviour (line buffering for interactive devices, "full" buffering otherwise). But isn't it basically universal?

I agree the user has options to handle the issue. But,
- "... and now I will send the output to a file for X"... hey, why is it now different?
- "I have tested it in my terminal and Doxygen works fine, I will put the exact same thing in my Jenkinsfile"... hey, why is it problematic in Jenkins?

Is not an ideal situation.

Defaulting to line buffering (`#ifdef GLIBC` if you think it makes sense) would avoid those situations.

**Comment by RedDwarf69** [comment] 2021-01-12 18:10
FWIW for my personal usage I'm fine using coreutils "stdbuf", I'm OK if you want to close this issue. I just think there must be people out there finding those issues who are not going to immediately say "oh yes, it's the buffering, obviously. I will just quickly do X".

**Comment by doxygen** [comment] 2021-01-12 19:10
doxygen has a not so well known command line option `-b` to make the stdout unbuffered.

So you should be able to get properly interleaved output using:

```
doxygen -b > out.txt 2>&1
```

**Comment by albert-github** [comment] 2021-01-13 12:45
The problem is usage, but it would be nice to have some documentation about it e.g. in the FAQ section.

I've just pushed a proposed patch, pull request #8332

**Comment by albert-github** [comment] 2021-04-30 08:27
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment] 2021-08-18 20:14
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.2.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2021-08-18 20:14 UTC
Labels: enhancement, documentation
