### ISSUE TITLE
include dependency graph: The boxes of files shows the name of the included file not its own filename 

### ISSUE THREAD

**Issue by sl42** [doxygen/doxygen#7934] opened 2020-07-30 21:58 UTC
I normally use doxygen under Windows with CLANG_ASSISTED_PARSING = YES.
With one of the latest doxygen 1.8.19 releases I noticed a real weird representation of the include dependency graph. The boxes of the files show now the names of the included header file and not the name of the file itself any more.

Here is a simple example (see attachment). Given are the following header files:

`Header File         :   Contains include statements                                   `
`======================================================================================`
`root_header.h                                                                         `
`layer_1_header_1.h  :   #include "root_header.h"                                      `
`layer_2_header_1.h  :   #include "layer_1_header_1.h"                                 `
`layer_3_header_1.h  :   #include "layer_2_header_1.h"                                 `
`layer_3_header_2.h  :   #include "layer_2_header_1.h" #include "layer_1_header_1.h"   `

What I expect is more or less this:
![grafik](https://user-images.githubusercontent.com/25041107/88977229-d3a9e480-d2bd-11ea-8d22-672ac0a039f6.png)

What I get with the latest Doxygen versions is this (it is reporducable):
![grafik](https://user-images.githubusercontent.com/25041107/88977398-21bee800-d2be-11ea-9e8e-95ae141382ee.png)

With an older 1.8.19 version (built 1 month ago) this effect does not occur).

Can it be that problem belongs to the commit https://github.com/doxygen/doxygen/commit/50fdb591d4abfdf88bfdda96ffd832cc4c024963 ? 

Here is the detailed info about my used doxygen version:
- doxygen --version
1.8.19 (b52706b8ee01f45cc3616c52c78dcc8b2d21b464*)
- compiled with Visual Studio 2019 16.6.5
- clang / llvm version 10.0
- OS: Windows 10 Pro 64 bit

Here is this simple example including the doxygen file:

[doxygen_dependency_include_graph_problem.zip](https://github.com/doxygen/doxygen/files/5003823/doxygen_dependency_include_graph_problem.zip)

Best regards and thank you for your help

**Comment by doxygen** [comment] 2020-07-31 09:30
@sl42 Thanks for the clear bug report. Please check if the problem is gone with the fix I just commited. Please keep the bug report open even if it is fixed; it will be closed automatically when a new release is made.

**Comment by doxygen** [comment] 2020-08-08 17:15
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.19.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2020-08-08 17:15 UTC
