### ISSUE TITLE
Have blazingly fast syntax checking mode (Origin: bugzilla #570778)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3256] opened 2018-07-02 01:50 UTC
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.7.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-02-06 11:10:28 +0000, Frans Englich wrote:

    To use doxygen for very large projects(for instance, Qt) it would be very
    practical if doxygen could report the syntax errors very quickly. It's a bit
    of a showstopper if developers have to wait for a very long time to get to
    know the syntax errors, or if an automated regression setup takes a very
    long time to run. In these cases the output is not of interest.
    
    Therefore it would be practical to have a mode which disables output(and
    hence all passes/checks/resolves related to that), and only reports syntax
    errors, missing link targets and so forth.

On 2009-02-08 15:51:31 +0000, Dimitri van Heesch wrote:

    When you talk about "syntax errors" do you mean errors in the comment blocks
    only or errors in the C++ code (i.e. compiler errors)?
    
    
    
    

On 2009-02-12 09:11:53 +0000, Frans Englich wrote:

    I mean those errors/warnings that doxygen produce when run upon a source
    which has no build errors. So yes, the errors in comment blocks.
    
    Running a relatively stripped down doxygen configuration on Qt takes about
    ten minutes, trying to cut that down.

**Comment by albert-github** [comment] 2024-06-15 10:28
Marking this as duplicate of #10938

**Closed** 2024-08-07 09:39 UTC
Labels: duplicate, enhancement
