### ISSUE TITLE
Report warning with wrong file and wrong line number

### ISSUE THREAD

**Issue by zejiang0jason** [doxygen/doxygen#10414] opened 2023-11-14 15:08 UTC
**Describe the bug**
I am using doxygen 1.9.8. The test project is attached. In this project there are two files, wrong.dox and right.dox. The content of these two files are added to the same group.
right.dox content is right, wrong.dox contains a warning. While running doxygen, it reports **right.dox** has warning.
[test_dox.zip](https://github.com/doxygen/doxygen/files/13350215/test_dox.zip)

**Expected behavior**
doxygen shall report the warning is in wrong.dox.

**Screenshots**
Doxygen log warning
`test_dox/right.dox:8: warning: Invalid list item found`
![image](https://github.com/doxygen/doxygen/assets/31212062/84bf592a-e403-4806-86b1-bcada994966d)

**To Reproduce**
Zip package attached.

**Version**
1.9.8 

**Stack trace**
No crash.

**Additional context**
No.

Thank you.

**Comment by albert-github** [comment] 2023-11-15 11:20
I've just pushed a proposed patch, pull request #10416

**Comment by zejiang0jason** [comment] 2023-11-17 01:44
Hi @albert-github , thanks for quick feedback, I tried but doesn't help

**Comment by albert-github** [comment] 2023-11-17 08:28
@zejiang0jason 
What did you try, with which version? Did you build your doxygen executable yourself or from where did you get the executable?

**Comment by albert-github** [comment] 2023-11-18 09:45
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by zejiang0jason** [comment] 2023-11-21 13:28
> @zejiang0jason What did you try, with which version? Did you build your doxygen executable yourself or from where did you get the executable? With your example I got:
> 
> ```
> .../wrong.dox:8: warning: Invalid list item found
> ```

Hi @albert-github , yes, I build the executable locally, based on the PR code.

**Comment by albert-github** [comment] 2023-11-21 14:48
I think the warning is correct as the indentation of the list in wrong.dox is incorrect, the item:
```
  - TITLE 1
```
has an indentation of 2, whilst the corresponding:
```
 - TITLE 2
```
has an indentation of 1 and this is reported by the warning message (before the fix the warning was pointing to the wrong file).

**Comment by zejiang0jason** [comment] 2023-11-22 02:52
Hi @albert-github , I built locally but the warning is still reported in incorrect place.
```
[~/test/test_dox]$ /usr/local/bin/doxygen --version
1.10.0 (4729e92540dbf6eb971fbec73f8fc855bb84a0b7*)
```
```
test/test_dox/right.dox:8: warning: Invalid list item found
```

I think I can try with next doxygen formal release. thanks.

**Comment by albert-github** [comment] 2023-11-22 09:34
That is very weird. 
It looks like that in case of `/usr/local/bin/doxygen --version` you use a different executable than in case you test the example.
Can you try to test your example again but with in the `Doxyfile` see to it that `QUIET  = NO` so you will get messages about progress etc. On the first line you will also see the full doxygen identification, is this also the `1.10.0 (4729e92540dbf6eb971fbec73f8fc855bb84a0b7*)` version?

**Comment by zejiang0jason** [comment] 2023-11-22 13:15
Hi @albert-github , I confirmed I am using the desired one, this is the log I got
```
Doxygen version used: 1.10.0 (4729e92540dbf6eb971fbec73f8fc855bb84a0b7*)
Searching for include files...
Searching for example files...
Searching for images...
Searching for dot files...
Searching for msc files...
Searching for dia files...
Searching for files to exclude
Searching INPUT for files to process...
Reading and parsing tag files
Parsing files
Preprocessing /home/jason/test/test_dox/wrong.dox...
Parsing file /home/jason/test/test_dox/wrong.dox...
Preprocessing /home/jason/test/test_dox/right.dox...
Parsing file /home/jason/test/test_dox/right.dox...
Building macro definition list...
Building group list...
Building directory list...
Building namespace list...
Building file list...
Building class list...
Building concept list...
Computing nesting relations for classes...
Associating documentation with classes...
Associating documentation with concepts...
Associating documentation with modules...
Building example list...
Searching for enumerations...
Searching for documented typedefs...
Searching for members imported via using declarations...
Searching for included using directives...
Searching for documented variables...
Building interface member list...
Building member list...
Searching for friends...
Searching for documented defines...
Computing class inheritance relations...
Computing class usage relations...
Flushing cached template relations that have become invalid...
Computing class relations...
Add enum values to enums...
Searching for member function documentation...
Creating members for template instances...
Building page list...
Search for main page...
Computing page relations...
Determining the scope of groups...
Computing module relations...
Sorting lists...
Determining which enums are documented
Computing member relations...
Building full member lists recursively...
Adding members to member groups.
Computing member references...
Inheriting documentation...
Generating disk names...
Adding source references...
Adding xrefitems...
Sorting member lists...
Setting anonymous enum type...
Computing dependencies between directories...
Generating citations page...
Counting members...
Counting data structures...
Resolving user defined references...
Finding anchors and sections in the documentation...
Transferring function references...
Combining using relations...
Adding members to index pages...
Correcting members for VHDL...
Computing tooltip texts...
Generating style sheet...
Generating search indices...
Generating example documentation...
Generating file sources...
Generating file documentation...
Generating page documentation...
Generating docs for page test...
/home/jason/test/test_dox/right.dox:8: warning: Invalid list item found
Generating group documentation...
Generating class documentation...
Generating concept documentation...
Generating module documentation...
Generating namespace documentation...
Generating graph info page...
Generating directory documentation...
Generating index page...
Generating page index...
Generating topic index...
Generating module index...
Generating module member index...
Generating namespace index...
Generating namespace member index...
Generating concept index...
Generating annotated compound index...
Generating alphabetical compound index...
Generating hierarchical class index...
Generating member index...
Generating file index...
Generating file member index...
Generating example index...
finalizing index lists...
writing tag file...
Running plantuml with JAVA...
type lookup cache used 0/65536 hits=0 misses=0
symbol lookup cache used 0/65536 hits=0 misses=0
finished...

```

**Comment by albert-github** [comment] 2023-11-22 13:46
Getting even more weird, looks all OK.
I assume you see the lines:
```
                                          addOutput(yyscanner," \\ifile \""+ yyextra->fileName);
                                          addOutput(yyscanner,"\" \\ilinebr \\iline " + QCString().setNum(yyextra->lineNr));
```
in commentscan.l around line 1383.

What happens when you run:
```
doxygen -d commentscan > commentscan.txt
```
and post /attach the file `commentscan.txt` so I can inspect that file.

**Comment by zejiang0jason** [comment] 2023-11-22 14:38
Yes, I can see your changes in commentscan.l.

The log attached. thanks.
[commentscan.txt](https://github.com/doxygen/doxygen/files/13440840/commentscan.txt)

**Comment by albert-github** [comment] 2023-11-22 15:00
Looks like this shines a bit of a light on the problem.
In the example I have I have in the files `wrong.dox` and `right.dox` the statement `@addtogroup test TEST` whilst from the `commentscan.txt` I see that you have(most likely) `@page test TEST` in these files. When I adjust the files accordingly I do see again the line
```
right.dox:8: warning: Invalid list item found
```
which is the wrong line, so we have here a problem with the same type of root cause but triggered in a different way, I have to think about this....

**Comment by albert-github** [comment] 2023-11-22 15:34
I've just pushed a proposed patch, pull request https://github.com/doxygen/doxygen/pull/10437 now for the `page` part

**Comment by zejiang0jason** [comment] 2023-11-23 02:00
Hi @albert-github , thanks, the new patch works:)

**Comment by albert-github** [comment] 2023-11-23 08:53
Code (#10437) has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by doxygen** [comment] 2023-12-25 11:04
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.10.0.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2023-12-25 11:04 UTC
Labels: bug
