### ISSUE TITLE
Code indentation sometimes not displayed in Safari with SEARCHENGINE off (Origin: bugzilla #731083)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5495] opened 2018-07-02 10:15 UTC
status NEW severity *minor* in component *build* for *---*
Reported in version *1.8.7* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[Doxyfile](https://sourceforge.net/projects/doxygen/files/attachments/bug731083_277695_Doxyfile/download/download)_ (ID 277695)
- _[Screenshot1.png](https://sourceforge.net/projects/doxygen/files/attachments/bug731083_277696_Screenshot1.png/download/download)_ (ID 277696)
- _[Screenshot2.png](https://sourceforge.net/projects/doxygen/files/attachments/bug731083_277697_Screenshot2.png/download/download)_ (ID 277697)

On 2014-06-01 17:07:50 +0000, John McNamara wrote:

    Created attachment 277695
    Doxyfile
    
    This one is a little odd and took me a while to isolate.
    
    Summary:
    --------
    
    Code indentation in rendered HTML code blocks is occasionally not displayed
    when the SEARCHENGINE option is set to NO.
    
    System information:
    
        $ doxygen --version
        1.8.7
    
        OS = OS X 10.9.3
    
        Safari = 7.0.4
    
    
    Steps to reproduce:
    -------------------
    
    
    Create a new directory and generate a new Doxyfile:
    
        $ mkdir mydox
        $ cd mydox/
    
        $ doxygen -g
    
    
        Configuration file `Doxyfile' created.
    
        Now edit the configuration file and enter
    
          doxygen Doxyfile
    
        to generate the documentation for your project
    
    
    Create a sample C file like the following (indentation is 4 spaces):
    
        $ cat > sample.c
        /**
        @page sample This is a sample page
    
        Some code:
    
        @code
        struct expense {
            char type[32];
            int  cost;
        };
        @endcode
    
    
        */
    
    Modify the Doxyfile to add the C file and turn off the SEARCHENGINE:
    
        $ vi Doxyfile
    
    The Doxyfile has the following 2 changes (the file is attached):
    
        $ git diff
        diff --git a/Doxyfile b/Doxyfile
        index b44af82..6dcb157 100644
        --- a/Doxyfile
        +++ b/Doxyfile
        @@ -754,7 +754,7 @@ WARN_LOGFILE           =
         # spaces.
         # Note: If this tag is empty the current directory is searched.
    
        -INPUT                  =
        +INPUT                  = ./sample.c
    
         # This tag can be used to specify the character encoding of the source
    files
         # that doxygen parses. Internally doxygen uses the UTF-8 encoding.
    Doxygen uses
        @@ -1497,7 +1497,7 @@ MATHJAX_CODEFILE       =
         # The default value is: YES.
         # This tag requires that the tag GENERATE_HTML is set to YES.
    
        -SEARCHENGINE           = YES
        +SEARCHENGINE           = NO
    
         # When the SERVER_BASED_SEARCH tag is enabled the search engine will be
         # implemented using a web server instead of a web client using
    Javascript. There
    
    
    Generate the HTML output and view the file:
    -------------------------------------------
    
        $ doxygen
        $ open html/sample.html
    
    
    Reload the file a 2-5 times. Sometimes the indentation will be shown,
    sometimes it won't be. See attached screenshots.
    
    This doesn't happen with Chrome on OS X and doesn't happen in Safari when
    SEARCHENGINE = YES.
    
    It is probably a Safari issue and I can workaround it but just so you are
    aware of it and just in case you are aware of some doxygen.css issue that
    may be causing it.
    
    Thanks for a great tool.
    
    John.
    --

On 2014-06-01 17:08:38 +0000, John McNamara wrote:

    Created attachment 277696
    Screenshot showing indentation

On 2014-06-01 17:09:19 +0000, John McNamara wrote:

    Created attachment 277697
    Screenshot without indentation

**Comment by jmcnamara** [comment] 2018-07-30 17:05
+1

**Comment by albert-github** [comment] 2023-03-24 18:40
@jmcnamara 
From the comment on July 30, 2018 I assume that at that stage the problem was still present.
Hard  problem for me to reproduce as I don't have Safari.

- Does this problem still occur with the current doxygen 1.9.6 version of doxygen?
- Which version of Safari did you use.

**Comment by jmcnamara** [comment] 2023-03-25 17:51
Hi @albert-github,

Thanks for following up. I can't reproduce this with Doxygen 1.8.20 or 1.9.6 (after an upgrade) and Safari version 16.3 (18614.4.6.1.6). So I would suggest closing this as fixed somewhere along the way.

Thanks once more. I really appreciate Doxygen. I think it is a great tool.

**Closed** 2023-05-18 20:27 UTC
Labels: HTML, solved in the mean time
