### ISSUE TITLE
Missing } inserted on DoxyParams in LaTeX

### ISSUE THREAD

**Issue by iabenz** [doxygen/doxygen#6810] opened 2019-02-01 14:04 UTC
I am having issues compiling Doxygen-generated LaTeX with pdflatex. I always get an error at the first instance of DoxyParams similar to the following:
> Chapter 2.
> (test_8h.tex
> ("C:\Users\User\AppData\Local\Programs\MiKTeX 2.9\tex/latex/psnfss\ts1phv.f
> d")
> ("C:\Users\User\AppData\Local\Programs\MiKTeX 2.9\tex/latex/psnfss\t1pcr.fd
> ")
> ! Missing } inserted.
> <inserted text>
>                 }
> l.23 \end{DoxyParams}

I am using Doxygen 1.8.15 and MiKTeX 2.9.6942 x64 on Windows . I have attached a small, self-contained 
[example](https://github.com/doxygen/doxygen/files/2821867/test.zip).

**Comment by albert-github** [comment] 2019-02-01 14:10
Did you recently update MikTeX (i.e. after mid of December 2018)?
I that case the problem is know and a duplicate of #6769.

**Comment by albert-github** [comment] 2019-02-01 16:44
Closing as duplicate of #6769

**Closed by albert-github** 2019-02-01 16:44 UTC
Labels: LaTeX, duplicate, needinfo
