### ISSUE TITLE
Functions defined by macro are missing in the output callgraphs generated by doxygen.

### ISSUE THREAD

**Issue by Heawen** [doxygen/doxygen#9648] opened 2022-10-25 07:23 UTC
**Describe the bug**
The function defined by macro is missing in the callgraph.

In my project, I use "#define ap_declare(type)  type" to define a macro and "ap_declare(int)" to declare the fucntion "func_3()".

I want to get the callgraphs of my project though Doxygen. However, there is no function func3 in the output. Instead, the macro "ap_declare(int)" defining it is recognized as a function.

**Expected behavior**
I want to get the complete and correct callgraph.

**Screenshots**
![image](https://user-images.githubusercontent.com/69815495/197665780-a7dcd09c-2796-419c-b8e5-f20b69e0e960.png)
![image](https://user-images.githubusercontent.com/69815495/197665599-7c155344-c534-4c09-aa5f-6b9b35d86245.png)
![image](https://user-images.githubusercontent.com/69815495/197665709-bcbb301f-1d7c-4cf2-9538-b229dd4dbc72.png)

**To Reproduce**
[test_1025.zip](https://github.com/doxygen/doxygen/files/9857995/test_1025.zip)

**Version**
Doxyfile 1.9.5

**Comment by albert-github** [comment] 2022-10-25 08:19
Form a comment with #5918

>    The call graph information is based on the data gathered by the source
>    browser, which looks at the un-preprocessed files. This is why you see the
>    relation. This is known limitation.

So I think this is a duplicate of (at least) #5918

**Comment by Heawen** [comment] 2022-10-25 13:13
I find this problem can be solved by setting "MACRO_EXPANSION        = YES".
However, this problem still exist when the macros are defined in other '.h' files, such as:
[test_1025-1.zip](https://github.com/doxygen/doxygen/files/9860516/test_1025-1.zip)

Later, I find this problem can be solved by "EXPAND_AS_DEFINED      = ap_declare" or "PREDEFINED      = ap_declare".

But, there are 3000+ macros in my project. Is there any methods to solve this problem? or How to put all macros in "PREDEFINED"?

**Comment by albert-github** [comment] 2022-10-25 14:34
I don't get what you actually solved as I don't see a settings file (`Doxyfile`) in your project.
When I take the settings file from your first example and set either `EXPAND_AS_DEFINED` or `PREDEFINED ` as indicated I don't see any difference.

Small remark regarding the example file, please don't add the `.vs` directory, the `vcproj` files and the object and executable (i.e. the `x64` directories), make it a minimal example.

**Comment by Heawen** [comment] 2022-10-27 09:13
Thanks for your help !

Can doxygen generate call graphs including standard library calls, such as the "printf" in my example ?

**Comment by albert-github** [comment] 2022-10-27 11:58
Regarding the "printf" question
- you could create just a dummy file with the definition of the functions you want to show extra and add this file to the INPUT files for doxygen

**Comment by Heawen** [comment] 2022-11-01 08:45
Thanks for your respond !

I want to generate call graphs of Apache http server, including the standard library calls. 

Since the source codes are too large, can I just copy the include files of the standard library calls into the source directory or add the standard library path into the INPUT files？
I try this method in my example, but the call graph of "main.cpp" still miss the "printf" function.

**Comment by Heawen** [comment] 2022-11-01 09:10
[test_1101.zip](https://github.com/doxygen/doxygen/files/9908469/test_1101.zip)

**Comment by albert-github** [comment] 2022-11-01 09:50
It is not easy, especially as the stdio.h from the Visual studio compiler contains quite a few path and decorators.
I added to the `PREDEFINED` settings:
```
                        _CRT_STDIO_INLINE= \
                        __CRTDECL= \
                        _Check_return_opt_=
```
and reduced the `stdio.h` to just:
```
    _Check_return_opt_
    _CRT_STDIO_INLINE int __CRTDECL printf(
        _In_z_ _Printf_format_string_ char const* const _Format,
        ...)
    #if defined _NO_CRT_STDIO_INLINE
    ;
    #else
    {
        int _Result;
        va_list _ArgList;
        __crt_va_start(_ArgList, _Format);
        _Result = _vfprintf_l(stdout, _Format, NULL, _ArgList);
        __crt_va_end(_ArgList);
        return _Result;
    }
    #endif
```
(this is from the `stdio.h` file around line 950).
now I get the desired call graph (to the best of my knowledge).

I also tried also with the original `stdio.h` but apparently there are some paths here that work against me, so I leave it to you.


Note: as you are, probably, not interested in your documentation in the internals of the `printf ` function and where the `printf` function is called you could also go for a `stdio.cpp` or `stdio.h` file like:
```
/// \file
/// This is a stub file with the definitions of a number of standard functions to show
/// them in the call / caller graphs of the documentation


    /// \hidecallgraph \hidecallergraph
    int printf( char const* const _Format, ...) { }
```

**Closed** 2022-12-27 10:23 UTC
Labels: duplicate
