### ISSUE TITLE
Minor nuisance: Doxywizard emits "Invalid option" warnings about SQLITE3

### ISSUE THREAD

**Issue by bobhairgrove** [doxygen/doxygen#9987] opened 2023-04-18 08:48 UTC
System: Ubuntu 22.04, Doxygen version 1.9.1

**Describe the bug**
When running Doxywizard, I get the following warnings although my Doxyfile has no such options (nor are these displayed in the GUI anywhere):

```
Invalid option: GENERATE_SQLITE3
Invalid option: SQLITE3_RECREATE_DB
Invalid option: SQLITE3_OUTPUT
```

**Expected behavior**
No warnings should be emitted unless there is a problem with the Doxyfile (I checked it, and these options do not exist in my file).

**To Reproduce**
In a terminal, create a template Doxyfile:
```
doxygen -g default_Doxyfile
```

Open this file in doxywizard, then close the GUI without doing anything:

```
doxywizard default_Doxyfile
```

Warnings are shown, although there should not be any warnings.

**Version**
doxygen 1.9.1

**Comment by albert-github** [comment] 2023-04-18 09:02
The doxygen version 1.9.1 is Jan\uary8, 2021, the current doxygen version is 1.9.6.
- what happens when you use the current doxygen version?

Looks like the version you are using is not compiled with `sqlite3` support.
- where do you see the waning?

**Comment by bobhairgrove** [comment] 2023-04-18 10:10
**Version**
I installed Doxygen from the Ubuntu 22.04 repositories. The version 1.9.1 is what they offer. Someone else with the current version could try the steps I outlined in my previous message?

**SQLite3 support**
I don't need this, actually. However, the bug seems to be in Doxywizard and not necessarily in Doxygen itself -- please see what I wrote above to reporoduce the problem. I only ran Doywizard with the template Doxyfile and closed the GUI immediately, without running Doxygen. The warnings are printed to `stderr`, presumably. You can see them if you run Doxywizard from the terminal, as i did.

Something in the GUI needs to be fixed so that it doesn't attempt to use those options if they are not referenced from the Doxyfile.

**Comment by albert-github** [comment] 2023-04-18 10:18
The problem is that I don't have an Ubuntu system so I cannot properly test it. 

You can, easily, test it by using / installing the version from https://github.com/doxygen/doxygen/releases/tag/Release_1_9_6 where in the file doxygen-1.9.6.linux.bin.tar.gz the doxywizard  (and also doxygen) is included.

**Comment by AuroraMaster** [comment] 2023-05-15 21:43
@albert-github  replaced this [1.9.6 version](https://github.com/doxygen/doxygen/releases/tag/Release_1_9_6) with the latest build [version](https://github.com/doxygen/doxygen/actions/runs/4980900742#artifacts) doxygen.exe file and run it using the command line (gui version is not perfect yet).In the 1.9.6 configuration file,There is no configuration for sqlite3
` Configuration options related to Sqlite3 output
`
After I added the new configuration
`GENERATE_SQLITE3   = YES`
`SQLITE3_OUTPUT  =  sqlite3`
`SQLITE3_RECREATE_DB  = YES`

`.\doxygen.exe D:\doxygen\Doxyfile`
sqlite3 data file still cannot be generated after executing the command,but there is no error message. I don't understand it very well. May I ask why thanks

**Comment by albert-github** [comment] 2023-05-16 08:11
@AuroraMaster strange as in the build procedure for Ubuntu I see `-Duse_sqlite3=ON` and during the build I see:
```
-- Checking for module 'sqlite3'
--   Found sqlite3, version 3.31.1
-- Found Sqlite3: /usr/lib/x86_64-linux-gnu/libsqlite3.so (found version "3.31.1")
```
and when using the setup you indicated it worked for me (I didn't run on Ubuntu but under Cygwin)

You wrote that you didn't get an error message, but maybe you got a warning that you overlooked (e.g. in the file set by `WARN_LOGFILE`) like;
```
warning: No output formats selected! Set at least one of the main GENERATE_* options to YES.
```

Is the libsqlite3.so installed on your system
(maybe you can check it with `dpkg --get-selections | grep -v deinstall | grep sq`)

Can you show the complete Doxyfile you used and the completer output that went to the console (and attach the files to the comment)?

**Comment by AuroraMaster** [comment] 2023-05-23 04:36
> 


I am using the windows side, after the updated version 1.9.7, the default gui does not have the sqlite3 generation option
![image](https://github.com/doxygen/doxygen/assets/45430047/6fb24080-89d7-4740-b6a3-0325401a94ac)
There are related descriptions in the configuration file generated by default, but there are no related configuration options
![image](https://github.com/doxygen/doxygen/assets/45430047/1600cade-0478-4ad5-ad57-8816ba36e91c)
![image](https://github.com/doxygen/doxygen/assets/45430047/ca7ae7d1-f958-4f77-a456-543deaf93e5b)
After adding and executing in cmd（Because the default configuration option will be executed in gui (that is, there is no related configuration)） `.\doxygen.exe D:\doxygen\Doxyfile`
May I ask if this function is not available on the windows side?

**Comment by albert-github** [comment] 2023-05-29 15:59
I've just pushed a proposed patch, pull request #10099

**Comment by albert-github** [comment] 2023-06-04 09:58
Code has been integrated in master on GitHub (please don't close the issue as this will be done at the moment of an official release).

**Comment by AuroraMaster** [comment] 2023-07-03 06:04
Has sqlit3 been deleted? I am now trying to generate documentation in debian12. 1.9.7 has no relevant configuration options by default. 
![image](https://github.com/doxygen/doxygen/assets/45430047/650cae5b-f49f-4d93-9904-e016e09f1104)
![image](https://github.com/doxygen/doxygen/assets/45430047/7c4acf78-8b63-4c8e-85b6-5edbcf74c672)
![image](https://github.com/doxygen/doxygen/assets/45430047/67bac31f-4b3f-42ea-8329-db3beaeb2c26)
![image](https://github.com/doxygen/doxygen/assets/45430047/480d7fdf-cc64-4518-913a-30ce168c63b0)
Tried ./doxygen Doxygen and doxywizard found that neither support
Is this support going to be canceled in the future?

> 代码已集成到GitHub上的master中（请不要关闭问题，因为这将在正式发布时完成）。

**Comment by albert-github** [comment] 2023-07-03 08:04
@AuroraMaster The sqlite3 support has not been removed / nor is scheduled for removal, as written it was not present in the Windows version but has been made an integral part in the doxygen executable by means of the the into the master version of doxygen (and thus scheduled to be in the next official release i.e. 1.9.8). In the 1.9.7 version of doxygen it is indeed not present.

**Comment by bobhairgrove** [comment] 2023-07-06 10:20
Using Doxygen version 1.9.6 on Linux now, I get more warnings from `doxywizard`:

```
Invalid option: SQLITE3_OUTPUT
Invalid option: CLANG_OPTIONS
Invalid option: CLANG_DATABASE_PATH
Invalid option: SQLITE3_RECREATE_DB
Invalid option: CLANG_ASSISTED_PARSING
Invalid option: CLANG_ADD_INC_PATHS
Invalid option: GENERATE_SQLITE3
```

This happens when I do the following, so it isn't anything I changed myself:

```
doxygen -g newest_doxyfile
doxywizard newest_doxyfile
```

It is the code in the `doxywizard` tool that needs to be fixed.

Strange that when I run `doxywizard` without specifying any file, there are no warnings...

**Comment by albert-github** [comment] 2023-07-06 10:28
@bobhairgrove 

I don't know where you obtained your Linux executable (probably the Ubuntu app store) and I don't know whether or not they compiled with the sglite3 option ON

As written in https://github.com/doxygen/doxygen/issues/9987#issuecomment-1617580755:
> The sqlite3 support has not been removed / nor is scheduled for removal, as written it was not present in the Windows version but has been made an integral part in the doxygen executable by means of the the into the master version of doxygen (and thus scheduled to be in the next official release i.e. 1.9.8). In the 1.9.7 version of doxygen it is indeed not present.


This should also solve, potential, problems in future with non Windows distributions.

**Comment by albert-github** [comment] 2023-07-06 11:17
@bobhairgrove That is correct as it is now integrated.

**Comment by doxygen** [comment] 2023-08-25 13:59
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.9.8.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2023-08-25 13:59 UTC
Labels: enhancement, doxywizard

**Comment by bobhairgrove** [comment] 2023-08-26 09:20
Now I get these warnings:

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Invalid option: CLANG_ASSISTED_PARSING
Invalid option: CLANG_DATABASE_PATH
Invalid option: CLANG_ADD_INC_PATHS
Invalid option: CLANG_OPTIONS
```
The first warning is from Qt, there is nothing one can do about that, apparently.

The other four seem to be similar to the SQLITE warnings I was getting in earlier versions of Doxygen.

Not sure how to reopen this? Maybe my user doesn't have sufficient privileges.

**Comment by albert-github** [comment] 2023-08-26 11:05
@bobhairgrove I assume that you tested the new doxygen release 1.9.8
It looks like you used an executable that was not compiled with `use_libclang` set during the CMake phase (i.e. without "Add support for libclang parsing.")

- <s>when do you get the warning, as in the doxygen code I cannot find "Invalid option"?</s> in the doxywizard.
- which platform did you use?
- where did you get the executable?

**Comment by bobhairgrove** [comment] 2023-08-26 11:44
> It looks like you used an executable that was not compiled with use_libclang set during the CMake phase (i.e. without "Add support for libclang parsing.")

Yes, but why should this cause Doxywizard to issue these warnings? If it is not a requirement to have `libclang` installed, then there should be no warnings about it, IMHO.

Platform: Ubuntu 22.04
Doxygen version: 1.9.8
(built from source, downloaded from here)

**Comment by bobhairgrove** [comment] 2023-08-26 11:44
Please reopen

**Comment by albert-github** [comment] 2023-08-26 11:51
When I get it right your `doxywizard` is compiled without `use_libclang` but the `Doxyfile` you feed into it contains the `CLANG_...` tags. These tags are unknown seen the compilation and this a warning is emitted, it is the same when you would place a tag like `BOBS_NICE_OPTION` into the `Doxyfile`.

**Comment by bobhairgrove** [comment] 2023-08-26 14:08
> When I get it right your `doxywizard` is compiled without `use_libclang` but the `Doxyfile` you feed into it contains the `CLANG_...` tags.

I built `doxywizard` using the same CMake command as I used to build `doxygen` itself. And the Doxyfile was generated using `doxygen -g doxyfile`, so why should it write those tags in the first place if it was compiled without `libclang`? Seems to me that `doxygen -g` should not generate them in that case.

**Comment by albert-github** [comment] 2023-08-26 15:31
So the generated `doxyfile` contains the line regarding `CLANG_...`, from your description the `doxyfile` should not contain these lines, strange.

So when I understand it correctly:
- you created the `doxygen` executable by means of cmake and make without the `-Duse_libclang=ON`  on the cmake line
- you ran `doxygen -g doxyfile`
   - what is the first line in the `doxyfile`?
   - what is the result of `which doxygen`
- you also created the `doxywizard` without the `-Duse_libclang=ON`  on the cmake line,, did you in one go do the cmake i.e. initially with `-Dbuild_wizard=ON`
  - what is the result of `which doxywizard`?

**Comment by bobhairgrove** [comment] 2023-08-27 09:56
The problem, at least way I see it, is that any given Doxyfile can be used as input to any version of doxygen, regardless of how each program was built. For example, we have a project developed mostly with C++ code, but other things -- such as our Doxygen input files -- are also under source code management (SCM). That way, the documentation can be generated on any platform where the developer(s) have access to the SCM system and have their own locally-installed doxygen program -- which might not be the latest version or would at least be different from one developer to the next.

Doxywizard will therefore not know how its Doxyfile was generated. This could also have been a manually-crafted text file bypassing the wizard. I would suggest that Doxywizard recognize that fact and simply ignore any options which are unknown to it, rather than displaying useless warnings such as these. Perhaps it could display them in the GUI somewhere but gray/disabled?

If Doxygen cannot use the options, let THAT program display the "invalid option" warnings. But maybe there should be two classes of "invalid option" such that options which could have been used would raise one kind of warning, and other options warn about "unsupported but valid option" or something else. This might also ease the pain when trying to build Doxygen docs using a newer Doxyfile than the current Doxygen version supports.

But, as the subject line of this thread suggests, this is all just a "minor nuisance". :)
