### ISSUE TITLE
doxygen does not follow symlinks correctly (Origin: bugzilla #595192)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#3518] opened 2018-07-02 02:49 UTC
status NEW severity *normal* in component *general* for *---*
Reported in version *1.5.9* on platform *Other*
Assigned to: Dimitri van Heesch

On 2009-09-14 16:53:05 +0000, pberuto@yahoo.com wrote:

    I'm using doxygen from within an auto-tool based project.
    The directory I build from is different from the one containing the sources.
    Autoconf simply substitute at "configure" time the correct paths for the
    source directory (input) and the build directory (output).
    The doxygen.cfg file contains all default options but specifies the
    STRIP_FROM_PATH and STRIP_FROM_INC_PATH tags to strip the SOURCE directory.
    
    The problem is the following:
    if the source path contains a symlinked directory, doxygen fails to produce
    any documentation, as if it didn't find any file to parse. Looking at the
    debug print it seems that doxygen tries to "resolve" the symlink and then
    gets somehow confused.
    
    - In my case the symlink was the project root directory:
    MYPROJ --> /real/path/to/of/project/dir/doxygen.cfg
    /home/projects/MYPROJ/doxygen.cfg
    
    - doxygen 1.5.9 prints something like this:
    searching /home/projects/MYPROJ
    searching /real/path/to/of/project/dir/src
    ...
    
    - before version 1.5.9 the prints look like this:
    searching /home/projects/MYPROJ
    searching /home/projects/MYPROJ/src
    ...
    
    
    Thank you!

**Comment by eborisch** [comment] 2018-12-06 15:04
We're running into the same issue here: https://github.com/macports/macports-ports/pull/3136 ... this would be nice to get fixed; currently it runs with no errors, but then creates empty documentation.

**Comment by albert-github** [comment] 2018-12-14 17:05
@eborisch I'm not able to reproduce the problem as I have a Windows system with Cygwin and on my system it looks like to work

- which version of doxygen do you use?
- do you see the problem only with `INPUT` or on other places as well?
- can you give some more details about:
  - the missing parsed pats
  - the console output
  - the directory structure
  - the settings in the Doxyfile

Interesting test is also to have "all " files in a directory as symbolic links to see what happens with them.

The fact that it works when appending `/.` to the `INPUT` does not really wonder me as in that case you are "hitting" again a real directory.

**Comment by albert-github** [comment] 2022-07-15 16:34
As it was not reproducible in 2018 and in 2021 the `QFile...` parts have been removed in favor of the `filesystem/filesystem.hpp` (first released with doxygen 1.9.2)I think we can conclude that the problem is solved in the mean time

**Closed** 2022-08-26 17:00 UTC
Labels: solved in the mean time
