### ISSUE TITLE
Links in Markdown Headlines not rendered properly in html output

### ISSUE THREAD

**Issue by nwrkbiz** [doxygen/doxygen#10307] opened 2023-09-13 12:38 UTC
**Describe the bug**
If there is a link within a markdown headline, the `<href>` is rendered as text within the html output.

**Expected behavior**
A link should be displayed instead.

**Screenshots**
![Screenshot from 2023-09-13 14-37-35](https://github.com/doxygen/doxygen/assets/6352567/4879267d-7084-4963-85a2-3b4a0624347d)

**To Reproduce**
Create a index.md file with following content:
```
# Test

# [Link Headline](https://doxygen.org)
```

Add the following to your Doxyfile:
```
USE_MDFILE_AS_MAINPAGE = index.md
```

**Version**
1.9.8 (c2fe5c3e4986974eb2a97608b24086683502f07f)
and   
1.9.4 (Debian Stable)

**Comment by albert-github** [comment] 2023-09-13 12:47
This is a known issue and, in my opinion, a duplicate of  "Markdown: Links in ATX headings processed incorrectly?" #6998 

Doxygen translates the:
```
# Test

# [Link Headline](https://doxygen.org)
```
into:
```
@mainpage Test\ilinebr @ianchor{Test} md_index\ilinebr

@section autotoc_md1 <a href="https://doxygen.org" >Link Headline</a>
```

and hence the problems.

**Comment by nwrkbiz** [comment] 2023-09-13 12:50
Also: https://github.com/doxygen/doxygen/issues/9449

**Closed** 2023-12-25 11:15 UTC
Labels: bug, duplicate

**Comment by nwrkbiz** [comment] 2023-12-25 11:45
@doxygen Fixed?

**Comment by albert-github** [comment] 2023-12-25 11:51
It was set to duplicate  and as a duplicate it was closed with the new release.
Some corrections have been made in respect to this problem, do you see still problems when so please add this to #6998 and  attach a, small, self contained example (source+configuration file in a, compressed, tar or zip file!) that allows us to reproduce the problem? Please don't add external links as they might not be persistent (also references to GitHub repositories are considered non persistent).
