### ISSUE TITLE
Doxywizard 1.9.3 Show HTML output button does not open browser

### ISSUE THREAD

**Issue by CodePassion20** [doxygen/doxygen#9130] opened 2022-02-17 17:40 UTC
Hey Dimitri,

I installed the latest version of Doxygen 1.9.3.  Tried running DoxyWizard for building, It worked fine. but when I tried opening output in the browser using the button "Show HTML output" it did not open it.  

![image](https://user-images.githubusercontent.com/27911647/154538735-6459a651-d6d0-423e-8f81-3d2d4dd667ff.png)

Finally reinstalled the older version of Doxygen 1.9.1 to resolve my problem temporarily.

Thanks

**Comment by doxygen** [comment] 2022-02-17 20:15
I think this is a duplicate of #9003

**Closed** 2022-05-05 19:55 UTC
Labels: bug, duplicate, doxywizard
