### ISSUE TITLE
Images Not Added to html output from VHDL source (Origin: bugzilla #694899)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5104] opened 2018-07-02 08:47 UTC
status NEW severity *normal* in component *general* for *---*
Reported in version *1.8.3.1* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[doxygen_bug.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug694899_237650_doxygen_bug.tar.gz/download)_ (ID 237650)

On 2013-02-28 21:15:12 +0000, Mark wrote:

    Created attachment 237650
    doxygen project to reproduce bugs
    
    Overview: Images included in documented vhdl source files are not being added to the generated documentation. Additionally if it in a @details section any other text in that section is also missing. It occurs on both linux and windows with Doxygen 1.8.3.1.
    
    Steps to Reproduce:
    Run attached doxygen with attached project and Doxyfile. Open the index page click Design unit list. Then click example_subsytem. Click the link Here.. next to block diagram and it should take you to the anchor where the image should be. 
    
    Actual Results: 
    Documentation is created correctly except that image(s) and any other included text from that details section are missing.
    
    Expected Results: 
    Documentation includes images and any text from related details section.

On 2013-03-06 21:23:12 +0000, mk wrote:

    
    1. set the IMAGE_PATH in Doxyfile  
    
    2. comments inside VHDL comments are not allowed
    
    --------------------------------------------------------------------------------
    -- BRIEF LINKS:
    --------------------------------------------------------------------------------
    --! @brief
    --! <b>Entity Description:</b> @ref ExampleSubSystem "Here..."<br>
    --! <b>Address Map:</b> @ref ExampleSubSystem_ADDR_MAP "Here..."<br>
    --! <b>Block Diagram:</b> @ref ExampleSubSystem_IMAGE "Here..."<br>
    --! @details @anchor ExampleSubSystem_IMAGE
    
    --------------------------------------------------------------------------------
    -- BLOCK DIAGRAM:
    --------------------------------------------------------------------------------
    --! @details
    --! @image html example/docs/images/example_sub_system.gif "Component Block Diagram"
    
    --------------------------------------------------------------------------------
    -- RETURN LINKS:
    --------------------------------------------------------------------------------
    --! <br> @ref ExampleSubSystem_BEH "Return to Top"
    
    +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    
    try
     
    
    --------------------------------------------------------------------------------
    -- BRIEF LINKS:
    --------------------------------------------------------------------------------
    --! @brief
    --! <b>Entity Description:</b> @ref ExampleSubSystem "Here..."<br>
    --! <b>Address Map:</b> @ref ExampleSubSystem_ADDR_MAP "Here..."<br>
    --! <b>Block Diagram:</b> @ref ExampleSubSystem_IMAGE "Here..."<br>
    
    --! @details @anchor ExampleSubSystem_IMAGE
    
    --! @details
    --! @image html example/docs/images/example_sub_system.gif "Component Block Diagram"
    --! <br> @ref ExampleSubSystem_BEH "Return to Top"

On 2013-03-07 15:03:11 +0000, Mark wrote:

    Thanks for the update. The VHDL comments were the problem. The white space between the @brief and the @details needed to be removed as shown below, but that is more related to our internal structure desire.
    
    Was there a change in the way the comments and white space were parsed. In the previous version used, 1.6.1,  the white space and comments did not cause any issues. Will this be ability be restored in the future?
    
    --------------------------------------------------------------------------------
    -- BRIEF LINKS:
    --------------------------------------------------------------------------------
    --! @brief
    --! <b>Entity Description:</b> @ref ExampleSubSystem "Here..."<br>
    --! <b>Address Map:</b> @ref ExampleSubSystem_ADDR_MAP "Here..."<br>
    --! <b>Block Diagram:</b> @ref ExampleSubSystem_IMAGE "Here..."<br>
    --! @details @anchor ExampleSubSystem_IMAGE
    
    --! @details
    --! @image html example/docs/images/example_sub_system.gif "Component Block
    Diagram"
    --! <br> @ref ExampleSubSystem_BEH "Return to Top"

On 2013-03-08 16:49:45 +0000, mk wrote:

    
    This possibility will not be supported in the future.
    I am surprised that comments inside VHDL comment  works at all (doxygen 1.6.1).
    Each VHDL comment line starts with --! included blank lines.
    Due to a bug  for parsing VHDL comments there is a change in the current doxygen svn trunk.
    
    example:
    
    --! @details
    --! The component simple instantiates a StreamingToSlaveSubSystem with a limited
    --! set of options
    --!
    --! @note - All data inputs and outputs should be on the same clock domain.
    --!
    --! @todo None
    --!
    --! @bug None
    --! <br> @ref ExampleSubSystem "Return to Top"

**Comment by albert-github** [comment] 2018-10-09 17:08
As already mentioned in the above discussion the copying of the images is not done due to the fact that parts of the code are not handled..
The handling of the code is also mentioned in #5107, with the same test case.

Closing issue as a duplicate of #5107

**Closed by albert-github** 2018-10-09 17:08 UTC
