### ISSUE TITLE
Wrong HTML output from markdown after `#` 

### ISSUE THREAD

**Issue by arttet** [doxygen/doxygen#8047] opened 2020-09-20 16:07 UTC
**Describe the bug**
Wrong HTML output from markdown after `#`

**Expected behavior**
![2020-09-20_19-03-17](https://user-images.githubusercontent.com/51746822/93715768-14aece80-fb74-11ea-8093-2444a45c880a.png)

**Screenshots**
![2020-09-20_19-02-31](https://user-images.githubusercontent.com/51746822/93715744-ddd8b880-fb73-11ea-972a-ed6237b154d2.png)

**To Reproduce**
```md
## [Fast pImpl (Pointer To Implementation)](https://en.wikibooks.org/wiki/C%2B%2B_Programming/Idioms)
```

**Version**
1.8.20 (f246dd2f1c58eea39ea3f50c108019e4d4137bd5)

**Comment by albert-github** [comment] 2020-09-20 16:13
I don't think this problem is in any w way related to #7675 as that is about counting for verbatim and code blocks.

I think this problem is a duplicate of #6998

**Closed** 2020-12-27 19:29 UTC
Labels: Markdown, bug, duplicate
