### ISSUE TITLE
TYPEDEF_HIDES_STRUCT stopped working properly

### ISSUE THREAD

**Issue by erez-o** [doxygen/doxygen#7508] opened 2020-01-12 19:21 UTC
Hi, 

I updated doxygen from 30.3.2019 to the latest version, and noticed that `TYPEDEF_HIDES_STRUCT=YES` is no longer working as it used to.

Attaching files

[doxygen_cfg.txt](https://github.com/doxygen/doxygen/files/4051178/doxygen_cfg.txt)
[rabbitmq3_html_output.zip](https://github.com/doxygen/doxygen/files/4051179/rabbitmq3_html_output.zip)
[rabbitmq-c-0.8.0.zip](https://github.com/doxygen/doxygen/files/4051180/rabbitmq-c-0.8.0.zip)

Notice in the html files all the structures ending with `_t_` at file `amqp_8h.html` (for example `amqp_array_t_`), while it used to end with `_t` (for example `amqp_array_t`) in my older doxygen version taken from https://github.com/doxygen/doxygen/tree/16d025c8a08b485f5d43ade0986d716bd6aa06f8

Thanks

**Comment by albert-github** [comment] 2020-01-13 11:25
The given example shows a difference but is a bit big, to make it easier to reproduce / debug can you reduce the problem a little:
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by albert-github** [comment] 2020-01-13 12:44
A test on the large case gives that the version:

> Commit: 4e21d19cf63b17aadb62905535262deb208a0c73 [4e21d19]
> Parents: 40f187cc3c, 74c74077aa
> Date: Saturday, September 28, 2019 12:08:11 PM
> Merge pull request #7282 from albert-github/feature/issue_7274
>
is still OK, but the next commit in master:

> Commit: d2b8ae16cb99621827f5dd860222c27e629f5a7f [d2b8ae1]
> Parents: 4e21d19cf6, ae0a5ec2a1
> Date: Monday, October 7, 2019 9:02:04 PM
> Merge branch 'std'

shows the different behavior, so looks like a regression when introducing "Use smartpointers to manage the lifetime of Entry objects".
Note also the current master shows still the problem.

**Comment by IvanoBilenchi** [comment] 2020-01-28 09:57
I'm experiencing this problem as well. I saw that the related issue #7514 is fixed by cbeaf57. Does that commit also fix this (e.g. can we expect this to be fixed in 1.8.18)?

**Comment by doxygen** [comment] 2020-01-28 19:58
@erez-o, @IvanoBilenchi  Please check if [this commit](https://github.com/doxygen/doxygen/commit/e468a6944f24152080c2a9b322c6623bfff208b4) fixes the problem for you.

**Comment by IvanoBilenchi** [comment] 2020-01-28 21:08
@doxygen Can confirm that the issue is fixed. Thanks a lot!

**Comment by erez-o** [comment] 2020-01-29 06:27
@doxygen confirmed. Thanks a lot.

**Comment by doxygen** [comment] 2020-01-29 10:07
Please leave the issue open until it is officially released to avoid duplicates being filed.

**Comment by doxygen** [comment] 2020-04-13 11:48
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.18.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2020-04-13 11:48 UTC
Labels: bug
