### ISSUE TITLE
The use of explicit namespace expressions makes that doxygen documents inexistent functions (Origin: bugzilla #700771)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5191] opened 2018-07-02 09:07 UTC
status NEW severity *major* in component *general* for *---*
Reported in version *1.8.4* on platform *Other*
Assigned to: Dimitri van Heesch

Original attachment names and IDs:
- _[bug-with-namespaces.tar.gz](https://sourceforge.net/projects/doxygen/files/attachments/bug700771_244906_bug-with-namespaces.tar.gz/download/download)_ (ID 244906)

On 2013-05-21 11:11:30 +0000, Manuel L. Pereira GarcÃ­a wrote:

    Created attachment 244906
    A small bug demonstration
    
    First at all, the information: I use doxygen 1.8.4 over Ubuntu 10.04 LTS.
    
    And now, the bug: when something is refered with :: doxygen documents it as
    a new function. In the attachment there is an example of that behaviour.
    Just run doxygen and then go to see the description of the file bug.cpp: it
    has a constants::C function!
    
    I was not sure about if this bug should be described or not as major, but
    finally I decided to classify it as a major bug because I think it could be
    confusing to a programmer who want to know which things a file contains.

**Comment by albert-github** [comment] 2023-09-04 16:21
I think this bug is a duplicate of #5423 ( Namespace variable declaration parsed as namespace function declaration (Origin: bugzilla #723441) )

**Closed** 2023-12-25 11:15 UTC
Labels: bug, duplicate, C/C++
