### ISSUE TITLE
Navigation bar disappears at certain display/window widths

### ISSUE THREAD

**Issue by tttapa** [doxygen/doxygen#8623] opened 2021-06-26 16:01 UTC
**Describe the bug**
When a vertical scroll bar is present, there are certain display or browser window widths at which the navigation bar is invisible. There is a range of widths between the width at which the wide navigation bar disappears and the width at which the mobile bar appears. See the video below (around 8 seconds).

**Expected behavior**
There should always be a navigation bar present, regardless of the display width.

**Screenshots**

https://user-images.githubusercontent.com/21296729/123518831-129c1200-d6a8-11eb-9fd2-9a23728f3f74.mp4

**To Reproduce**  
[Doxygen-8623.zip](https://github.com/doxygen/doxygen/files/6720355/Doxygen-8623.zip)

**Version**
Doxygen 1.9.2 (ff2a7670c50743547495f0ebee35323b11a74e6a), compiled from source (master branch) today.

The issue is present in both Firefox 89 and Chrome 91 on Ubuntu 20.04.

**Comment by albert-github** [comment] 2021-06-26 16:11
I don't think this is directly a doxygen issue, but ...

I tried to reproduce the problem with Firefox 89.0.2 (64-bit) but I was not able to reproduce the problem.

- When you make the window smaller and the scrollbar disappear (which is visible in the movie you posted) and you stop moving the cursor does the scrollbar reappear automatically?
- do you use a special resolution of your screen or a native resolution of your monitor?

**Comment by tttapa** [comment] 2021-06-26 16:29
> * When you make the window smaller and the scrollbar disappear (which is visible in the movie you posted) and you stop moving the cursor does the scrollbar reappear automatically?

I'm not entirely sure what you mean, when does the scroll bar disappear? Here's a static image, where I'm not moving the cursor:
![Screenshot from 2021-06-26 18-27-54](https://user-images.githubusercontent.com/21296729/123519566-60b31480-d6ac-11eb-8456-bfaad96f4967.png)

> * do you use a special resolution of your screen or a native resolution of your monitor?

No, I'm using the native resolution with 100% scaling (1920×1200).

**Comment by albert-github** [comment] 2021-06-26 16:44
> > - When you make the window smaller and the scrollbar disappear (which is visible in the movie you posted) and you stop moving the cursor does the scrollbar reappear automatically?

> I'm not entirely sure what you mean, when does the scroll bar disappear? Here's a static image, where I'm not moving the cursor:

What I meant is that at a certain stage the scrollbar disappears and when you don't change the size of the window at that moment (and release the mouse) does the scroll bar re-appear or is it still gone?

In the static image you posted the scrollbar is present. 

(Note I tested on Windows 10)

**Comment by tttapa** [comment] 2021-06-26 17:02
> What I meant is that at a certain stage the scrollbar disappears and when you don't change the size of the window at that moment (and release the mouse) does the scroll bar re-appear or is it still gone?

The scroll bar is always present, it only looks like it's gone when you resize the window faster than the rendering of the page can keep up with.

**Comment by albert-github** [comment] 2021-06-26 17:06
That is a limitation of the GPU / CPU as it is busy with the rendering and at that moment a next rendering request already appears and doxygen cannot do anything about it (to the best of my knowledge).
It doesn't look nice.

I don't think this is a bug but is usage (the user is to fast ...

**Comment by tttapa** [comment] 2021-06-26 17:08
But the issue is not only _while_ you're resizing, the same happens on static pages with a specific width.

**Comment by albert-github** [comment] 2021-06-26 17:10
Can you give an example? I don't know what you mean in this context with "static page".

**Comment by tttapa** [comment] 2021-06-26 17:16
Maybe there is some confusion about the terminology: by navigation bar and scroll bar I mean the following:
![Screenshot from 2021-06-26 19-09-55-2](https://user-images.githubusercontent.com/21296729/123520766-a4a91800-d6b2-11eb-9749-402f4cf9b6d5.png)

If my browser window has a certain width and if I then open a tall Doxygen page, the Doxygen navigation bar is absent.

The video above simply shows the behavior different widths, but the problem is unrelated to the act of resizing itself, only the current width.

**Comment by tttapa** [comment] 2021-06-26 17:21
The reason I mentioned the scroll bar is because it seems to be the cause of the issue, if a scroll bar is present, the width of the window is calculated incorrectly.

If I open two pages with the same width, one with a scroll bar, and one without, the problem only manifests itself on the page with the scroll bar:
![Screenshot from 2021-06-26 19-18-43](https://user-images.githubusercontent.com/21296729/123520909-990a2100-d6b3-11eb-8c23-7356c057249b.png)

Note that I was not resizing anything while taking the screenshot.

**Comment by albert-github** [comment] 2021-06-26 17:28
Indeed there was a confusion about the terminology at my side, you wrote Navigation bar and I thought it was about the scroll bar as I saw the scroll bar disappear a few times in the movie. All my remarks were regarding the scroll bar, sorry.

The problem with the navigation bar is visible when it switches  between the normal blue bar with the names of the "tabs" next to each other to a collapsible stacked representation as introduced as part of "Improved responsive design of dynamic menus".

This might well be a doxygen problem.

**Comment by doxygen** [comment] 2021-06-27 09:14
`innerWidth()` was used to determine when to switch menu styles instead of `outerWidth()` which includes the scrollbar. Please verify if the commit fixes the problem.

**Comment by tttapa** [comment] 2021-06-27 11:42
This indeed seems to have fixed the problem, thanks a lot!

**Comment by albert-github** [comment] 2021-06-27 11:49
The issue only appeared in a not released version, closing the issue.

**Closed by albert-github** 2021-06-27 11:49 UTC
Labels: HTML, bug
