### ISSUE TITLE
First paragraph broken in the first sentence when using JAVADOC_AUTOBRIEF (Origin: bugzilla #742616)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#5712] opened 2018-07-02 11:05 UTC
status NEW severity *enhancement* in component *build* for *---*
Reported in version *1.8.9.1* on platform *Other*
Assigned to: Dimitri van Heesch

On 2015-01-08 21:05:13 +0000, an3moreno@gmail.com wrote:

    When using JAVADOC_AUTOBRIEF and REPEAT_BRIEF, the first sentence is
    generated as an independent paragraph in the detailed description. However,
    the expected behavior is that the paragraph where the first sentence is
    included is not broken.
    
    For example, given this doc:
    
    /**
     * This class does this. It does it this way.
     *
     * More explanations...
     */
    
    
    the generated detailed description has 3 paragraphs:
    
       This class does this.
    
       It does it this way.
    
       More explanations...
    
    
    but the expected result is:
    
       This class does this. It does it this way.
    
       More explanations...

On 2015-01-11 10:46:59 +0000, albert wrote:

    From the documentation:
    
    JAVADOC_AUTOBRIEF If the JAVADOC_AUTOBRIEF tag is set to YES then doxygen
    will interpret the first line
    (until the first dot) of a Javadoc-style comment as the brief description.
    If set to NO, the Javadoc-style will
    behave just like regular Qt-style comments (thus requiring an explicit
    @brief command for a brief description.)
    The default value is: NO.
    
    So I think this is by design and is not a bug.

On 2015-01-11 11:26:44 +0000, an3moreno@gmail.com wrote:

    The behavior regarding the brief description is correct, but my report
    relates to the detailed description only: if the first comment sentence
    belongs to a longer paragraph, it should be kept that way in the detailed
    description.
    
    Sometimes you want to complement the (auto) brief description with another
    sentence in the same paragraph and it will look wrong if that sentence is
    separated in a new paragraph. For example:
    
    /**
     * This class is the driving component of the X framework. It acts as
     * the controller part in the MVC pattern.
     */
    
    This comment will generate:
    
       This class is the driving component of the X framework.
    
       It acts as the controller part in the MVC pattern.

On 2015-01-11 13:17:16 +0000, Dimitri van Heesch wrote:

    Doxygen stores the brief and detailed descriptions into two separate strings
    internally. The parser doesn't keep track if there was a paragraph between
    the two. When rendering the brief and detailed description to the output a
    paragraph separator is always introduced.
    
    One workaround you could consider is to extend the brief description with
    the second sentence by ending the first sentence with .\ like so
    
    /**
     * This class does this.\ It does it this way.
     *
     * More explanations...
     */

On 2015-01-11 17:49:20 +0000, an3moreno@gmail.com wrote:

    I understand, thank you for the suggestion. Still, I cannot achieve what I
    want, which is this:
    
    Brief description:
    <p>This class does this.</p>
    
    Detailed description:
    <p>This class does this. It does it this way.</p>
    <p>More explanations...</p>
    
    With JavaDoc I would be able to do it, but now it's PHP code that I am
    trying to document.
    
    Anyway, feel free to delete this report if you consider that it's working as
    designed.
    
    Best regards.

**Comment by albert-github** [comment] 2021-12-08 17:36
As written in the explanation by Dimitri this is by design and the given workaround is working.

So I think this problem is usage / won't fix

**Closed** 2021-12-31 11:09 UTC
Labels: wontfix, Usage
