### ISSUE TITLE
1.8.16: Function returning void pointer generates warning

### ISSUE THREAD

**Issue by AlmeidaAndre** [doxygen/doxygen#7212] opened 2019-08-20 14:58 UTC
I have the following function:

``` c
/*
* \brief        Allocate memory
* \param[in]    wSize Size of desired memory
* \return       Pointer to allocated memory
*/
void *malloc(u16 wSize)
{
    void * pBuffer = NULL;
    // ...
    return pBuffer;
}
```

When I run doxygen, I get the following warning:

`warning: documented empty return type of  malloc`

Since the return is not empty, but a void pointer, I think it should not generate a warning in this situation.

This warning appeared after I updated doxygen from 1.8.15 to 1.8.16. I think it is related to #6788.

**Comment by albert-github** [comment] 2019-08-20 15:10
I can see your point, though I cannot reproduce it. (I already changed the first line from `/*` to `/**`).
I used the default Doxyfile.

- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by albert-github** [comment] 2019-08-20 16:22
I've just pushed a proposed patch, pull request #7213

**Comment by chlandsi** [comment] 2019-08-30 12:42
The same thing happens for a function returning a `std::future<void>`.

**Comment by albert-github** [comment] 2019-08-30 12:46
@chlandsi 
- Which doxygen version are you using
- Does this still happen when applying the proposed patch?
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by chlandsi** [comment] 2019-08-30 12:49
The warning started to show when switching from 1.8.15 to 1.8.16. I'll try to make up an example and apply the patch (although I don't think it will affect this particular issue) later.

**Comment by albert-github** [comment] 2019-08-31 11:30
Code has been integrated in master on github, including problems with e.g `std::future<void>` (please don't close the issue as this will be done at the moment of a release).

**Comment by Mekk** [comment] 2019-10-25 17:19
Just faced it. Any chances for aforementioned release?

**Comment by skypjack** [comment] 2019-12-16 23:09
@albert-github 

If you want another test case for your patch, I've had the same error with [this](https://github.com/skypjack/entt) project available on GH.
I'm interested in the next release as this issue is pretty annoying. Any ETA or such yet?

**Comment by albert-github** [comment] 2019-12-17 13:28
From private communications  I heard that there are plans to have a release in the period around Christmas / new year.

**Comment by doxygen** [comment] 2019-12-28 10:54
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.17.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2019-12-28 10:54 UTC
Labels: bug

**Comment by infohoschie** [comment] 2019-12-31 22:14
commit 361f3e10a86370a568733a7e4d862b180cf45fd9 reverts major changes and results in the warnings happening again.
Therefore this issue is not closed!

**Comment by HoutarouOreki** [comment] 2020-03-27 21:55
Using 1.8.17, I'm encountering this warning on virtual void functions.

![image](https://user-images.githubusercontent.com/16261733/77801210-b0a1c680-7078-11ea-86d6-5ee45c12b52b.png)

All header files:
#### baseclass.h
```c++
#ifndef BASECLASS_H
#define BASECLASS_H

///
/// \brief The baseClass class
///
class baseClass
{
public:
    ///
    /// \brief baseClass
    ///
    baseClass();

    ///
    /// \brief virtualFunction
    ///
    virtual void virtualFunction() = 0;
};

#endif // BASECLASS_H
```
#### derivedclass.h
```c++
#include "baseclass.h"

#ifndef DERIVEDCLASS_H
#define DERIVEDCLASS_H

///
/// \brief The derivedClass class
///
class derivedClass : public baseClass
{
public:
    ///
    /// \brief derivedClass
    ///
    derivedClass();

    ///
    /// \brief virtualFunction
    ///
    virtual void virtualFunction() override;
};

#endif // DERIVEDCLASS_H
```
[Doxyfile.txt](https://github.com/doxygen/doxygen/files/4395983/Doxyfile.txt)

**Comment by albert-github** [comment] 2020-03-28 10:34
With version 1.8.17 I see the warnings as  well, with the current master (2e406f88cd4698e119944707d69a8984aa8d0108 ) these warnings are gone.
