### ISSUE TITLE
JAVADOC_AUTOBRIEF doesn't match javadoc behavior. (Origin: bugzilla #344713)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2162] opened 2018-07-01 21:44 UTC
status NEW severity *normal* in component *general* for *---*
Reported in version *1.4.x* on platform *Other*
Assigned to: Dimitri van Heesch

On 2006-06-12 23:51:38 +0000, K Walrath wrote:

    Please describe the problem:
    When you specify JAVADOC_AUTOBRIEF=YES, the summary description looks OK,
    but the detailed description has a paragraph break between the summary
    sentence and the next sentence in the paragraph. This line break doesn't
    appear in javadoc-generated documentation, and I think the default behavior
    of JAVADOC_AUTOBRIEF=YES should be to match the javadoc behavior.
    
    Steps to reproduce:
    Specify AUTOBRIEF=YES, point doxygen at a source file that has at least one
    description with multiple sentences in the first paragraph.
    
    Actual results:
    You get an OK summary, but the detailed description has a paragraph break
    between the first and second sentences.
    
    Expected results:
    No paragraph break between the first and second sentences in a description
    if there's no paragraph break in the input. It should match what javadoc
    does.
    
    Does this happen every time?
    Yes.
    
    Other information:
    Here's one way to see the javadoc behavior:
    
    1. Go to http://java.sun.com/j2se/1.5.0/docs/api/java/awt/Component.html.
    2. Click the summary method link at the top left (3rd line from top, labeled
    "SUMMARY" and then "METHOD").
    3. Look at addComponentListener. Notice its summary has one sentence, chosen
    automatically by the javadoc tool.
    4. Click add addComponentListener to go to its detailed doc.
    5. Note that the description has just ONE paragraph with two sentences --
    the summary and another sentence.

**Comment by albert-github** [comment] 2021-12-08 17:06
I think this behavior is by design in doxygen, so I don't think this is a bug.

Example: [example.tar.gz](https://github.com/doxygen/doxygen/files/7677701/example.tar.gz)

@doxygen what do you think?

**Comment by albert-github** [comment] 2021-12-09 10:18
Seen the comments with #5712 I think there here also usage / won't fix applies.

**Closed** 2021-12-31 11:09 UTC
Labels: wontfix, Usage
