### ISSUE TITLE
some code line are missed in the xml file for java

### ISSUE THREAD

**Issue by sdrgroup** [doxygen/doxygen#7123] opened 2019-07-13 14:39 UTC
When I used 1.8.16 to parse the source code of undertow(https://github.com/undertow-io/undertow), the generated xml files,named _ajp_server_request_conduit_8java.xml and _cookies_8java.xml, are wrong,but  classio_1_1undertow_1_1server_1_1protocol_1_1ajp_1_1_ajp_server_request_conduit.xml and classio_1_1undertow_1_1util_1_1_cookies.xml are correct.
I find the lineno from 110 to 367 and after 201 are skiped in _8java.xml.

The two files I used are in https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/server/protocol/ajp/AjpServerRequestConduit.java and https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/util/Cookies.java

**Comment by albert-github** [comment] 2019-07-13 14:42
- I see you used the current master version, would be good to give the git version with it. The 1.8.16 version is stil lunder development.
- Can you please attach a, small, self contained example (source+configuration file in a tar or zip) that allows us to reproduce the problem?  Please don't add external links as they might not be persistent.

**Comment by albert-github** [comment] 2019-07-13 14:47
Looks like that in, at least https://github.com/undertow-io/undertow/blob/master/core/src/main/java/io/undertow/server/protocol/ajp/AjpServerRequestConduit.java , there is an error regarding nested comment at lines 96 / 97 same in the other file line 175 / 176.

**Comment by sdrgroup** [comment] 2019-07-13 15:55
[problem3.zip](https://github.com/doxygen/doxygen/files/3388955/problem3.zip)
the attached zip file includes config file and the java files parsed.

**Comment by albert-github** [comment] 2019-07-13 16:14
I see in the problem.zip the 2 files AjpServerRequestConduit.java and Cookies.java. In these there are the double comments as indicated in my precious comment. When removing these comments there is a big difference between the resulting xml output.
Is the output as generated when this lines are removed the output you expect?

**Comment by sdrgroup** [comment] 2019-07-14 02:43
Yes, the output is correct after I remove them. Thank you!
Btw, is it possible to modify the doxygen to skip the error comments?

**Comment by albert-github** [comment] 2019-07-14 07:19
I've made an enhancement request out of it. It has to be investigated what can be done.

**Comment by albert-github** [comment] 2019-07-14 10:59
I've just pushed a proposed patch, pull request #7124

**Comment by albert-github** [comment] 2019-08-07 09:14
Code has been integrated in master on github (please don't close the issue as this will be done at the moment of a release).

**Comment by doxygen** [comment] 2019-08-08 17:45
This issue was previously marked 'fixed but not released',
which means it should be fixed in doxygen version 1.8.16.
Please verify if this is indeed the case. Reopen the
issue if you think it is not fixed and please include any additional information
that you think can be relevant (preferably in the form of a self-contained example).

**Closed by doxygen** 2019-08-08 17:45 UTC
Labels: C/C++, Java, Usage, enhancement
