### ISSUE TITLE
Override/specify Doxyfile options on doxygen command line... (Origin: bugzilla #536643)

### ISSUE THREAD

**Issue by doxygen** [doxygen/doxygen#2983] opened 2018-07-02 00:49 UTC
status NEW severity *enhancement* in component *general* for *---*
Reported in version *1.5.5* on platform *Other*
Assigned to: Dimitri van Heesch

On 2008-06-04 16:26:44 +0000, Mike Allen wrote:

    Provide the ability to specify and/or override Doxyfile fields and their
    values via the "doxygen" command line.
    
    Proposed syntax:
    
    doxygen -O:field=value
    
    Where "field" is a Doxyfile option and "value" is the value to be assigned
    to that field.  If "field" is also present in the Doxyfile, then the command
    line's version would supersede and replace it.
    
    Advantages:
    
    Doxyfile contents could become more standard/generic and you would not
    necessarily need different configuration files for different projects.
    Furthermore, then information produced by doxygen could then be controlled
    as part of a software build system.
    
    For example, identification of the documentation version number (using the
    PROJECT_NUMBER configuration option) in the Doxyfile means that the Doxygen
    file has to be modified each time the version number changes.  If the
    version number is maintained by your build process, then the build process
    should be able to specify the version number when it invokes doxygen to
    create the documentation.  (As it is, the build system currently has to
    modify the Doxygen file in order to achieve this - which is cumbersome and
    non-trivial.)
    
    For example:
    
    doxygen -O:PROJECT_NUMBER="3.2-2"
    
    It would also allow the same Doxyfile (so that the vast majority of options
    are preserved) to be used for different classes of documentation: user vs.
    internal, etc.
    
    I'd be glad to assist with the coding if you think this would be a useful
    addition.

On 2008-12-22 15:59:27 +0000, Dimitri van Heesch wrote:

    This is already possible without like so:
    
    (cat Doxyfile ; echo PROJECT_NUMBER="3.2-2") | doxygen -
    
    I'll keep this bug open as a placeholder for people looking for this
    enhancement.

On 2011-08-26 11:37:39 +0000, Lorenzo Cappelletti wrote:

    On Windows platforms, one would use:
    
    ( type Doxyfile.txt && echo PROJECT_NUMBER="3.2-2" ) | doxygen -
    
    Nonetheless, my thumb-up for this proposal as it is cleaner (think of make
    or any C preprocessor).

**Comment by albert-github** [comment] 2022-10-11 16:43
The mentioned solution is also mentioned in the documentation as FAQ https://www.doxygen.nl/manual/faq.html#faq_cmdline
(the `cat` version was already in the manual at the moment of the writing of the issue, the `type` version has been added after the comment of Lorenzo Cappelletti)

I think the problem is solved in the mean time (as it is in the documentation) and the suggestion with the `-O` is won't fix

**Closed** 2022-12-27 10:21 UTC
Labels: wontfix, solved in the mean time
